### ISSUE TITLE
Link to github organization

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#10]
The page at https://conda-forge.github.io has no link back to this repo and/or organisation.
It would be useful if it had at least one of the two.

**Comment by ChrisBarker-NOAA** [comment]
Is that page all hand-coded html?

**Comment by pelson** [comment]
> Is that page all hand-coded html?

Sure is. Good old html. :smile: 
I don't anticipate doing that for anything other than the front page, so we aren't currently bound to any particular technology (though, of course, many of us know ~~and love~~ sphinx)

**Comment by Juanlu001** [comment]
Doesn't https://github.com/conda-forge/conda-forge.github.io/commit/9cde9a65ce827a5bcb613433a71a0db781436037 fix this?

**Comment by pelson** [comment]
Yeah, I think so (though it isn't particularly pretty - anyone with any eye for these kinds of details want to get involved?).
