### ISSUE TITLE
Add ability to run all scripts without GH_TOKEN

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#100]
Would be great for testing if we could run through everything without a `GH_TOKEN`. We could just skip anything that involved the GitHub API. This is perfect for having local testing.

**Comment by pelson** [comment]
There probably isn't much that *can* be run without a GH_TOKEN. Without authentication there is a rate limit on the GitHub API that we are likely to hit very quickly if applying something to *all* feedstocks.

Which script in particular were you wanting to run without a GH_TOKEN?

**Comment by jakirkham** [comment]
Sorry, I should have been clearer. By running without having a `GH_TOKEN`, I was thinking we skip the GitHub API stuff. This way we can see if all the stuff runs correctly without changing the state of the organization or its content.

**Comment by pelson** [comment]
> This way we can see if all the stuff runs correctly without changing the state of the organization or its content.

Sounds good, but there really isn't a lot you can do without accessing the API. Could you be specific with the script you have in mind? If you are wanting to catch syntax errors etc. there is always flake8 to statically analyse the code.

**Comment by jakirkham** [comment]
For instance, we had an issue parsing one recipe. Being able to test that change in a single PR without having to do several go's of it would be nice.

**Comment by jakirkham** [comment]
Honestly, I don't want to bother with a new script. I just want us to run the existing code and have guards against the GitHub API stuff if the token is undefined. That way we can still run `update_teams` and the like. Basically, the goal here is to increase code coverage with relatively little effort.

**Comment by pelson** [comment]
> Being able to test that change in a single PR without having to do several go's of it would be nice.

Honestly, in that case I tested outside of the script:

```
import yaml
import jinja2


class NullUndefined(jinja2.Undefined):
    def __unicode__(self):
        return unicode(self._undefined_name)

    def __getattr__(self, name):
        return unicode('{}.{}'.format(self, name))

    def __getitem__(self, name):
        return '{}.{}'.format(self, name)

env = jinja2.Environment(undefined=NullUndefined)


with open('../feedstocks/jpeg-feedstock/recipe/meta.yaml') as fh:
    contents = env.from_string(''.join(fh)).render()

d = yaml.safe_load(contents)

from pprint import pprint

pprint(d)
```

I completely agree with your rationale, but I don't think there is anything we can do here - you *really* can't do *anything* without the github API when it comes to teams. There is already a pretty good error (from memory), but I'd be happy if it needs improving.

**Comment by jakirkham** [comment]
Agreed. Closing as unresolvable. Thoughts and suggestions on how to better test things welcome. Maybe looking at what PyGithub does will help.
