### ISSUE TITLE
unarchive jellyfish-feedstock

### ISSUE THREAD

**Issue by blabalme** [conda-forge/conda-forge.github.io#1001]
How unarchive https://github.com/conda-forge/jellyfish-feedstock ?

Is it possible to add new a reviewer ?

there is an issue to rename it but it's already the same name on pypi : https://pypi.org/project/jellyfish/

**Comment by jakirkham** [comment]
Yep that can be done. Are you wanting to add yourself as a maintainer?

**Comment by blabalme** [comment]
If there is no active maintainer I can become one.

**Comment by jakirkham** [comment]
Ok it's unarchived. Please send a PR to add yourself as a maintainer and I'll merge. Thanks for offering to help out btw 🙂

**Comment by blabalme** [comment]
Thank you.
I do it but build failed ...
I try rerender, but i need your help.

**Comment by blabalme** [comment]
@jakirkham Can you help me become maintainer  ?

**Comment by jakirkham** [comment]
Did you submit a PR to add yourself?

**Comment by blabalme** [comment]
yes but build failed ... I ask rerender but i can't approved it.

**Comment by jakirkham** [comment]
Do you have a link?

That’s fine we can just merge it anyways. Though looking at CI failures is probably the next order of business.

**Comment by blabalme** [comment]
https://github.com/conda-forge/jellyfish-feedstock/pull/11

**Comment by jakirkham** [comment]
Thanks! Merged 😄

Should be good to go. Will close this out. 😉

Can engage further on the feedstock as needed 🙂

**Comment by CJ-Wright** [comment]
we also need to update the bot graph to include this as not archived

**Comment by jakirkham** [comment]
How do we do that?

**Comment by jakirkham** [comment]
Should add we probably need to rename it anyways ( https://github.com/conda-forge/jellyfish-feedstock/issues/10 ) (in case that fixes this issue too).

**Comment by CJ-Wright** [comment]
you can flip the value or remove this key https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/jellyfish.json#L69
