### ISSUE TITLE
Documentation for CDT/libGL may need updating

### ISSUE THREAD

**Issue by cmeyer** [conda-forge/conda-forge.github.io#1006]
To get my package to link against libGL on Linux, I followed these instructions:

https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl

However, I needed to add the CDT package `libxext` in addition to the ones already listed.

```
@@ -30,6 +30,7 @@ requirements:
     - {{ cdt('libselinux') }}  # [linux]
     - {{ cdt('libxdamage') }}  # [linux]
     - {{ cdt('libxxf86vm') }}  # [linux]
+    - {{ cdt('libxext') }}     # [linux]
     - cmake
     - make  # [not win]
     - python 3.7
```

The errors without adding that package were missing symbols like `XextAddDisplay`, `XextRemoveDisplay`, `XextFindDisplay`, etc.

It might be worthwhile to update the documentation to include `libxext` as a `build` requirement or otherwise figure out a cleaner way for maintainers to ensure they are linking libGL properly.

**Comment by jakirkham** [comment]
A PR would be welcome 🙂
