### ISSUE TITLE
pypy team?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#1009]
First congrats on the pypy migration, this is super awesome!

Do we want a pypy help team? If so who would be interested in being on it? There seems to be a bunch of questions around the pypy migration to it would be great to know who to ask for help.

**Comment by isuruf** [comment]
We can add a `help-pypy` team and I'm happy to be in it.

cc @mattip

**Comment by CJ-Wright** [comment]
Also has anyone let pypy leadership that we are packaging their language in a serious way? They might be able to include it on their website and such (and maybe provide some support?)

**Comment by ocefpaf** [comment]
> Also has anyone let pypy leadership that we are packaging their language in a serious way? They might be able to include it on their website and such (and maybe provide some support?)

I believe @mattip knows ;-p

**Comment by mattip** [comment]
Yes, PyPy is in the loop. I would be happy to link to information about using conda in our [install page](http://doc.pypy.org/en/latest/install.html), what should I write? How would a newbie get started with using pypy3 + numpy + django?

**Comment by mattip** [comment]
and of course ping me if there are any issues

**Comment by isuruf** [comment]
> How would a newbie get started with using pypy3 + numpy + django?

If they have a conda installation,
```
conda create -n pypy-env pypy numpy django
conda activate pypy-env
```
If they don't, they can download [miniforge-pypy3](https://github.com/conda-forge/miniforge#miniforge-pypy3) which is a conda installation with pypy.

**Comment by CJ-Wright** [comment]
(once https://github.com/conda-forge/django-feedstock/pull/94 goes in)

**Comment by isuruf** [comment]
Ah, we need `psycopg2` first which needs a new PyPy release. https://github.com/conda-forge/psycopg2-feedstock/pull/35

**Comment by mattip** [comment]
Thanks. I guess it might be prudent to wait a few more days before making noise about this, and in the mean time I will push forward with a new release. It will be ABI backward-compatible with the current one, and include improvements for things like psycopg2. Since the ABI tag will not change, I think successful feedstock builds should not need to be rerun.

**Comment by mattip** [comment]
PyPy 7.3.1 has been released.

**Comment by scopatz** [comment]
Awesome! I saw the announcment!

**Comment by isuruf** [comment]
https://github.com/conda-forge/pypy3.6-feedstock/pull/20

**Comment by isuruf** [comment]
There's a `help-pypy` team now and the migrator mentions this
