### ISSUE TITLE
Organizational Hackpad

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#101]
I added an organizational hackpad ( https://conda-forge.hackpad.com/ ). I tried to invite everyone using the emails I could find from the old hackpad. If I missed somebody, sorry it was not intentional. Also, anyone is welcome to join. If you have issues, just ping me.

Might be nice to get all of our hackpad(s) in here. ~~Though I am a bit baffled how at the moment. So, if someone knows how, I would definitely appreciate your help.~~ However, it turns out copying and pasting works great and still retains all of the history including who wrote what.

Also, might be worth splitting out each meeting into separate hackpads now that they are in an organization. After all, we can always label them by their purpose (e.g. "agenda" or similar).

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf @msarahan @takluyver @jjhelmus @ericdill

**Comment by jakirkham** [comment]
Apparently, one can drag and drop the original Hackpad into the organization. However, they must be the owner of the Hackpad. In this case, I am guessing it is @ericdill. Would you be willing to transfer it into the org @ericdill? It might be nicer if we consolidate these sorts of things. Also, it would be nice to keep the original around instead of a copy of it. Please let me know if I can help in any way.

**Comment by ocefpaf** [comment]
> Apparently, one can drag and drop the original Hackpad into the organization.

Cool!.

> However, they must be the owner of the Hackpad. In this case, I am guessing it is @ericdill.

That would be me :grin: 

> Would you be willing to transfer it into the org @ericdill? It might be nicer if we consolidate these sorts of things. Also, it would be nice to keep the original around instead of a copy of it. Please let me know if I can help in any way.

Done! Let me know if you can see it on your end and that things worked.

**Comment by jakirkham** [comment]
>> However, they must be the owner of the Hackpad. In this case, I am guessing it is @ericdill.

> That would be me :grin: 

Ah, sorry, for some reason I thought he created it.

>> Would you be willing to transfer it into the org @ericdill? It might be nicer if we consolidate these sorts of things. Also, it would be nice to keep the original around instead of a copy of it. Please let me know if I can help in any way.

> Done! Let me know if you can see it on your end and that things worked.

Hmm...I see two Hackpads with URLs, but I don't see the original. I have given you admin access to the org just in case that was the issue.

**Comment by jakirkham** [comment]
Looks like we may need to move [soon]( https://paper.dropbox.com/doc/Dropbox-Paper-beta-Is-Ready-For-You-Xlvlkb3yI23hLvuZxvn2Q ). Looks like they are going to stop adding new Hackpad accounts at some point. So we may need to switch to Dropbox Paper. Let's wait a bit while they sort out the bugs and then hopefully it should be a smooth transition.

**Comment by ocefpaf** [comment]
> Hmm...I see two Hackpads with URLs, but I don't see the original. 

I used the drag and drop and it looked like it worked. I will try again. (But your copy does have the history, so that is not too important then.)

**Comment by jakirkham** [comment]
Weird. Maybe it is a bug. Yeah, it's not a big deal either way.

**Comment by jakirkham** [comment]
I think I know the issue now. When transferring the hackpad, it preserves the [same privacy settings]( https://hackpad.com/tq56fI63mz3_Eo3crjqavQK#:h=Can-I-move-a-Pad-between-Works ). That means it is still shared only with those that have the link. So, I think you will need to update the settings to [make it public]( https://hackpad.com/Hackpad-FAQ-tq56fI63mz3#:h=How-can-I-change-the-Settings- ), @ocefpaf. Then we should be able to see it.

**Comment by ocefpaf** [comment]
I made it public, but the drag and drop created [this now](https://hackpad.com/-httpsconda-forge.hackpad.comconda-forge-meeting-notes-2YkV96cvxPG-YkkgGPWXvXJ), just a link...

**Comment by jakirkham** [comment]
Ack, what a mess. Sorry for bringing it up again. I suppose we could just delete the old one after copying any potentially new changes over. On the other hand, maybe we just leave it alone. I'll leave it up to you.

**Comment by ocefpaf** [comment]
Let's just leave it alone. We are in the org hackpad now.

**Comment by pelson** [comment]
Think this one is done then. Thanks @jakirkham & @ocefpaf
