### ISSUE TITLE
cffi implementation meta-package

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-forge.github.io#1011]
With `pypy` providing `cffi`, we now have the problem that we need to make `noarch: python` packages that depend on `cffi` `non-arch` packages that are specific to the Python implementation. As this would blow up the CI matrix for these packages again a lot, I would propose to make a either a `cffi-?` meta package that either depends on `cffi` for `cpython` or nothing for `pypy`. Alternatively, we could also build an empty `cffi` package for `pypy` instead of going the metapackage route.

**Comment by isuruf** [comment]
There's a `cffi` meta package now

**Comment by mattip** [comment]
@isuruf how do we update the meta package for 1.14.2 which is needed for pypy3.6-v7.3.2?

**Comment by isuruf** [comment]
You already did in https://github.com/conda-forge/pypy-meta-feedstock/commit/95f9f0f66547ebd3604cc1ec85b0470c28c0598c
There was an upload issue because of a new security feature we implemented. Will fix in a moment.

**Comment by mattip** [comment]
thanks

**Comment by isuruf** [comment]
Should be fixed now
