### ISSUE TITLE
appveyor and `vs2015` deprecation

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#1012]
## To Do
- [x] update to `vs2017` (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/501)
- [x] bump default in appveyor to vs2017 (https://github.com/conda-forge/conda-smithy/pull/1278)
- [x] update the vc feedstock (https://github.com/conda-forge/vc-feedstock/pull/11)
- [x] figure out if we need to exempt any feedstocks (https://github.com/conda-forge/feedstock-outputs/pull/2)
- [x] need to turn off all appveyor as many feedstocks as possible to prevent new appveyor usage (https://github.com/conda-forge/admin-migrations/pull/18, https://github.com/conda-forge/admin-migrations/pull/21)
- [x] need to remove appveyor from the docs and make an announcement item (https://github.com/conda-forge/conda-forge.github.io/pull/1010)

## Feedstock Census

**See notes here: https://hackmd.io/@beckermr/rJPw0tnDL/edit**

**Comment by isuruf** [comment]
From the [announcements page](https://conda-forge.org/docs/user/announcements.html#announcements)

> We are formally deprecating vs2015 in two weeks on 2020-04-07 and will move to vs2017. This change will enable us to support the usage of msbuild on Azure for the win platform and will provide additional support for C++. Most packages built with vs2015 can be linked with vs2017 toolchain (but not vice-versa). An exception is static libraries compiled with whole program optimization (/GL flag) which may be incompatible with the vs2017 toolchain. These static libraries will need to be rebuilt using vs2017.

**Comment by isuruf** [comment]
@xhochy, we added `/GL` by default to `CFLAGS` env variable in `vs2015_win-64` package. So some static libraries might have been created with `/GL` inadvertently.

**Comment by beckermr** [comment]
I'm seeing this conda-build warning a lot:

```
WARNING (lz4-c,Library\bin\liblz4.dll): Needed DSO C:\Windows\System32\VCRUNTIME140.dll not found in any CDT/compiler package, nor the whitelist?!
```

any ideas anyone?

cc @conda-forge/core @isuruf

**Comment by beckermr** [comment]
Besides the warning above, the new compiler appears to be working. It has built lz4-c, mpfrc, mpc, m4ri and libdb.

**Comment by isuruf** [comment]
> any ideas anyone?

That's a conda-build issue. conda-build checking is case sensitive, when it shouldn't be.

**Comment by beckermr** [comment]
I think overall the new compiler is good to go.

**Comment by beckermr** [comment]
All of the work here is done! Closing!
