### ISSUE TITLE
Including Python debug builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1017]
Previously we have discussed adding debug mode builds of Python in issue ( https://github.com/conda-forge/python-feedstock/issues/73 ) and PR ( https://github.com/conda-forge/python-feedstock/pull/86 ). However we lacked some of the prerequisite tooling to enable selection and align debug builds, which made this difficult to pursue. With the recent work on PyPy, we have wound up adding sufficient tooling to allow for debug builds to be carried out. Given this, I wanted to reraise this idea of including debug builds of Python. Is there interest in this kind of functionality? What would be the next steps? Any other thoughts? 🙂

cc @conda-forge/core

**Comment by rgommers** [comment]
I just found this issue when wanting to write docs on how to use a debug build for Python. It's not too hard to build Python from source, but a conda-forge package would be way nicer of course. So +1 from me.

I assume this would be for the Python package only, and not propagate to debug builds of other packages? If so, the scope is fairly limited and probably worth it.

**Comment by jakirkham** [comment]
Historically this issue has been more complicated.

In other words the debug libraries of Python were not ABI compatible with the release builds. So one needed to rebuild Python and all dependencies (so it effectively became another Python version/implementation). Python 3.8 changed [the debug build to be ABI compatible with the release build]( https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build ). Meaning with Python 3.8+ one can swap in a debug build for a release build.

Seem to recall the Windows debug build story had more wrinkles, but don't recall what they were or whether they still apply. This comment from Ray ( https://github.com/conda-forge/python-feedstock/issues/73#issuecomment-605151779 ) seems to suggest that Python 3.8 on Windows isn't entirely ABI compatible between debug and release builds. Idk if that got fixed in later Python versions or not.

**Comment by nikhilweee** [comment]
@rgommers can you share your documentation of building python from source with the debug symbols included? I intend to do so using conda (I don't have sudo access) but I can't find any relevant documentation.

**Comment by jakirkham** [comment]
This [doc]( https://docs.python.org/3/using/configure.html#python-debug-build ) provides some info. There's an old PR ( https://github.com/conda-forge/python-feedstock/pull/86 ) that may also offer some guidance

**Comment by pitrou** [comment]
Sorry for the belated question, but while this was supposedly done some time ago, I can't find which package to install to get a debug-enabled CPython interpreter. Could someone perhaps enlighten me? cc @isuruf @nikhilweee

**Comment by pitrou** [comment]
Replying to myself: the package reference `conda-forge/label/python_debug::python` seems to work. Sorry for the noise!
