### ISSUE TITLE
1.4.3 appdirs broken on anaconda's conda-forge channel

### ISSUE THREAD

**Issue by Denisevi4** [conda-forge/conda-forge.github.io#1019]
Hi,

I don't know where should I ask, but 1.4.3 appdirs broken on anaconda, Can this be fixed?

https://anaconda.org/conda-forge/appdirs/files

**Comment by jakirkham** [comment]
Hi, I just transferred your other issue ( https://github.com/conda-forge/appdirs-feedstock/issues/10 ). Let's please follow up there. 🙂

Closing this as a duplicate.
