### ISSUE TITLE
terraform maintenance team

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#1023]
Per discussion gitter, we were thinking of making a terraform maintenance team

They would be on the terraform-feedstock and then be added to all of the terraform-provider-* feedstocks so help with the easy maintenance of this little ecosystem.

cc @mariusvniekerk @dhirschfeld 

cc @oblute @rluria14 @ndmaxar

**Comment by beckermr** [comment]
OK. As long as @mariusvniekerk is ok, then we can go ahead with this.

**Comment by mariusvniekerk** [comment]
Cool with it. My recommendation is to turn on auto mode on everything

**Comment by beckermr** [comment]
great! PR for the team here: https://github.com/conda-forge/terraform-feedstock/pull/56

**Comment by beckermr** [comment]
it looks like @sodre took care of adding the team and enabling automerge.

**Comment by beckermr** [comment]
OK. The above PR is merged and @sodre appears to have taken care of the rest. Closing this! Thanks everyone!
