### ISSUE TITLE
osx CI slowdown: 10 minutes to remove homebrew

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#1026]
I have been seeing that it consistently takes about 10 minutes to remove homebrew on the azure CI. 

Do we have any ideas on how to speed this up?

cc @conda-forge/core

**Comment by isuruf** [comment]
I've seen 10 minutes runs, but not consistently.

If we know the paths, then we can move them instead of deleting them. This makes it faster.

**Comment by jakirkham** [comment]
The problem is Homebrew mixes itself with the system. So it’s not so easy to just move directories. Would suggest raising this to Azure if it’s a persistent problem.

**Comment by beckermr** [comment]
We don’t need any of the system dirs though. We use a downloaded sdk. The code right now is deleting a bunch of stuff iiuic.

**Comment by isuruf** [comment]
We need system dirs to run stuff, but we don't need `/usr/local` which homebrew uses.

**Comment by beckermr** [comment]
Here is a gist that uses the `--dry-run` option from the homebrew uninstall script to mangle all of the paths. It runs in about 1 minute when I tested it out.

**Comment by jakirkham** [comment]
It seems like we should be able to get that down to just a couple lines of `bash`. Maybe using `xargs`?

**Comment by jakirkham** [comment]
Anyways do we know why deleting should be slow? Seems like we have been just running the uninstall script without issues for a couple of years and we are only now hearing about this. Has anyone reached out to Azure?

**Comment by beckermr** [comment]
We shipped a script that mangles the paths in the ci setup package. Sorry for not getting back to you earlier.

**Comment by beckermr** [comment]
We also pushed a PR into smithy to use this.

xref: https://github.com/conda-forge/conda-smithy/pull/1280, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/80, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/78

closing!
