### ISSUE TITLE
Docker Hub Organization

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#103]
It would be nice if we create an organization on Docker Hub to hold relevant images and/or mirrors of relevant images. It looks like there is [an account]( https://hub.docker.com/u/condaforge/ ) already. Could we convert it to an organization?

cc @pelson @jjhelmus

**Comment by jjhelmus** [comment]
I made the condaforge account, I though it was an organization but I am still learning about Docker Hub.  I've added quite a few others including you @jakirkham  to the owners team, let me know if other should be added.

**Comment by jakirkham** [comment]
They changed a bunch of stuff near the end of last year both in obvious and non-obvious ways. Though I think it is going to stay basically the same at this point.

Thanks. Did you add @pelson? Also probably should add @msarahan too. Do you have any interest, @ocefpaf? If you don't that's fine, just wanted to make sure you know what is happening at least. If you have already added them, that is awesome. Unfortunately, I can't quite see who is already there.

My hope here is that we can move our existing images into this common space. This way if something goes wrong we don't ping @pelson 20 times. :wink: Also, we may decide to mirror images from Continuum here. So, this let's us give an official sign off of what is ok to use. Related to this, we should probably add a `docker-core` team here at conda-forge that mirrors who has access to the Docker image so that we can be pinged easily.

The other part we need to discuss at some point is the movement of Dockerfiles to GitHub. Not sure how we want to do this, but we can discuss it at our next meeting if we don't figure out something sooner.

**Comment by bgruening** [comment]
You might also consider to create a https://quay.io/ account for condaforge. It is faster and currently much more reliable.

**Comment by jakirkham** [comment]
Not a bad thought. I know I have had issues with Docker Hub before. Though aren't they using the same OSS?

**Comment by jakirkham** [comment]
So, this is done already and with the exception of two feedstocks (still have legacy code for complicated reasons) all feedstocks use that image.
