### ISSUE TITLE
Update docs to use cf-mark-broken procedure

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#1046]
This section is outdated: https://conda-forge.org/docs/orga/guidelines.html#fix-broken-packages

See: https://github.com/conda-forge/cloudpickle-feedstock/issues/37

We should consider moving the instructions to the maintainer section. At the moment it's a bit difficult to find.

**Comment by jakirkham** [comment]
This is also filed as issue ( https://github.com/conda-forge/conda-forge.github.io/issues/973 ).
