### ISSUE TITLE
[VOTE] Conda-forge AWS Spending

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-forge.github.io#1050]
In enabling DynamoDB on the official conda-forge AWS account, the bot subteam got eneding up mistakenly setting up certain flags and alerts. We ended up with using 840 M write requests / month, or about 1000/month.  This lasted from mid-February through yesterday, when we shut the service off.  

The total amount invoiced so far is $2200. Only the February time was successfully billed ($600). 

This vote is to allow:

* Reimbursing the $600 billed so far
* Authorization attempt to get AWS credits via Numfocus or otherwise to pay for this.
* Authorization to apply for Numfocus PEX cards to apply to the AWS account
* Spending of funds on the remaining balance (currently $1600) if we cannot obtain AWS credits by the point we need to use AWS again if/when our AWS account is suspended.

@conda-forge/core
This vote falls under the "Spending of funds" policy, please vote and/or comment on this PR.
This vote needs 50% of core to vote yea to pass.
To vote please leave Approve (yea) or Request Changes (nay) reviews.
If you would like changes to the current language please leave a comment or push to this branch.
This vote will end on 2020-05-06.

**Comment by beckermr** [comment]
Approve!

**Comment by jakirkham** [comment]
I'm fine with the spending as [the die has been cast]( https://en.wikipedia.org/wiki/Alea_iacta_est ).

Though I would also second @ocefpaf's point about using NumFOCUS cards for this sort of thing (instead of personal cards) and raising expenses to the group beforehand. Was not aware this was something we were spending on (though may not have been paying that close of attention). Admittedly that doesn't prevent bugs from happening (I think everyone involved tried to address the issue as soon as they were aware), but better visibility might help us catch this sort of issue faster (reducing the magnitude of overruns).

**Comment by isuruf** [comment]
Approve.

**Comment by pkgw** [comment]
Approve.

**Comment by xhochy** [comment]
Approve.

**Comment by msarahan** [comment]
Approve

**Comment by bgruening** [comment]
Approve.

**Comment by synapticarbors** [comment]
Approve

**Comment by scopatz** [comment]
> Though I would also second @ocefpaf's point about using NumFOCUS cards for this sort of thing (instead of personal cards) and raising expenses to the group beforehand. Was not aware this was something we were spending on (though may not have been paying that close of attention). Admittedly that doesn't prevent bugs from happening (I think everyone involved tried to address the issue as soon as they were aware), but better visibility might help us catch this sort of issue faster (reducing the magnitude of overruns).

Yeah - I totally agree. We really thought we were on the free tier here. I think we should definitely move to the PEX cards ASAP.

**Comment by jjhelmus** [comment]
Approve

**Comment by sodre** [comment]
Approve

**Comment by mariusvniekerk** [comment]
Approve

**Comment by scopatz** [comment]
This vote has passed. Thanks to all who voted.

**Comment by jakirkham** [comment]
Does that mean the check is in the mail? :)
