### ISSUE TITLE
Conda-forge build failing due to error in conda_build

### ISSUE THREAD

**Issue by RyanGutenkunst** [conda-forge/conda-forge.github.io#1055]
My apologies if this isn't the right forum, but my issue on the staged-recipes repository has been ignored for more than two weeks, and this is breaking my distribution plans. https://github.com/conda-forge/staged-recipes/issues/11293

The build in my pull request at https://github.com/conda-forge/staged-recipes/pull/11291 is failing due to an error in conda_build.

The last error is
File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 400, in mk_relative_osx
log.warn("Found Mach-O file but patching is only supported on macOS, skipping: %s", path)
NameError: name 'log' is not defined

The fact that a warning is (trying) to be emitted may point to underlying issues with my build script, but it seems like bad logging in conda_build is the immediate cause of the error.

What can I do to help resolve this? Even if I submit a pull request to fix the error in conda_build, how will that get propagated to the staged-recipes system?

**Comment by croth1** [comment]
Of you are stuck in a staged-recipe PR, you can ping the team for help using our web-services: see here: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team

**Comment by RyanGutenkunst** [comment]
Thanks!
