### ISSUE TITLE
broken feedstock?

### ISSUE THREAD

**Issue by RubendeBruin** [conda-forge/conda-forge.github.io#1056]
Issue: No write access to feedstock as maintainer and autotick-bot not working.

I am one of the maintainers of  conda-forge/vtkplotter-feedstock. 

A new version of vtkplotter has been released on pypi and I was expecting the bot to notice this and create a merge request.
When this did not happen (why?) I manually created a merge request (https://github.com/conda-forge/vtkplotter-feedstock/pull/2) for the updated the recipe.
I was expecting to be able to merge but it look like I don't have write access. I am listed as maintainer.

**Comment by CJ-Wright** [comment]
I updated the team you should now have all the needed permissions. The bot is erroring getting the upstream https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/vtkplotter.json I'm not certain why. You could try using the github url.

**Comment by RubendeBruin** [comment]
Hi @CJ-Wright , thanks for fixing this so quickly. Merging now works. I can live without the bot :-)
