### ISSUE TITLE
Rolling out the blog - getting feedback from the community

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#1060]
I agree with @xhochy here https://github.com/conda-forge/conda-forge.github.io/pull/1058#pullrequestreview-408712851 that using both the blog and the *Announcements* section will make it very inconvenient for conda-forge users to stay up-to-date.
In fact I am not sure how many people actually know that we have the Annoucement section, let alone follow it.

The blog has the advantage that it offers an RSS feed, which would be my preferred way to get news from conda-forge, but I am not sure how well that generalizes.

I propose that at this point it would make sense to ask the community for feedback what suits them best.

I would suggest following strategy:
- Finishing up #1049 - otherwise people may have a hard time finding the blog.
- Make a public poll with following options: I am interested in subscribing to the latest news from conda-forge and I would prefer:
  - RSS feed
  - Twitter+RSS feed
  - Mailing list
  - Other, please comment
  Apart from getting the information what's the best strategy to distribute news best, we also advertise the blog, which I think should also be a high priority.
- Migrating the announcement section fully to the new blog, I think we should keep the history.
- link to the blog in the former announcement section.

I think without knowing that the risk is high that the time spent creating and updating the blog is not going to be a good investment.

BTW: What is actually the best way to reach a broad range of our community? Putting the poll only on twitter will probably lead to very biased results.

**Comment by beckermr** [comment]
I put this comment on the wrong issue. Repeated below.

@xhochy @croth1

I think the blog and the announcements serve two different purposes.

The announcements section is linked as NEWS on the main page and is effectively the changelog for conda-forge. It contains technical changes and some documentation about them for users and maintainers.

The blog is for us to present long-form content that goes beyond technical documentation.

PS: We have to keep a changelog somewhere and the announcements section is it. So we cannot get rid of it.

**Comment by beckermr** [comment]
One option is for use to title the blog "The `conda-forge` Changelog" and then use it for both. This has more personality than either but is not terribly original either.

**Comment by croth1** [comment]
What about posting them under a special tag on the blog? I wouldn't rename the blog to Changelog - If we were to rename it, I'd rather make the name more general, e.g. conda-forge news and then offer a broad variety of information.

I feel it would be advantageous to centralize everything we want to communicate to the community in one place, rather than scattering it around. If a changelog is important, I'd rather generate it from that centralized news place than storing the information somewhere else.

**Comment by beckermr** [comment]
They really do serve two different purposes, but I could imagine posting changelog entries to the blog and then scraping them back into the docs. 

cc @conda-forge/core for other thoughts

**Comment by jakirkham** [comment]
Agree with @beckermr. Announcements and blogposts serve two different purposes and should remain differentiated.

**Comment by croth1** [comment]
Okay, I have thought about it again, and I can see your point here. Closing this.
