### ISSUE TITLE
Clarify stance on shipping static libraries

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge.github.io#1068]
Issue:
Guidance on how we want to package static libraries is rather thin.

Windows users are requesting that we ship static libraries to easy `pypi` packaging.

https://github.com/conda-forge/lcms2-feedstock/pull/8#issuecomment-633565037

A few notes I found about static linking include:
* Pinnings for static libraries: https://conda-forge.org/docs/maintainer/pinning_deps.html?highlight=static#globally-pinned-packages
* Cmake prefering dynamic of static https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=static

I guess whatever the decision is, I would like to be able to document it so that I can refer to it in the future.

**Comment by scopatz** [comment]
We should not be shipping static binaries because it geometrically increases package size.

**Comment by xhochy** [comment]
Our tooling (the bots, pinnings as well as the conda itself) are doing much better with dynamic linkage than with static linkage. Dynamic linkage is directly visible in the recipes and in the solver itself. 

As a simple example, if we would link statically and would have a version update of OpenSSL, we would need to rebuild all packages that depend on OpenSSL and all packages that have an indirect dependency for OpenSSL. We would have to do these rebuilds not only for ABI breaking releases but for every new build of the openssl-feedstock.

Also the size @scopatz mentioned is quite annoying in a lot of cases, even when we only look at the static archives in the packages. The statically binaries though are a real headache.

**Comment by hmaarrfk** [comment]
Would we want to say:

- [ ] A PR for adding static linking is not welcome. Users needing static libraries should fork, and use conda-smithy to register themselves with Azure.
- [ ] A PR for adding static linking is welcome, provided it is in a split package

**Comment by isuruf** [comment]
The 2nd one, but we should clarify how the splitting should be done. (What names and files should go in the output)

**Comment by hmaarrfk** [comment]
I remeber conda being bad at "catching the remaining files". So it was tedious to build packages where many files were generated, and few needed to be split.

**Comment by jakirkham** [comment]
For split packages the usual logic is have a build step that builds everything you care about. Then add install scripts for each split package that moves the files of interest into `PREFIX` for packaging.

**Comment by jjhelmus** [comment]
I agree that the 2nd option (split packages) is preferred.  There are a few cases where static libraries are needed or at least of use.  Dynamic libraries should be encouraged and promoted but static libraries should not be un-welcome where a use case exists.

**Comment by beckermr** [comment]
see conda-forge/cfep#18

**Comment by beckermr** [comment]
closing due to cfep18
