### ISSUE TITLE
A private conda-forge?

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-forge.github.io#1069]
Is there is some documentation about building a private conda channel that is automated similarly than conda-forge?

I plan to create a channel with some recipes from closed source code (less than 10 packages) and would like to reuse some of the conda-forge infrastructures whenever possible (legally and technically of course).

**Comment by isuruf** [comment]
See the README at https://github.com/conda-forge/conda-smithy

**Comment by hadim** [comment]
Haven't realize that `conda-smithy` was doing already almost all the job. Will give it a try. Thanks @isuruf !

**Comment by hadim** [comment]
I will continue the discussion on another ticket.
