### ISSUE TITLE
Are feedstock renames reflected in conda-forge/feedstocks?

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#1070]
Was just cloning the feedstocks repo and got an error cloning the setuptools_markdown repo. Seems that it was renamed to setuptools-markdown, but was never removed from the .gitmodules on feedstocks. Is there an automated process for this or should we add the "submit PR to feedstocks removing old feedstock from .gitmodules" as part of the renaming instructions?

**Comment by jakirkham** [comment]
In general we suggest user's submit a new recipe to `staged-recipes` and then archive the old feedstock. This procedure doesn't cause that problem.

Likely this recipe/feedstock proceeded that recommendation. We could probably spell this out in the docs more clearly (if that isn't already the case).
