### ISSUE TITLE
pydstool-feedstock, offer of new maintainer

### ISSUE THREAD

**Issue by repagh** [conda-forge/conda-forge.github.io#1078]
Issue: Current maintainer of pydstool has moved on, see quote from e-mail:

> Hey,
>  I no longer maintain that feedstock since there was little to no gain and the Julia package ecosystem is already much more advanced in this area that we've dropped our usage of pydstool. Best of luck to you.

I hope this is the right forum for this issue. 

I am OK with taking over the feedstock, can you add me as maintainer?

repagh / René van Paassen

**Comment by croth1** [comment]
You can add yourself to the maintainer list in the [meta.yaml](https://github.com/conda-forge/pydstool-feedstock/blob/master/recipe/meta.yaml#L61) and submit this as a PR. The current maintainer or core (e.g. by pinging) [at]conda-forge/core can merge the PR and our infrastructure will make sure that you get writing permission.

**Comment by repagh** [comment]
Thanks, I see this is much clearer now #1079
