### ISSUE TITLE
Azure not starting when @github-actions merges

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1082]
Saw this happen with two commits from merged PRs by @github-actions today. Namely `opencv` ( https://github.com/conda-forge/opencv-feedstock/commit/e1517f06598451b45d6c86ed3d0233f912f51309 ) and `arrow-cpp` ( https://github.com/conda-forge/arrow-cpp-feedstock/commit/913bbcbed50ad0dcae230968f9b47aa2c73ef186 ). In both cases Azure did not start by itself and had to resort to manually trigger a build through the Azure UI.

**Comment by isuruf** [comment]
What have you done to debug this? Can you create a similar PR and merge it yourself to see what happens?

**Comment by jakirkham** [comment]
I looked for webhooks that may have had issues on `opencv`, but didn't find any. Have not debugged it further as I have too much on my plate to dig deeper atm.

**Comment by beckermr** [comment]
I think this is a transient bug and appears to have gone away. Closing for now!
