### ISSUE TITLE
Recipe builds on staged-recipes, but fails once accepted

### ISSUE THREAD

**Issue by lrntct** [conda-forge/conda-forge.github.io#1086]
Hi,

I recently added a recipe for a binary package that was built fine in the staged-recipes PR:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=174085&view=results

Now that it has been merged, the build of the feedstock is failing on Windows:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=175813&view=results

It is not obvious to me what is the issue.
Any clue?

**Comment by scopatz** [comment]
not sure, but I restarted the job

**Comment by lrntct** [comment]
@scopatz Thanks for looking into this. The build still fails at the same place.
It is not clear to me which file the build process cannot find in this specific environment (while it could in staged-recipes).
 https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=175813&view=logs&j=37bee0ae-db5a-53f5-b493-e446c7432842&t=ecca33be-d29b-5457-f50e-ca186b53f729&l=421

Are there some subtle changes between the env in staged-recipes and the general build env?

**Comment by scopatz** [comment]
Staged-recipes is slightly different, but it is 99% the same

**Comment by lrntct** [comment]
Just got the same issue in another feedstock (thanks for the merge!). Was building fine during staging:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=177791&view=results
Fails on Windows after merging:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=178212&view=results

It seems to fail in the installation step. Both recipes have in common the use of `copy` to install the binaries. It seems that the location of the generated binaries move from bin/ to bin/Release after staging. That seems to be the reason.
I wonder if adding a cmake installation rule will solve the issue.

**Comment by isuruf** [comment]
Add `set "CMAKE_GENRATOR=NMake Makefiles"` to the top of bld.bat

**Comment by lrntct** [comment]
@isuruf Thanks a lot, the builds work now!

**Comment by beckermr** [comment]
closing this since it appears resolved. feel free to reopen if you are having trouble!
