### ISSUE TITLE
Identify -> Modify -> PR

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#109]
It would be useful to generalise the MNT script to do another job. Essentially, I want to be able to scan all of the feedstocks, identify those that meet a particular criteria, modify them in some way, then submit a PR with the proposed change.

The usecases in mind:

JPEG:
- scan all recipes looking for an explicit dependence on jpeg
- pin the recipe, increment the build number
- submit a PR

Numpy (the numpy needed rebuilding for some reason, and anything depending on its C ABI has changed):
- scan all recipes looking for an explicit dependence on numpy
- increment the build number
- submit a PR

In fairness, the scripts wont take much modification to achieve this, but that is little condolence to @ocefpaf 😄

**Comment by jakirkham** [comment]
This was at least one idea that I had in the back of my mind when mentioning dependency tracking issues ( https://github.com/conda-forge/conda-forge.github.io/issues/79 ).

**Comment by jakirkham** [comment]
Is this still relevant @pelson? The use cases noted have been implemented AFAIK and have even been supplanted by other workflows.
