### ISSUE TITLE
new apple ARM architecture fretting

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#1090]
This issue is for us to publicly fret (and also collect info) on the new ARM-based OSX macs dropping later this year.

Some collected links:

- https://twitter.com/mycoliza/status/1275305517066227712
- https://www.wired.com/story/apple-will-put-its-own-chips-into-macs/

TL;DR

- there will be an emulator at first so we won't be caught completely off guard
- the situation around shared libs looks interesting, to say the least. If they really are cached in memory this might break
  many builds.
- we do not know if we can build our own compilers or if we will have to use the system ones.

cc @jjhelmus @jakirkham @isuruf

**Comment by jjhelmus** [comment]
Apple has a "Developer Transition Kit (DTK)" which is a ARM based machine that can be used for developing and testing, more details at https://developer.apple.com/programs/universal/.  You have to apply, pay $500, meet eligibility requirements and be selected to receive on of these kits.

**Comment by beckermr** [comment]
I’d be happy to host the machine at my house if we wanted to try this.

**Comment by jakirkham** [comment]
Yeah they mentioned something about getting a Mac Mini for development. Guessing that's what you are referring to. Agree that's a good idea. I wonder if they would give it to us for free if we asked nicely 😁

**Comment by beckermr** [comment]
Would nvidia or anaconda be willing to host it for us?

**Comment by jjhelmus** [comment]
The DTK is a mac mini with a Apple A12Z Bionic (8 cores, 4 big, 4 little, ARMv8.3-A) with 16 GB RAM and a 512 GB SSD.  It needs to be returned to Apple.  I'm discussing with folks at Anaconda about applying for one. I'll inquire about getting conda-forge access or hosting a separate machine as well.

**Comment by beckermr** [comment]
Bump here @isuruf

**Comment by beckermr** [comment]
We good to close this @isuruf?

**Comment by isuruf** [comment]
Sure

**Comment by isuruf** [comment]
Closing in favour of https://github.com/conda-forge/conda-forge.github.io/issues/1126
