### ISSUE TITLE
Moving from `master` to `main`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1099]
The broader OSS community has been moving away from terms like `master`, `whitelist`/`blacklist`, etc. Would recommend we do the same in conda-forge. Admittedly this is going to be a heavier lift than for some other communities (simply because of the large number of repos, scripts, tooling, etc.) that may need to be updated as well. So this may require a bit of planning to make the change in a minimally disruptive way. It looks like GitHub is also trying to figure out this transition. May be worth reaching out to them for guidance. Would be interested in hearing thoughts on this proposal generally as well as on next steps 🙂

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by jjhelmus** [comment]
I am in favor of this change.  `main` may not be the best replacement name as this is the same name as the primary channel in `defaults`.

**Comment by jakirkham** [comment]
GitHub is starting to work on this.

We could choose a different name. Though I'm hoping people understand the differences between branches and channels. Maybe there are particular fuzzy spots we could further clarify? 🙂 Asking this as GitHub seems to be leaning towards using `main` as well.

https://github.com/github/renaming

**Comment by scopatz** [comment]
Main is better if for no other reason than it is shorter than defaults :wink:
