### ISSUE TITLE
Develop code to manage github teams

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#11]
Looking for an example of code which, given a list of github handles, a repo, and a team name, creates/updates the GH team as appropriate using their API.

```
def manage_team(org, team_name, members, repo):
    <code here>
```

With inputs such as:

```
manage_team('conda-forge', 'matplotlib', ['pelson', 'tcaswell'], 'matplotlib']
```

Given its existence, it makes sense to use pygithub for this.

**Comment by ericdill** [comment]
Is the purpose of this `manage_team` function to add `members` to `team_name` in `org` / `repo`?  So for example, the second code block above would add you and Tom to the `matplotlib` team in the `matplotlib` repo in the `conda-forge` org?

**Comment by pelson** [comment]
Sorry for not getting back sooner. I'm afraid I've been a little bit disorganised and forgot to close this issue - and was delivered in https://github.com/conda-forge/conda-forge.github.io/pull/15. Basically, that code looks at the ``extra/recipe-maintainer`` section, and puts each member in an appropriate conda-forge team.

> So for example, the second code block above would add you and Tom to the matplotlib team in the matplotlib repo in the conda-forge org?

Almost. It would put Tom and myself in a team called matplotlib under the conda-forge organisation, and the team named matplotlib would have permission to modify the matplotlib-feedstock repo in conda-forge.
