### ISSUE TITLE
ROS packages & large multi-package builds

### ISSUE THREAD

**Issue by wolfv** [conda-forge/conda-forge.github.io#1100]
We have made quite some progress on ROS recipes for conda -- which hasn't really progressed to conda-forge yet.

As a reminder:

- ROS has their own "distro", and a large yaml file that contains all versions for that distro (for example: https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml)

This makes it easy to automate the recipe generation for conda recipes. We have a generator for these recipes called vinca now: https://github.com/ros-forge/vinca (thanks to @seanyen!).

Additionally, @seanyen has made a lot of progress on getting some low-level libraries needed for ROS on conda-forge, and adding Windows builds! 

The big problem that remains is that:

- There are many ROS packages (~2000 or so)
- They have many interdependencies
- There are no guarantees about binary compatibility. If, for example, the lowest level package (catkin) changes, the entire tree needs to be rebuilt
- Due to the way conda-forge and anaconda works, this would mean a lot of waiting for packages to arrive on the CDN...
- Managing that many feedstocks as single git repositories would be _hard_, and would need bots etc.

@seanyen has worked around this by creating "fat" feedstocks: https://github.com/ros-forge/ros-melodic-fat-feedstock

This contains one huge package that ships all the dependencies inside. It's definitely working and an easier solution, but IMHO preferable are many outputs.

However, with one recipe and many of outputs, we might run into build time limits on Azure.

I am interested to try out another server or a hosted solution somewhere where we have no restrictions on build times.

**Comment by beckermr** [comment]
Some other ideas for this

1. use automerge + mamba and the bot on conda-forge
2. enable a model where we package more than one recipe per feedstock

**Comment by isuruf** [comment]
> enable a model where we package more than one recipe per feedstock

You can already do this with outputs.

> I am interested to try out another server or a hosted solution somewhere where we have no restrictions on build times.

As I said on the other meeting, any help is appreciated in setting up Drone CI instances.

**Comment by beckermr** [comment]
> You can already do this with outputs.

@wolfv had some issues with the current outputs model. It assumes a joint build at the start and didn't isolate them enough. He can explain more. Separate recipes might have an advantage in some cases.

**Comment by isuruf** [comment]
> It assumes a joint build at the start and didn't isolate them enough.

It doesn't have to. You can separate build scripts for each output

**Comment by beckermr** [comment]
I'll let @wolfv explain more, but I think the issue was that conda-build was not making a new build dir for each output.

**Comment by beckermr** [comment]
> It doesn't have to. You can have separate build scripts for each output

Yes I know. 😄

**Comment by wolfv** [comment]
There is one problem with conda-build and pinnings -- I believe.

Let's say we have a conda_build_config.yaml that pins boost to 1.70.0 (as conda forge did before).
When you have some package A that depends on, let's say, cgal, and cgal depends on boost-cpp. Then conda-build will choose:

```
A:

- cgal
- boost ==1.72.0
```

because cgal has already passed the migration to 1.72.0

However, when we have another package (maybe in the same recipe, but I guess it doesn't really matter much) that depends directly on boost, it will choose boost from the pins:

```
B:

- boost = 1.70.0
```

It's kind of unfortunate side-effect of non-complete migrations and conda-build not taking into account the pinnings on a deeper level. Also (afaik) we currently don't automatically backport new releases (e.g. of cgal) to older boost versions even if they are still the pinned version.

At least this is how I remember the bug. I might have it wrong though.
I am looking into fixing this with boa, once we have proper pinning's for mamba :)

**Comment by isuruf** [comment]
That doesn't sound like it is related to the original issue. Please create another issue.

**Comment by wolfv** [comment]
yeah I already opened this issue on conda-build: github.com/thesnakepit/boa

**Comment by wolfv** [comment]
https://github.com/conda/conda-build/issues/3964

**Comment by CJ-Wright** [comment]
To my quick reading this issue seems rather implementation driven rather than solution/problem driven. What is the desired experience for the ROS maintainers and users? That might provide a better lens for producing implementations that deliver the needed outcomes.

Some of my questions (not exhaustive):
1. How often does ROS require a stack rebuilding?
2. How quickly does the rebuild need to be finished?
3. What has been the experience and approach of other teams that manage large chunks of the ecosystem (eg. R)?

**Comment by jakirkham** [comment]
Yeah one more point to add here. Looking at every package in Python, R, or other large ecosystems, we could walk away with the impression these are intractably large. However in practice it seems the community has gravitated towards a smaller set of things deemed worth packaging. Do we have a sense of what this set looks like for ROS? What things are ROS users needing in practice?

**Comment by wolfv** [comment]
closed as we have RoboStack these days: https://github.com/robostack/
