### ISSUE TITLE
Search for and remove specific *built distributions*

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#111]
Sometimes we build stuff which doesn't actually work. It happens.
One example is the packages which didn't pin their jpeg version, so we have built distributions which claim to support any version of libjpeg, but in reality they only work with libjpeg 9. I want to find all distributions which don't pin a jpeg version and potentially remove them all.

**Comment by 183amir** [comment]
Is there any process that we can go through and ask for removal? for example I have been stuck at this pull request for days: https://github.com/conda-forge/bob.ip.optflow.liu-feedstock/pull/5 but I think If I remove the old `bob.io.image` packages, it should make it work. I think it's a pity that have push access in our feedstocks but no delete access in anaconda.org.

**Comment by pelson** [comment]
> I think it's a pity that have push access in our feedstocks but no delete access in anaconda.org.

I agree. The problem is that anaconda.org simply doesn't have the granularity to give you access to one package without having access to *all*. I've not pushed this one further because it grates every time we remove a package from the channel - it is essentially reneging on the reproducibility of conda environments, and I believe there is a better way (even if that way hasn't yet been implemented).

If there are some packages to remove, please give one of us a request to remove them and we will happily facilitate. You will only have to do it a few times before we get so sick of doing it that we automate the process 😉

**Comment by 183amir** [comment]
I think even if we can't remove them, we should be able to reproduce them. Like if they are compiled with `boost 1.60` without any pinning, then we can recompile them and pin properly and replace them.

**Comment by 183amir** [comment]
we don't even need to recompile them. We need to download them, change their metadata and replace them in anaconda.org. This should be feasible with a script.

**Comment by pelson** [comment]
The only reason for changing their metadata is so that conda solves an environment correctly. For reproducibility I don't want conda to solve an environment for me, I want to use the *exact* same environment that the author of a paper used. For me, that means I don't even need the broken distributions available for conda to resolve, I just want them to be floating around via a permalink so that I can download them directly if my environment tells me to.

**Comment by 183amir** [comment]
If you don't want to fix their metadata, you can move them to another label (`archive`?) in the `conda-forge` channel in anaconda.org.

**Comment by jakirkham** [comment]
If you are interested in metadata hotfixes of this sort, it may be worth looking at the discussion on this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/126 ).

**Comment by jakirkham** [comment]
We probably should add a safety for this removal script. We don't want to accidentally remove all of conda-forge. 😉

Maybe we can just have it list everything that needs to be removed so we can copy and paste it to the command line and tell it to go (assuming its suggestions are ok).

**Comment by pelson** [comment]
> Maybe we can just have it list everything that needs to be removed so we can copy and paste it to the command line and tell it to go (assuming its suggestions are ok).

Or get to the point where we put the list in an issue, and as soon as there are more than one 👍 , go ahead and do the deletion 😉

**Comment by jakirkham** [comment]
Honestly I'm becoming less a fan of deletion as there is no way to reverse it if needed and it really messes with reproducibility. I'd rather see a relabeling script that boots it from `main`. See this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/181 ) for the proposal.

**Comment by jakirkham** [comment]
It's possible to mark things as broken. It's also possible to patch the repodata. Additionally there are a large swath of tools that have come forward over time to work with the conda-forge graph. This includes bots that use this information and perform updates. My guess is this is pretty well solved, but there could always be gaps. Would be interesting to see what you find that still would be nice to have in new issues 😉
