### ISSUE TITLE
DOC: New maintainer 

### ISSUE THREAD

**Issue by westurner** [conda-forge/conda-forge.github.io#1117]
Suggestions for improving the docs in regards to new maintainers and the bot:

- Contributing packages: 
https://conda-forge.org/docs/maintainer/adding_pkgs.html
- Maintaining packages: https://conda-forge.org/docs/maintainer/updating_pkgs.html

  - "Pushing to regro-cf-autotick-bot branch" is maybe a bit obscure to new maintainers.
https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch

    - [ ] additional / different heading?
    - [ ] how does it know to create a version update / PR?
    - [ ] link to https://github.com/regro/cf-scripts ( cf-regro-autotick-bot )
      - https://regro.github.io/cf-scripts/

**Comment by croth1** [comment]
Hi @westurner! Thanks for the feedback. I agree that this part of the documentation could benefit from extension and clarification. We e.g. do not have a dedicated section on the PR bot yet. If you are interested in contribution, we would be of course very happy to help! 👍

**Comment by PrernaSingh587** [comment]
Hi, I am willing to learn and work on this. Could you give me some pointers? @croth1

**Comment by Martins-O-U** [comment]
@croth1 @viniciusdc a dedicated section for the PR bot sounds interesting. More information here would be great help
