### ISSUE TITLE
Twitter bot

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#114]
You know, the kind that posts useful posts every now and again highlighting how awesome conda-forge is 😄  (and maybe giving some information about the packages which have been added/updated).

**Comment by jakirkham** [comment]
Seems like a good idea. To get some more discussion on it, I added it to the hackpad.

**Comment by ericdill** [comment]
xref https://github.com/conda-forge/conda-forge.github.io/issues/443

**Comment by jakirkham** [comment]
So at this point the [`feedstocks` repo]( https://github.com/conda-forge/feedstocks ) (linked for those that don't know), is live updated for any change in conda-forge. GitHub also provides the ability to have an Atom feed. Here is the feed regarding [individual feedstock updates]( https://github.com/conda-forge/feedstocks/commits/master.atom ) just the commits on `master`. 😄 Admittedly that may be too much information. Though maybe there is a way to filter that feed.

Some caveats though. We currently don't distinguish "Added" vs. "Updated" in the commit message, but that is certainly desirable and noted as issue ( https://github.com/conda-forge/conda-forge-webservices/issues/140 ). Also we don't really note what changed (e.g. version update), but that might be a bit more difficult to tackle without some constraints (e.g. PR subject formatting). Deletions are done manually, but that should change. ( https://github.com/conda-forge/conda-forge-webservices/issues/152 ). Also the occasional force push requires a manual correction (though ideally these should never happen). ( https://github.com/conda-forge/conda-forge-webservices/issues/139 )

**Comment by jakirkham** [comment]
We have a Twitter bot at this stage and it has been getting some good use. 😄
