### ISSUE TITLE
Add links to all our various chat rooms

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#1146]
it's rather painful to keep track of all of the ways in which the conda-forge community stays in touch. It'd be nice to enumerate them somewhere in our docs. The ones that I know of:

* conda-forge-core google group
* gitter.im for:
  * [core](https://gitter.im/conda-forge/core)
  * [public](https://gitter.im/conda-forge/conda-forge.github.io)
  * [power pc](https://gitter.im/conda-forge-ppc64le/Lobby)
* keybase

conda-tools stuff, kinda related
* conda google group
* conda slack org

What am I missing?

**Comment by croth1** [comment]
It might be also worth thinking about adding an additional chat item to the navigation bar at conda-forge.org. I think chat is a very low-barrier medium for people to reach out to the community and it may not serve us well if users need to dig into the documentation to find that information.
