### ISSUE TITLE
Current dependency breaks that need to be addressed (with potential solutions)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#115]
There are a few dependency issues that we are trying to handle where there are breaks. Personally, I am having trouble keeping track as this affects us on multiple feedstocks and some of them are interconnected. This issue is meant to gather that data in one place and figure out how we resolve them.

cc @pelson @ocefpaf @183amir

**Comment by jakirkham** [comment]
Current known breaks include `hdf5`, `libtiff`, `jpeg`, `xz`, `openjpeg`.

Some like `xz` will be fixed when we add our own Python ( https://github.com/conda-forge/staged-recipes/pull/370 ). Current workarounds include avoiding Python 3.5. Not as clear on the Python 3.4 situation.

HDF5 has been largely fixed (?) by pinning everything to the old version (`1.8.15.1` via `1.8.15.*`) this includes `h5py`.

Others like `jpeg` have a bit more unclear solutions.

**Comment by ocefpaf** [comment]
Here is the situation for gdal:

`openjpeg` &rarr; `libtiff` &rarr; `xz`

`libspatialite` &rarr; `libxml2` &rarr; `xz`

and our `xz 5.2.2` is a no-no in `Python 3.4.4` and `Python 3.5`. (It is OK on Python `3.4.1` though.)

The `hdf5` situation will be solved once we have our `libnetcdf` compiled against `1.8.16`

**Comment by jakirkham** [comment]
Could we remove our version `xz` and rebuild the same version as Continuum with a higher build number? I don't love the idea of handling this through build numbers, but we don't have a better mechanism the number of things this hits is quite large.

**Comment by ocefpaf** [comment]
> Could we remove our version `xz` and rebuild the same version as Continuum with a higher build number? I don't love the idea of handling this through build numbers, but we don't have a better mechanism ATM and the number of things this hits is quite large.

Been there, done that. See https://github.com/conda-forge/xz-feedstock/pull/2

**Comment by jakirkham** [comment]
Why can't we roll back `libtiff` too?

**Comment by ocefpaf** [comment]
It is not only `libtiff` that complaint with

```shell
Reason: Incompatible library version: libtiff.5.dylib requires version 8.0.0 or later,
but liblzma.5.dylib provides version 6.0.0
```

Also, I am not sure how all that started, but I had issues with the default channel `libtiff` on OS X too.

**Comment by jakirkham** [comment]
Yeah, I guess I am trying to find a way back to the stable system we had before we both check out for a bit. The simplest way I can think of is just to start building only the versions that Anaconda had from the ground up, but bump build numbers as needed and potential shadow Continuum packages so that ours are selected.

**Comment by ocefpaf** [comment]
I had that plan when I created https://github.com/conda-forge/conda-forge.github.io/issues/22 :smile: 

I guess that ship has :boat: now and we need to catch up with new software.

**Comment by ocefpaf** [comment]
I wonder why the default channel downgraded `xz` in the first place as `Python 3.4.1` is OK with `xz 5.2.2`, but `Python 3.4.4` and `3.5` are not.

**Comment by jakirkham** [comment]
Good question. @msarahan, do you know what the story is with `xz` and `python` 3.x?

**Comment by pelson** [comment]
Also worth seeing https://github.com/conda-forge/conda-forge.github.io/pull/116 which tells me some useful information:

```
$ conda execute list_deps.py conda-forge --packages '.*' --dependencies xz --platform osx-64     

Fetching package metadata: ..
gdal 1.11.4 np110py27_4 osx-64     : xz
gdal 1.11.4 np110py34_4 osx-64     : xz
gdal 1.11.4 np110py35_4 osx-64     : xz
gdal 1.11.4 np111py27_4 osx-64     : xz
gdal 1.11.4 np111py34_4 osx-64     : xz
gdal 1.11.4 np111py35_4 osx-64     : xz
libtiff 4.0.6 1 osx-64             : xz 5.2.*
libtiff 4.0.6 3 osx-64             : xz 5.2.*
libxml2 2.9.3 0 osx-64             : xz
libxml2 2.9.3 1 osx-64             : xz
libxml2 2.9.3 3 osx-64             : xz
libxml2 2.9.3 4 osx-64             : xz
sox 14.4.2 0 osx-64                : xz
sox 14.4.2 1 osx-64                : xz 5.2.*
```

As far as I'm concerned, at this point anything which doesn't pin a specific xz version is likely to cause the kinds of issues we have seen over the last few days and IMO should be removed/rebuilt.

**Comment by jakirkham** [comment]
We need to start pinning `libgcc` for packages still building with the packaged `gcc`. There appears to be a `libgcc` 5.2.0 in the `defaults` channel. However, the `gcc` version used to build things here is 4.8.5. So, we can pin to 4.8.5 exactly without issues. I suppose we could investigate having a looser pinning `libgcc`, but I'm not sure it is worthwhile as there doesn't seem to be a plan to rebuild the compiler.

cc @msarahan

**Comment by msarahan** [comment]
Sorry I missed this earlier. You should not need to pin libgcc.  It was
backwards compatible in all the tests I ran.  If you clobber it, not much
will break right now, as we haven't rebuilt much with it thus far.

This is the libgcc from the docker image.

**Comment by jakirkham** [comment]
You're sure it is compatible? What about `libgfortran` and `libgomp`?

**Comment by msarahan** [comment]
Again, to the best of my knowledge, they are compatible.  If you find
otherwise, please tell me ASAP.

**Comment by kmuehlbauer** [comment]
New issue with `jpeg 8` vs `jpeg 9` on windows.

At the moment `qt-4.8.7` depends on `jpeg 8` whereas conda-forge pinning advice is `jpeg 9*`. 

Problem: Packages which are pinned to `jpeg 9*` cannot be installed in the same environment with `qt-4.8.7` (e.g. `matplotlib`). Since matplotlib will be needed by most users, this has major effect. ATM there are some discussions at the feedstocks about this problem.

**Comment by 183amir** [comment]
I think hotfixing our old packages is the first thing we should do. `gdal`, `sox`, ... and all other packages which don't have a pinned dependency should be fixed. I have a not complete script to do that. If anyone can pick this up and complete it, I would appreciate it.
```python
#!/usr/bin/env conda-execute

# conda execute
# env:
#  - python
#  - conda
# run_with: python

import argparse
import tarfile
import json
import tempfile

#bob.blitz 2.0.8 np111py35_6 linux-64: boost
def download_package(channel, name, version, build_string, platform):
	pass

def main(args):
# maybe its better to create a temp directory, extract package there, fix index.json and repackage it.
	with tempfile.NamedTemporaryFile() as f, tempfile.NamedTemporaryFile() as f2:
		f = download_package(args.channel, args.name, args.version,
			args.build_string, args.platform)
		f.seek(0)
		tar = tarfile.read(f)
		index_info = tar.getmember('info/index.json')
		info_file = tar.extractfile(index_info)
		data = json.loads(info_file.read().decode)
		if args.dependency in data['depends']:
			i = data['depends'].index(args.dependency)
			data['depends'][i] = args.replace
		with tarfile.open(f2, 'w:bz2') as tar2:
			for tarinfo in tar:
				if tarinfo.name == 'info/index.json':
					tar2.add(tarinfo.name)
					tar
					json.dump(data)
				else:
					tar2.add(tarinfo.name)





if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('channel')
	parser.add_argument('--package', required=True)
	parser.add_argument('--dependency', required=True)
	parser.add_argument('--replace', required=True)

	args = parser.parse_args()

	main(args)
```

**Comment by 183amir** [comment]
I am also seeing a loose dependency tracking here: https://circleci.com/gh/conda-forge/bob.ip.facedetect-feedstock/12
```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Headers are 1.8.16, library is 1.8.17
```

**Comment by jakirkham** [comment]
Yeah, we updated to HDF5 very recently. I think we sent a pinning PR against part of your stack that used HDF5. ( https://github.com/conda-forge/bob.io.base-feedstock/pull/10 ) Are there other things that were are linking to HDF5? If so, let us know and we can send more pinning PRs.

**Comment by 183amir** [comment]
> Again, to the best of my knowledge, they are compatible. If you find otherwise, please tell me ASAP.

@msarahan I am using Arch Linux on my personal computer and most of the time I cannot compile packages with Arch Linux's GCC (which is very new) and use them with packages compiled on `conda-forge`. I am not very familiar with ABI and API things but this is also mentioned on Archlinux's website: https://www.archlinux.org/news/c-abi-change/ .
For example I have compiled `bob.learn.activation` with `bob.io.base` from `conda-forge`. Now I have compiled `bob.io.base` also locally (with arch linux's gcc) and cannot use `bob.learn.activation` with this new `bob.io.base`. I get an error like this:
```python
Failure: OSError (/home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/learn/activation/libbob_learn_activation.so: undefined symbol: _ZN3bob2io4base8HDF5TypeC1ERKSs) ... ERROR
```
Now I was wondering if this is ok to break or it should not break.

**Comment by msarahan** [comment]
Gcc 5.1 and above will use the c++11 ABI by default. In the continuum
docker image, we try to make it easy to select which ABI you use.
Essentially you need to set a preprocessor definition. Take a look at
https://hub.docker.com/r/continuumio/conda_builder_linux/ and the links
therein. Pay special attention to
https://github.com/ContinuumIO/docker-images/blob/master/conda_builder_linux/build/internal_startup.sh#L16

This switch forced most (all?) Linux distributions to do a complete rebuild
of their repositories. We as a community will need to do that eventually.

It's fine to have old ABI stuff on a new system and vice versa, but what
does not work is to mix libraries with different ABI.

**Comment by msarahan** [comment]
One important detail: libstdc++ in our libgcc package is actually dual ABI. That is not causing your problem. The problem is that you have one of your Bob  libraries with c++11 ABI and another with c++98 ABI.

**Comment by 183amir** [comment]
Thank you. Now I get it. So it is ok that this is breaking.

**Comment by msarahan** [comment]
Yeah, I'd say it's expected behavior that we know workarounds for (setting that preprocessor definition on your Arch linux compiles should work)

**Comment by jakirkham** [comment]
Going to close this out as the original issues this was trying solve back in later April/early May have been resolved. Please open a new issue for other problems.
