### ISSUE TITLE
[WSGI:ERROR] ModuleNotFoundError: No module named 'regex._regex' on  Miniconda Environment

### ISSUE THREAD

**Issue by Mahbuba-Tasmin** [conda-forge/conda-forge.github.io#1161]
Issue: ### When calling nltk package installed at miniconda3 environment from flask on apache server, Centos 7 platform, the module regex not found error raises. The python script runs perfect when running standalone, but serving from server creating the issue. Apache server also works fine without specific call to nltk package. I have checked the regex installation, it does not have any script name '_regex', **regex version ==2020.7.14**, why is WSGI asking for this particular package? @nltk @mod_wsgi @conda-forge-admin #No module named 'regex._regex'; 'regex' is not a package #1207

[wsgi:error]  ModuleNotFoundError: No module named 'regex._regex'
 [wsgi:error]  mod_wsgi Failed to exec Python script file '/var/www/chatbotv1/chatbotv1.wsgi'.
 [wsgi:error] Exception occurred processing WSGI script '/var/www/chatbotv1/chatbotv1.wsgi'.
 [wsgi:error]  Traceback (most recent call last):,
 [wsgi:error]  File "/var/www/chatbotv1/chatbotv1.wsgi", line 16, in <module>, 
 [wsgi:error]  from app import app as application, 
 [wsgi:error]  File "/var/www/chatbotv1/app.py", line 2, in <module>
 [wsgi:error] from chatbot_response import response
 [wsgi:error]  File "/var/www/chatbotv1/chatbot_response.py", line 2, in <module>
 [wsgi:error] import nltk
 [wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/__init__.py", line 133
 [wsgi:error]  from nltk.text import *
 [wsgi:error]  File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/text.py", line 30, in <module>
 [wsgi:error] from nltk.tokenize import sent_tokenize
 [wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 66, in <module>
 [wsgi:error] from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
 [wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/tokenize/casual.py", line 38, in <module>
 [wsgi:error] import regex  # https://github.com/nltk/nltk/issues/2409
 [wsgi:error]  File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/__init__.py", line 1, in <module>
 [wsgi:error] from .regex import *
 [wsgi:error]  File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/regex.py", line 404, in <module>
 [wsgi:error]  import regex._regex_core as _regex_core
 [wsgi:error]   File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/_regex_core.py", line 21, in <module>
 [wsgi:error] import regex._regex as _regex
 [wsgi:error]  ModuleNotFoundError: No module named 'regex._regex'

<br/>
Environment (<code>conda list</code>):
<details>
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_tflow_select             2.3.0                       mkl
absl-py                   0.10.0                   py38_0
aniso8601                 8.0.0                      py_0
astunparse                1.6.3                      py_0
blas                      1.0                         mkl
blinker                   1.4                      py38_0
brotlipy                  0.7.0           py38h7b6447c_1000
c-ares                    1.16.1               h7b6447c_0
ca-certificates           2020.7.22                     0    anaconda
cachetools                4.1.1                      py_0
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.3           py38he30daa8_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cryptography              3.1.1            py38h1ba5d50_0
flask                     1.1.2                      py_0
flask-restful             0.3.8                      py_0    conda-forge
gast                      0.3.3                      py_0
google-auth               1.21.3                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
grpcio                    1.31.0           py38hf8bcb03_0
h5py                      2.10.0           py38hd6299e0_1
hdf5                      1.10.6               hb1b8bf9_0
idna                      2.10                       py_0
importlib-metadata        1.7.0                    py38_0
intel-openmp              2020.2                      254
itsdangerous              1.1.0                      py_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0    anaconda
keras-preprocessing       1.1.0                      py_1
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libprotobuf               3.12.4               hd408876_0
libstdcxx-ng              9.1.0                hdf63c60_0
markdown                  3.2.2                    py38_0
markupsafe                1.1.1            py38h7b6447c_0
mkl                       2020.2                      256
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.2.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
ncurses                   6.2                  he6710b0_1
nltk                      3.5                        py_0    anaconda
numpy                     1.19.1           py38hbc911f0_0
numpy-base                1.19.1           py38hfa32c7d_0
oauthlib                  3.1.0                      py_0
openssl                   1.1.1h               h7b6447c_0    anaconda
opt_einsum                3.1.0                      py_0
pip                       20.2.2                   py38_0
protobuf                  3.12.4           py38he6710b0_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.20                       py_2
pyjwt                     1.7.1                    py38_0
pyopenssl                 19.1.0                     py_1
pysocks                   1.7.1                    py38_0
python                    3.8.5                h7579374_1
python-dateutil           2.8.1                      py_0
pytz                      2020.1                     py_0
readline                  8.0                  h7b6447c_0
regex                     2020.7.14        py38h7b6447c_0    anaconda
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.6                        py_0
scipy                     1.5.2            py38h0b6359f_0
setuptools                49.6.0                   py38_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.2.0           mkl_py38h6d3daf0_0
tensorflow-base           2.2.0           mkl_py38h5059a2d_0
tensorflow-estimator      2.2.0              pyh208ff02_0
termcolor                 1.1.0                    py38_1
tk                        8.6.10               hbc83047_0
tqdm                      4.49.0                     py_0    anaconda
urllib3                   1.25.10                    py_0
werkzeug                  1.0.1                      py_0
wheel                     0.35.1                     py_0
wrapt                     1.12.1           py38h7b6447c_1
xz                        5.2.5                h7b6447c_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
$ conda info
     active environment : base
    active env location : /var/www/chatbotv1/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.17
       base environment : /var/www/chatbotv1/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/www/chatbotv1/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /var/www/chatbotv1/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.8.3 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
</details>

Here is the WSGI script

`#!/var/www/chatbotv1/miniconda3/

import sys
import site
site.addsitedir('/var/www/chatbotv1//miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/')
sys.path.insert(0, '/var/www/chatbotv1/')
import os
print(os.listdir('/var/www/chatbotv1'))
from app import app as application
`

Also the configuration file of apache

`LoadModule wsgi_module /usr/lib64/httpd/modules/mod_wsgi.so
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1 python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined

</VirtualHost>
`

**Comment by isuruf** [comment]
Since you are using `defaults` and not `conda-forge`, this is not the correct place to create this issue.
