### ISSUE TITLE
conda-build does not seem to execute tests on Windows

### ISSUE THREAD

**Issue by certik** [conda-forge/conda-forge.github.io#1164]
As reported in https://github.com/conda-forge/lfortran-feedstock/issues/17#issuecomment-705209887, we have a test in `meta.yaml` to run the built executable in `bin/`:

https://github.com/conda-forge/lfortran-feedstock/blob/10fbedd5ca9e8a2be50a41d8a06e1b66d3f68d91/recipe/meta.yaml#L34

But that line does not seem to actually be executed on Windows:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=211496&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1906

The last line that gets executed is is:
```
(%PREFIX%) %SRC_DIR%>if exist %PREFIX%\Library\bin\lfortran.exe (exit 0 )  else (exit 1 ) 
```
That seems like a bug in `conda-build`.

Note that on Linux and macOS that line gets executed:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=211496&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1213

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=211496&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1535

As a result of this bug, or Windows conda package is currently broken: https://github.com/conda-forge/lfortran-feedstock/issues/17 and the executable does not actually run.

**Comment by isuruf** [comment]
This is not the correct issue tracker. As to the problem at hand, don't do `exit 0` which stops the other commands from running.

**Comment by certik** [comment]
Thanks, I think that must be it, I am trying it in https://github.com/conda-forge/lfortran-feedstock/pull/18.

What is the correct issue tracker for this?

**Comment by isuruf** [comment]
https://github.com/conda/conda-build

**Comment by certik** [comment]
Thanks. I wasn't sure it was a bug in `conda-build`, so I posted here first per the conda-forge's official [instructions](https://conda-forge.org/docs/orga/getting-in-touch.html) ("You’ll use this repo as a catch-all for issues where you’re not sure where else to put them").

It turns out it was a bug in my recipe after all.
