### ISSUE TITLE
Permission for @ocefpaf to add conda-forge recipe for qhub.

### ISSUE THREAD

**Issue by dharhas** [conda-forge/conda-forge.github.io#1183]
Issue:

@ocefpaf has created a conda-forge recipe for our new open source project [QHub](https://github.com/Quansight/qhub). Creating this issue to confirm that he has permission to add the recipe to conda forge.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
N/A
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
N/A
```
$ conda info
N/A
```
</details>

**Comment by isuruf** [comment]
We don't actually require permission from upstream to add a recipe to conda-forge, but good to know.

**Comment by ocefpaf** [comment]
> We don't actually require permission from upstream to add a recipe to conda-forge, but good to know.

@isuruf this was a special case and I requested this just to be documented here to avoid annoyances in the future.

**Comment by beckermr** [comment]
I am going to lock this issue so it is preserved.
