### ISSUE TITLE
Clarify contributing older versions of existing packages

### ISSUE THREAD

**Issue by vnlitvinov** [conda-forge/conda-forge.github.io#1192]
Issue: it is slightly unclear how to contribute an older version of already existing package.
The only information I was able to find is [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html#post-staging-process):

> Branches of the main repository are used for maintaining different versions only.

I would suggest to add a separate paragraph there stating the process of contributing an older version.

Current process (based on gitter discussion) is: making an issue or (better) a draft PR to master of existing feedstock and having a maintainer create a branch and re-target the PR on that branch.

**Comment by beckermr** [comment]
This was added in #1231
