### ISSUE TITLE
OSX linker errors trying to update 2 different python/C++ feedstocks

### ISSUE THREAD

**Issue by virgesmith** [conda-forge/conda-forge.github.io#1194]
Issue: see https://github.com/conda-forge/humanleague-feedstock/pull/7
and https://github.com/conda-forge/neworder-feedstock/pull/7

The errors seem identical in both, e.g. from the humanleague PR

I'm trying to update the version of this package and 2 of the builds (both OSX) are failing with:

```
2020-11-07T14:03:44.4972520Z   clang-10: error: -Wl,-export_dynamic: 'linker' input unused [-Werror,-Wunused-command-line-argument]
2020-11-07T14:03:44.4996480Z   error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
2020-11-07T14:03:44.5178070Z   Building wheel for humanleague (setup.py): finished with status 'error'
```

I could silence this by adding -Wno-unused-command-line-argument (if I knew where to put it, which I don't) but it's probably not the best solution anyway. The other OSX build is fine (despite using the same version of clang), but does emit this warning:

```
2020-11-07T14:01:19.6837930Z   ld: warning: -pie being ignored. It is only used when linking a main executable
```

which I'm assuming is relevant. I've no idea where the -fPIE flag has come from, it's not in my setup.py and its not appropriate here as the target is a library? So I'm stumped, can anybody help please?

**Comment by beckermr** [comment]
cc @isuruf - do we need to edit the clang activation scripts or is this a problem in a recipe?

**Comment by isuruf** [comment]
You can ignore the `-fPIE` warning. It's needed for executables and there's no way to specify it for just executables.
To fix the error add `-Wno-unused-command-line-argument` to `CFLAGS` env variable

**Comment by virgesmith** [comment]
@isuruf can you clarify if you mean I do this on my side, or does it belong in the clang activation scripts that @beckermr referred to?

**Comment by isuruf** [comment]
On your side

**Comment by virgesmith** [comment]
Ok, but the -fPIE addition must be a recent change on your side, it's not in my build configuration (which hasnt changed) and the neworder 0.0.8 build was fine less than a month ago. I can fix the problem for my two packages, but isn't this issue likely to come up over and over again in other projects? If you fixed it in your build scripts it would fix the issue for everyone? (Just sayin')

**Comment by isuruf** [comment]
> Ok, but the -fPIE addition must be a recent change on your side, it's not in my build configuration (which hasnt changed) and the neworder 0.0.8 build was fine less than a month ago.

No, it's not. It's been there for at least a couple of years. If you look at the neworder 0.0.8 build in https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/223271/logs/78 it has the warning there.

> isn't this issue likely to come up over and over again in other projects?

Is it so bad to have a harmless warning?

> If you fixed it in your build scripts it would fix the issue for everyone? (Just sayin')

How do you propose that we fix this given my above comment "It's needed for executables and there's no way to specify it for just executables." ?

**Comment by virgesmith** [comment]
If "It's needed for executables and there's no way to specify it for just executables." then you just have `-fPIE -Wno-unused-command-line-argument` in your CFLAGS and everyone is happy? ...Thats what I meant

But fair enough, if neworder 0.0.8 had the *warning* but not the 2 failures, then I wonder if its a red herring that the failures are due to the same warning being promoted to an error? It could be another unused link arg?, sadly clang's error message isn't expliciit. Anyway I'll update one of the packages over the weekend and see if that fixes it...

**Comment by isuruf** [comment]
>  then you just have -fPIE -Wno-unused-command-line-argument in your CFLAGS and everyone is happy?

That'd make `autoconf` scripts go crazy.

> But fair enough, if neworder 0.0.8 had the warning but not the 2 failures, then I wonder if its a red herring that the failures are due to the same warning being promoted to an error? It could be another unused link arg?, sadly clang's error message isn't expliciit. Anyway I'll update one of the packages over the weekend and see if that fixes it...

The only error is the `-Wl,-export_dynamic` being unused. `-fPIE` is a harmless warning. You should remove https://github.com/virgesmith/neworder/blob/master/setup.py#L36 as compiler warnings increase in every new compiler version and then you'll have to have workarounds. You should only add them in your CI scripts.

**Comment by virgesmith** [comment]
all done now, thanks @isuruf
