### ISSUE TITLE
The instruction `conda config --set channel_priority strict` breaks anaconda on fresh install

### ISSUE THREAD

**Issue by changhe3** [conda-forge/conda-forge.github.io#1195]
After a fresh installation of Anaconda, I followed the instruction and run commands:
```
 conda config --add channels conda-forge 
 conda config --set channel_priority strict 
```
Trying to execute `conda update conda` after that will get causes the command stuck in `Solving Environment` for 10 minutes and after that it prints out a huge list of conflicting packages. 

```
 conda config --set channel_priority false
```
fixes said problem.

**Comment by wolfv** [comment]
Try miniforge or miniconda instead of anaconda

**Comment by ocefpaf** [comment]
@changhe3 the Anaconda Distribution has a lot of pre-installed packages. Most of them are not compatible with third party channels or, if compatible, required a lot of churn to find the versions that work nicely with the third party channel. Like @wolfv said, starting from a lighter installer, like minconda or miniforge, may help. Ideally, regardless of the installer, you should always be creating a new environment for new "work context" to avoid mixing packages and long solver times.

**Comment by changhe3** [comment]
Thanks. I will give a try if there're any more troubles.
