### ISSUE TITLE
[docs] Meeting minutes pollute search results

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/conda-forge.github.io#1210]
from #1208:

> - @bollwyvl  as the meeting minutes end up crushing everything.
> - @xhochy  Splitting of the meeting minutes into a separate sounds like a good idea. Maybe we can just make them a second Sphinx site?
> - @ocepaf +1 to that. This has been raise a few times. The current setup makes it really hard to search the docs b/c the returns are mostly the meeting minutes.

This seems like sufficient evidence for doing... something. I'll do a little looking, but off the top of my head:
- as suggested, splitting out the meeting minutes as a separate sphinx site
- configuring the search to ignore the minutes, or offer a second search page
- figure out some kind of faceted search that allows for defaulting to opting out of the minutes in the search

**Comment by bollwyvl** [comment]
This monkeypatch in `conf.py` would allow for keeping them in the site and table of contents (and keeping stable URLs), but hide them in the HTML search. The search engines would continue to pick them up, which is probably fine...

```py
from docutils import nodes
from sphinx.search import IndexBuilder

_feed = IndexBuilder.feed

def feed(self, docname: str, filename: str, title: str, doctree: nodes.document) -> None:
    if "orga/minutes" in docname:
        return
    return _feed(self, docname, filename, title, doctree)

IndexBuilder.feed = feed
```

**Comment by jakirkham** [comment]
Maybe instead of dropping them entirely we could group the search results by topic somehow?

**Comment by bollwyvl** [comment]
I looked into it... The generated js is kind of a mess for compactness
reasons, and has a bunch of things based on array indices, and I wouldn't
feel comfortable hacking that in post.

The indexing is remarkably inflexible, and hard to research because of the
_other_ sphinx search which supports facets and fancy query syntax.

The only plugin I did find didn't really do much for us:

https://github.com/readthedocs/readthedocs-sphinx-search

One thing that _could_ work would be to build the site (with this patch)
and then build it again (with the reverse of the patch) and make a second
search page (or tweak the search.html, which is probably easier to reason
about than the compacted js) to load the other index. I'll give that a
look...

**Comment by bollwyvl** [comment]
Yeah, something like this _basically_ works...

```py
# conf.py
def feed(self, docname: str, filename: str, title: str, doctree: nodes.document) -> None:
    if bool(os.environ.get("INDEX_MINUTES")) != ("orga/minutes" in docname):
        return
    return _feed(self, docname, filename, title, doctree)
```

```bash
# .ci_scripts/update_docs
INDEX_MINUTES=1 make html \
      && mv _build/html/searchindex.js minutesindex.js \
      && rm -rf _build \
      && make html \
      && cp minutesindex.js _build/html/
```

```html
<!-- search.html -->
  <script type="text/javascript">
    jQuery(function() {
      Search.loadIndex(
        window.location.href.indexOf("minutes") !== -1 ?
        "minutesindex.js" :
        "searchindex.js");
    });
  </script>
...
    <label><input type="checkbox" name="minutes"></input> Include Meeting Minutes</label>

```

The size difference is marked, which is nice for making the search feel snappy:
```
-rw-rw-r-- 1 weg weg  37K Dec  7 08:23 _build/html/searchindex.js
-rw-rw-r-- 1 weg weg 118K Dec  7 08:23 _build/html/minutesindex.js

```

**Comment by beckermr** [comment]
I'd support a PR with this change as long as everything is automated.

**Comment by beckermr** [comment]
We should be able to specify a custom search scorer.

https://github.com/conda-forge/conda-forge.github.io/blob/master/docs/_static/searchtools.js#L21

html_search_scorer
The name of a JavaScript file (relative to the configuration directory) that implements a search results scorer. If empty, the default will be used.

I cannot find an example of how to do this though.

**Comment by beckermr** [comment]
here is the PR: https://github.com/sphinx-doc/sphinx/commit/1832284e89435572f778dd3abbd53ef67494cfb5

It looks like you implement the entire score var. We can use the function there to down weight the meeting minutes I think.

**Comment by bollwyvl** [comment]
Looks like a less hacky hack! Will take a look when next i get a chance.

**Comment by bollwyvl** [comment]
Can't keep up with all your efforts! Thanks!
