### ISSUE TITLE
Recipes for builds of software not maintained by the contributor

### ISSUE THREAD

**Issue by padix-key** [conda-forge/conda-forge.github.io#1234]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I would like to contribute a recipe for a software project not maintained by myself. Specifically I would like to add a recipe for https://github.com/schrodinger/pymol-open-source, a project I do not directly contribute to.

However, I did not find a paragraph in the `conda-forge` documentation, whether this is encouraged or discouraged. What is your stance in this situation?

**Comment by synapticarbors** [comment]
Hi @padix-key -- most recipes are contributed by individuals who are not the maintainer of the actual package. It's generally nice to let the author know that you're doing so and ask if they'd like to be a co-maintainer of the recipe, but it is by no means required.

**Comment by padix-key** [comment]
OK, thank you.
