### ISSUE TITLE
Feedstocks still using macOS builds on Travis-CI

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#1237]
This is from November 20 to January 6.

- [ ] conda-forge / gdb-feedstock  
- [x] conda-forge / lastools-feedstock  
- [x] conda-forge / pulsewaves-feedstock  
- [x] conda-forge / cxxopts-feedstock  
- [ ] conda-forge / gmsh-feedstock  
- [x] conda-forge / ocaml-feedstock  
- [x] conda-forge / udunits2-feedstock  
- [x] conda-forge / sfepy-feedstock  
- [x] conda-forge / nspr-feedstock

we should move away from travis-CI for macOS builds and use it only for ppc64le.

cc @conda-forge/core, @conda-forge/gdb, @conda-forge/lastools, @conda-forge/pulsewaves @conda-forge/cxxopts, @conda-forge/gmsh, @conda-forge/ocaml, @conda-forge/udunits2, @conda-forge/sfepy, @conda-forge/nspr.

A simple rerender should switch to azure for macos

**Comment by phil-blain** [comment]
regarding GDB, we need macOS 10.13 unfortunately, because GDB hangs about half the time on 10.14+ (see https://github.com/conda-forge/gdb-feedstock/tree/master/recipe). So I'm not sure what can be done.. apart from just removing the test on macOS.

**Comment by jakirkham** [comment]
AFAICT `nspr` is only using Travis CI for `ppc64le` builds, but please let me know if I'm missing something

**Comment by peterjc** [comment]
This happened last month for ocaml during https://github.com/conda-forge/ocaml-feedstock/pull/22, we have ``.azure-pipelines/azure-pipelines-osx.yml`` replacing ``.travis.yml``

**Comment by zklaus** [comment]
I think conda-forge / udunits2-feedstock was fixed in the mean-time as
part of a version upgrade.

**Comment by jakirkham** [comment]
sfepy was fixed in PR ( https://github.com/conda-forge/sfepy-feedstock/pull/32 )

**Comment by jakirkham** [comment]
`gmsh` seems to [need a specific macOS SDK]( https://github.com/conda-forge/gmsh-feedstock/blob/3fdf61a5519d3db20062094815c07c48f61c9182/recipe/conda_build_config.yaml#L1-L2 ). Not entirely sure the history there. Maybe this can be moved to Azure with a little work? Started this with PR ( https://github.com/conda-forge/gmsh-feedstock/pull/38 ), but may need help from others to complete this.

**Comment by isuruf** [comment]
gmsh and gdb are legitimate uses of travis. Thanks everyone for the help in fixing this issue.
