### ISSUE TITLE
Keep artifacts of feedstock pr's

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/conda-forge.github.io#124]
I'm sorry if that has been discussed before, but I haven't found anything related.

If the feedstock is alive and a PR is issued (eg. change of recipe) then the CI's will build the recipe to see if everything works. If things work nicely, the PR gets merged and all CI's will build the same recipe again. 

Is it possible to just use the already built artifacts? This would make the packages available on time of merge and relieve the CI's substantially.

Would that be possible to realize within the conda-forge workflow?

**Comment by jakirkham** [comment]
Thanks writing this @kmuehlbauer. I have also been thinking about this for some time, but am unsure the correct solution. Some options include

1. Uploading packages to somewhere special on Anaconda.org and then moving them on PR merge.
2. Using CI artifacts to keep these around.

The main issue that we face is less where to put these, but more about how we check the recipe has not changed since the last build. Related is whether the last build completed to generate all binaries or not.

**Comment by pelson** [comment]
> This would make the packages available on time of merge and relieve the CI's substantially.

It would indeed. Down from 2 (```staged-recipes```: pr build, pr merge build [skipped], feedstock creation build; ```feedtock pr```: pr build, merged build) to 1 (pr build, feedstock commit [skipped]).

> Would that be possible to realize within the conda-forge workflow?

It is of course *possible*. I'm not sure it is entirely desirable though - it would require some logic in the feestocks which would be non-trivial and if done without a good deal of care, could easily open up security concerns for the build binaries.

In terms of my own workload, I believe there are easier/quicker wins which we can achieve for conda-forge right now.

**Comment by jakirkham** [comment]
To summarize the concerns:

1. Provenance
2. Caching

**Comment by kmuehlbauer** [comment]
@jakirkham, @pelson I appreciate your comments and concerns.

We should definitely not introduce security problems inside the conda-forge workflow. 

If I understand [Labels](http://docs.anaconda.org/using.html#Labels) correctly, we could upload packages from a PR and label them as eg. `dev` or `pr`. Those packages would not be delivered by `conda`, unless the user specifies the label.

It the PR gets merged, the package label should be set from `pr` to `main` to make it available in the normal `conda install`. For correct differentiation of the packages, we could have the label be like `pr_#`, where `#` is the feedstocks PR number (there are certainly hundreds of possibilities to do this). 

When merging a PR the *logic* within the feedstocks needs to check if there is already a 'pr'-version at anaconda cloud and use that (relabel). We could also think about having a kind of switch in the merge commit like `[relabel pr]`, to explicitely use the already built package.

One thing that might also become valuable is that those 'pr' packages can be tested by developers in live environments (not CI) before they move into anacondas `main`-label channel. This can be really have impact, when investigating runtime problems etc.

However, I acknowledge that this has not highest priority. But I really like to hear more opinions.

**Comment by kmuehlbauer** [comment]
> One thing that might also become valuable is that those 'pr' packages can be tested by developers in live environments (not CI) before they move into anacondas main-label channel. This can be really have impact, when investigating runtime problems etc.

It seems that this part is discussed in #147.  @pelson Can we somehow combine this?

If #147 takes over, we can close this one down.

**Comment by pelson** [comment]
> If #147 takes over, we can close this one down.

Sure. But does that cover your usecase? In #147 we are talking about pre-release versions, but the subject here was simply build-artefacts, no?

**Comment by kmuehlbauer** [comment]
You're right. This doesn't match exactly.

**Comment by jakirkham** [comment]
This isn't quite what this was initially about, but maybe it is coming around in that direction. Have been thinking of staged-releases to improve stability and make early builds available sooner. Please see this [hackpad]( https://conda-forge.hackpad.com/Staged-Releases-DZNKZdgiMbF ) for an outline and issue ( https://github.com/conda-forge/conda-forge.github.io/issues/204 ) for some discussion.

**Comment by jaimergp** [comment]
Is this still being considered? I saw that `staged-recipes` now publishes the artifacts in Azure, which is really useful when we want to debug packages prior to `main` release. Could [this](https://github.com/conda-forge/staged-recipes/blob/master/.azure-pipelines/azure-pipelines-linux.yml#L30-L31) be added to `conda smithy` [templates](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/azure-pipelines-linux.yml.tmpl), maybe as an opt in choice via `conda-forge.yml`?

**Comment by kmuehlbauer** [comment]
I think my original request is resolved somehow.
