### ISSUE TITLE
Add index of CFEPs

### ISSUE THREAD

**Issue by beenje** [conda-forge/conda-forge.github.io#1241]
I think it would be nice to have an index of CFEPs in the main documentation.

Even when the main content of a CFEP has been included in the docs, CFEPs provide useful information. They are not very easy to find today. An index would ease that.
It would be good if this was automated but I don't really see how it would fit with the sphinx documentation. On the other side, there aren't that many CFEPs. Updating the index manually should be fine.

If there is interest, I could make a PR.

**Comment by beckermr** [comment]
Please do!
