### ISSUE TITLE
Team management probably race conditioning

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#125]
https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/128283830

In particular:

```
Prefix: /home/travis/conda/tmp_envs/0a2f51c4c88b9dcaf16e
Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py", line 108, in <module>
    [repo])
  File "/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py", line 62, in create_team
    input=post_parameters
  File "/home/travis/conda/tmp_envs/0a2f51c4c88b9dcaf16e/lib/python3.5/site-packages/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/travis/conda/tmp_envs/0a2f51c4c88b9dcaf16e/lib/python3.5/site-packages/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {'message': 'Validation Failed', 'errors': [{'code': 'already_exists', 'field': 'name', 'resource': 'Team'}], 'documentation_url': 'https://developer.github.com/v3/orgs/teams/#create-team'}
CalledProcessError: Command '['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', 
```

Truth be told, we don't need to be running this script so frequently anyway (once an hour would be fine). I will take a look at doing this with heroku.

**Comment by jakirkham** [comment]
I think I agree. Adding people immediately doesn't seem to be super necessary. Also, this strikes a healthy balance of handling team additions in existing feedstocks vs new ones.

Should also help cut down GitHub API throttling. Though at this point running the team script once is enough to stop us from feedstocking for ~20mins.

**Comment by pelson** [comment]
Additionally we can use the ephemeral filesystem to debounce the requests if necessary.

**Comment by jakirkham** [comment]
We have restructured things so this runs once per day. Though merges here still trigger it. ( https://github.com/conda-forge/conda-forge.github.io/issues/214 ) Would be great if we could eliminate that cause too. In any event, closing this as effectively resolved.
