### ISSUE TITLE
add bootstrapping variable to conda_build_config.yaml

### ISSUE THREAD

**Issue by ilanschnell** [conda-forge/conda-forge.github.io#1256]
During the process of bootstrapping packages to a new architecture, it is sometimes necessary to build packages in bootstrapping mode. For example, when the full functionality of the package isn't available yet, but the package is necessary to build other packages will make the full functionality available later (in a regular non-bootstrapping) build.

In order to decide whether or not a build is run in bootstrapping mode, I suggest adding a new variable to `conda_build_config.yaml` named bootstrapping whose value is either "yes" or "no".

For more details, see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1187

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by beckermr** [comment]
We have a GitHub discussion going on this. Maybe close this in favor of that?

**Comment by jakirkham** [comment]
Issues are a bit easier to see on mobile. Is there a reason a discussion was preferred over an issue?

**Comment by ocefpaf** [comment]
> We have a GitHub discussion going on this. Maybe close this in favor of that?

Can we post the link to it here? I tend to agree with the mobile friendly argument, specially lately since I work at least half-day on mobile only.

**Comment by jakirkham** [comment]
I think this is it ( https://github.com/conda-forge/conda-forge.github.io/discussions/1255 )

**Comment by ilanschnell** [comment]
Closing in favor of: https://github.com/conda-forge/conda-forge.github.io/discussions/1255
