### ISSUE TITLE
Add section to docs about empty packages for specific python versions

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1270]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

There are some packages in python that include features added to later python versions like dataclasses and typing_extensions.

Originally, they could only be installed under specific python versions which meant that packages that depend on those cannot be `noarch: python`. This has been solved by creating empty packages for specific python versions like in [dataclasses](https://github.com/conda-forge/dataclasses-feedstock/blob/master/recipe/meta.yaml) and [typing](https://github.com/conda-forge/typing-feedstock/blob/master/recipe/meta.yaml).

If this is something that will become more widespread, it might be good to have his mentioned in the docs as new maintainers are normally not aware of this (One example is [here](https://gitter.im/conda-forge/conda-forge.github.io?at=5ebfd4d0aac441316a801b28) and another one was me 😄).

**Comment by beckermr** [comment]
PRs welcome!

**Comment by BastianZim** [comment]
Will do! Is there a database somewhere? If not, might make sense since that could also be read by Grayskull when creating recipes.

**Comment by BastianZim** [comment]
And I assume this should be under https://conda-forge.org/docs/maintainer/knowledge_base.html correct?

**Comment by BastianZim** [comment]
@beckermr Just gently bumping this again.

**Comment by beckermr** [comment]
Sorry I missed these messages! Yes, those sections above are fine. We do not have a database.

**Comment by BastianZim** [comment]
Ok no worries, then I'll just add something to the docs.
