### ISSUE TITLE
Some packages are not shown in the website search

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1285]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Some packages are not listed at https://conda-forge.org/feedstock-outputs/ despite them being available.

I have not yet been able to find a pattern but the following is missing:

- python-wget – https://github.com/conda-forge/python-wget-feedstock

**Comment by beckermr** [comment]
Any package that has not been built in the past ~1.5 years would likely not have registered its outputs and so won't appear.

**Comment by BastianZim** [comment]
Ahh ok, thanks for the info!
