### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by TinoMako** [conda-forge/conda-forge.github.io#1287]
Conda supports other languages other than Python. I believe the languages should be listed in the documentation so that people get aware of this. 
Languages supported
Perl
Fortran
Go
C++
R
C
Python
Polyglot
Rust
Ocaml
Lisp
Ruby

And more?

**Comment by viniciusdc** [comment]
cc @conda-forge/core

**Comment by beckermr** [comment]
We should probably define what we mean by "support" here? For example, in some cases we provide compilers but not actual packages (e.g., rust) because the language itself has a separate packaging infrastructure.

**Comment by viniciusdc** [comment]
@TinoMako would you mind closing this issue and open a PR instead? see this [comments](https://github.com/conda-forge/conda-forge.github.io/issues/986#issuecomment-811249672)
