### ISSUE TITLE
Document how to use `mambabuild`

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1290]
https://gitter.im/conda-forge/conda-forge.github.io?at=602417279fa6765ef80e6bf4

I think we need to add
1. How to enable it in CI: IIUC we need `build_with_mambabuild: True` in `conda-forge.yaml`
2. How to use it locally for debugging: `conda mambabuild ...`

cc: @wolfv

**Comment by wolfv** [comment]
hi @leofang, thanks for opening this issue! Yes, it would be great to have some docs around this. Are you willing to write something up?

For conda-forge:

- add build_with_mambabuild: True to conda-forge.yaml, then _rerender_ . also important to note: the builds made with mambabuild won't (and probably shouldn't) be uploaded to conda-forge, this is purely for debugging (for now)
- locally, first: `{conda,mamba} install boa -c conda-forge`, then you can use `conda mambabuild myrecipe`

**Comment by leofang** [comment]
Thanks, @wolfv. I posted this mainly to prevent it from being forgotten. If someone is interested in writing it up, that couldn't be better. Otherwise, I could pick it up at some point (definitely not this week) 🙂

**Comment by Aaishpra** [comment]
@wolfv @leofang if you allow I would like to give this issue a try as an outreachy internship applicant.
Since this is my first time with conda-forge I would appreciate it if you can guide me on how to approach this issue. 🙌🏻

**Comment by jakirkham** [comment]
@viniciusdc, is the contact point for Outreachy. Cc-ing him here

**Comment by leofang** [comment]
@ForgottenProgramme asked me about `mambabuild` offline, I think she's also interested in contributing. I'll let you coordinate..

**Comment by Aaishpra** [comment]
Sure👍🏻 I am good with anything.

**Comment by jakirkham** [comment]
I think people are interested in trying to use `mambabuild`. However there's not really documentation covering this currently. Unfortunately that's about all the context I have here as this is not an issue I've been following too closely

**Comment by viniciusdc** [comment]
@ForgottenProgramme @Aaishpra any news on this ?

**Comment by ForgottenProgramme** [comment]
Yes, @viniciusdc. 
I've been reading about mamba-build. 
I realized the conda-forge docs do not have any section dedicated to mamba. I think we need one. Therein we put steps to config mamba with conda-forge, and how to enable it in CI and so on.

**Comment by ForgottenProgramme** [comment]
Also, @leofang had suggested the 'Knowledge Base' page in the maintainer docs might be a good place for adding 'mamba' section. 

https://conda-forge.org/docs/maintainer/knowledge_base.html

**Comment by viniciusdc** [comment]
> Also, @leofang had suggested the 'Knowledge Base' page in the maintainer docs might be a good place for adding 'mamba' section.
> 
> https://conda-forge.org/docs/maintainer/knowledge_base.html

I agree

**Comment by ForgottenProgramme** [comment]
For future reference (whenever work on mamba docs begins full fledged): 

@wolfv 's  blog that answers 'what to do if conda is too slow/ why mamba?' : https://wolfv.medium.com/making-conda-fast-again-4da4debfb3b7

Information about the mamba organization and how mamba actually works under the hood : https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23

(Although we might not need to include this information in conda-forge docs(atleast not in detail). It's correct place would be mamba-org's own docs. It might still be helpful to read this before beginning documentation around mamba. )

**Comment by ForgottenProgramme** [comment]
Link to the Gitter chat on this issue. Could be useful later. 

https://gitter.im/conda-forge/conda-forge.github.io?at=60742f23ae90f3684077029e

**Comment by leofang** [comment]
Closed by #1353. Related: #1381.
