### ISSUE TITLE
Conda-forge logo link to Homepage

### ISSUE THREAD

**Issue by SehrishHussain** [conda-forge/conda-forge.github.io#1292]
The conda-forge logo on [**DOCS**](https://conda-forge.org/docs/) and [**BLOG**](https://conda-forge.org/blog/) page should be linked to [**Homepage**.](https://conda-forge.org/) 

There is no other option to go back to homepage other than clicking browser's back button.

**Comment by ocefpaf** [comment]
Indeed. Those three pages started independently and we never really tied them together as we should. Thanks!!

**Comment by Aaishpra** [comment]
Can I take this Up?
cc: @ocefpaf

**Comment by viniciusdc** [comment]
HI @Aaishpra great, go for it. I will assign this for you then

**Comment by Aaishpra** [comment]
Thanks 😄

**Comment by Aaishpra** [comment]
@viniciusdc just confirming if this is the right [file](https://github1s.com/conda-forge/conda-forge.github.io/blob/master/docs/index.html) to make changes for `docs`.
And, the `contact` and `news` section also doesn't contain links to go back to the homepage. Shall I add links on those pages to including `blog` and `docs`

**Comment by viniciusdc** [comment]
> @viniciusdc just confirming if this is the right [file](https://github1s.com/conda-forge/conda-forge.github.io/blob/master/docs/index.html) to make changes for `docs`.
> And, the `contact` and `news` section also doesn't contain links to go back to the homepage. Shall I add links on those pages too including `blog` and `docs`

Hi @Aaishpra thanks for the comment. Actually the correct docs contents are inside the `src` directory (the one you pointed is build by our internal process). For the proposed ideas, feel free to create a PR with those additions and ping me there!

**Comment by viniciusdc** [comment]
Also, before submitting the PR try it locally to check if the changes are correct rendered, see more information [here](https://conda-forge.org/docs/user/contributing.html#improving-the-documentation)

**Comment by Aaishpra** [comment]
@viniciusdc I am a bit confused about how to add links to the logo, for example, I tried adding the links in the HTML files in the src, but it isn't showing in my additions in Git although the link works correctly when I serve the page on localhost. (see line 121)
![image](https://user-images.githubusercontent.com/66299533/113243968-ab053f00-92d1-11eb-918b-5afc950130de.png)
And I see no logo and image on.`.rst` files

**Comment by prachi237** [comment]
@Aaishpra  actually these are auto generated html files, I too thought that we have to make changes in the html file but all we need to do is to modify the .rst files in src folder wherever needed. Sphinx will automatically convert that into html file in docs.
I too had been thru such confusion yester night 😅

**Comment by Aaishpra** [comment]
Thanks, @prachi237 for helping.
@viniciusdc I couldn't find any way to link the logos to go back to the home page instead I added this at the bottom of every page, by making changes in `.rst` files.
If this feels correct to you shall I go forward with a PR?
![image](https://user-images.githubusercontent.com/66299533/113253057-5c13d580-92e2-11eb-809b-df0dedf5a5b2.png)

**Comment by viniciusdc** [comment]
> Thanks, @prachi237 for helping.
> @viniciusdc I couldn't find any way to link the logos to go back to the home page instead I added this at the bottom of every page, by making changes in `.rst` files.
> If this feels correct to you shall I go forward with a PR?
> ![image](https://user-images.githubusercontent.com/66299533/113253057-5c13d580-92e2-11eb-809b-df0dedf5a5b2.png)

Great @Aaishpra go for it! Also, if possible could you try add more space between the bottom and the search bar (only if you think that i would be easy)

**Comment by viniciusdc** [comment]
> @viniciusdc I am a bit confused about how to add links to the logo, for example, I tried adding the links in the HTML files in the src, but it isn't showing in my additions in Git although the link works correctly when I serve the page on localhost. (see line 121)
> ![image](https://user-images.githubusercontent.com/66299533/113243968-ab053f00-92d1-11eb-918b-5afc950130de.png)
> And I see no logo and image on.`.rst` files

Was you able to build these changes locally then? By your comment you changed it inside the `src` file right? Could you please add a PR with these changes then? As commented above, some changes will only be visible in GIthub docs folder (and consequently at the docs page) once our automated service runs and build them

**Comment by Aaishpra** [comment]
> 
> Was you able to build these changes locally then? By your comment you changed it inside the `src` file right? Could you please add a PR with these changes then? As commented above, some changes will only be visible in GIthub docs folder (and consequently at the docs page) once our automated service runs and build them

Since I added those changes in `.html` files I can't commit those files, which means git doesn't show my additions in the file.
Maybe since those files are autogenerated that's why 🤔
