### ISSUE TITLE
[Missing module errors] Make html command, to build docs, produces errors.

### ISSUE THREAD

**Issue by tab1tha** [conda-forge/conda-forge.github.io#1294]
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Building docs using instructions in README file after forking and cloning repo produces `ModuleNotFound` errors.

I forked and cloned the conda-forge codebase forty minutes ago and as I proceeded to build the docs following the instructions outlined in the README file, I received a `ModuleNotFound` error when I ran the `make html` command.
I then tried to install sphinx, thinking that sphinxcontrib-newsfeed will be installed with it by default but that did not work because the error persisted even after the installation of sphinx was complete. Therefore, I uninstalled sphinx using `conda remove sphinx`.

Trying `conda install sphinxcontrib-newsfeed` produces a `PackageNotFound` error so I install it instead with `pip install sphinxcontrib-newsfeed`. Then I ran `make html` again and received a Configuration error as such.

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/tab1tha/anaconda3/envs/conda-forge-docs/lib/python3.9/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/home/tab1tha/anaconda3/envs/conda-forge-docs/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/tab1tha/Documents/conda-forge.github.io/src/conf.py", line 19, in <module>
    import cloud_sptheme as csp
ModuleNotFoundError: No module named 'cloud_sptheme'

make: *** [Makefile:58: html] Error 2

 <br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
active environment : conda-forge-docs
    active env location : /home/tab1tha/anaconda3/envs/conda-forge-docs
            shell level : 2
       user config file : /home/tab1tha/.condarc
   populated config files : 
          conda version : 4.9.2
   conda-build version : 3.20.5
         python version : 3.8.5.final.0
   virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
   base environment : /home/tab1tha/anaconda3  (writable)
   channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
   package cache : /home/tab1tha/anaconda3/pkgs
                          /home/tab1tha/.conda/pkgs
   envs directories : /home/tab1tha/anaconda3/envs
                          /home/tab1tha/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.3.0-53-generic 
   elementary/5.1.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

</details>

I want to delete the repo and start the process again. However, it will be really helpful if I can receive any pointers on what I did wrong so that I do not repeat it again.

**Comment by beckermr** [comment]
Those docs are out of date. See the ci scripts in the repo.

**Comment by tab1tha** [comment]
Thank you !. I will proceed to check those

> Those docs are out of date. See the ci scripts in the repo.

**Comment by viniciusdc** [comment]
I am closing this issue as #1302 match the specifications for the correct approach to build the docs. Thanks everyone
