### ISSUE TITLE
Better layout configs. 

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1300]
building the docs repo locally:
<br>-Their is a scope of improving the  Readme docs file, in docs it can be made more eloquent. 
![Screenshot (79)](https://user-images.githubusercontent.com/72700861/113113811-4d68e800-9228-11eb-819a-5528cb6ac83b.png)

-If we share the info step by step, then  we can make it more user friendly and comprehensible.
<br>-The idea is to add bullet points, this will enable clarity for each and every steps that is to be followed.
<br>https://conda-forge.org/docs/maintainer/00_intro.html

**Comment by prachi237** [comment]
@viniciusdc  sir  kindly please review this,  I had already improved the docs if u approve this issue I will send the PR

**Comment by viniciusdc** [comment]
> @viniciusdc sir kindly please review this, I had already improved the docs if u approve this issue I will send the PR

Hi @prachi237, this looks good! please feel free to make the PR and I will review it further. Next time, feel free to open the PR directly :smile:
