### ISSUE TITLE
Glossary Section Modifications

### ISSUE THREAD

**Issue by PrernaSingh587** [conda-forge/conda-forge.github.io#1301]
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
https://conda-forge.org/docs/misc/00_intro.html
In this, the Glossary Section contains some abbreviations of whose only full forms have been written. I think it would be nice if we also provide brief definitions about each one of them and provide a link wherever required and appropriate in the Docs.

**Comment by brngylni** [comment]
I can work on this

**Comment by PrernaSingh587** [comment]
> I am an Outreachy Applicant and I can work on this.

Hi, I am currently working on this.
