### ISSUE TITLE
Outreachy 2021 Hall

### ISSUE THREAD

**Issue by viniciusdc** [conda-forge/conda-forge.github.io#1306]
Hi everyone thanks for your interest within conda-forge and our project ["Documenting the conda-forge ecosystem"](https://www.outreachy.org/outreachy-may-2021-internship-round/communities/conda-forge/documenting-the-conda-forge-ecosystem/cfp/). As you will definitely notice, our community is really eclectic and in constant growth. That said, here are some directions for the new applicants:

- First, don't forget to ping me in a private chat on [Gitter](https://gitter.im/), if you have any questions, doubts or concerns feel free to ask here or with me directly :smile: to ping me just write @viniciusdc and I will be notified
- [Here](https://conda-forge.org/blog/posts/2021-02-02-Outreachy/) are some initial directions about the project and the community. There you can find some initial tasks and issues for Outreachy, feel free to ping me for any doubts. 

- Once you find something you would like to work on, please ping me there because I need to add some labels and assign you to it! It helps us to track the issue progress.
- The main issue pages are: [this one](https://github.com/conda-forge/conda-forge.github.io/issues) for general contributions and the docs. See for instance the issues labeled as **Docs** and **Outreachy** (also check if the issue already haven't someone assigned to it)
- **IMPORTANT!** Once you create your first PR (even if it's not merged yet) don't forget to submit it to the [contributions page](https://www.outreachy.org/outreachy-may-2021-internship-round/communities/conda-forge/documenting-the-conda-forge-ecosystem/contributions/) of the Outreachy project. As part of the application process, all applicants must make at least one contribution to be accepted as an intern for this project. Only applicants who make a contribution will be eligible to be accepted as interns.

## Outreachy Deadlines

- March 29, 2021 | Contribution period begins
- April 30, 2021 | Contribution period ends
- April 30, 2021 at 4pm UTC | Final application deadline

This issue was created due to the great increase in applicants for this Round of Outreachy. All of you feel free to tag along too!

Some useful links:
- How to improve the docs: https://conda-forge.org/docs/user/contributing.html#improve-docs
- Contributing new packages: https://conda-forge.org/docs/maintainer/adding_pkgs.html
- The role of a mainteiner: https://conda-forge.org/docs/maintainer/updating_pkgs.html
- Conda-forge introduction: https://conda-forge.org/docs/user/introduction.html
- repo for docs: https://github.com/conda-forge/conda-forge.github.io/tree/master/src

All changes in the docs **must** be made in the `src` directory. Nice to meet you all :smiley:

**Comment by viniciusdc** [comment]
@Martins-O-U @PrernaSingh587  @prachi237   @bashirk  @ForgottenProgramme @jenniferokafor @Uttam-Singhh @SanchiMittal @cmgraser @victory-lydia  @2001asjad @angeloobeta @neha-b2001

**Comment by viniciusdc** [comment]
As conda-forge continuously modifies it's  structure or enhances it further, some discussions, errors and also tools developed by us were badly documented or, in the worst case, weren't  documentation at all. For this purpose, digging our issues,  docs (to check if there is outdated information) and even the Gitter channels is a great direction to go when attempting to modify our documentation. Also, modifying it to be of a better use for new users, maintainers and a friendly looking are also part of this project. A hope this might clarify some parts of this project and help you with all of your proposals.

**Comment by beckermr** [comment]
closing so we can move on to 2022
