### ISSUE TITLE
Reword the Why conda-forge section

### ISSUE THREAD

**Issue by bashirk** [conda-forge/conda-forge.github.io#1307]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The first paragraph of the `Why conda-forge?` section of the [introduction page](https://conda-forge.org/docs/user/introduction.html#why-conda-forge) should be reworded.

- `Anaconda, Inc` should follow the abbreviation format for the `Incorporated` word.
- Additional commas might be added for an appropriate structure of the paragraph.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
Looks like that PR was merged. So going to go ahead and close. Though happy to reopen if there are other issues still pending resolution. Thanks for your help 🙂
