### ISSUE TITLE
Update the Glossary in the Miscellaneous section of Conda-forge documentation

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1315]
![Screenshot (93)](https://user-images.githubusercontent.com/72700861/113492596-1f202c80-94f6-11eb-8994-b9a0c8e58feb.png)
I had a glance over this section and what I observed that only  `ABI` is highlighted (colored yellow) while other keyword that are mentioned in the glossary like `CL` , `PR`, `CDT` are not highlighted. 
This is causing a non-uniformity in the section hence causing visual imbalance. Either the highlight has to be removed or all the keywords are to be highlighted.

**Comment by prachi237** [comment]
@beckermr  and @viniciusdc  shall  I remove the highlight or shall I add in all of them. But before that I would like to know if it is intentionally highlighted or it is by default😅

**Comment by viniciusdc** [comment]
> @beckermr  and @viniciusdc  shall  I remove the highlight or shall I add in all of them. But before that I would like to know if it is intentionally highlighted or it is by default😅

Hi @prachi237 this is probably because the link you are using, if you go directly to the miscellaneous page by https://conda-forge.org/docs/misc/00_intro.html you will observer that there is not high-tech text

**Comment by prachi237** [comment]
> > @beckermr  and @viniciusdc  shall  I remove the highlight or shall I add in all of them. But before that I would like to know if it is intentionally highlighted or it is by default😅
> 
> Hi @prachi237 this is probably because the link you are using, if you go directly to the miscellaneous page by https://conda-forge.org/docs/misc/00_intro.html you will observe that there is no highlighted text there

my bad😥😓

**Comment by viniciusdc** [comment]
> > > @beckermr  and @viniciusdc  shall  I remove the highlight or shall I add in all of them. But before that I would like to know if it is intentionally highlighted or it is by defaultsweat_smile
> > 
> > 
> > Hi @prachi237 this is probably because the link you are using, if you go directly to the miscellaneous page by https://conda-forge.org/docs/misc/00_intro.html you will observe that there is no highlighted text there
> 
> my bad sorry for the inconvenience

No problem, I am glad you are reviewing the docs :smile:
