### ISSUE TITLE
Proposal for Better documentation  for  ``becoming involved`` in user documentation section.

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1319]
The  documentation done in this section could have been more formal in the sense of expressing the contribution guidelines. It should have standard punctuation, and a third-person perspective.
https://conda-forge.org/docs/user/contributing.html .

**Comment by prachi237** [comment]
I have edited the document and the changes that I made are as follows:
![Screenshot (102)](https://user-images.githubusercontent.com/72700861/113519865-9c0ddd80-95ac-11eb-8bdf-8d535d3b640d.png)
![Screenshot (103)](https://user-images.githubusercontent.com/72700861/113519874-a7610900-95ac-11eb-88f3-9d470c009d67.png)

let me know if this sound good,  I will send the PR

**Comment by viniciusdc** [comment]
uhm... I liked your changes, but I do prefer the original title "Becoming involved", and kind of prefer a more informal way of talking here (we really are happy to see someone interested in contributing, so we don't want to scare them)

**Comment by viniciusdc** [comment]
I'm closing this issue as #1320 corresponds to our necessities.

**Comment by viniciusdc** [comment]
I'm closing this issue as #1320 corresponds to our necessities.
