### ISSUE TITLE
What is the policy on adding a conda recipe for a project that I am not the maintainer of?

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#133]
So we have a lot of dependencies in our stack at NSLS-II.  For example, we use the enaml stack (enaml, atom and kiwi) for at least one GUI.  I am happy to manage feedstocks for those projects, but I am only affiliated with them as a user.  Is the recommended approach to post an issue on these three projects and ask for their blessing on maintaining a conda-forge feedstock for those three projects?

**Comment by msarahan** [comment]
Usually it's nice to add the maintainer as a recipe-maintainer, then ping them in the addition PR.  Sometimes they respond.  Look through some of @jakirkham's merged PR's - he has good text for this message that you can copy/paste.

You don't need a blessing, by any means, but it's nice to involve them where they want to be involved.

**Comment by ericdill** [comment]
Ok, great thanks @msarahan . I'll do what you suggest and ping them in the PR with the text from @jakirkham
