### ISSUE TITLE
Explain how to become a maintainer

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1331]
Was searching for [`recipe-maintainers` in the docs]( https://conda-forge.org/docs/search.html?q=recipe-maintainers ), but found nothing. This should come up when explaining how to become a recipe maintainer for a feedstock, but it doesn't seem to. Would be good to spell this out more clearly. Some places to add this

* https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml (add "extra" section spelling this out)
* https://conda-forge.org/docs/maintainer/updating_pkgs.html (add "Becoming a maintainer")
* https://conda-forge.org/#update_recipe (we suggest becoming a maintainer, but don't say how; could add a link)
* ?

**Comment by jakirkham** [comment]
cc @viniciusdc

**Comment by prachi237** [comment]
@jakirkham thanks for opening this issue, I would like work on it.

**Comment by jakirkham** [comment]
That would be great Prachi! 😄

I'll let Vini chime in on next steps here 🙂

**Comment by prachi237** [comment]
> Was searching for [`recipe-maintainers` in the docs](https://conda-forge.org/docs/search.html?q=recipe-maintainers), but found nothing. This should come up when explaining how to become a recipe maintainer for a feedstock, but it doesn't seem to. Would be good to spell this out more clearly. Some places to add this
> 
> * https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml (add "extra" section spelling this out)
> * https://conda-forge.org/docs/maintainer/updating_pkgs.html (add "Becoming a maintainer")
> * https://conda-forge.org/#update_recipe (we suggest becoming a maintainer, but don't say how; could add a link)
> * ?

what I inferred , so basically we r supposed to add three more  sections so that while searching for  ``recipe-maintainers`` in the docs we can avail those sections too.

**Comment by prachi237** [comment]
> That would be great Prachi! 😄
> 
> I'll let Vini chime in on next steps here 🙂

Thanku sir it would be a great help if I can get some more info abt it.

**Comment by jakirkham** [comment]
> > Was searching for [`recipe-maintainers` in the docs](https://conda-forge.org/docs/search.html?q=recipe-maintainers), but found nothing. This should come up when explaining how to become a recipe maintainer for a feedstock, but it doesn't seem to. Would be good to spell this out more clearly. Some places to add this
> > 
> > * https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml (add "extra" section spelling this out)
> > * https://conda-forge.org/docs/maintainer/updating_pkgs.html (add "Becoming a maintainer")
> > * https://conda-forge.org/#update_recipe (we suggest becoming a maintainer, but don't say how; could add a link)
> > * ?
> 
> what I inferred , so basically we r supposed to add three more sections so that while searching for `recipe-maintainers` in the docs we can avail those sections too.

Probably 2 sections and then a link from the homepage to the becoming a maintainer section

That said, don't want to prescribe this too much in case you have other thoughts on how to improve clarity here

**Comment by viniciusdc** [comment]
I do think that is a lot to be done, here for instance we need to annex the comments of staged recipes to it too, as also a better understanding of maintaining already built packages. The first step here would be determining a good starting location: as @jakirkham said https://conda-forge.org/docs/maintainer/updating_pkgs.html  this would be a good place to start, then a PR with some really brief introduction to the mainterner role (it's already written somewhere) the some explanation about our policies of requesting to be a package maintainer and how to do that once approved (`recipe` updates and so on)

**Comment by viniciusdc** [comment]
once that is done, we can add links to the relative sections and main page (there are some issue opened about maintaining docs too, it should be good have a look into them, maybe it might help)

**Comment by prachi237** [comment]
@viniciusdc  can u help me with this issue, what the first step I shd take to begin with this. like I got it that I am supposed to add two  more sections ,followed by link  but I am a bit confused from where to start with.

**Comment by viniciusdc** [comment]
> @viniciusdc can u help me with this issue, what the first step I shd take to begin with this. like I got it that I am supposed to add two more sections ,followed by link but I am a bit confused from where to start with.

Hi @prachi237, I think the first step would be creating a PR describing how to become a mainteiner in https://conda-forge.org/docs/maintainer/updating_pkgs.html. (Add a new section there). About the content, we can discuss more about it later, I would also like to link that to the [maintainer roles](https://conda-forge.org/docs/maintainer/updating_pkgs.html#important-notes). Also, as there is no previous mention about what is a maintainer in that section the note there seems to be referring to something not completely defined. 

I think you may start with this text https://conda-forge.org/docs/orga/guidelines.html#becoming-a-maintainer and enhancing it a little bit more to explain that besides maintaining already existing packages, you are a maintein when creating one too.

**Comment by ssurbhi560** [comment]
Hi @jakirkham, there is a section in the docs now : [Becoming a maintainer](https://conda-forge.org/docs/orga/guidelines.html#becoming-a-maintainer) which briefly explains how to become a maintainer. Would you suggest adding something more to this, or is it enough and we can consider this issue solved?

**Comment by viniciusdc** [comment]
@ssurbhi560 indeed the new addition would close this issue, but I also would like to:
- see a link to the [Become a mantainer](https://conda-forge.org/docs/orga/guidelines.html#becoming-a-maintainer) section  in https://conda-forge.org/#update_recipe;  
- and as suggested by @jakirkham, maybe adding a link to https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list in a new `extra` section [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml) 

would satisfy all requirements suggested.

**Comment by ssurbhi560** [comment]
Hi @viniciusdc! These would be some great additions. I will open a PR with these changes.

**Comment by ssurbhi560** [comment]
@jakirkham @viniciusdc, I have opened the PRs with the remaining changes that you folks suggested. Please review those changes and let me know if there is something more that needs to be done

**Comment by kathatherine** [comment]
@beckermr This one can also be closed
