### ISSUE TITLE
FAQ link is not working

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1334]
This is an easy one:
https://github.com/conda-forge/conda-forge.github.io/blob/bceba6e91eb7b404814d88b6a2c87d631c5699b0/src/user/faq.rst#L76
The hyperlink to "(Q)" is not working, see the rendered page:
https://conda-forge.org/docs/user/faq.html

**Comment by PrernaSingh587** [comment]
Can I take this up?

**Comment by leofang** [comment]
Closed by #1338.
