### ISSUE TITLE
Misleading documentation title

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1336]
I am referring to this page in particular: https://conda-forge.org/docs/user/ci-skeleton.html. The title is "Using conda-forge to manage your CI", but it is unclear to me since when is Conda-Forge doing this for us? See #1277 for a discussion on the renewed definition of "Conda-Forge".

I'd suggest to change it to "Using **conda-smithy** to manage your CI", but if someone has a better suggestion please go for it.

**Comment by leofang** [comment]
cc @viniciusdc

**Comment by Aaishpra** [comment]
@leofang can i take this up?

**Comment by Aaishpra** [comment]
We can use "Using conda-smithy to manage your CI" or "How to use conda-smithy to manage your CI" as titles.

**Comment by viniciusdc** [comment]
@Aaishpra would you mind oppening a PR for that change and link to this issue?

**Comment by Aaishpra** [comment]
Yup sure will send the PR as soon as i get to work.
