### ISSUE TITLE
"Code of Conduct" and "Reporting Guidelines"

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1346]
I was reading the conda-forge docs, In the Governance section I found the code of conduct, but what I feel is we must link the code of conduct or can write them in brief and add in the readme.md file.  Any contributor who would be visiting the page will be reading the readme.md file first and they shd be well aware of the code of conduct and reporting guidelines, and the consequences incase that is violated.

Not sure if this can be implemented, but I would like to know ur views on this

**Comment by jakirkham** [comment]
It's ok to keep this open. It will just take feedback from @conda-forge/core to move forward

**Comment by beckermr** [comment]
Yup. I second that this is a very good idea!

**Comment by viniciusdc** [comment]
Great idea!

**Comment by ocefpaf** [comment]
Yep. We needed that recently and struggled to find it!

BTW, we follow NumFOCUS CoC and we report to them. You'll find [more info on their page](https://numfocus.org/code-of-conduct).

**Comment by chicken-biryani** [comment]
Hello, @kathatherine and @beckermr hope this text finds you well! 
I am an aspiring Outreachy applicant and saw this issue under the 'Initial submission' section.
Can I take this up?

To clarify,
Code of conduct adheres to [NumFOCUS Code of Conduct](https://www.numfocus.org/code-of-conduct).
Needs to be added to this repository's Readme.md?

Since the Reporting Guidelines is covered under the code of conduct I believe that it isn't supposed to be added?

**Comment by prachi237** [comment]
Hi there!  my name is Prachi Nandi and I am an aspiring Outreachy intern, I am so excited and gripped to contribute to Conda forge.

To begin with, it will be my pleasure to work on the issue opened by me last year which I wanted to work on.  I would like to enquire, exactly at present are we supposed to prepare a draft of the Code of Conduct for Readme.md by taking reference from [NumFOCUS Code of Conduct](https://www.numfocus.org/code-of-conduct)?
@beckermr  @kathatherine  can you please give some clarification on this.

Thank you!

**Comment by beckermr** [comment]
Yes the readme in this repo.

**Comment by leofang** [comment]
@beckermr is this some kind of contest? Why do we have 3 PRs addressing the same thing? #1640 #1641 #1644

**Comment by beckermr** [comment]
Outreachy applications have started again. As usual, folks tend to not notice the other PRs and make their own. Please don't worry about it.

**Comment by leilayesufu** [comment]
Good day, my name is Leila Yesufu and i'm an aspiring outreachy intern. 
I have worked on this, please review @beckermr @kathatherine #1180

**Comment by leofang** [comment]
You sure...? There is one more: #1646.

**Comment by ngam** [comment]
> Outreachy applications have started again. As usual, folks tend to not notice the other PRs and make their own. Please don't worry about it.

@beckermr is it okay to provide them feedback? I wasn't aware these were part of applications and I offered feedback to two PRs. Happy to avoid that, just let me know if there are restrictions or procedures you'd like the community to follow. Thanks!

@leofang, I think it is fine; in fact, it is a good thing :)

**Comment by Abraham-Deng** [comment]
Hello everyone, my name is Abraham Deng, am an aspiring Outreachy applicant. am really glad to be here.  
Is it okay to take up the same prompt #1644, as some of them seem to have been added to the main Readme.md already OR I need another different one?
Please clarify for me @beckermr
Thanks!

**Comment by beckermr** [comment]
Feel free to find another issue.

**Comment by beckermr** [comment]
@ngam helpful comments are appreciated. Remember that outreachy applicants are typically new to our community. Please be patient as they get aquatinted with our tools and processes.

**Comment by leofang** [comment]
I meant to say it'd be nice if someone can help coordinate. Even applicants' time is valuable and we shouldn't duplicate their effort.

**Comment by Austin-tawe** [comment]
Hello Mentor,

I am called Fad from Cameroon. I am an Outreachy Applicant for the March 2022 cohort. I am very much interested in the project.
Please, how do I get started?
Thanks

**Comment by beckermr** [comment]
We're doing our best @leofang. Feel free to join us.

**Comment by Abraham-Deng** [comment]
> Feel free to find another issue.

Okay, Thanks! @beckermr

**Comment by Austin-tawe** [comment]
Hello Mentor,

I am called Austin Tawe from Cameroon. I am an Outreachy Applicant for the March 2022 cohort. I am very much interested in the project.
Please, how do I get started?
Thanks

**Comment by beckermr** [comment]
Please see our interns gitter channel for some instructions.

**Comment by Rufaida98** [comment]
Hi I am Rufaida Ali an outreachy applicant is it possible to contribute to this project?. please guide me

**Comment by beckermr** [comment]
Hi! Please see our intern gitter channel for some introduction.

**Comment by Shivani-Parihar99** [comment]
Hello everyone! I am Shivani Parihar, an outreachy applicant. I am from India.
I'm excited to learn and contribute to this community. Should I work on this issue or find a different one as I saw many PRs related o this issue.

**Comment by beckermr** [comment]
Feel free to find another issue.

**Comment by Shivani-Parihar99** [comment]
> Feel free to find another issue.
Okay, Thankyou.

**Comment by AghaSaad04** [comment]
Hi This is Saad, I am an Outreachy aspirant. Looking forward to contribute :)

**Comment by tracycod3r** [comment]
Hello everyone, I am Tracy an Outreachy applicant from Uganda. I have seen PRs related to this issue, should I work on this issue or continue to another one?

**Comment by beckermr** [comment]
Either way is fine!

**Comment by Lukong123** [comment]
Hello everyone I am Lukong Anne from Cameroon looking forward to contributing to the community.

**Comment by Lukong123** [comment]
@prachi237 I think it is a good idea to do add the code of conduct to the readme file, as you said adding it in brief.

**Comment by harshita214** [comment]
Hello, I am harshita and I would like to work on this issue
Can I be assigned this as an Outreachy participant

Thanks in advance :)

**Comment by kathatherine** [comment]
Hi, @harshita214. You don't need to be assigned any issues during the Outreachy application period for conda-forge. You can work on this issue if you want to (we are using this issue in particular as an easy one to start with), but you are welcome to create a PR for any docs issue you would like to work on and let us know about it in the conda forge interns chat.
