### ISSUE TITLE
Invalid Link for  Polys.me

### ISSUE THREAD

**Issue by PrernaSingh587** [conda-forge/conda-forge.github.io#1351]
https://conda-forge.org/docs/orga/governance.html#voting

There's a sentence about Polys.me and its linked to some doc under organization documents. But it shows invalid upon clicking. Do we need a doc about Polys ?

**Comment by beckermr** [comment]
Let's not touch the governance pages please.

**Comment by beckermr** [comment]
I'm going to close this issue for now.
