### ISSUE TITLE
Absence of a favicon in the conda-forge documentation

### ISSUE THREAD

**Issue by angeloobeta** [conda-forge/conda-forge.github.io#1362]
#

- [ ] I was navigating through [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) only to notice that the absence of a favicon in the documentation.
**What is a Favicon?**
Favicon serves as branding for the documentation website. Its main purpose is to help visitors locate the documentation page easier when they have multiple tabs open. Due to their tiny size, favicon work best as simple images or one-to-three characters of text. Creating a favicon is a small but important step to setting up a Conda-forge documentation website. It would legitimacy to the Conda-forge site and helps boost the online documentation. Favicon are an immediate visual marker for the website which enables easy and quick identification for web users as well as unifies all of the various browser components into a well branded browsing experience. #1361  #1306

**Comment by viniciusdc** [comment]
for the favicon configuration https://github.com/conda-forge/conda-forge.github.io/blob/2843194b8221fa457cc8230259269550d673ff15/src/conf.py#L159, just test it localy before creating the PR
