### ISSUE TITLE
Homepage not responsive in mobile view

### ISSUE THREAD

**Issue by Aaishpra** [conda-forge/conda-forge.github.io#1371]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
The homepage is not responsive in smaller screens/mobile view. 
Check below screenshots
![image](https://user-images.githubusercontent.com/66299533/114425347-9d578f80-9bd6-11eb-8098-899c5fb04ca9.png)

**Comment by Aaishpra** [comment]
@viniciusdc there is a similar problem in the blog section but at the footer instead of navbar.
I was confused about where to open the issue for it here or in conda-forge/blog

**Comment by beckermr** [comment]
This works fine on my iphone. are you sure?

**Comment by Aaishpra** [comment]
Yupp, checked on my phone too

**Comment by Aaishpra** [comment]
@viniciusdc also mentioned it [here](https://github.com/conda-forge/conda-forge.github.io/issues/1358#issuecomment-817369808)

**Comment by beckermr** [comment]
It is responding fine in my browers as I resize the screen and on my phone. I can reproduce the issue you posted only when using the browser inspection to resize the screen and not resizing the actual window.

**Comment by Aaishpra** [comment]
![IMG_20210412_121713](https://user-images.githubusercontent.com/66299533/114427568-d55fd200-9bd8-11eb-9584-53ce3eafd786.jpg)
This is what is see on my phone when i open the homepage

**Comment by Aaishpra** [comment]
> It is responding fine in my brower as I resize the screen and on my phone. I can reproduce the issue you posted only when using the browser inspection to resize the screen and not resizing the actual window.

Try a little bit scrolling to the right when you open it on phone, the navbar menu is present at the rightmost corner.

**Comment by viniciusdc** [comment]
> ![IMG_20210412_121713](https://user-images.githubusercontent.com/66299533/114427568-d55fd200-9bd8-11eb-9584-53ce3eafd786.jpg)
> This is what is see on my phone when i open the homepage

Yes, same here too.

**Comment by viniciusdc** [comment]
> > It is responding fine in my brower as I resize the screen and on my phone. I can reproduce the issue you posted only when using the browser inspection to resize the screen and not resizing the actual window.
> 
> Try a little bit scrolling to the right when you open it on phone, the navbar menu is present at the rightmost corner.

Yes, same behaviour here too.

**Comment by BastianZim** [comment]
I think this comes from the NUMFOCUS graphic:

![image](https://user-images.githubusercontent.com/10774221/114456014-aba8aa00-9bdc-11eb-8af3-343a7d168fe3.png)

It only is there though if I zoom out on my phone or scroll to the right.

**Comment by viniciusdc** [comment]
> I think this comes from the NUMFOCUS graphic:
> 
> ![image](https://user-images.githubusercontent.com/10774221/114456014-aba8aa00-9bdc-11eb-8af3-343a7d168fe3.png)
> 
> It's only there though if I zoom out on my phone or scroll to the right.

oh great point, I do agree with you that it might be the culprit. I think that the next step is deciding if we can do a dynamic resize of that logo.

**Comment by BastianZim** [comment]
Maybe something like so: 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_image_responsive2
https://www.w3schools.com/howto/howto_css_image_responsive.asp

**Comment by Martins-O-U** [comment]
@viniciusdc Outreachy Applicant here. Please I'd like to work on documenting this issue. Kindly assign the task to me and confirm I can go ahead.

**Comment by Aaishpra** [comment]
@Martins-O-U i am already working here, although if you want we can collaborate.

**Comment by Martins-O-U** [comment]
@Aaishpra yes, that would be great. I'd love to collaborate with you.

**Comment by Aaishpra** [comment]
Sure, @Martins-O-U 
@viniciusdc can you assign both of us here. I have started looking into the issue 😄

**Comment by Martins-O-U** [comment]
Thank you @viniciusdc

**Comment by Aaishpra** [comment]
Thanks for your comment @BastianZim I have solved this issue, basically, the problem was arising because the NUMFocus logo and the youtube video were not responsive.

**Comment by Aaishpra** [comment]
@Martins-O-U basically what I did was add a class in `index.html.tmpl` named responsive to both logo and the Youtube video,
and add some custom css in `../css/theme.css`
Here are the code snippet of what I did
* Add responsive class in line 149 of `index.html.tmpl`

`<iframe width="560" class="responsive" height="315" src="https://www.youtube.com/embed/EWh-BtdYE7M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

* and same class in line 250 of the same file

` <img src="img/NumFocus_LRG.png" class="responsive" alt="Numfocus Logo" />`

* and here is the code of what I added in `theme.css`
```
.responsive {
    max-width: 100%;
    height: auto;
  }
  
```
Since we both were working on this issue you can go forward and make a PR for this with the code I provided, just add me as coauthors in the description of the PR.
and as @viniciusdc already has said the PR can be counted for our as both of our contributions.

**Comment by Aaishpra** [comment]
Adding screenshots for confirming
![image](https://user-images.githubusercontent.com/66299533/115115773-e54e2c00-9fb3-11eb-8732-1bb4b01677b2.png)
![image](https://user-images.githubusercontent.com/66299533/115115782-eda66700-9fb3-11eb-914a-be206d53aa33.png)

**Comment by Martins-O-U** [comment]
awesome @Aaishpra, I am on it

**Comment by Martins-O-U** [comment]
Fix completed, and a Pull Request has been raised. https://github.com/conda-forge/conda-forge.github.io/pull/1392

**Comment by viniciusdc** [comment]
closing this issue as #1392 solved it! :tada:
