### ISSUE TITLE
Link to guidelines from "Add a recipe" section

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#138]
As suggested by @wholmgren in this [comment](https://github.com/conda-forge/staged-recipes/pull/616#issuecomment-219543636), it would be great if we had a link to the guidelines from the website. This should help a user see what is needed and recommended for recipes when they are learning how to add them.

**Comment by kathatherine** [comment]
Note, the Guidelines page can now be found here: https://conda-forge.org/docs/orga/guidelines.html

@beckermr Would this be a good Outreachy candidate? I'm not sure where the files are to edit the conda-forge.org website or if we want them doing that.

**Comment by beckermr** [comment]
Editing the website is tricky business but if people want to do that, It'd be fine. they are right in the main directory.

**Comment by ssurbhi560** [comment]
Hi @jakirkham, I would like to work on this issue. 
I am thinking of adding a line such as `Please follow these guidelines.` in the third point [here](https://conda-forge.org/#add_recipe). Could you please let me know if that's how we would want it to be @beckermr @kathatherine ?

**Comment by beckermr** [comment]
Looks ok to me. We should fix the grammar in that bullet while we are there.

**Comment by ssurbhi560** [comment]
> Looks ok to me. We should fix the grammar in that bullet while we are there.

Cool then, I will open a PR with these changes.
