### ISSUE TITLE
Document ignoring conda-verify

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1399]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

During the build process, the following error is shown: `Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.`

This can safely be ignored and it would be good to have this documented somewhere. 

Prompted by: https://gitter.im/conda-forge/conda-forge.github.io?at=6079b460dc24646812c5cf4b

**Comment by ForgottenProgramme** [comment]
Oh thanks for linking the Gitter conversation. It was funny.

**Comment by ForgottenProgramme** [comment]
Somewhere here: https://conda-forge.org/docs/maintainer/infrastructure.html#azure-pipelines ?
What do you think?

**Comment by BastianZim** [comment]
It also happens under the other CIs and when building locally, so I would suggest somewhere more general, maybe the FAQs?

**Comment by BastianZim** [comment]
Just to add, it's run by `conda-build`: https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#no-verify

**Comment by ForgottenProgramme** [comment]
FAQ should be a good place!
Thanks.

**Comment by ForgottenProgramme** [comment]
I'm taking this up. :)

**Comment by BastianZim** [comment]
Awesome, thanks! :)
