### ISSUE TITLE
Add  CFEP in Glossary

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1415]
`CFEP` : conda-forge enhancement proposals.

Since all the major changes in the projects are submitted as CFEP.  It's a prominent keyword as well. So what I think we can add this keyword in the Glossary section, to help the readers know about it. The keyword is used in docs many a time so to make that clear what CFEP exactly is we can add that in the Glossary.
Reference:  https://github.com/conda-forge/cfep

Not sure if it's gonna help, I would like to know your views on it.

**Comment by prachi237** [comment]
@isuruf  @viniciusdc  @beckermr

**Comment by beckermr** [comment]
go for it!

**Comment by viniciusdc** [comment]
Hi @prachi237 feel free to start a PR with that addition! thanks for the work on this too :smile:
