### ISSUE TITLE
Search-bar in the navigation get hidden

### ISSUE THREAD

**Issue by PrernaSingh587** [conda-forge/conda-forge.github.io#1419]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
**The search bar hides sometimes when the navigation menu overflows. This creates a bad user experience. This is shown below**

https://user-images.githubusercontent.com/51945896/116347529-ff84d700-a809-11eb-8cf8-f00d69471d81.mp4

**Here, I have tried to twitch an HTML a bit to see how it looks like** : 

https://user-images.githubusercontent.com/51945896/116347697-4ffc3480-a80a-11eb-801b-68db8fb1c810.mp4

I think this is a good thing to have the search bar at the top. I would want to know which part of the codebase to edit to achieve this?

**Comment by PrernaSingh587** [comment]
@viniciusdc @beckermr @leofang @ocefpaf 
What are your thoughts on this?

**Comment by viniciusdc** [comment]
> @viniciusdc @beckermr @leofang @ocefpaf
> What are your thoughts on this?

Hi @PrernaSingh587, we won't be able to change the html directly but I do remember that the search bar has a special treatment somewhere in the doc files... I will need to have a look into that. For this, I would love it if you could put the search bar as you showed.

**Comment by PrernaSingh587** [comment]
> > @viniciusdc @beckermr @leofang @ocefpaf
> > What are your thoughts on this?
> 
> Hi @PrernaSingh587, we won't be able to change the html directly but I do remember that the search bar has a special treatment somewhere in the doc files... I will need to have a look into that. For this, I would love it if you could put the search bar as you showed.

Yeah! Sure. I will too look into the docs for this . :)

**Comment by viniciusdc** [comment]
Also @PrernaSingh587 this issue seems to be a duplicate of #1358, so if you could post this info as a comment there, to move the discussion forward,  and then close this one....
Thanks for the update on this too.

**Comment by PrernaSingh587** [comment]
Oh yes, I just checked . I will link this issue there and close this .
