### ISSUE TITLE
Rectification in the FAQ of maintainer section 

### ISSUE THREAD

**Issue by prachi237** [conda-forge/conda-forge.github.io#1426]
![Screenshot (43)_LI](https://user-images.githubusercontent.com/72700861/116738036-8d7ddf00-aa0f-11eb-8246-47882d2063e7.jpg)
https://conda-forge.org/docs/maintainer/maintainer_faq.html
May I know how the error message (the one that I had underlined above) during the build will look like. Accordingly, I can redraft the error message for this particular question.  coz I think the error message is not well documented, I mean it is incomprehensible.

**Comment by ForgottenProgramme** [comment]
I don't think that's needed. 
Just break that error message into multiple lines.

**Comment by prachi237** [comment]
> I don't think that's needed.
> Just break that error message into multiple lines.

umm ofc , I would have done that but ain't it would more conveyable if it is just like the one that I attached below:
![Screenshot (45)_LI](https://user-images.githubusercontent.com/72700861/116740446-ab007800-aa12-11eb-9dfe-57743f5efa8e.jpg)

**Comment by ForgottenProgramme** [comment]
Right.
Look here:
https://gitter.im/conda-forge/conda-forge.github.io?at=6079b451c60826673baa5913

Maybe you'll get some ideas.

If not, maybe someone who has seen this error (eg. Sekou from this chat) can help you.

**Comment by BastianZim** [comment]
The error message looks exactly like this, it's just one line.

**Comment by prachi237** [comment]
> The error message looks exactly like this, it's just one line.

Thanks @BastianZim  for the info:)
