### ISSUE TITLE
[DOC] Explain the etiquette of merging version updates.

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1430]
When the bot creates a pull request to a feedstock to update the version, some maintainers aren't sure if they should approve the pull request and wait with merging until everybody else that is a code owner has approved the PR.

It might be good to mention somewhere that there is no need to approve the PR and that every maintainer can merge the bot PR (After verifying everything of course) without waiting on the approval of the other maintainers.

**Comment by hitblunders** [comment]
@BastianZim may I work on this?

**Comment by BastianZim** [comment]
@hitblunders Sure but @viniciusdc would have the final say on it.

**Comment by hitblunders** [comment]
@BastianZim Sure! I will wait for his response.
