### ISSUE TITLE
Outreachy Spending of Funds

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#1457]
@conda-forge/core
This vote falls under the Spending of funds policy, please vote and/or comment on this issue.
This vote needs 50% of core to vote yea to pass.
To vote please leave +1 (yea) or -1 (nay) responses on this comment.
If you would like changes to the current language please leave a comment.
This vote will end on June 24th at noon Eastern.

The invoice is for $6500 USD.

The description from NumFOCUS accounting:

>Charitable donation for sponsorship of 1 intern(s) for conda-forge in the May 2021 Outreachy internship cohort

@viniciusdc please feel free to add a more descriptive description.

**Comment by viniciusdc** [comment]
Hello everyone, thanks @CJ-Wright for opening this issue. Just a brief context, Conda-forge community is currently participating in the Outreachy program under the project [Documenting the conda-forge ecossytem](https://www.outreachy.org/outreachy-may-2021-internship-round/communities/conda-forge/documenting-the-conda-forge-ecosystem/cfp/). 

We already have an intern working on submitting reviews for our docs as well as updating/managing some enhancements under it. This invoice refers to the intern sponsorship commented above (see [Community funding-requirements](https://www.outreachy.org/docs/community/#funding-requirements) and [payments](https://www.outreachy.org/docs/internship/#payments) pages on Outreachy for more details)

cc. @ocefpaf @beckermr

**Comment by CJ-Wright** [comment]
The vote passes.
