### ISSUE TITLE
[DOCS] Condensing the sections within the docs 

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda-forge/conda-forge.github.io#1469]
It might make the docs appear a lot neater if the sections were less expanded. 

Current:
![expanded](https://user-images.githubusercontent.com/65779580/123693558-d3bbb700-d875-11eb-9d21-497995002b24.png)

Proposed:
![condensed](https://user-images.githubusercontent.com/65779580/123693680-fc43b100-d875-11eb-8056-9ce4c13f9956.png)

**Comment by jakirkham** [comment]
cc @croth1 @beckermr

**Comment by ForgottenProgramme** [comment]
Present:
![image](https://user-images.githubusercontent.com/65779580/123695034-b2f46100-d877-11eb-92d0-47a5ae7b2555.png)

Proposed:
![image](https://user-images.githubusercontent.com/65779580/123695083-c0a9e680-d877-11eb-8e49-e0087f7fbc26.png)

**Comment by ForgottenProgramme** [comment]
Present:
![expanded1](https://user-images.githubusercontent.com/65779580/123695401-21392380-d878-11eb-8b82-e062a429d0b3.png)

Proposed:
![condensed1](https://user-images.githubusercontent.com/65779580/123695427-27c79b00-d878-11eb-9e35-fa5b034f533e.png)

**Comment by beckermr** [comment]
I don't like this change and don't think it adds much. I do think we could do better at making the section titles more clear. Maintainer vs user documentation is confusing since a lot of people consider using conda-forge being a maintainer.

**Comment by jakirkham** [comment]
What sticks out to me about the current organization is there is a lot to grok in the TOC. I think making it less busy does help that

Though maybe different section titles (as you suggest) would also improve discoverability

**Comment by ForgottenProgramme** [comment]
> I don't like this change and don't think it adds much.

Why don't you like it @beckermr ?

**Comment by viniciusdc** [comment]
> I don't like this change and don't think it adds much. I do think we could do better at making the section titles more clear. Maintainer vs user documentation is confusing since a lot of people consider using conda-forge being a maintainer.

Definitely, I do think we need to condense the meeting notes as a whole though... for the Maintainer vs user docs we are currently working into making that more clear and with a better reading flow... Mahe's intention here was to ease the huge amount of information that a new user might encounter when first visiting our docs...
 
TBH I think we should not expose those index pages as it doesn't seem to add much to the users... and use as a homepage for docs some kind of introduction directing the user to the sections they might be interested in (if they are users or maintainers)

I do agree @jakirkham, but to start working on that we should think about what's the most necessary information for a maintainer x user would be, and have some kind of links in the homepage of the docs pointing to those segments as well... after that we should then start cleaning the other sections to improve readability

**Comment by viniciusdc** [comment]
Summarizing the end user problem here: this might lead to some time consumption of the new contributors when attempting to find specific information under the hood of a section. And, probably, might as well restrain the user's attention to certain parts of the docs information.

I am closing this issue now.
