### ISSUE TITLE
Encoding python runtime variant in build string

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#1479]
Currently, the default `CONDA_PY` in the build string resolves to `py37` for both cpython & pypy. It would help IMO to see immediately from the artefact name for which python variant a package has been built.

Example for a current numpy [build](https://anaconda.org/conda-forge/numpy/files) (using `pypy37` instead of `py37` for the pypy variant)
* `linux-64/numpy-1.21.1-py37h038b26d_0.tar.bz2`
* `linux-64/numpy-1.21.1-py37h620df1f_0.tar.bz2` --> `linux-64/numpy-1.21.1-pypy37h620df1f_0.tar.bz2`

This would also apply if conda-forge ever packages other runtimes, e.g. https://github.com/conda-forge/staged-recipes/issues/13019

**Comment by isuruf** [comment]
Please open this in conda/conda-build
