### ISSUE TITLE
Fix documentation for 'add user' command

### ISSUE THREAD

**Issue by fatihkurtoglu** [conda-forge/conda-forge.github.io#1480]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Documentation for adding a new user via the bot is currently misleading. 

I've been referring to the [document](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user) here and the command template there is `@conda-forge-admin, please add <@user>`.

But the actual command is: `@conda-forge-admin, please add user @username`

- Missing the `user` after `add`
- Having angled brackets creates confusion (my opinion)

You can see my efforts for trying to trigger the bot [here](https://github.com/conda-forge/scaleapi-feedstock/issues?q=is%3Aissue+shaun) :) 

I couldn't find the source repo for the documentation to submit a change.
<br/>

**Comment by ForgottenProgramme** [comment]
@fatihkurtoglu , thankyou for pointing this out!
