### ISSUE TITLE
Start Python 3.10 migration with the release candidate

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-forge.github.io#1499]
Given the discussion in https://discuss.python.org/t/encouraging-3-10-wheels-on-pypi/10207 and especially in https://github.com/numpy/numpy/issues/19630 I would argue that we should also start the Python 3.10 migration before the final 3.10 release is done. This would also enable us to have as many as possible packages ready on the day of the release. It would also help a lot of downstream projects that use conda-forge as their source for their test environments with providing the necessary dependencies.

## How to do this 

1. Get a 3.10rc build and upload it to `conda-forge/labels/python_rc`. By not having the RC on the main label, users will not be able to get Python 3.10 environments by chance, only if explicitly requested. Work on this has started in https://github.com/conda-forge/python-feedstock/pull/481
2. Create a Python 3.10 migration that also adds this channel for Python 3.10 builds
3. Write a script that lists all yet built Python 3.10 builds. This is a safety net if something goes really wrong.
4. Start the migration and work on it
5. Wait until 3.10 is released 
6. Build 3.10 final
7. Remove the special channel from the migration 

## What if things go wrong?

We can easily mark builds as broken. In the case that this really happens, we have built a script as part of step 3. We would simply run this.

## Will end-users end up with pre-release Python 3.10 environments?

No, the built packages will be all uploaded to the main channel except the one for Python itself. Thus `python=3.10` won't be solvable until the final release has been built. The packages in CI can be built because there we are adding an additional channel.

## What happens if there will be ABI breakage between the RC and the final release?

This is a very unlikely case and as outlined in https://github.com/numpy/numpy/issues/19630 between the RCs and the final release are stricter requirements for changea than between patch releases.

If this still happens, we would simply mark all existing builds as broken using the script from point 3 and restart the migrator.

**Comment by ocefpaf** [comment]
Great idea. We need to build 3.10 first though :-|

I know that @isuruf is working on it but he'll probably need help.

**Comment by rgommers** [comment]
I see that Python 3.10 is now available on all architectures except `win32` (https://anaconda.org/conda-forge/python). But the migration / special channel idea didn't happen, right? Will there be automated PRs opened for the migration, or is a manual step needed here? Would be happy to have NumPy/SciPy 3.10 packages soon, especially given that the 3.10 wheels for non-Linux platforms are taking unexpectedly long.

**Comment by rgommers** [comment]
Thanks for the context @xhochy!
