### ISSUE TITLE
Selectors `# [py3x]` for x>6 not working

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#1526]
I just [learned](https://github.com/conda/conda/issues/10975) that conda-build (more or less intentionally) does not support `# [py37]` and higher (see https://github.com/conda/conda-build/issues/4297), in favour of `# [py==37]` etc.

Looking at a code-search in conda-forge, these tags are definitely in use (albeit with less frequency that I had thought), not least because they are a very natural extension of the (working) `# [py27 or py36]` - is @conda-forge/core aware of this? If so, we should probably teach the linter to reject the old syntax (or chime in on the conda-build issue).

**Comment by isuruf** [comment]
https://conda-forge.org/docs/maintainer/maintainer_faq.html?highlight=py37#mfaq-py37-selector
