### ISSUE TITLE
Launcher icons missing when using conda-forge channel

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#153]
If I use the Anaconda launcher and add the conda-forge channel by default, all the icons appear to be broken:
### Before

![screen shot 2016-05-25 at 14 19 37](https://cloud.githubusercontent.com/assets/314716/15541314/d7a71178-2283-11e6-9ffa-ad9aa784080e.png)
### After

![screen shot 2016-05-25 at 14 19 11](https://cloud.githubusercontent.com/assets/314716/15541311/d662b560-2283-11e6-89ff-f75ca156f8fb.png)

Is this not the right way to include icons:

https://github.com/conda-forge/glueviz-feedstock/blob/master/recipe/meta.yaml#L52

?

cc @ccordoba12 (for Spyder) and @jakirkham for notebook (which is also missing a description)

(not sure why the glue icon is missing in the 'before' view - it's usually there though)

**Comment by jakirkham** [comment]
@pelson @ocefpaf, maybe we need to revisit ( https://github.com/conda-forge/conda-forge.github.io/issues/119 )? 😉

**Comment by ocefpaf** [comment]
Agreed. I had no idea the launcher used these metadata.

**Comment by jakirkham** [comment]
Yeah, it's weird as I would expect it to use the `summary` metadata here, but it does not seem to be doing that for some reason.

**Comment by astrofrog** [comment]
Any idea why the icons aren't working though?

**Comment by ccordoba12** [comment]
The Launcher is deprecated and (I think) it was removed in Anaconda 4.0. It's replacement is Anaconda Navigator.

Pinging @goanpeca, who is the tech lead of Navigator to explain how entries are shown in its Home tab (I'm not so sure how that works :-).

**Comment by astrofrog** [comment]
@ccordoba12 - is there a way to install the navigator into a miniconda installation? For the launcher, it was possible to do ``conda install launcher``. Is there something equivalent for the navigator?

**Comment by jakirkham** [comment]
Is this still an issue with the navigator, @astrofrog?

**Comment by astrofrog** [comment]
@jakirkham - hard to tell, the navigator is pretty buggy at the moment. It doesn't seem to show the icon I included in the recipe in conda-forge which is a little different from the one in the defaults channel.

**Comment by goanpeca** [comment]
@astrofrog @jakevdp, I am not even certain how to use the icon for packages.

We were using builtin icons cause the things listed in the repodata.json refer to locations where the pacakge was built. I dont know if this has been fixed or how conda-forge manages this

**Comment by jakirkham** [comment]
Based on the last comment, it sounds like this is an upstream issue with `conda-build`. Perhaps it is best to raise an issue on `conda-build`'s issue tracker and see what can be done about recording icon file location in `repodata.json` correctly. Once it is addressed, we can reassess what actions need to be taken in conda-forge.
