### ISSUE TITLE
[DOC] Update documentation about tokens

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1532]
Previously feedstocks stored encrypted tokens, which were used to upload packages. However we have since moved away from that. Though the documentation still refers to [tokens in `conda-forge.yml`]( https://github.com/conda-forge/conda-forge.github.io/blob/09bc2d08f0e3ebe583621054a8bda52cf878e75b/src/maintainer/conda_forge_yml.rst#appveyor ). Also it doesn't cover how users should update tokens. It would be good to remove these outdated sections and include some text on how to [update feedstock tokens]( https://github.com/conda-forge/admin-requests#reset-your-feedstock-token ).

**Comment by prachi237** [comment]
@jakirkham @beckermr  @kathatherine  I think I can and would like to fix this issue, can you help me provide the necessary details so that I can get started with this?

**Comment by jakirkham** [comment]
Mostly this is about deleting text that is outdated

Though it might be nice to write up a paragraph on how tokens are handled now. This [SO answer]( https://stackoverflow.com/a/69586535 ) is pretty good. Matt is the expert with token handling so he probably has thoughts on that 😉

**Comment by beckermr** [comment]
That SO answer is really great. Let's avoid saying why we are trustworthy (ie declaring that anaconda trusts us) and instead update our docs with how we handle tokens etc. the description of that process is correct on this answer. Please do not copy any text from that SO answer. We do not have rights to it.

**Comment by shreya024** [comment]
> That SO answer is really great. Let's avoid saying why we are trustworthy (ie declaring that anaconda trusts us) and instead update our docs with how we handle tokens etc. the description of that process is correct on this answer. Please do not copy any text from that SO answer. We do not have rights to it.

Hey @beckermr I would like to work on this issue.

**Comment by beckermr** [comment]
Go for it!

**Comment by prachi237** [comment]
> > That SO answer is really great. Let's avoid saying why we are trustworthy (ie declaring that anaconda trusts us) and instead update our docs with how we handle tokens etc. the description of that process is correct on this answer. Please do not copy any text from that SO answer. We do not have rights to it.
> 
> Hey @beckermr I would like to work on this issue.
I have been working on it, have not send the PR but have made edits and I'm on the verge of completion .

**Comment by ssurbhi560** [comment]
Hi @prachi237, are you still working on this issue? I would be happy to take it if you are busy and couldn't complete it for any reasons. :)

**Comment by prachi237** [comment]
> Hi @prachi237, are you still working on this issue? I would be happy to take it if you are busy and couldn't complete it for any reasons. :)

Yep I can complete the task and send the PR asap ...my university exams were going on so was busy these days :)

**Comment by ssurbhi560** [comment]
@prachi237, just wanted to ask if you are still working on it? 
Actually, I have been working on the issues related to Maintainer documentation, and completing this one would be towards that. Also this issue it about removing outdated information so, it would be good to do this soon.
