### ISSUE TITLE
Introduction suggests no Apple ARM packages

### ISSUE THREAD

**Issue by peterjc** [conda-forge/conda-forge.github.io#1534]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

As an Apple user I am interested in the status of conda and conda-forge on the new Apple silicon ARM machines like the M1 CPU.

Quoting https://conda-forge.org/docs/user/introduction.html

> *By default, we build packages for macOS, Linux AMD64 and Windows AMD64.*

This suggests osx-arm64 is not supported, where as https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ suggests this is quite mature now.

Suggested wording:

> *By default, we build packages for macOS (AMD64 and ARM64), Linux AMD64 and Windows AMD64.*

**Comment by BastianZim** [comment]
Summarising my comment here from https://github.com/conda-forge/miniforge/issues/223#issuecomment-962063995

MacStadium seems to be a partner of conda forge: https://conda-forge.org/#partners and https://www.macstadium.com/opensource/members

Using https://github.com/conda-forge/conda-smithy/pull/1526, might it be possible to test (and maybe build) Apple ARM packages on native hardware and maybe even build them by default?

**Comment by peterjc** [comment]
How about replacing:

> *By default, we build packages for macOS, Linux AMD64 and Windows AMD64.*

with:

> *By default, we build AMD64 packages for macOS, Linux and Windows. Many packages are now  also being built for Apple ARM64.*

**Comment by jakirkham** [comment]
^ @conda-forge/core ?

**Comment by wolfv** [comment]
we could also add linux-aarch64 and linux-ppc64le?

**Comment by peterjc** [comment]
If they are built by default (I don't know), then that would be good.

**Comment by wolfv** [comment]
Nope, it's the same story as for Apple M1 (built by request, basically)

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-forge.github.io/pull/1985
