### ISSUE TITLE
Update mamba section

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1542]
The mamba part of the FAQ (https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-mamba-local) is outdated with mamba now being the default.

Before I create a PR, should it be removed completely or updated to something else?

**Comment by BastianZim** [comment]
Gentle ping here @conda-forge/core

**Comment by beckermr** [comment]
Sorry for missing this. Let's leave the bit on using mamba locally via `conda mambabuild` but we can remove the rest.

**Comment by BastianZim** [comment]
No worries, PR is in https://github.com/conda-forge/conda-forge.github.io/pull/1566
