### ISSUE TITLE
DTN image is missing

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1567]
The logo of DTN is missing, resulting in an empty spot under the DEVELOPER SUPPORT section at https://conda-forge.org.

The current logo URL does not point to anything: https://github.com/conda-forge/conda-forge.github.io/blob/811ab06a8b11157549e4ac0c0d19fbed3dd8659e/src/inst_partners.yaml#L29

Not sure what image is preferred here which is why I just opened an issue instead of a PR.

**Comment by jakirkham** [comment]
Probably the answer is just to drop that line. Eric changed jobs

cc @ericdill (in case you have other thoughts here)

**Comment by BastianZim** [comment]
Anything specific this should be replaced with?

CC @ericdill

**Comment by jakirkham** [comment]
IIUC Voltron Data. Idk if there is a specific image we should use here.

cc @kkraus14 (in case you have thoughts 🙂)

**Comment by kkraus14** [comment]
I asked internally and will report back. Thanks @jakirkham
