### ISSUE TITLE
`Reason: image not found` for macOS packages

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/conda-forge.github.io#1574]
Recently we've seen tests begin to fail on macOS for a few independent project in the Dask ecosystem, all of which are failing with `Reason: image not found`. For example, over in https://github.com/dask/dask/pull/8472 we're getting (see [this CI build](https://github.com/dask/dask/runs/4540096557?check_suite_focus=true)):

```python
py.test dask --runslow --cov=dask --cov-report=xml -n4 
ImportError while loading conftest '/Users/runner/work/dask/dask/conftest.py'.
conftest.py:43: in <module>
    import tiledb  # noqa: F401
../../../miniconda3/envs/test-environment/lib/python3.7/site-packages/tiledb/__init__.py:34: in <module>
    ctypes.CDLL(lib_name)
../../../miniconda3/envs/test-environment/lib/python3.7/ctypes/__init__.py:364: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: dlopen(libtiledb.dylib, 6): Library not loaded: @rpath/libcrypto.1.1.dylib
E     Referenced from: /Users/runner/miniconda3/envs/test-environment/lib/libtiledb.dylib
E     Reason: image not found
```

in https://github.com/coiled/dask-bigquery/pull/31 (see [this CI build](https://github.com/coiled/dask-bigquery/runs/4538787882?check_suite_focus=true)):

```python
 E            - dlopen(/Users/runner/miniconda3/envs/test-environment/lib/python3.7/site-packages/pyarrow/_parquet.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libssl.1.1.dylib
E             Referenced from: /Users/runner/miniconda3/envs/test-environment/lib/libthrift.0.13.0.dylib
E             Reason: image not found
```

and a similar issue was reported in https://github.com/dask/distributed/issues/5601.

The errors are similar, but appear to be pointing towards separate libraries not being loaded. I get the sense this may be some sort of packing issue (we're using conda-forge packages in these CI builds) and I'm wondering if this is a know issue, or is folks here have any thoughts on how we may proceed in debugging. Apologies for the very vague issue, happy to dig in more if additional details would be useful.

**Comment by jakirkham** [comment]
Hmm...not really sure. The last `openssl` build was from early November (so ~1.5months ago). The other packages mentioned like `pyarrow` and `tiledb` haven't really seen any relevant changes recently.

Is it possible things are just really out-of-date in the installer or environment used? Have you tried running `conda update --all` to start?

**Comment by jrbourbeau** [comment]
I gave `conda update --all` a try and, while it did update some packages, it didn't resolve the `Reason: image not found` error.

Looking at `dask-bigquery` (which has a relatively simple CI setup), I noticed that using [this environment file](https://github.com/coiled/dask-bigquery/blob/c3726943e4b8154744d8fa1c1ef36008a36cefbf/ci/environment-3.9.yaml) which specifies only the `conda-forge` channel, along with [this `conda-incubator/setup-miniconda` GitHub actions setup](https://github.com/coiled/dask-bigquery/blob/c3726943e4b8154744d8fa1c1ef36008a36cefbf/.github/workflows/tests.yml#L32-L42), which is using mambaforge and strict channel priority, we still end up with a few packages installed from the `main` channel ([including `libthrift`](https://github.com/coiled/dask-bigquery/runs/4538787882?check_suite_focus=true#step:3:886) which the `image not found` error is pointing to). That mixing of conda channels seems like it might be to blame, but I'm not yet sure why we're pulling in packages from `main` in the first place

**Comment by jakirkham** [comment]
>  I'm not yet sure why we're pulling in packages from main in the first place

Hmm...missed this bit. Is Distributed not using [strict channel priority]( https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge )? If so, that should be changed (as not using it tends to result in this mismatch of incompatible packages)

**Comment by jrbourbeau** [comment]
Distributed is using [this condarc file](https://github.com/dask/distributed/blob/1bbb7f7474e27a434e97427c518f7fdd8e255dd5/continuous_integration/condarc) with strict channel priority, and conda-forge at a higher priority than defaults

**Comment by jakirkham** [comment]
Does this reproduce with Conda?

**Comment by jakirkham** [comment]
Also is there a reason [this]( https://github.com/dask/distributed/blob/1bbb7f7474e27a434e97427c518f7fdd8e255dd5/continuous_integration/condarc#L4 ) says `true` instead of `strict`?

**Comment by jrbourbeau** [comment]
Hmm good catch, I suspect that's an oversight and should be changed to `strict`. That said, `dask-bigquery` is using `strict` already and experiencing the same issue of a few packages being installed from `main`. FWIW it looks like the `conda-incubator/setup-miniconda` action may be where the `defaults` channel is added (xref https://github.com/conda-incubator/setup-miniconda/issues/207)

**Comment by jsignell** [comment]
Just to say that dask is encountering similar issues even though channel-priority is strict and tiledb is coming from conda-forge.

**Comment by jsignell** [comment]
I thought adding `nodefaults` to the env might help https://github.com/dask/dask/pull/8505

**Comment by jakirkham** [comment]
Is this issue still active?

**Comment by jsignell** [comment]
Well it seems to have stopped. I did add `nodefaults` and that seemed to make things better, so I guess we can close and just reopen if it comes up again.

**Comment by jakirkham** [comment]
Sounds good. Thanks Julia! 😄
