### ISSUE TITLE
Supporting more than the two latest Numpy version

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#158]
I'd like to add a recipe here for Astropy (there is a recipe already in [anaconda-recipes](https://github.com/ContinuumIO/anaconda-recipes/tree/master/astropy) we can start from).

However, it would be nice if we could build conda packages not just for the last two Numpy versions (1.10 and 1.11 currently) but actually for all versions from 1.7 to 1.11. Astropy is used by a lot of other packages in Astronomy, and it's useful to have builds with older (supported) versions of Numpy for packages that run continuous integration. Therefore, I was wondering if it would be possible for us to do so, and if so, what the best way is to do that.

Astropy has a minor release every ~2 months, and major release every ~6-7 months (just to give an idea of how often we'd do builds).

[This discussion started on Gitter with @jakirkham. It can be seen from [start](https://gitter.im/conda-forge/conda-forge.github.io?at=574efcffa78d5a256e39ebbd) to [end](https://gitter.im/conda-forge/conda-forge.github.io?at=574f042df44fde236e52746e).]

cc @mwcraig

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf

**Comment by mwcraig** [comment]
That would certainly be nicer than adding another custom build channel...

**Comment by pelson** [comment]
I have felt that pain with other packages, but it really isn't a healthy place to be. Numpy v1.7 is over 3 years old. I do get the reproducibility argument, but IMO we would be doing the numpy developers a disservice by actively supporting codebases which treat the last 3 years of numpy development in such a way.

I'd need to be massively convinced of the value of doing this. As a heads up / indication of direction, we have agreed a scheduled removal of py34 support before the end of this year from conda-forge (when py36 becomes available). conda-forge can't be a place for every possible permutation of runtime dependencies - it simply doesn't scale, and IMHO is extremely unhealthy. In this situation, I'd argue there is a huge difference between what users want and what is good for them 😉  .

@astrofrog - do you know *why* your users are stuck on 1.7? Is there more value in spending the effort in helping them get off 1.7 than implementing this in conda-forge (or some other channel)?

To be clear, this isn't a pronouncement, and there is certainly a lot of room for healthy debate.

**Comment by jakirkham** [comment]
> do you know why your users are stuck on 1.7? Is there more value in spending the effort in helping them get off 1.7 than implementing this in conda-forge (or some other channel)?

So, the main reason that I have seen/experienced in the past is that the system package manager has a woefully out-of-date version of NumPy or one is deploying to a cluster where that is all one has available.

Admittedly, with the advent of `conda`, this is not as much of a problem as it can be deployed in a user's home directory (`sudo`-free) and is able to install the SciPy stack without relying on these external sources. As a result, I would have to wonder why someone doesn't just install Miniconda and go forward.

**Comment by astrofrog** [comment]
Just to be clear, we are **not** expecting the end user to use **conda** to install Numpy 1.8 with the latest version of Astropy. Users using conda really have no excuse to not use the latest or second latest Numpy release. I think we are on the same page there.

What do expect however is that some users may for example be running Ubuntu 14.04 LTS (supported until 2019) which comes with Numpy 1.8 (I think) and might want to ``pip install astropy`` and a package depending on astropy, say astroquery, and we want to make sure that will work. For the purposes of continuous integration (e.g. for astroquery), we use conda to set up the environment on Travis and AppVeyor, and that's why we might want Astropy + Numpy 1.8 conda builds.

If your reaction is 'why don't e.g. Ubuntu 14.04 users install Anaconda/Miniconda?', I agree that would be the easiest solution, but I've encountered at least one system administrator that doesn't allow any scientists at their institute to install conda in their home directories and actively checks for that. So there may be some archaic policies that we are battling against.

Another example is that we want users to be able to install Astropy into CASA, which is an IPython-based environment for radio astronomy - it comes pre-compiled with fixed versions of Numpy that can't be upgraded without breaking everything (they bundle Numpy 1.8 I think, and they update very slowly).

Now I don't think that all packages should be built with 5 versions of Numpy and 3 versions of Python, since I agree this doesn't scale well. However, I think it might be worth considering some exceptions for packages that have a good use case for this. I also don't think we need to run all combinations. For instance, we could run extra builds only for Python 2.7 for the old versions of Numpy, or something similar. I don't think it makes any sense to do Python 3.5 and Numpy 1.7, since 'legacy' systems will all be running Python 2.7.

**Comment by jakirkham** [comment]
Basically, what you have said above was my understanding of your request. 

> What do expect however is that some users may for example be running Ubuntu 14.04 LTS (supported until 2019) which comes with Numpy 1.8 (I think) and might want to ``pip install astropy`` and a package depending on astropy, say astroquery, and we want to make sure that will work. For the purposes of continuous integration (e.g. for astroquery), we use conda to set up the environment on Travis and AppVeyor, and that's why we might want Astropy + Numpy 1.8 conda builds.

However, if that is the case, wouldn't it be best to test by using `pip` to do the install? This can still be done in your `conda` environment. While it initially feels wrong, this normally works ok-ish. Besides the goal here is to have CI mimic the end user's setup as closely as possible. Even though using `conda` would be faster, using `pip` is more accurate and should catch similar errors.

> If your reaction is 'why don't e.g. Ubuntu 14.04 users install Anaconda/Miniconda?', I agree that would be the easiest solution, but I've encountered at least one system administrator that doesn't allow any scientists at their institute to install conda in their home directories and actively checks for that. So there may be some archaic policies that we are battling against.

This is an interesting data point that I was wondering about.

> Now I don't think that all packages should be built with 5 versions of Numpy and 3 versions of Python, since I agree this doesn't scale well. However, I think it might be worth considering some exceptions for packages that have a good use case for this.

Agreed that considering this is worthwhile.

After hearing more about your rationale it is feeling like this lives in the gray area between doing CI at conda-forge and shipping packages. While it is true you are not doing CI at conda-forge, this is being done for explicit purpose of CI and not distribution. Maybe there is an appropriate in-between solution here, but we might need to think a bit about what that is.

**Comment by jakirkham** [comment]
At this stage we build against a relatively old version of NumPy and allow users to install that version of NumPy or any version since. This solves the original request and has been done for all maintained packages at this stage. Feel free to update any feedstocks that are not already using this behavior.
