### ISSUE TITLE
[DOC] Explain how to handle a ABI/API breakage of a package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1581]
Currently when a package breaks, there are a few steps people need to go through. Roughly they are:

* Rebuild the package with corrected `run_exports` (build number bump)
* Hot-fix repodata of previous package to apply the right `run_exports` 
* Hot-fix the repodata of dependencies to include corrected pinnings for the package

There may be other things here I'm forgetting (feel free to just edit the OP or comment below). Would be good to have this documented better so we can just point people to the appropriate doc page when an issue like this arises

**Comment by ssurbhi560** [comment]
Hi @jakirkham, I have started working on this. I was wondering where should we add this in the documentation? I would propose putting it in Tips and Tricks section or add it as a question `What to do if your package breaks?` in FAQs in user documentation. Please let me know what are your thoughts on this.

**Comment by kathatherine** [comment]
@ssurbhi560 Let's pick one place so we don't have redundant documentation. My opinion is that the FAQ is a great spot for it. If it turns out that it's a lot of information, we can create an entire section somewhere and then link to it from the FAQ, but let's start with the FAQ.

**Comment by ssurbhi560** [comment]
Hi @jakirkham, can you please share some more info about what could be the reasons for API/ABI breakage and anything, any resource where I can read more about this? I am struggling to understand this, specifically this : "Hot-fix repodata", what does this mean?

**Comment by jakirkham** [comment]
This is sort of a catch 22. We need docs so people can understand how to do this, but we don't have them so it is hard to understand/explain.

Probably we shouldn't get too hung up on a deep explanation of repodata hot-fixing as individual solutions could be very different. Plus others may be able to fill this out more as time goes on. So instead would focus on a good examples. Here are a few:

* Replacing an existing pin that was incorrect ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/217 )
* Loosen a pin ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/132 )
* Tighten a pin ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/154 )

There can be more complex situations of course, but hopefully the covers a few common ones to get these docs started.
