### ISSUE TITLE
build and process `.conda` artifacts

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#1586]
This issue is to track to-do items for building and handling `.conda` artifacts. 

to dos:
 - [x] adjust repodata patching (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/215)
 - [x] adjust instances where `.tar.bz2` is assumed to be at the tail end of packages
   - [x] artifact validation (https://github.com/conda-forge/artifact-validation/pull/790)
   - [x] webservices (https://github.com/conda-forge/conda-forge-webservices/pull/487)
   - [x] ci setup package (https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/182)
   - [x] repodata tools (https://github.com/conda-forge/repodata-tools/pull/8)
   - [x] admin requests (https://github.com/conda-forge/admin-requests/pull/384)
   - [x] libcfgraph (https://github.com/regro/libcflib/pull/75)
   - [x] conda-smithy (https://github.com/conda-forge/conda-smithy/pull/1693)
- [x] wait for support from `anaconda.org` ( https://github.com/conda/infra/issues/637#issuecomment-1307776730 )
- [x] figure out story on transmutation of old artifacts (not going to)
- [x] test uploads on the cf-autotick-test-feedstock and copy of ci setup package from PR above (https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/439)
- [x] test we can mark .conda artifacts as broken (https://github.com/conda-forge/admin-requests/pull/511)
- [x] test we can mark .conda artifacts as unbroken (https://github.com/conda-forge/admin-requests/pull/512)
- [x] test we can make the repodata patches for them properly (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/356)
- [x] test for no duplicate uploads for packages of the same name but different extensions (https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/441, https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/442)
- [x] merge all PRs
- [x] make an announcement (https://github.com/conda-forge/conda-forge.github.io/pull/1852)
- [x] start admin migration to switch over feedstocks (do this slowly to look for breakages, https://github.com/conda-forge/admin-migrations/pull/82)
- [x] set default as .conda in ci-setup package (https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/212)

**Comment by jakirkham** [comment]
cc @conda-forge/core (as Anaconda.org & CDN can now handle `.conda`)

**Comment by beckermr** [comment]
notes from core call:

```
        * [ ] make sure on announcement you mention the minimum conda version (4.7)
        * [ ] check that ci services do not do duplicate uploads
        * [ ] set compression level for big packages
            * flag is [`--zstd-compression-level`](https://github.com/conda/conda-build/blob/3baa21e0af022b3f971068566831c812497545f1/conda_build/cli/main_build.py#L159-L165)
            * default is 22, set [here](https://github.com/conda/conda-build/blob/3baa21e0af022b3f971068566831c812497545f1/conda_build/config.py#L53)

```

**Comment by beckermr** [comment]
use 

```
conda_build:
  zstd_compression_level: 16 to 19
```

in the condarc

**Comment by beckermr** [comment]
@conda-forge/core I went with compression level 16. LMK if you have any issues with that.

cc @mbargull @mariusvniekerk

**Comment by jakirkham** [comment]
How long does it take to run 16 or 19?

Should we allow this to be overridable? For example if compression takes too long on a feedstock close to a CI time limit and we want to dial it down.

**Comment by beckermr** [comment]
> How long does it take to run 16 (or 19)? How much more compression does one see between the two? Understand we may not have benchmarks, but any info that can help guide us would be useful.

I don't have any of this info. I think we ship this PR and then figure out as things run how it is working.

**Comment by jakirkham** [comment]
Yeah being able to configure it is more important I think.

From past experience with compressors the last little bit tends to take a lot longer for minimal gain. So was just trying to get a sense of how "flat" the curve was getting to aid in decision making.

**Comment by beckermr** [comment]
Here is a benchmark for numpy using the following script on my (old intel) mac

```
#!/usr/bin/env bash

in_pkg=$1
out_pkg=${in_pkg/.tar.bz2/.conda}
bak_pkg=${in_pkg}.bak

cp ${in_pkg} ${bak_pkg}

for level in 1 4 10 16 17 18 19 20 21; do
    cp ${bak_pkg} ${in_pkg}
    rm -f ${out_pkg}
    rm -rf ${out_pkg/.conda//}
    start=`python -c "import time; print(time.time())"`
    cph transmute --zstd-compression-level=${level} ${in_pkg} .conda
    end=`python -c "import time; print(time.time())"`
    ttime=$( echo "$end - $start" | bc -l )
    start=`python -c "import time; print(time.time())"`
    cph x ${out_pkg}
    end=`python -c "import time; print(time.time())"`
    runtime=$( echo "$end - $start" | bc -l )

    size=$(ls -lah ${out_pkg} | cut -w -f 5)

    echo "${level} ${size} ${runtime} ${ttime}"
done

cp ${bak_pkg} ${in_pkg}
rm -f ${bak_pkg}
rm -f ${out_pkg}
rm -rf ${out_pkg/.conda//}
```

results

```
$ ./bench.sh numpy-1.23.4-py39h9e3402d_1.tar.bz2 
1 8.2M 2.182568 7.1936909                                                                                                                                                 
4 7.2M 1.803828 7.8562648                                                                                                                                                 
10 6.4M 1.9773452 8.359201                                                                                                                                                
16 5.9M 1.975351 16.997171                                                                                                                                                
17 5.8M 3.171298 20.3572858                                                                                                                                               
18 5.7M 2.3847492 23.3421962                                                                                                                                              
19 5.7M 2.237947 36.101651                                                                                                                                                
20 5.2M 3.756540 35.1239249                                                                                                                                               
21 5.2M 3.2139912 40.8598119           
```

Things flatten for this size around 10-16.

**Comment by beckermr** [comment]
Here is the start of a benchmark for a much bigger file (compressed around 450 MB)

```
1 464M 17.158145 161.082254                                                                                                                                               
4 419M 14.839792 157.401964                                                                                                                                               
10 375M 16.084401 199.193263         
```

**Comment by beckermr** [comment]
I think 16 will be fine for now. We can lower it as needed for big packages and we only take a small hit on small ones.

**Comment by beckermr** [comment]
We really could use an adaptive option in conda build.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Agreed 16 seems like plenty.

Also notably better than their `.tar.bz2` equivalents:

| name                                      | .tar.bz2 (MB) | .conda @ 16 (MB) |
|:------------------------------------------|--------------:|-----------------:|
| `numpy-1.23.4-py39h9e3402d_1`             |           6.6 |              5.9 |
| `stackvana-afw-0.2022.46-py310hff52083_0` |         435.0 |            338.0 |

**Comment by jakirkham** [comment]
On a different note (kind of related to adaptive), we may in the future want to leverage [Zstandard's dictionary]( https://facebook.github.io/zstd/#small-data ) to pretrain on the content of many packages. We could then package this constructed dictionary and use it to cutdown compression/decompression time.

One question here is how compressible are packages in aggregate. There may be some things (like text) that compress really well and other things (like dynamic libraries) that may do less well. A somewhat related question is whether it is worth creating per file format dictionaries (though this would be a modification to the format). Given other packagers, filesystems, etc. have gone down the path of using Zstandard already, we may be able to glean results from their efforts.

**Comment by dhirschfeld** [comment]
Great to see this happening - I'm excited about the performance improvements this might bring! :heart:

I've been building my own `.conda` packages for a bit now and one usability issue I've run into is not being able to see inside the package.

With the old `.tar.bz2` packages I could open them in 7-Zip and browse the contents / folder-structure. That was often invaluable in debugging broken builds.

With the `.conda` format the contents appear as a `pkg-*.tar.zst` binary blob:

![image](https://user-images.githubusercontent.com/881019/202580737-a90faa3c-3b4a-49dc-bc24-021fb6d9184a.png)

Is there an easy way to browse the contents of a `.conda` package?

**Comment by jakirkham** [comment]
We have made the same observation ( https://github.com/conda/conda-package-handling/issues/5 ) 🙂

**Comment by chrisburr** [comment]
> Is there an easy way to browse the contents of a .conda package?

All of this information is in https://github.com/regro/libcfgraph and I have a local clone which I regularly use with `rg`.

Longer term I was already thingking this would be a great feature for https://prefix.dev/ if @wolfv is interested.

**Comment by dhirschfeld** [comment]
> All of this information is in https://github.com/regro/libcfgraph

The idea is that this is useful for debugging broken builds - i.e. the build fails because of missing files in the package so the new package version never gets published outside of CI. As a dev I want to know what the internal file/folder structure of the newly built (broken) package was so I can compare with my expectations.

I don't know much about prefix.dev but doesn't that just report on dependencies between published packages?

**Comment by jakirkham** [comment]
Related to this have filed an issue to create a CEP spelling out the `.conda` spec more fully ( https://github.com/conda-incubator/ceps/issues/42 )

**Comment by jaimergp** [comment]
@dhirschfeld - you can use [`conda_package_handling`](https://github.com/conda/conda-package-handling) (via `cph extract`) for your `.conda` needs!

**Comment by dholth** [comment]
zstd has built-in benchmarking

**Comment by beckermr** [comment]
What does this mean?

**Comment by dholth** [comment]
If you run `zstd -b1 -e19 somefile` it will tell you how long each level took.

**Comment by mbargull** [comment]
" copy-pasta" of some comments of mine from internal chat:
> Re: dictionary:
> Those can make sense in some cases, but we're also then treading in the "over-optimizing and leaving utilities behind" area. Meaning, we get diminishing returns with those minor optimizations and also I wouldn't be able to `bsdtar -x all-the-things` then ;).

> Re: memory usage:
> This is also why I recommend to not use the `--ultra`, e.g., `-22` settings, but limit ourselves to `-19` at max. Yes, compressing would take an unreasonable amount of resources in some cases, but for me more importantly would that decompression would also be affected! `zstd` by default ~~uses~~ can use much more memory on decompression (i.e., our users' side) as ye olde `gzip`/`bzip2` anyway. If you use `--ultra` settings, then it its window sizes can surpass the 128MB mark and ~~needs~~ may need as much memory on decompression as well.
\[edited to say "can use"/"may need"\]

> A thing orthogonal to tweaking the compression level would be to give the compressor a better arranged stream of data. Previously, Ray did some experimentation with `binsort`, but it was rarely used and slow as hell in the chosen configuration. But in some cases it could yield notable improved compression. I'm not sure how much of an impact it would have for `zstd` because it already uses much bigger window sizes (128MB vs 900KB block size of `bzip2 -9` IIRC). Nowadays, one would probably look at, e.g., how https://github.com/mhx/dwarfs/tree/v0.6.2#overview (see similarity hashing) arrange their input instead of trying the `binsort` approach.

**Comment by dholth** [comment]
Thankfully the window size is also limited by the uncompressed archive size.

**Comment by michaelosthege** [comment]
Even though I have `conda 4.12.0`, my `mamba 0.27.0` has trouble finding packages that are only avaialable as `.conda` artifacts: https://github.com/mamba-org/mamba/issues/2172
