### ISSUE TITLE
policy on copying conda-forge's "products"

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-forge.github.io#1591]
There is this [copy mechanism](https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/copy-pkg/) where one could copy a selection of conda-forge's packages into another channel for whatever reason. 

Someone may do this to conduct additional testing to ensure said packages work together in a certain fashion they so desire. Someone else may do this as part of a product of some sort, e.g. a corporate entity using these packages to sell some product (via containers, cloud environments, and so on).

I understand we have a relatively permissive license in the feedstocks themselves. However, it is not clear to me what the license of the end product is. That is, when downloading and unzipping the tar.bz2 file that gets uploaded to anaconda.org, I don't see any particular license related to the feedstocks or conda-forge. So could we clarify this? What's our position on this? Could someone link any documents on said matters here?

I personally primarily have two concerns around this matter.

First (more importantly): As a contributor to conda-forge, I'd like to know the extent we are allowing random corporate entities to benefit from our work in selling their random products.

Second (less importantly): This community has [more than 15000 packages](https://github.com/orgs/conda-forge/repositories); and so we are going to have all sorts of conflicts between these packages --- to remedy that, we might want to consider creating our own sub-channels for specific domains like AI/ML or a julia-specific subdomain (just picking two random examples), where we tighten the dependencies and migrations as applicable. 

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
Some links to related discussions and comments:

**Comment by BastianZim** [comment]
Re 1: My understanding is that the package is under its license and the feedstock under `BSD-3-Clause` as outlined in the readme (Example: https://github.com/conda-forge/aiofile-feedstock#about-aiofile)

Re 2: Because of the [global pinning](https://conda-forge.org/docs/maintainer/pinning_deps.html), there should be no conflicts (In theory). Of course, this doesn't always apply in the real world.

**Comment by ngam** [comment]
> Re 1: My understanding is that the package is under its license and the feedstock under `BSD-3-Clause` as outlined in the readme

Thanks! This makes perfect sense; but if so, shouldn't this license be packaged as part of the artifact (tar.bz2) as well? When you copy the artifact using the copying mechanism, it's not going to be straightforward to retrieve/know the license (or maybe it is, idk)

**Comment by ngam** [comment]
You mean the **artifact is under the license of the package** itself (upstream) while the feedstock is under BSD-3-Clause, right? This makes sense, but maybe it needs further clarification vis-a-vis copying.

**Comment by BastianZim** [comment]
Yes. Copying stuff should be under the license of whatever it is copied from (Anaconda.org here) but tbh, this is just my first take – might be that more is involved.
