### ISSUE TITLE
"getting started" documentation

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-forge.github.io#1603]
### Where should the content be added?

https://conda-forge.org/docs/user/introduction.html

### What should be added?

More thorough details about getting started, including .yaml file format, conda-lock stuff, general introductory remarks about the philosophy of conda-forge, differences between `conda activate env_x; conda update --all` and `conda env update -f env_x.yaml`, the interaction between pip and conda, relocatability, reproducibility, etc. etc.

### Additional information

I can try to add some info --- I'm relatively verbose and happy to do gather info and spend time on this (I also moonlight as a writer... allegedly). However, I am not sure if we have anything preventing us from doing this type of extra, detailed documentation because [conda.io](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) has some of these details already... and I never quite wrapped my head around the relationship between the conda/anaconda peeps and conda-forge (this space).

Tagging @beckermr for advice and guidance.

**Comment by jakirkham** [comment]
Sorry @ngam was there some reason this was closed?

**Comment by ngam** [comment]
Nothing in particular --- things change/evolve and this may be untimely
