### ISSUE TITLE
Azure pipelines failing with "no hosted parallelism purchased or granted"

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#1604]
Something's up with azure pipelines at the moment. All jobs are failing instantly with 
```
No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

Examples: [scipy](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=456025&view=logs&jobId=5be07ae1-d8ba-5406-47b6-8e3a3a12f825), [sentencepiece](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=456024&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81)

CC @conda-forge/core

**Comment by fatihkurtoglu** [comment]
Having the same issue over here: https://github.com/conda-forge/scaleapi-feedstock/pull/10

**Comment by beckermr** [comment]
Thanks. I've updated the status page. Let's centralize the details there.

**Comment by h-vetinari** [comment]
> Thanks. I've updated the status page. Let's centralize the details there.

Absolutely, I just didn't want to be the one who writes the official status message. 🙃

**Comment by hodgestar** [comment]
Seeing the same issue at https://github.com/conda-forge/qutip-feedstock/pull/74.

**Comment by juarezr** [comment]
Same at: conda-forge/petl-feedstock/#29

**Comment by bashtage** [comment]
Same at conda-forge/statsmodels-feedstock#51

**Comment by h-vetinari** [comment]
Maybe asking differently: are there _any_ known conda-forge feedstocks where azure is still running? My impression is that it's all down currently...

**Comment by adam-urbanczyk** [comment]
Similar issue in an unrelated project using conda build. Did MS abuse detection mechanisms start to classify conda build as abusive all of the sudden? Does anyone here have better communication channels with MS than the form they link to in the error?

NB: according to this post this should not happen to existing projects https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/.

**Comment by h-vetinari** [comment]
First successful job restarts happening for me. 💪 

Hope it lasts 🤞 

If so, thanks to everyone involved in fixing this!

**Comment by beckermr** [comment]
Closing this as it seems resolved. Please reopen or comment if you notice any issues!

**Comment by guzman-raphael** [comment]
@beckermr Could be mistaken but I believe this is still an issue for us. Would you mind taking a look to see if there is anything we are missing? I checked on Azure Pipelines logs and the error reads:

```
##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
Started: Wed at 22:06
Duration: 4d 19h 55m
```

**Comment by jakirkham** [comment]
@guzman-raphael, the build there is from 5 days ago (around the time the issue was present). Restarting CI should fix it (though please let us know if not). Asked for CI to restart here ( https://github.com/conda-forge/datajoint-feedstock/pull/23#issuecomment-1039728594 )

**Comment by valeriupredoi** [comment]
@beckermr this exact issue is striking again today, started about 20min ago - had a look at all the other pipelines, and they're all failing because of this, AzureDevOps status says all nice and dandy, but it's not :grin:

**Comment by ocefpaf** [comment]
@valeriupredoi today is a holiday in the USA and this will probably be resolved only Monday :-/
Let's have a CI restart party then, for now, we wait.

**Comment by valeriupredoi** [comment]
@ocefpaf ah completely forgot it's your independence day from us, ya bloody rebels :rofl: Good man, let's just wait then. Happy 4th of July :us_outlying_islands:

**Comment by ocefpaf** [comment]
> @ocefpaf ah completely forgot it's your independence day from us, ya bloody rebels 🤣 Good man, let's just wait then. Happy 4th of July 🇺🇲

Oh. I don't take part in any of that ;-p
My home country independence is yet to come depending on how you look at it 😬

**Comment by valeriupredoi** [comment]
ah my apols, mate! Thought you were based in South Carolina - proves out that's Santa Catarina in Brazil (excuse my continental ignorance :grin: ) - the land of Ayrton Senna and wonderful football :brazil:

**Comment by dbkeitel** [comment]
As I'm not sure if answers on an old closed issue will receive attention (even post-4th-of-July), I've made a new one at #2218 just to be sure.

**Comment by valeriupredoi** [comment]
cheers @dbkeitel - a lot more exposure to that indeed, I lazed out thinking someone will indeed open an issue since all the feedstocks are affected :grin:
