### ISSUE TITLE
Better anchoring of announcements

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1611]
### Where should the content be added?

Announcements

### What should be added?

Currently when clicking on a specific year to get an anchor, the link given is  `id1` or similar. However these anchors will become outdated as each year passes and the links will then point to the wrong year.

Specific announcement themselves don't include anchors, so one is currently unable to link to a specific announcement they may wish to share with others.

Would be helpful to have permalinks (to the extent possible) to both years and specific announcements. This would make it easier to highlight a specific announcement to share with others.

**Comment by ssurbhi560** [comment]
I am taking this up @jakirkham! :)

**Comment by jakirkham** [comment]
Great thank you! This would be nice to solve 🙂

**Comment by kathatherine** [comment]
@ssurbhi560 Great to see that the year headers can now be properly linked to! There is also a question above about being able to link to specific announcements. Maybe an important announcement would be separated out in a level 3 header with an explicit link. Might be the only way to get around the restrictions of the sphinxcontrib.newsfeed extension.

**Comment by ssurbhi560** [comment]
@kathatherine, that's right. I have also been reading and trying to find some way to do it but couldn't find anything till now. I will keep looking for it and find any way to do so, but till then I think what you are suggesting might be the only way to do this.

**Comment by kathatherine** [comment]
Just leaving a note here to say that Surbhi tested this and any important announcements can just be given an [explicit target](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#explicit-targets) right above it, like the targets that were added to the year headers and that should satisfy the second requirement of this issue, should it ever come up. We haven't added any currently for any specific announcements.

@beckermr or @jakirkham, we good to close this issue?

**Comment by beckermr** [comment]
Should we go through and add targets to the old announcements?

**Comment by jakirkham** [comment]
I think if we could anchor to each date that would be sufficient to close

**Comment by beckermr** [comment]
Also, when you say you tested it, I presume you mean the RSS feed came out ok?

**Comment by kathatherine** [comment]
By each date, do you mean the years themselves, @jakirkham, which is already done, or each announcement date?

And good point about the RSS feed, Matt. I am not sure about that. I just saw a screenshot of the output of Surbhi trying an explict target for each announcement. We should definitely double-check the feed before closing.

**Comment by beckermr** [comment]
I was saying each announcement.

**Comment by kathatherine** [comment]
That works for me. @ssurbhi560, do you mind editing the branch you had showed me with each announcement given an explicit target, but make the target the date instead of the announcement name? And then push it to a PR so we can check that the feed looks good? Thanks!
