### ISSUE TITLE
Drop Python 3.7 support

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge.github.io#1616]
### Your question:

In accordance to the suggestions made in nep29, some packages have started dropping support for python 3.7.

https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule

Given that Python 3.10 is rolling out, it seems like it would make sense to stop generating packages for python 3.7 by default to limit the size of the build matrix and to encourage the open source community to move forward.

Thoughts?

xref: Imagecodecs dropping 3.7 support upstream https://github.com/cgohlke/imagecodecs/issues/34

**Comment by dopplershift** [comment]
I'm actually fine with doing it and have no stake since my projects have dropped 3.7. Having said that

> encourage the open source community to move forward.

I'm not a fan of this line of reasoning and IMO it's not conda-forge's place to be pushing people along the upgrade path.

**Comment by jakirkham** [comment]
Typically we have only dropped Python versions when adding a new one. Usually this has happened when the older version was nearing or reaching EOL.

While the Scientific Python/PyData ecosystem is an important use case for conda-forge and its users, they are not the only users. So am somewhat reluctant to adopt a policy from some users and applying them to all users.

**Comment by hmaarrfk** [comment]
> older version was nearing or reaching EOL

Understood. I can simply drop support on the packages that start to drop them.

**Comment by jakirkham** [comment]
> I can simply drop support on the packages that start to drop them.

Yeah that we can always do :)

**Comment by hmaarrfk** [comment]
Followup question.

For upstream packages that are dropping python 3.7, what should we do about pypy? pypy is "3.7" with more bells and whistles.

**Comment by jakirkham** [comment]
> For upstream packages that are dropping python 3.7, what should we do about pypy? pypy is "3.7" with more bells and whistles.

Short term: If Python 3.7 is dropped, then that would mean all Python builds that are 3.7 based would be dropped. Not sure there is much we can do about that if Python 3.7 is no longer supported in a release. If we want to maintain some kind of support, we could add a branch for the last release that still supports Python 3.7 and maintain that (though this can be done as needed).

Medium term: There is discussion about PyPy 3.8 in issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2089 ). Once ready, adding PyPy 3.8 would then provide a PyPy option.

**Comment by hmaarrfk** [comment]
thank you

**Comment by jakirkham** [comment]
Please see this comment: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2623#issuecomment-1656855600
