### ISSUE TITLE
include "update branch" feature?

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-forge.github.io#1628]
### Your question:

https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

This can be a handy feature to incorporate, however, I see one potential problem of adopting it wholesale. Updating the branch means rerunning the CI and that effectively means wasted resources in many cases. Just putting this out there as outdated branches (even if they have no conflicts to resolve) can introduce some unintended errors in some circumstances. Even though the link above is about announcing the rebase feature, I mean the general "update branch" feature here for consideration, as it is currently missing.

cc @beckermr (thanks so much btw for the main branch migration --- that was very smooth!!!)

**Comment by beckermr** [comment]
Yeah we should let folks do this as needed.

**Comment by ngam** [comment]
I looked around and I couldn't find a toggle for it in a private org where I am an admin. Do you know if there is a way to even enable this generally for conda-forge feedstocks? For regular members in feedstocks, there is not a "settings" tab and it ends at "insights". It is available under settings in regular repos

**Comment by ngam** [comment]
One way I guess would be to ask core members to enable it on a per feedstock basis, but that'd be too much trouble and not worth it imo

**Comment by ngam** [comment]
For reference: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

**Comment by beckermr** [comment]
Let me check the global settings when I get a chance.

**Comment by beckermr** [comment]
We'll have to do this per feedstock for now.

**Comment by ngam** [comment]
> We'll have to do this per feedstock for now.

Yeah... then it is not worth it! A lot of effort for the core team for no real benefit. 

I will keep track of this and if Github changes the way this is enabled, I will bring it to your attention again. Closing, but feel free to reopen :)
