### ISSUE TITLE
Add more steps in Improve the documentation section.

### ISSUE THREAD

**Issue by ssurbhi560** [conda-forge/conda-forge.github.io#1651]
### Where should the content be added?

Becoming Involved -> Improve the documentation

### What should be added?

More steps should be added in this section some of them are: 
1. How to create and activate conda environment.
2. How can folks see the changes they did locally before pushing them.

### Additional information

As the title of this section which is, **Improve the documentation**, this just includes the steps to do any change and jnot specifically just the documentation changes. The steps that we have added in our project's README.md for the same, should be added here as well. 

**Why?** As a new contributor, when I first setup of the project locally on my machine, I saw the steps in the README.md file. But when I tried to go back to see these steps again, I searched for them in the docs and could not find the `make html` step, as it is not mentioned there. Adding these steps would make our docs more user friendly and save the time of the contributors in trying to find these steps somewhere else.

**Comment by ssurbhi560** [comment]
@beckermr @kathatherine , please share your thoughts on this. If doing this sounds reasonable to all you folks, I will go ahead and create a PR for this.

**Comment by beckermr** [comment]
Seems ok to try out!

**Comment by kathatherine** [comment]
@ssurbhi560 Did you want to reopen this PR?

**Comment by ssurbhi560** [comment]
@kathatherine, I have reopened a PR for this here #1776.
