### ISSUE TITLE
Add more information about Grayskull in the documentation itself.

### ISSUE THREAD

**Issue by ssurbhi560** [conda-forge/conda-forge.github.io#1655]
### Where should the content be added?

Maintainer Documentation -> Contributing Packages -> The staging process -> Getting started 

### What should be added?

More information answering questions such as : 
1. What is grayskull?
2. How should one use grayskull to generate a recipe?

We can add a note below the ``Getting Started`` section explaining more about grayskull.

### Additional information

No response

**Comment by ssurbhi560** [comment]
@beckermr @kathatherine please share what do you folks think about this? If this sounds like a useful addition, I will start working on this!

**Comment by beckermr** [comment]
Go for it.

**Comment by kathatherine** [comment]
@ssurbhi560 Did you want to reopen this PR?

**Comment by ssurbhi560** [comment]
@kathatherine I have reopened this here #1777.
