### ISSUE TITLE
Sporadic false positive with `linkcheck` Polys

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1663]
We've seen the `linkcheck` error a few times on the Polys link even though it works. Not sure if it is slow for `linkcheck` or something else. In any event it would be nice to address this somehow to make sure we are not holding up PRs & doc updates. Idk if we can make `linkcheck` more reliable here. Alternatively maybe we can tell `linkcheck` to skip this line. Or maybe run `linkcheck` in another job separate from `deploy`. Open to other suggestions if anyone has any 🙂

Edit: If we just want to skip this link, maybe we can add it [here]( https://github.com/conda-forge/conda-forge.github.io/blob/80b927d3ace392ae5ea2fa7e0e5f4526c581d8d4/src/conf.py#L125-L129 )?

**Comment by jakirkham** [comment]
cc @croth1 (in case you have thoughts here)

**Comment by croth1** [comment]
I agree, I would just add it to the other ignores in the conf.py for now. It seems to me that 403 are mostly false positives anyway and it's really the 404 that are relevant (when one mistypes a url or it becomes invalid for some reason).

**Comment by jakirkham** [comment]
Sounds good. Submitted PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1669 ) to add it to that list. Please let me know if that looks ok 🙂
