### ISSUE TITLE
Improve the documentation on `arch_rebuild.txt`

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1668]
### What should be added?

See https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2679#issuecomment-1084100146. We need to add perhaps to the knowledge base that any feedstocks that could benefit from a rebuild targeting different architectures/platforms should add themselves to this `arch_rebuild.txt` list. The current mention is too short & terse.

**Comment by prachi237** [comment]
@leofang  I would like to take this issue can I?

**Comment by ssurbhi560** [comment]
@jakirkham @leofang, I am working on this, but its still not very clear to me that how does adding a feedstock to ``arch_rebuild.txt`` takes care of migrating the feedstocks. Can you please explain this in a little more detail?

**Comment by leofang** [comment]
IIRC, the migration bot will send a migration PR to the feedstocks (and their dependencies) listed in `arch_rebuild.txt` and enable the aarch64/ppc64le builds. It's very similar to the idea of `osx_arm64.txt` for the Apple Silicon migration, which is well documented here:
https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds
