### ISSUE TITLE
Add "overview of conda-forge" as a separate section.

### ISSUE THREAD

**Issue by ssurbhi560** [conda-forge/conda-forge.github.io#1673]
### Where should the content be added?

At the very beginning of the docs (sort of an opening page for the docs)

### What should be added?

Here we should add all the information about conda-forge. This section should address the questions such as: what is conda-forge, why should we use conda-forge, etc. 

### Additional information

We should add a separate section in the docs "overview of conda-forge". Currently, there is a section in the user documentation - brief introduction which acts as a introduction page for conda-forge. But all of the content of that page should be outside of the user documentation as that might not be the right place for this section (in user documentation)
Besides this, when anyone (probably someone who has never heard about conda-forge) visits the docs page, this should be the first thing they should see i.e., What is conda-forge?

**Comment by ssurbhi560** [comment]
@beckermr @kathatherine @BastianZim, please share what you folks think about this! I can work on this, if this sounds like a good addition.

**Comment by prachi237** [comment]
@ssurbhi560  there is a section named  brief introduction  in user documentation of the docs where the overview section is already added l, and what is conda forge why conda forge all these questions have been answered there😅 thought loved your idea.

**Comment by ssurbhi560** [comment]
> @ssurbhi560 there is a section named brief introduction in user documentation of the docs where the overview section is already added. what is conda forge, why conda forge all these questions have been answered there😅 though I loved your idea.

@prachi237, I guess I could not properly convey what I wanted to say; I will try to make things more clear now. 

The change I proposed was to move the "Brief Introduction" section (which already covers all these questions you mentioned). I think it probably should have its own section rather than being under any other sections ( it is under the user documentation section right now.)

I could share a few other documentations like [this](https://pip.pypa.io/en/stable/) and [this](https://docs.conda.io/en/latest/#) -- here the first page we see when we open these is the introduction about the tool/project the documentation is about. While in our documentation, the first thing we see on opening our docs is that: We have five sections. And then, within one of these sections, the introduction of conda-forge resides.

When someone opens the docs page, they should first see what these docs are for? And that's what I wanted to propose: to have an opening page with all the content of the "the brief introduction" page. Once we have it in place, we can remove it from the user documentation section. 

I might be a little repetitive here, but I am trying to be as verbose as possible to share what I am proposing here.

**Comment by chicken-biryani** [comment]
@ssurbhi560 
I had a similar thought. Sections like Introduction, About conda forge etc can be kept out of User Documentation.

Also, is 'user documentation' the correct name?

Maybe we can adapt names that are commonly used? What do you think?

**Comment by ssurbhi560** [comment]
> Also, is 'user documentation' the correct name?
> Maybe we can adapt names that are commonly used across organizations? What do you think?

@chicken-biryani, I would say that we should do this. Something that I can think of right away and is also used at a lot of other places as well is "User guide".

**Comment by kathatherine** [comment]
I think an introductory page is a great idea. Clicking on Docs on conda-forge.org and immediately seeing that table of contents is very intimidating. It's good to know where you need to be looking for information, so I can see why the tables of contents are used, but they're overwhelming. Maybe add some sentences directing people to various parts of the documentation from the introductory page you're proposing. Like, "To get started contributing packages, click here." "To see our governance policies, click here." Things like that.

This one might need some discussion as you work on it, but go ahead and start on your idea, @ssurbhi560,  and we'll see how it looks!

**Comment by ssurbhi560** [comment]
@kathatherine I agree with you on this, seeing the table of contents as the first thing can make people a little overwhelmed. I will go ahead and open a PR for this then.

**Comment by kathatherine** [comment]
@ssurbhi560 Does this fulfill the acceptance criteria of this issue?

**Comment by ssurbhi560** [comment]
Yes @kathatherine! :) I will go ahead this close this issue.
