### ISSUE TITLE
Change ``master`` to ``main`` in all the git commands.

### ISSUE THREAD

**Issue by ssurbhi560** [conda-forge/conda-forge.github.io#1676]
### Where should the content be added?

At all the places where git commands are present.

### What should be added?

We should change all the git commands we have in our docs.

### Additional information

No response

**Comment by ssurbhi560** [comment]
I will take this up @kathatherine, @beckermr!

**Comment by kathatherine** [comment]
@ssurbhi560 Go for it!

**Comment by victorabba** [comment]
I would love to take on this issue. Please which folder contains the git commands?

**Comment by ssurbhi560** [comment]
@victorabba, I already started working on it last night and almost completed half of it. Could you please take another issue, that way our efforts won't be wasted?
