### ISSUE TITLE
Remove the section 'Can I contribute packages to conda-forge?' from User Documentation

### ISSUE THREAD

**Issue by chicken-biryani** [conda-forge/conda-forge.github.io#1678]
### Where should the content be added?

https://conda-forge.org/docs/user/introduction.html#can-i-contribute-packages-to-conda-forge

### What should be added?

The section seems to be redundant.

The 'Becoming involved' section under ['What is conda-forge'](https://conda-forge.org/docs/user/introduction.html#what-is-conda-forge) already suggests that a person can contribute to packages by either help maintain them or create new ones through the staging process.

So do we really need the ['Can I contribute packages to conda-forge?'](https://conda-forge.org/docs/user/introduction.html#can-i-contribute-packages-to-conda-forge) section?

**Comment by chicken-biryani** [comment]
@beckermr @kathatherine @BastianZim 
What do you think?

**Comment by kathatherine** [comment]
@chicken-biryani Yeah, I agree. Removing redundancy will also help with the overall restructuring of the docs.

**Comment by chicken-biryani** [comment]
@kathatherine 
Definitely! I have made a PR for the same #1679 do let me know if I could improve in any way!
