### ISSUE TITLE
Separate linkcheck to a different job from deploy

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#1715]
We've had linkcheck running for a bit. Generally this seems useful. That said, we have had a few cases recently ( https://github.com/conda-forge/conda-forge.github.io/issues/1663 ) ( https://github.com/conda-forge/conda-forge.github.io/pull/1710 ) where linkcheck caused deployment to fail. Given this, would like to suggest we break linkcheck out into a separate GH Actions job. This way if it fails it will be clearer that linkcheck in particular is failing and separate it from the deployment process (especially if we need to get a doc fix out while the linkcheck issue is triaged).

**Comment by beckermr** [comment]
With the new webpage we no longer have this issue.

**Comment by jakirkham** [comment]
Do we still check the validity of links?
