### ISSUE TITLE
Restructuring feedstock/team update for better rate limit

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#172]
Our current strategy with team updates is running into issues. ( https://github.com/conda-forge/conda-forge.github.io/issues/125 ) ( https://github.com/conda-forge/conda-forge.github.io/issues/88 ) That much is clear. Now how might we fix it. Here are some thoughts.

1. ~~Manage staged-recipes with a different bot/token.~~ Done with PR ( https://github.com/conda-forge/staged-recipes/pull/927 ).
  1. ~~Easy to do.~~
  2. ~~Doesn't block more merges.~~
  3. ~~Saves reviewer time (otherwise spent handling the fallout of rate limits).~~
  4. ~~Small savings so isn't sufficient alone.~~
  5. ~~Could handle team additions and user additions.~~ Done with PR ( https://github.com/conda-forge/staged-recipes/pull/733 )
  6. ~~Obviates needed for triggering feedstock/team update script run.~~ Also done with PR ( https://github.com/conda-forge/staged-recipes/pull/733 )
2. ~~More bot accounts/tokens.~~ Skipping per discussion with @pelson.
  1. ~~Allows some scaling by number of bots.~~
  2. ~~Effectively bumps our rate limit.~~
  3. ~~Second bot is most expensive. The rest are cheap.~~
  4. ~~Leaves us vulnerable to the same problems in the future.~~
3. Leverage the feedstock repo. ( related to @pelson's [suggestion]( https://github.com/conda-forge/conda-forge.github.io/issues/88#issuecomment-217548992 ) )
  1. Already updating the feedstock repo.
  2. Only feedstocks that were added/changed get picked up. (couple order of magnitude improvement)
  3. Additional optimizations from diffing previous/current feedstock commits for name additions.
  4. Should actually catch everyone.
  5. Can always resort to the check and add everyone script.
4. ~~Move to a time based non-CI (Heroku) approach as opposed to on demand. (self-throttling 😄)~~ Done. See this ( https://github.com/conda-forge/conda-forge.github.io/issues/48#issuecomment-226571553 ).
  1. ~~Saves time spent cloning everything. (cache)~~
  2. ~~Reasonable for existing feedstocks.~~
  3. ~~Can still be triggered as needed.~~
  4. ~~Avoids script running when merging things here.~~
  5. ~~Solves race condition problems. (debouncing requests)~~
  6. ~~Kind of annoying for brand new feedstocks. (maintainers can't fix problems right away)~~
5. Alternatives to a full Travis CI sync.
  1. This sync is probably costing us dearly with our GitHub API token.
  2. It probably needs to check the settings of each repo and update.
  3. This means it is `O(N)` on repos present here, which is bad when our rate limit is fixed.
  4. Need to be able to add a single repo to Travis CI. See issue ( https://github.com/travis-ci/travis-ci/issues/6320 ).

Basically we should do 1 to simplify the life of reviewers at staged-recipes. Whether or not it amounts to much savings for the rate limit is irrelevant as it saves people's time. Examples of wasted time of people there include reporting these rate limiting issues, communicating rate limiting issues to each other, and working out the backlog at staged-recipes. Also, by doing this we would then break the problem into two pieces. How do we handle adding maintainers to a new feedstock vs. how do we add people to existing feedstocks? This would also put us on good footing for addressing 4.6.

Doing 2 is pretty easy. Though I'm not sure we should do it as it is a bit of a crutch.

Doing 3 has clear benefits as it is doubtful that many feedstocks are changing. With diffing the number that actually add maintainers, this should be quite small. We should definitely do this, but it will be a bit of work.

Doing 4 is generally a net plus. Though we should figure out how to address 4.6. For instance, 1.5 would help this. In general, this nicely couples with 1 and addresses the underlying reason for triggering the feedstock updating script on merge at staged-recipes.

Thoughts? Feedback other suggestions?

cc @pelson @ocefpaf @ericdill @janschulz

**Comment by jakirkham** [comment]
Tried to add a PR ( https://github.com/conda-forge/staged-recipes/pull/733 ) that will deal with team creation and member addition directly at staged-recipes. This should mostly obviate the need to trigger the CI here. However, we still want to be able to update the webpage. So, we will need to address 4. Once that is addressed we can add back the CI trigger.

**Comment by jakirkham** [comment]
Responding to you over here @patricksnape as this seems like the better issue to discuss solutions at this point.

> Tell me off if this is a stupid question, but would it be OK to get a short breakdown of the top couple of API calls that are pushing us over the limit?

Sure, it would be ok. If you can figure something out, go for it. This is the API for getting the current rate limit ( https://developer.github.com/v3/rate_limit/ ). Perhaps a run before and after running the team update script would give you a good idea of what it is. Though we basically know that the team update/feedstocking script is the problem and @pelson has some numbers that seem to back this up. It also follows one's intuition when knowing how these scripts run.

> For example, when do we call the team update script and at what frequency?

Every time something is merged to staged-recipes. While this was fine in the beginning and for a long time, it clear this is going to have to stop. The main reason this was done was to ensure people were given permissions to their feedstocks right away. Often ugly hacks were needed in the beginning that require direct access. Also, if CIs failed, users needed the ability to restart them. As the code already lived here, the easy solution was to add an auto-trigger script. Was thinking the other day that we should just add the user addition and team creation portion to staged-recipes directly so opened this PR ( https://github.com/conda-forge/staged-recipes/pull/733 ).

The other script this was trigger was the feedstock listing script. It just adds new feedstocks to a [list]( https://conda-forge.github.io/feedstocks.html ) on the webapage. If we remove triggering of CI here on staged-recipes, the webpage will lag. Unfortunately, triggering one build in the matrix didn't seem straightforward and wasn't interested in digging in. IMHO this is an acceptable loss at this stage. Once we move the team update and feedstocking scripts to Heroku, it will be trivial to bring back the CI trigger from staged-recipes to here.

> Although Heroku is an option for occasionally calling the update script, what if we just took the `meta.yaml` as gospel and on a PR merge we simple replaced the current set of users with the `meta-yaml` rather than even bothering to check?

Not totally sure what you mean by this, but I might follow better after 😴. Could you flesh this out a bit more?

**Comment by patricksnape** [comment]
> Not totally sure what you mean by this, but I might follow better after :sleeping:. Could you flesh this out a bit more?
I had a look at the API and it appears you can't batch add/remove members so ignore that comment as it clearly isn't applicable!

**Comment by jakirkham** [comment]
Yeah, I was hoping to see something like that too, but unfortunately it doesn't have that level of abstraction. Was thinking last night that your suggestion was sounding kind of like 3.

**Comment by jakirkham** [comment]
We have addressed 1.v and 1.vi by merging PR ( https://github.com/conda-forge/staged-recipes/pull/733 ). Also, PR ( https://github.com/conda-forge/staged-recipes/pull/772 ) would be a nice addition for some final tweaks to add people to the `all-members` team, but is not crucial. However, the rest of 1 is not addressed yet and will require PR ( https://github.com/conda-forge/staged-recipes/pull/757 ) with some more tweaks.

**Comment by jakirkham** [comment]
So, we have solved 1 and 4 at this point. We are skipping 2 as we don't really want to go that route. We still need to try 3.

**Comment by jakirkham** [comment]
Added 5 as I fear doing the full Travis CI sync is costing us significant w.r.t our GitHub API rate limit. See this related issue ( https://github.com/travis-ci/travis-ci/issues/6320 ). @pelson, any thoughts on this point?

**Comment by jakirkham** [comment]
This is amazing. Here we we add 3 recipes and nearly deplete our GitHub API Rate Limit. See this [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/146197004 ). I've put it in a [gist]( https://gist.github.com/jakirkham/ee82c366b9e886b2189185a68a7d83d0 ) too. We go from 5000 to 1372. However, I can't imagine that we are getting such usage by what we are doing alone. Instead I think the Travis CI sync is really eating into this, but I could be wrong. See the issue I raised with them in the comment above.

**Comment by jjhelmus** [comment]
Would it make sense to sprinkle in more calls to `print_rate_limiting_info(gh)` in the `create_feedstock.py` script so that we can have a more fine grained view of where we and using the GitHub API?  Perhaps before each subprocess.check_call?

**Comment by jakirkham** [comment]
Absolutely. I don't if we need it before every call as we know some don't interacting with GitHub, but yes adding many more before and after calls that do should help quite a bit.

**Comment by jakirkham** [comment]
So, this [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/146689416 ) had a lower usage. It used only 45 API calls. I guess the main point that I'm struggling with is how variable the usage is. Though even 45 seems too high to me, but is at least in a closer ballpark.

**Comment by jakirkham** [comment]
Given how effective storing the Travis CI token at staged-recipes was both at solving Travis CI API unreliability and keeping stable GitHub API usage, I'd like to suggest we do the same here for `conda-forge-admin`. It should be easy to do and has been demonstrated to be effective. Added as item 6.

**Comment by jakirkham** [comment]
Going to close this for now. There is more work that can be done, but things seem to be more reliable now and less pressing.
