### ISSUE TITLE
Add virtual environment (VENV) to glossary section

### ISSUE THREAD

**Issue by Hil-dred** [conda-forge/conda-forge.github.io#1729]
### Where should the content be added?

Glossary under Miscellaneous section

### What should be added?

Meaning of virtual environment  

### Additional information

Considering the recommendation that packages be installed with conda-forge in a new environment aside from the base environment, it would be very helpful especially for a new user, to understand what a virtual environment is, making the essence of the recommendation much clearer.

**Comment by Arshita-CHD** [comment]
Hey I would like to work on this issue

**Comment by Hil-dred** [comment]
Hello @Arshita-CHD, I already created a pull request awaiting approval as a fix to the issue
