### ISSUE TITLE
Docs out of date regarding CDN time 

### ISSUE THREAD

**Issue by mikemhenry** [conda-forge/conda-forge.github.io#1735]
### Where should the content be changed?

https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-anaconda-delay

### What should be changed?

The FAQ should say that it may take several hours for the CDN to update. 

### Additional information

See: https://app.element.io/#/room/#conda-forge:matrix.org/$1649163456813vMMND:gitter.im
![image](https://user-images.githubusercontent.com/11765982/164680342-c76d876d-f5f9-4568-a712-ae08947aaa5d.png)

### Incorrect or outdated

- [X] Incorrect
- [ ] Outdated

**Comment by kathatherine** [comment]
This week, a change is being pushed that will have the CDN update time at ~8 minutes instead of several hours. Will update this comment with a link to that PR and then we can change the docs in a more positive direction!

**Comment by jakirkham** [comment]
Also would want to update [this line]( https://github.com/conda-forge/conda-forge-webservices/blob/43c215b3f98703a251d875e191f37e5e4dbe0fe0/conda_forge_webservices/update_teams.py#L108 ) to reflect that change

**Comment by leofang** [comment]
@kathatherine any update on this? 🙂

**Comment by jakirkham** [comment]
Anyone is welcome to submit this PR and update the FAQ

**Comment by kathatherine** [comment]
Thanks for the reminder, @leofang. I recall there being a bit of a delay on this as some bugs were worked out. If anyone can give me the actual new number, I'm happy to create a PR.

**Comment by leofang** [comment]
I can help make the PR, but I was simply curious if there's any reference I can link to 🙂
> Will update this comment with a link to that PR

**Comment by barabo** [comment]
The channel clone job runs every ~2 minutes, and it takes about 6 minutes to complete.  So, it's typically about a 10 minute delay from upload in anaconda.org to availability in the CDN.

If that's not happening, check the status page: https://conda-forge.org/status/ for the `CDN cloning status` for problems.

If the clone is not sync'ing - you can open a CDN Issue in the Anaconda Issues repo.  I have a draft PR open for a new CDN issue template.
https://github.com/ContinuumIO/anaconda-issues/pull/13096

**Comment by jakirkham** [comment]
From our perspective (conda-forge), things have been working smoothly for some time now 🙂
