### ISSUE TITLE
Is there a team for pypy builds?

### ISSUE THREAD

**Issue by HeavyTony2** [conda-forge/conda-forge.github.io#1742]
### Your question:

The bot has been trying to rebuild a package I maintain for pypy, but it doesn't work. https://github.com/conda-forge/py2exe-feedstock/pull/5 There's apparently an issue with setutptools but I'm not able to find what is the cause of the problem. I'd need help from someone who knows pypy. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=497953&view=logs&j=2d03c380-16cc-53df-474d-81b5b5dc65ac&t=4f8f475c-3e8e-56b8-f5aa-7599dd696a73&l=773

**Comment by jakirkham** [comment]
Asked for help on that PR

Though generally yeah having a team for Q&A seems useful and documenting that

**Comment by mattip** [comment]
There is `@conda-forge/help-pypy`, or just @mattip works too.

**Comment by jakirkham** [comment]
Good point. Maybe we should just add a line mentioning users should reach out for help [in these PyPy docs]( https://conda-forge.org/docs/maintainer/knowledge_base.html#pypy-builds )?
