### ISSUE TITLE
Information on Dev Meetings should be updated

### ISSUE THREAD

**Issue by Hil-dred** [conda-forge/conda-forge.github.io#1749]
### Where should the content be changed?

README 

### What should be changed?

The link to the google calendar item schedules meetings for every 2 weeks on Wednesday until 13th November 2019. This could imply that dev meetings are obsolete. It would avoid confusion, by updating the google calendar info about meetings especially for first-time contributors, looking to understand the community better through these meetings. 

### Incorrect or outdated

- [ ] Incorrect
- [X] Outdated

**Comment by ericdill** [comment]
Thanks for pointing that out @Hil-dred!

**Comment by chicken-biryani** [comment]
PR related to info about dev meetings - https://github.com/conda-forge/conda-forge.github.io/pull/1659
