### ISSUE TITLE
Additions to maintainer list

### ISSUE THREAD

**Issue by pizzimathy** [conda-forge/conda-forge.github.io#1791]
### Your question:

Hello — our organization is attempting to make updates to our package on conda-forge, but a previous developer is marked as the only maintainer. If possible, we would like to add new maintainers so we can push updates — we are more than three build versions (more than one year!) behind. Thank you!

**Comment by BastianZim** [comment]
Hi, please follow the process outlined in the docs: https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-abandoned-feedstock

**Comment by jakirkham** [comment]
Closing as answered
