### ISSUE TITLE
Dropping PyPy3.7 support

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge.github.io#1800]
### Your question:

In a few recipes, cross compiling is really beneficial to speed up the release process.

Unfortunately, I've hit a few corner cases where cross compilation + aarch64/pcc64le seems to be problematic with pypy3.7

https://github.com/conda-forge/healpy-feedstock/pull/49

Given the overall increasing maintenance burden from the growing build matrix (not just pypy), Is it reasonable to drop pypy3.7? 

@conda-forge/help-pypy @mattip  @pkgw

**Comment by mattip** [comment]
> Is it reasonable to drop pypy3.7

I think so. As a maintainer, I would prefer people move to the newer versions. I think PyPy is still quite an edge case, and do not want it to be a burden on the limited conda-forge team's time.

**Comment by h-vetinari** [comment]
> Or, the error looks like a corrupted package, but it is very surprising to me that switching from cross-compile to emulation makes it go away.

This looks like https://github.com/conda-forge/pypy3.6-feedstock/issues/83 which was fixed by https://github.com/conda-forge/cross-python-feedstock/pull/44, but only for pypy 3.8+

**Comment by h-vetinari** [comment]
Big +1 on removing the pypy3.7 builds (not because I dislike pypy, much to the contrary - I just think we should focus on pypy 3.8+).

**Comment by h-vetinari** [comment]
Opened a PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3227

**Comment by beckermr** [comment]
We have a core meeting in ~40 minutes. It'd be good to bring this up there before we drop it.
