### ISSUE TITLE
Add a section in docs on security aspects of conda-forge.

### ISSUE THREAD

**Issue by ssurbhi560** [conda-forge/conda-forge.github.io#1808]
### Where should the content be added?

Maintainer Documentation

### What should be added?

Currently, the documentation on the security considerations for conda-forge builds is not complete and is scattered throughout the documentation. We want to add a dedicated section for this in Maintainer Documentation which would cover everything in one place. 

The documentation already available in different places are : 
- [Source](https://conda-forge.org/docs/maintainer/adding_pkgs.html#source) section in Maintainer Documentation.
- [CFEP 14](https://github.com/conda-forge/cfep/blob/main/cfep-14.md) - outlines the security team's responsibilities.
- [An announcement on artifact validation](https://conda-forge.org/docs/user/announcements.html#artifact-validation) in the User Documentation. 
- [A blog post on a TravisCI security incident](https://conda-forge.org/blog/posts/2021-09-24-travis-security/)

 We would want to include the following in the new section : 
 - Sources can be pulled from GitHub, PyPI or other sources - sha256 hashes are always used, so moving of tags or uploading of new sdists can not cause automatic package rebuilds
 - Binaries are built on secure infra from merged PRs only and can not be manually uploaded by anyone outside the core team.
 - More details on infra & checks/validation
 - Ideally, scenarios considered that conda-forge is robust against (or not).

### Additional information

This [SO answer](https://stackoverflow.com/a/69586535) can be helpful.

**Comment by ssurbhi560** [comment]
@beckermr @jakirkham @kathatherine

**Comment by beckermr** [comment]
Some comments from the core call:

 - All `conda-forge` packages are built by random folks you don't know on the internet on public cloud infrastructure from source code you likely have not inspected.
 - Do not use conda-forge packages if you need a high level of security.
 - You can download the recipes and build them yourself if you'd like.

However, even given all of the above, it's likely just fine and lots of people use conda-forge all the time.
