### ISSUE TITLE
Pinning to older compilers

### ISSUE THREAD

**Issue by rtburns-jpl** [conda-forge/conda-forge.github.io#1814]
### Your question:

Hi, I maintain a feedstock for isce2 (https://github.com/conda-forge/isce2-feedstock). The package is currently stuck on an older version and unable to update, because it contains legacy Fortran code which is unable to compile with gfortran > 9, and re-rendering the feedstock attempts to bump all compilers to the latest version.

Is it possible to pin a recipe's compilers to an older version temporarily, until such compilation issues are resolved?

**Comment by jakirkham** [comment]
cc @beckermr (who may have thoughts here)

**Comment by beckermr** [comment]
You can set the compiler version in the conda_build_)config.yaml in the feedstock. Follow the examples in the pinnings repo. Not sure what knock-on effects this will have though.

**Comment by rtburns-jpl** [comment]
Do you mean this example repo? https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

I tried to pin like that: https://github.com/conda-forge/isce2-feedstock/pull/52/commits/eb5e3f294de94af2cbf2a6178025786401f8c990

But the subsequent rerender is still trying to bump to gfortran 10: https://github.com/conda-forge/isce2-feedstock/pull/52/commits/98529cc38a64b8970ff7498dfcba7601cbd352b3#diff-bdce2a62e3553c4887356fd46baa0666501e91df44229c66f7202b9624412dc9

**Comment by beckermr** [comment]
you need to make a new empty conda_build_Config.yaml in the recipe directory and place just the fortan compiler version pin you want there.

never edit the generated pinning files - a rerender will always change those back.

**Comment by rtburns-jpl** [comment]
Thank you, I think I just had the yaml file in the wrong directory. I rerendered and it looks like it is pinning properly now.

A couple of the builds are failing with:

```
mv: relocation error: /lib64/libacl.so.1: symbol getxattr, version ATTR_1.0 not defined in file libattr.so.1 with link time reference
```

Does this look like one of the knock-on effects you hinted at? Or is this more likely a dependency issue, since the feedstock has gone a while without its dependency update rebuilds?

**Comment by beckermr** [comment]
That one is odd. No idea.

**Comment by rtburns-jpl** [comment]
Is there harm in merging the feedstock despite some of the builds failing? We'd at least be able to publish the package for the majority of platforms + python versions, and I could try out the pending dependency updates to see if they help.

**Comment by beckermr** [comment]
IDK

**Comment by rtburns-jpl** [comment]
Haha ok, well I'll give it a try. I suppose a partly working recipe is better than one that isn't working at all.

**Comment by beckermr** [comment]
cc @conda-forge/core 

You all might be able to further answer questions here.

**Comment by hmaarrfk** [comment]
Its really strange that sometimes your linux builds fails, sometimes they pass.

It seems that one error message is realted to libaec. So i tried to add it as a dependency.

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/isce2-feedstock/pull/55

**Comment by rtburns-jpl** [comment]
Thanks! I'll take a look
