### ISSUE TITLE
PERF: conda-forge index download speed slow (~1 MB/s)

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/conda-forge.github.io#1835]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
mamba 0.27.0
```

### Issue

I've noticed that the max download speed of the conda-forge package index is remarkably slow: download speed is only 1MB/s

My connection can easily do 20MB/s upwards.

This causes the package download to take ~10s when it should be only 1s.

This may be an infrastructure issue. Not sure whom with and where to raise this. So trying here.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/25161793/196168996-7bcf168d-697d-495e-b657-f59d23c51bf2.png">

**Comment by jakirkham** [comment]
Please raise as a [new discussion item on the `conda/infra` repo]( https://github.com/conda/infra/discussions ). Thanks!

**Comment by corneliusroemer** [comment]
Thanks @jakirkham - we've investigated this in the mamba repo, mentioning here for context: https://github.com/mamba-org/mamba/issues/2021
