### ISSUE TITLE
Ownership of the Matrix-bridged Gitter room 

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge.github.io#1872]
Our beloved Gitter room (https://gitter.im/conda-forge/conda-forge.github.io) can also be accessed from the Matrix network and some of us do it with the Element client. This integration has used several versions of a bridging approach. conda-forge's main room uses an older iteration where Matrix members can end up assuming `admin` permissions in that view of the Gitter room.

@Cadair is the current admin in that room and has agreed to promote core members to admins too. For the sake of transparency, I am writing this issue so there's a public record. I am volunteering here to do so.

> Note we are working with Gitter to transition the conda-forge room to a newer version of the bridge so this is a non-issue.

**Comment by Cadair** [comment]
:wave: happy to help!

Can you give me the mxids of the people who should get admin?

**Comment by jaimergp** [comment]
AFAIK, only @beckermr and I are using the matrix.org sides so that would be:

- `@beckermr:matrix.org`
- `@jaimergp:matrix.org`

**Comment by jaimergp** [comment]
@jakirkham are you also on Matrix?

**Comment by beckermr** [comment]
Thanks a bunch @Cadair! I will write back when I see the permissions change.

**Comment by jakirkham** [comment]
> @jakirkham are you also on Matrix?

Yes and am also jakirkham there :)

**Comment by jakirkham** [comment]
> Thanks a bunch @Cadair! I will write back when I see the permissions change.

Indeed thank you for the help Stuart! 🙏

**Comment by jakirkham** [comment]
@Cadair, is there anything else you need from us?

**Comment by Cadair** [comment]
I have made the changes, you are now all admins.

**Comment by jaimergp** [comment]
Thank you so much @Cadair! I can see the changes now 🚀

**Comment by beckermr** [comment]
Same here. Thank you!

**Comment by beckermr** [comment]
closing!

**Comment by jakirkham** [comment]
Thanks Stuart! 🙏
