### ISSUE TITLE
Urgent: Update project size

### ISSUE THREAD

**Issue by henrykironde** [conda-forge/conda-forge.github.io#1899]
Please add the missing required, 175 or 350 hr designation @jaimergp
https://hackmd.io/@conda-forge/ryxecoj2j

**Comment by ocefpaf** [comment]
@henrykironde I believe projects can be flexible on this depending on the participant proposal, no?

**Comment by henrykironde** [comment]
I would recommend that you choose one.  Google may provide project extensions along the way.

**Comment by jaimergp** [comment]
I updated the wording. I can commit to 12 weeks of mentorship, but it's ok to do it in less time. Hence, it now says "12 weeks, maximum". I hope that works!

**Comment by henrykironde** [comment]
Use either 175 hr or 350 hr (hours not wks)

**Comment by henrykironde** [comment]
@jaimergp please update the project. Google needs to budget, and they can't create the budgets with weeks. The metric used is hr.

**Comment by jaimergp** [comment]
Oh I get it, check now. I went for 350h, which should be like 30h/week for 12 weeks.
