### ISSUE TITLE
Can a package bind to a platform, but not a specific python version?

### ISSUE THREAD

**Issue by paulbkoch** [conda-forge/conda-forge.github.io#1900]
### Your question:

I have what I think might be an atypical python project that is not well covered in the documentation, and I feel that I need some high-level advice on how to improve it.  I've gotten it to work, but the solution feels very hacky to me.  The project is: https://github.com/interpretml/interpret and the feedstock is https://github.com/conda-forge/interpret-core-feedstock

Our project's Azure pipeline is setup to build native libraries for Windows/Mac-Intel/Mac-arm/manylinux-Intel.  These are non-python shared libraries that you could link to from pure C++ code.  For PyPi we take those 4 libraries and include them all in a single bdist, so it behaves like a noarch package in PyPi.  In python we pick the correct library to load and then use ctypes to call the native functions (https://github.com/interpretml/interpret/blob/cb1e0ebb71d0cd43644078d2dfcdb7f55865ef9e/python/interpret-core/interpret/utils/_native.py#L558).  This allows us to work on any python version and use any reasonable numpy version.

When it came to creating the conda-forge package, my thinking was that we could use the conda-forge infrastructure to build the shared library on the various platforms supported by conda-forge.  I modified our build scripts to work in conda-forge since you can't call g++ or gcc directly apparently due to the cross-compilation abilities of conda-forge (https://github.com/interpretml/interpret/blob/cb1e0ebb71d0cd43644078d2dfcdb7f55865ef9e/build.sh#L234).  

In theory, we should be able to work with any version of python just like in PyPi, but the conda-forge build process seems to build for 3.8, 3.9, 3.10 by default, which seems wasteful to me.  I would prefer just a single python 3.* build per platform if that's possible.  There are also quite a few warnings in the build output that look concerning (I can give specifics if necessary) that I suspect are due to the way that I'm building these shared libraries.

Appreciate any comments on better approaches!

**Comment by carterbox** [comment]
My understanding is that `intepret` is a python package which loads shared objects using ctypes.

You should split your package as follows:

`interpret-core` is a CXX-only package which ships shared objects. It does not depend on python. Each target platform has its own build.

`interpret` is a python-only package which depends on `interpret-core` and loads shared objects at runtime using ctypes. It is `noarch: python`, so it built exactly once and shared between all platforms. 

Related: https://github.com/conda-forge/staged-recipes/pull/21691

**Comment by carterbox** [comment]
It looks like with interpret 0.2.4:

- Your noarch python package contains no python modules, but installs python metadata?

- interpret-core contains all of the python modules and the compiled module.

You should move your shared objects to $PREFIX/lib or the standard library location for the platform instead of installing them in site-packages, and use `ctypes.util.find_library()` to locate them.

**Comment by paulbkoch** [comment]
The 0.2.4 package was released in our own conda channel and was packaged the same way as the PyPi package with binaries for all the major platforms.

The 0.2.7 package was our first release in conda-forge.  I made that one just for Windows since I knew I could get that working fairly quickly and that the linux/mac builds would take a bit more effort and changes in the main InterpretML codebase.

Our dependencies are a bit unusual too.  This got discussed while the recipe was staged, and the link for that is: https://github.com/conda-forge/staged-recipes/pull/21691#issuecomment-1405385843

**Comment by paulbkoch** [comment]
Thanks @carterbox -- I'll investigate that further.  This also appears to be the solution that XGBoost took, so that gives me a template on how to achieve it:  https://github.com/conda-forge/xgboost-feedstock/blob/65bdddddf876fce7bafbf82ca109f5a8b48844b2/recipe/meta.yaml#L39

**Comment by carterbox** [comment]
conda doesn't support optional features like pip does. Instead you can create noarch meta packages. i.e. interpret-all, intepret-some-feature-set You would add these metapackages to the interpret feedstock.

**Comment by jakirkham** [comment]
Might also be worth reading PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1839 ). There are still features we'd like in conda-build to adopt to improve the user experience

**Comment by carterbox** [comment]
> Let's say that I wanted to convert my existing recipe into a multi-output recipe to create a new conda package called something like libinterpret. I gather that I need to make a PR in https://github.com/conda-forge/feedstock-outputs/ which will allow the interpret feedstock to publish the new package.

You only need to open a PR there if you are *moving* an output from one feedstock to another; this is to prevent package hijacking/clashes. You can add *new* ouputs to an existing feedstock arbitrarily.

> Does this all sound reasonable so far? Am I missing anything?

Sometimes it's nice to have python and compiled artifacts built in separate feedstocks because it can reduce build times and avoid redundant builds.

> One thing that perplexes me is how the conda_build_config.yaml and conda-forge.yml files values know which of the 3 outputs they should be applied to. 

These variables/pinnings are applied on the recipe level, not per output. See mention above about redundant builds. I've never tried, but you may be able to add `skip` statements to the build section of outputs using selectors, so the noarch packages are only built on linux64, but the logic becomes for this type of selection increases in complexity with the number of build variants.

**Comment by paulbkoch** [comment]
I think based solely on the added complexity of handling conda_forge.yaml I will use separate feedstocks, so thank you for that insight @carterbox!
