### ISSUE TITLE
Doc update script failing?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#192]
Appears the doc update script started failing in its last run. It's not entirely clear from the log what the failure is. It simply prints the diff of the new commit and fails. @pelson, any ideas as to what is going on?

**Comment by pelson** [comment]
Given it is SciPy time of year, it could very easily be a token expiring or something. I'll take a look.

**Comment by jakirkham** [comment]
> Nope, looks fine.

Is that denial? 😆

**Comment by jakirkham** [comment]
Looks like the last build completed. 😕 Had tried to restart it before, but it had made no difference. Not sure what changed, but am closing this. We should keep an eye on it though.

**Comment by jakirkham** [comment]
Weirdly the docs [failed]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/145013773 ) again last night, but worked fine today after merging the [minutes]( https://github.com/conda-forge/conda-forge.github.io/pull/187 ). Not sure why though as there is no clear error. Very strange. 😕

**Comment by jakirkham** [comment]
Failing again. See this [log]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/145384907 ). Restarting did not help. Still no clear error message.

**Comment by jakirkham** [comment]
Worked last night. So closing again. Still don't know what changed. 😕

**Comment by jakirkham** [comment]
Looked into this recently and think I found the fix. Please see PR ( https://github.com/conda-forge/conda-forge.github.io/pull/202 ). There are other cases that may fail, but they can at least be navigated around by a restart now (if needed).

**Comment by jakirkham** [comment]
This has been much better behaved with the aforementioned change.
