### ISSUE TITLE
@conda-forge-admin update version

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/conda-forge.github.io#1929]
### Your question:

Sometimes I would not like to wait for the bot to detect an upgrade. It would be great to tell the bot to look now!

---

It is true that all it needs is changing two lines, but is does require rebasing a fork, computing the checksum, pushing, opening the PR. All in all tedious work that the bot could do so easily

@jaimergp @beckermr

**Comment by tdegeus** [comment]
Amazing that we will have this command! However, on initial use the bot fails to find v0.22.0 here : https://github.com/conda-forge/goosehdf5-feedstock/pull/46

**Comment by beckermr** [comment]
It will never happen right away since we use github actions to do the work. I think we'll need to improve the messaging so people will know it will take a bit of time.

**Comment by leofang** [comment]
@beckermr Is the bot using [this code](https://github.com/regro/cf-scripts/blob/36cdec4560688d99aeced594f9d7e5da10e093b2/conda_forge_tick/update_sources.py#L68) to guess versions? I noticed that it has hard time in guessing a CalVer (ex: it wouldn't be able to jump from 22.11 to 23.03), but I don't have a good way to improve it without storing some metadata in each feedstock to help the bot make a guess.

**Comment by beckermr** [comment]
yes it is using that code.

**Comment by tdegeus** [comment]
Is it intentional that the `automerge` is not added? I would have find it logical to add it as the PR will be like other bot opened PRs

**Comment by beckermr** [comment]
Yes. If we added automerge than anyone would be able to merge prs into our feedstocks. That is a security risk.

**Comment by tdegeus** [comment]
Makes sense

**Comment by jakirkham** [comment]
Since it doesn't appear to be explicitly noted here, [this command was added]( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-update-version ). So users can request an update
