### ISSUE TITLE
Is there a web API for searching for conda packages?

### ISSUE THREAD

**Issue by abalter** [conda-forge/conda-forge.github.io#1931]
### Your question:

Something equivalent to `conda search` but as a web API.

**Comment by isuruf** [comment]
See https://api.anaconda.org/docs

**Comment by abalter** [comment]
[This](https://api.anaconda.org/docs#/package/get_search) does not work. Or, if you can get it to work, could you create a URL with an example search?

**Comment by dopplershift** [comment]
Well it's not an API we maintain or maintain documentation for. I'd suggest [reaching out to them](https://anaconda.org/contact) with this question.
