### ISSUE TITLE
Way to search for latest version of package?

### ISSUE THREAD

**Issue by abalter** [conda-forge/conda-forge.github.io#1932]
### Your question:

The [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-search.html) on searching for packages is great. I don't see an option to search for just the most recent version. In addition to other simplifications, it would allow to just get a single result.

**Comment by isuruf** [comment]
This doesn't seem to be related to conda-forge

**Comment by abalter** [comment]
If I understand correctly, to search for packages in conda-forge I would do `conda search -c conda-forge`. So doesn't that have to do with conda-forge?

**Comment by carterbox** [comment]
conda-forge is an organization which publishes packages to a specific conda channel. We do not develop "conda", the package manager. If you have questions about the conda CLI, this is no the place to ask them.

**Comment by abalter** [comment]
Ok. That makes sense. But I would say kind of surly answers.
