### ISSUE TITLE
Uploads broken for (likely) all feedstocks

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/conda-forge.github.io#1958]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
Happens in CI
```

### Environment info

```shell
Happens in CI
```

### Issue

Currently CI fails when uploading with:
```
Distribution /home/conda/feedstock_root/build_artifacts/noarch/coiled-0.6.3-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
WARNING: Distribution /home/conda/feedstock_root/build_artifacts/noarch/coiled-0.6.3-pyhd8ed1ab_0.conda already existed in cf-staging for a while. Deleting and re-uploading.

  0%|          | 0.00/116k [00:00<?, ?B/s]
  7%|▋         | 8.00k/116k [00:00<00:03, 34.9kB/s]
 69%|██████▉   | 80.0k/116k [00:00<00:00, 288kB/s] 
121kB [00:00, 236kB/s]                            
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 87.96388244628906 seconds
```
I saw this happen for these recently updated feedstocks:
- https://github.com/conda-forge/coiled-feedstock
- https://github.com/conda-forge/adaptive-feedstock
- https://github.com/conda-forge/lightning-cloud-feedstock
- https://github.com/conda-forge/pymdown-extensions-feedstock
- https://github.com/conda-forge/r-collections-feedstock

I believe this affects *all* feedstocks.

**Comment by basnijholt** [comment]
It's probably appropriate to tag @conda-forge/core here.

No new upload can happen at the moment.

**Comment by beckermr** [comment]
heroku does a daily restart of the webserver and recently it has been failing sometimes. IDK why. I have rebooted it again.

**Comment by basnijholt** [comment]
Thanks, that seems to have worked 😄 

I will close this issue.

Is there an open issue for the failing reboot of the webserver? This will be useful for folks that run into this issue in the future.

**Comment by beckermr** [comment]
I do not know of one...
