### ISSUE TITLE
Problems with bot-rerun

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#1959]
I've seen a number of PRs recently where the bot did not reopen a PR even days after the label was added (e.g. https://github.com/conda-forge/gymnasium-feedstock/pull/26, https://github.com/conda-forge/qt-main-feedstock/pull/156).

Not sure if the bot is just slow, but that seems much longer than it used to take.

CC @beckermr @hmaarrfk

**Comment by beckermr** [comment]
This was a bug. I fixed it today I think. If you mark a pr today and it doesn't get remade, let me know.

**Comment by mfansler** [comment]
I can confirm it has worked properly several times since.

**Comment by jakirkham** [comment]
Yep also was able to use this successfully within the last day
