### ISSUE TITLE
Segmentation Fault error in recent conda mambabuild step in builds on linux-64 and osx-64

### ISSUE THREAD

**Issue by traversaro** [conda-forge/conda-forge.github.io#1960]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

### Issue

I still need to investigate the issue, but I saw many segmentation fault during the `conda mambabuild`  step of package generation in different unrelated repositories:
* https://github.com/conda-forge/yarp-feedstock/pull/25
* https://github.com/conda-forge/libsdformat-feedstock/pull/92
* https://github.com/conda-forge/gz-rendering-feedstock/pull/9

The errors are all like:
~~~
INFO:conda_build.metadata:Attempting to finalize metadata for gz-rendering7
Attempting to finalize metadata for gz-rendering7
Reloading output folder: /home/conda/feedstock_root/build_artifacts
Reloading output folder: /home/conda/feedstock_root/build_artifacts
BUILD START: ['libgz-rendering7-7.3.1-h5c09c84_0.conda', 'gz-rendering7-7.3.1-ha770c72_0.conda']
Reloading output folder: /home/conda/feedstock_root/build_artifacts
Reloading output folder: /home/conda/feedstock_root/build_artifacts
/home/conda/feedstock_root/.scripts/build_steps.sh: line 86:   168 Segmentation fault      (core dumped) conda mambabuild "${RECIPE_ROOT}" -m "${CI_SUPPORT}/${CONFIG}.yaml" --suppress-variables ${EXTRA_CB_OPTIONS:-} --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"
##[error]Bash exited with code '139'.
Finishing: Run docker build
~~~

As a first step, I need to check the version of conda/mamba/boa of this failing jobs against the latest successful jobs. However, I opened the issue here in case anyone else is experiencing this.

Interestingly, Windows and cross-compilation builds do not seem to be affected by this.

**Comment by traversaro** [comment]
> Please let me know if I need to create separated issue

I think it is the same issue. I also noticed that a new version of boa was released yesterday, not sure if you is related.

**Comment by artanokhov** [comment]
@traversaro 
I've pinned boa to version 0.14.0 and seems like it helps after re-rendering project in PR
https://github.com/conda-forge/openvino-feedstock/pull/2/commits/59af9eab6c75813385d77cb122ebf534b4d782ef

FYI
I'm also pinned py-lief & liblief from this original issue
conda-forge/conda-forge.github.io/issues/1823
So my local fix contain following lines for [conda-forge.yml](https://github.com/conda-forge/openvino-feedstock/blob/59af9eab6c75813385d77cb122ebf534b4d782ef/conda-forge.yml)

```
remote_ci_setup:
  - liblief=0.11.5
  - py-lief<0.12
  - boa=0.14.0
  - conda-forge-ci-setup=3
```

**Comment by artanokhov** [comment]
I've prepared PR with short-term fix for conda-forge CI
https://github.com/conda-forge/conda-smithy/pull/1736

**Comment by artanokhov** [comment]
> I've prepared PR with short-term fix for conda-forge CI [conda-forge/conda-smithy#1736](https://github.com/conda-forge/conda-smithy/pull/1736)

UPD It's not necessary due to conda-forge/admin-requests/pull/720

**Comment by traversaro** [comment]
The error seems resolved by https://github.com/conda-forge/admin-requests/pull/720 . Is the boa 0.15 problem tracked somewhere @conda-forge/boa ? Can we just close this?

**Comment by traversaro** [comment]
Let's close this, if necessary we can open again.
