### ISSUE TITLE
gst-plugins-base is not built with Pango

### ISSUE THREAD

**Issue by KeithThorneLIGO** [conda-forge/conda-forge.github.io#1968]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
# packages in environment at /opt/conda/base/envs/cds:
#
# Name                    Version                   Build  Channel
gst-libav                 1.21.3               h64eab2d_0    conda-forge
gst-plugins-base          1.21.3               h4243ec0_1    conda-forge
gst-plugins-good          1.21.3               hbba150b_1    conda-forge
gst-python                1.21.3           py39h7e41a24_1    conda-forge
gstreamer                 1.21.3               h25f0c4b_1    conda-forge
gstreamer-orc             0.4.33               h166bdaf_0    http://puppet1/conda
```

### Environment info

```shell
active environment : cds
    active env location : /opt/conda/base/envs/cds
            shell level : 1
       user config file : /home/keith.thorne/.condarc
 populated config files : /opt/conda/base/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.9
         python version : 3.9.13.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda/base  (read only)
      conda av data dir : /opt/conda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/base/pkgs
                          /home/keith.thorne/.conda/pkgs
       envs directories : /home/keith.thorne/.conda/envs
                          /opt/conda/base/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Linux/3.10.0-1160.66.1.el7.x86_64 scientific/7.9 glibc/2.17
                UID:GID : 40034:40034
             netrc file : None
           offline mode : False
```

### Issue

The gst-plugins-base package is supposed to have Pango and related items, like clockoverlay.  This is clearly detailed in the gst-plugins-base sub-project in gstreamer [gst-plugins-base repo](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/tree/main/subprojects/gst-plugins-basel).  However, it appears the process uploaded this to conda-forge is not building it with the Pango dependencey, so the clockoverlay, etc are not there
(cds) keith.thorne@cr81:~$ gst-inspect-1.0 clockoverlay
No such element or plugin 'clockoverlay'
- using native packages for the same from Fedora (also Debian) it is there
- keith.thorne@cr81:~$ gst-inspect-1.0 clockoverlay
Factory Details:
  Rank                     none (0)
  Long-name                Clock overlay
  Klass                    Filter/Editor/Video
  Description              Overlays the current clock time on a video stream
  Author                   Tim-Philipp Müller <tim@centricular.net>

Plugin Details:
  Name                     pango
  Description              Pango-based text rendering and overlay
  Filename                 /usr/lib64/gstreamer-1.0/libgstpango.so
  Version                  1.14.4
  License                  LGPL
  Source module            gst-plugins-base
  Source release date      2018-10-02
  Binary package           Fedora GStreamer-plugins-base package
  Origin URL               http://download.fedoraproject.org

At present, I find no way to get these plugins from conda-forge

**Comment by mfansler** [comment]
Probably better filed on the feedstock: https://github.com/conda-forge/gstreamer-feedstock

**Comment by KeithThorneLIGO** [comment]
I will do that.  Thanks
