### ISSUE TITLE
Bump minimal CUDA version to CUDA 11.8?

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge.github.io#1981]
Follow-up of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708, which removed the support for CUDA 11.1 and below.

For now, all GPU packages are built with CUDA 11.2+. But, for CUDA 11 users there are still a few issues left unaddressed:
1. Hopper GPUs (cc_90/sm_90) are not supported
2. NCCL does not have CUDA graph support (https://github.com/conda-forge/nccl-feedstock/issues/62)

I would like to suggest that we issue a migrator to move from CUDA 11.2 to 11.8. Because of CUDA minor version compatibility since CUDA 11.0 (or 11.2 if NVRTC is involved), most likely most packages should work just fine. For example, recent cuQuantum/cuTENSOR libraries ship binaries built with CUDA 11.8 to serve all CUDA 11 users.

The main exception would be packages shipping PTX code, as discussed [here](https://pypackaging-native.github.io/key-issues/gpus/#additional-notes-on-cuda-compatibility) and in CUDA documentation. It could be possible that we issue a message in the migrator to keep feedstock maintainers alerted?

Discussion/feedback is more than welcome!

**Comment by bdice** [comment]
Yes, this agrees with my understanding of CUDA minor version compatibility and would be necessary to support Hopper GPUs. RAPIDS has been building conda packages with CUDA 11.8 for some time now with minor version compatibility extensively tested on 11.2, 11.4, 11.5, 11.8. I support this.

**Comment by leofang** [comment]
> Can we backport CUDA 12 packages to 11.8? I remember that we can do that for 11.4+

As much as I'd like for a backport, I am not the right person to answer this question (@jakirkham @adibbley for vis). But, I do think it's an independent discussion worth of its own issue. @isuruf how is a backport relevant here?

**Comment by isuruf** [comment]
If we are going to rebuild, it would be good to have. Otherwise we'd have to do a migration again.

**Comment by adibbley** [comment]
There are no plans to backport the CUDA 12 packages, we started there to give a clean cut away from `cudatoolkit`.

**Comment by jakirkham** [comment]
Based on discussion in the core meeting today, it sounds like we are ok with going ahead with a CUDA 11.8 migration using `cudatoolkit`. Will get this started and update here once that PR is up. Thanks all! 🙏

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4834 ) to add a CUDA 11.8 migrator

While many of the pieces are there (Docker images, Windows, etc.) for CUDA 11.8, cross-compilation support doesn't currently exist for CUDA 11.8. To that end, started PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/261 ), which will need a review (and maybe more changes)
