### ISSUE TITLE
osx_arm64: more detailed instructions

### ISSUE THREAD

**Issue by MarDiehl** [conda-forge/conda-forge.github.io#1983]
### Where should the content be added?

https://conda-forge.org/docs/maintainer/knowledge_base.html

### What should be added?

I could not find detailed instructions for adding osx-arm64 support for an MPI package and succeeded only with the help of @isuruf. Some information is available on
- https://conda-forge.org/docs/maintainer/knowledge_base.html#cross-compilation
- https://conda-forge.org/blog/posts/2020-10-29-macos-arm64

An related issue is https://github.com/conda-forge/conda-forge.github.io/issues/1534, which also mentions a migrator (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt).

There are two routes for an improved documentation: Either have add an extra section on (cross)-compiling for osx-arm64 or add content to https://conda-forge.org/docs/maintainer/knowledge_base.html#cross-compilation and https://conda-forge.org/docs/maintainer/knowledge_base.html#message-passing-interface-mpi. This should be consistent with the approach for other non-default architectures.

### Additional information

Content of the documentation
- https://conda-forge.org/blog/posts/2020-10-29-macos-arm64 is a good starting point, most of it should become part of the official documentation to emphasize that this is the current state and not just an potentially outdated blog post.
- for https://github.com/conda-forge/libfyaml-feedstock (autotools) `cp $BUILD_PREFIX/share/gnuconfig/config.* .` was not required.
- build requirement for mpi: ` openmpi  # [mpi == 'openmpi' and build_platform != target_platform]` (with explicit explanation why openMPI and MPICH behave differently).

**Comment by jaimergp** [comment]
Excellent timing, @MarDiehl!

@FFY00 is currently documenting how different ecosystems approach cross-compilation in Python projects in [PEP720 (draft)](https://peps.python.org/pep-0720/) and I've been instructed to compile some info about how we do things over here.

As you can see, conda-forge's strategy is not fully documented so this is a good time to revisit and consolidate how we are doing things. I for one don't know too much about all the business concerning `crossenv`, even after reading the blog post or the PEP. 

I'd like to ask folks to help me understand and collaborate in writing something we can refer to officially. I will do some more reading and start a PR soon.

Tagging @conda-forge/core for awareness.

**Comment by jaimergp** [comment]
Hi again! I started a PR at https://github.com/conda-forge/conda-forge.github.io/pull/1985. Hopefully we can all collaborate there to have better documentation around cross-compilation!
