### ISSUE TITLE
Get higher resolution logo

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#2]
Source can be found in attribution.txt. Needed for introduction section of conda-forge.github.io.

**Comment by jakirkham** [comment]
It looks pretty high res. Are we thinking about using conda-forge on a PS4 hooked up to a giant flat screen? 😆 Or more realistically a projector?

**Comment by pelson** [comment]
The image is 90x47... it looks pretty blocky on conda-forge.github.io (https://github.com/conda-forge/conda-forge.github.io/blob/master/img/anvil_white.png). Are we looking at the same image?

**Comment by viniciusdc** [comment]
@isuruf may we close this one?

**Comment by jakirkham** [comment]
Logos can be found here ( https://github.com/conda-forge/marketing/tree/master/logo )
