### ISSUE TITLE
build fails after upgrading to jpeg 9

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/conda-forge.github.io#200]
Here is the compiler error
```
$ make
[  1%] Building CXX object libEM/CMakeFiles/EM2.dir/jpegio.o
/Users/durmaz/anaconda/conda-bld/work/libEM/jpegio.cpp:155:2: error: no matching function for call to 'jpeg_set_quality'
        jpeg_set_quality(&cinfo, jpegqual, true);
        ^~~~~~~~~~~~~~~~
/Users/durmaz/anaconda/envs/_build/include/jpeglib.h:991:14: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 3rd argument
EXTERN(void) jpeg_set_quality JPP((j_compress_ptr cinfo, int quality,
             ^
```

Tracking down the definition lines for `boolean` in conda-forge's and anaconda's `libjpeg` files, in `jmorecfg.h`

anaconda, jpeg-8d-1: jmorecfg.h
`typedef int boolean;`

conda-forge, jpeg-9b-0: jmorecfg.h
`typedef enum { FALSE = 0, TRUE = 1 } boolean;`

**Comment by ocefpaf** [comment]
@shadowwalkersb what are you trying to build? If that is a package in `conda-forge` can you open an issue in that package's feedstock?

BTW `conda-forge` uses `jpeg 9b`, so maybe whatever you are trying to build may need a patch to work with the modern `jpeg` or you need to pin it to the older version.

Closing this as this issue does not belong in `conda-forge.github.io`, but feel free to answer here so we can find more about the problem.

**Comment by shadowwalkersb** [comment]
Sorry for the noise! I guess this IS the wrong place. Now, I know where to seek help for specific packages.
