### ISSUE TITLE
Make python 3.12.1 available in conda-forge

### ISSUE THREAD

**Issue by Chuck321123** [conda-forge/conda-forge.github.io#2042]
### Your question:

Hi, I dont know how to proceed to put the newest version of python to conda-forge. Therefore, I wondered if someone else could do it? Thanks

**Comment by hmaarrfk** [comment]
see https://github.com/conda-forge/python-feedstock/pull/655

feel free to open your PR that updates the `meta.yaml` as needed and others can review.
