### ISSUE TITLE
Image `macOS-11` deprecated

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#2067]
Related (but tangential) to #1844, I just saw that the `macOS-11` image is now deprecated: https://github.com/actions/runner-images/commit/5418817c5fd272379f7d5a56c2e63a3d7f1a49d8

This isn't creating noise in the pipelines yet, but will be removed in Q2 according to https://github.com/actions/runner-images/issues/9255. Compare the last time this happened: https://github.com/conda-forge/conda-forge.github.io/issues/1798

**Comment by jaimergp** [comment]
[Azure hasn't deprecated it yet](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software). According to that repo README:

> The availability of images for GitHub Actions and Azure DevOps is the same. However, deprecation policies may differ. 

On GHA, [we use `-latest`](https://github.com/conda-forge/conda-smithy/blob/a8d97615481230ff3aa87bab8a92d0e2c98f1ec6/conda_smithy/configure_feedstock.py#L1324).

**Comment by jaimergp** [comment]
Ok, macos-11 is now deprecated:

<img width="683" alt="image" src="https://github.com/conda-forge/conda-forge.github.io/assets/2559438/967ddf8b-4592-441f-8230-2f9c87cfeaa7">

**Comment by jaimergp** [comment]
I opened https://github.com/conda-forge/conda-smithy/pull/1914 for now. We have ~2 months.

**Comment by jakirkham** [comment]
Anything else still needed here?

**Comment by jaimergp** [comment]
Release a new Smithy and maybe publish an announcement here.

**Comment by jakirkham** [comment]
Requested a release here: https://github.com/conda-forge/conda-smithy/issues/1915

**Comment by jaimergp** [comment]
Release is out. I'll put a short announcement.
