### ISSUE TITLE
Automated Pinning pull requests are not sent

### ISSUE THREAD

**Issue by 183amir** [conda-forge/conda-forge.github.io#207]
I have added some new pinnings in this pull: https://github.com/conda-forge/conda-forge.github.io/pull/194 but have not seen any pull requests in my feedstocks proposing these changes.
The affected feedstocks as many as I can find are: 

* `bob.io.video`
* `bob.learn.libsvm`
* `bob.blitz`
* `bob.io.matlab`
* `bob.io.audio`
* `bob.ip.base`

**Comment by jakirkham** [comment]
Putting this one on your radar, @pelson.

**Comment by pelson** [comment]
I have started iterating on the pinning script in https://github.com/conda-forge/conda-smithy/pull/269.

**Comment by jakirkham** [comment]
They appear to be going out. So am closing this. Please let us know if more issues arise.
