### ISSUE TITLE
repodata does not match actual package dependencies

### ISSUE THREAD

**Issue by bronsonrudner** [conda-forge/conda-forge.github.io#2082]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### Issue

# Summary

The repodata for conda-forge/linux-64 gives incorrect dependencies for package pycurl-7.45.1-py39h9297c8b_3, and possibly other packages too.

This breaks the following use case:
1. Solve for an environment from conda-forge
2. Ingest solved packages and reindex in self-hosted repository
3. Solve for environment from self-hosted repository <- does not work, because dependencies no longer match

# Issue for pycurl in detail
repodata shows this build of pycurl depends on libcurl<9.0a0
```
>>> import requests
>>> response = requests.get("https://conda.anaconda.org/conda-forge/linux-64/repodata.json")
>>> repodata = response.json()
>>> repodata["packages"]["pycurl-7.45.1-py39h9297c8b_3.tar.bz2"]["depends"]
['libcurl >=7.86.0,<9.0a0', 'libgcc-ng >=12', 'openssl >=3.0.5,<4.0a0', 'python >=3.9,<3.10.0a0', 'python_abi 3.9.* *_cp39']
```
However, actually downloading the package and looking at the index.json shows it depends on libcurl<8.0a0
```
{
  "arch": "x86_64",
  "build": "py39h9297c8b_3",
  "build_number": 3,
  "depends": [
    "libcurl >=7.86.0,<8.0a0",
    "libgcc-ng >=12",
    "openssl >=3.0.5,<4.0a0",
    "python >=3.9,<3.10.0a0",
    "python_abi 3.9.* *_cp39"
  ],
  "license": "LGPL, MIT",
  "license_family": "LGPL",
  "name": "pycurl",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1666966322861,
  "version": "7.45.1"
}
```

**Comment by xhochy** [comment]
> This breaks the following use case:
>
> 1. Solve for an environment from conda-forge
> 2. Ingest solved packages and reindex in self-hosted repository

This use-case is not supported as we do repodata patching. This will end up in having lots of instances where package metadata and repodata no longer match. If you want to mirror some packages, please also mirror the repodata. For example, you could use https://github.com/conda-incubator/conda-mirror for this.

**Comment by xhochy** [comment]
> I'm unsure what to propose as a workaround.

To make it clear: Also mirroring the repodata is the workaround.

Alternatively, you could also apply the repodata patches locally, but this will probably be much slower.

**Comment by bronsonrudner** [comment]
Thank you for the context! We'll try those workarounds.
