### ISSUE TITLE
conda_build.conda_interface is getting deprecated

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#2117]
There are instances of these scattered throughout conda-forge. See https://github.com/search?q=org%3Aconda-forge+conda_interface&type=code

conda_build PR: https://github.com/conda/conda-build/pull/5222

tasks:

- [x] https://github.com/mamba-org/boa/pull/395
- [x] https://github.com/conda-forge/conda-smithy/pull/1868
- [x] https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/305
- [x] https://github.com/conda-forge/cdt-builds/pull/69
- [x] https://github.com/conda-forge/conda-forge-webservices/pull/577
- [x] https://github.com/regro/conda-forge-feedstock-check-solvable/pull/20
- [x] https://github.com/conda-forge/staged-recipes/pull/25762
- [x] repodata patches (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/686)
  - [x] boa
  - [x] smithy
  - [x] conda-forge-ci-setup-feedstock
  - [x] conda-forge-feedstock-check-solvable
 - [x] new releases with updates
   - [x] boa (https://github.com/mamba-org/boa/pull/396, https://github.com/conda-forge/boa-feedstock/pull/80)
   - [x] conda-smithy (https://github.com/conda-forge/conda-smithy-feedstock/pull/283)
   - [x] conda-forge-ci-setup-feedstock (happens with fixes on feedstock)
   - [x] conda-forge-feedstock-check-solvable (https://github.com/regro/conda-forge-feedstock-check-solvable/releases/tag/0.5.0)

**Comment by mbargull** [comment]
- https://github.com/mamba-org/boa/pull/395
- https://github.com/conda-forge/conda-smithy/pull/1868
- https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/305
- https://github.com/conda-forge/cdt-builds/pull/69
- https://github.com/conda-forge/conda-forge-webservices/pull/577
- https://github.com/regro/conda-forge-feedstock-check-solvable/pull/20
- https://github.com/conda-forge/staged-recipes/pull/25762

**Comment by mbargull** [comment]
AFAICT, we just have to hit merge for the remaining `conda-forge-repodata-patches-feedstock` and `boa-feedstock` PR and should be all set then.

I wouldn't mind if someone took a quick look on whether I missed something important.
I used these queries to look for `conda`/`conda_build` imports:
- conda-forge:
    https://github.com/search?q=org%3Aconda-forge+-is%3Aarchived+%2F%28%3F-i%29%5Cbfrom+%2B%28conda%7Cconda_build%29%5Cb%28%3F%3A%5B.+%28%5C%5C%5D%29.*%28%5Cbimport%5Cb%7C%5C%5C%24%29%7C%5Cbimport+.*%5Cb%28conda%7Cconda_build%29%5Cb%28%5B.%2C+%3B%5C%5C%5D%7C%24%29%2F&type=code
- regro:
    https://github.com/search?q=org%3Aregro+-is%3Aarchived+%2F%28%3F-i%29%5Cbfrom+%2B%28conda%7Cconda_build%29%5Cb%28%3F%3A%5B.+%28%5C%5C%5D%29.*%28%5Cbimport%5Cb%7C%5C%5C%24%29%7C%5Cbimport+.*%5Cb%28conda%7Cconda_build%29%5Cb%28%5B.%2C+%3B%5C%5C%5D%7C%24%29%2F&type=code
- mamba-org:
    https://github.com/search?q=org%3Amamba-org+-is%3Aarchived+%2F%28%3F-i%29%5Cbfrom+%2B%28conda%7Cconda_build%29%5Cb%28%3F%3A%5B.+%28%5C%5C%5D%29.*%28%5Cbimport%5Cb%7C%5C%5C%24%29%7C%5Cbimport+.*%5Cb%28conda%7Cconda_build%29%5Cb%28%5B.%2C+%3B%5C%5C%5D%7C%24%29%2F&type=code

**Comment by beckermr** [comment]
LGTM!

**Comment by mbargull** [comment]
Task list all done; closing.
