### ISSUE TITLE
Status page: query params instead of pretty URLs?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge.github.io#2132]
@afshin was mentioning (please, extend this as necessary) that technically speaking, we shouldn't be using pretty URLs (`/status/migration/name`) for the migration details page, but instead query params (`/status/?migration=name`).

This would prevent the "404 flash" and would better comply with the "contract of page permanence".

**Comment by afshin** [comment]
I think it would most likely look like `/status/migration?name={name}`, but yes, otherwise exactly as Jaime says!

**Comment by jaimergp** [comment]
While we are at it, could we also add a `view={table,graph}` param?

**Comment by afshin** [comment]
That is also pretty straightforward and sounds reasonable.
