### ISSUE TITLE
Add a clickable link for migrations svgs

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#2135]
### What should be added?

Previously the svg was clickable and it redirected to https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/migration_svg/aarch64andppc64leaddition.svg for eg. This is gone with the new website.

cc @jaimergp

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-forge.github.io/pull/2136
