### ISSUE TITLE
Assign more disk space to the azure runner

### ISSUE THREAD

**Issue by xiki-tempula** [conda-forge/conda-forge.github.io#2198]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### Issue

I'm trying to build a MPI+cuda package https://github.com/conda-forge/ambertools-feedstock/pull/144, however, the build failed due to `No space left on device`, I wonder how to assign more disk space to the azure runner? Thanks.

**Comment by jakirkham** [comment]
Would look at [`conda-forge.yml`'s `azure` key]( https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure ). Something like this is what you would need (with a [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks )):

```yaml
azure:
  free_disk_space: true
```

**Comment by xiki-tempula** [comment]
It works. Thanks.
