### ISSUE TITLE
Cuda build varient got removed for unknown reason

### ISSUE THREAD

**Issue by xiki-tempula** [conda-forge/conda-forge.github.io#2202]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### Issue

For the Gromacs-feedstock, we used to have build variant for CUDA support. However, this PR (https://github.com/conda-forge/gromacs-feedstock/pull/50), which only changes the build number in the meta.yaml file somehow wiped out all the cuda builds. We tried to bring the cuda build back (https://github.com/conda-forge/gromacs-feedstock/pull/54) but cannot seems to get it to work.
I wonder if I could have some help from the conda-forge team, please? Thanks.

**Comment by carterbox** [comment]
We dropped support for CUDA 11.2. https://conda-forge.org/news/2024/03/06/dropping-cuda-112/

Please enable you recipe to build against later CUDA Toolkit versions.

**Comment by xiki-tempula** [comment]
I see thanks.
