### ISSUE TITLE
My package has not updated on `conda-forge` after merging the feedstock PR

### ISSUE THREAD

**Issue by jtherrmann** [conda-forge/conda-forge.github.io#2213]
A `conda-forge` package that I help to maintain, [`asf_tools`](https://anaconda.org/conda-forge/asf_tools), currently shows v0.7.2, although I merged the [feedstock PR](https://github.com/conda-forge/asf_tools-feedstock/pull/23) for v0.8.0 about 20 hours ago. I'm not sure where to look for failures in the update process. Can someone point me in the right direction?

**Comment by isuruf** [comment]
Azure CI did not start. Restarted manually. You can push an empty commit next time

**Comment by jtherrmann** [comment]
@isuruf It's updated now, thanks! Is the Azure CI something I could have diagnosed myself, or do I not have permissions to view it?

**Comment by isuruf** [comment]
You can see the links at https://github.com/conda-forge/asf_tools-feedstock?tab=readme-ov-file#current-build-status

**Comment by jtherrmann** [comment]
Thanks!
