### ISSUE TITLE
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. 

### ISSUE THREAD

**Issue by dhzhen2009** [conda-forge/conda-forge.github.io#2217]
### Comment:

I have an Apple M1 computer. I have confirmed that PyTorch, TensorFlow and Flax are all installed. When installing Dify using Docker Compose and starting the containers for api and worker, the following errors are reported: None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

**Comment by jakirkham** [comment]
Have transferred this to the webpage repo, which is a good place for general questions

In order for someone to help you here, would recommend including a minimal reproducer that shows what you tried, what happened, and some way others can repeat what you saw (and thus be able to advise further). Could you please give that a go? Even a rough attempt at this would be helpful 🙂

**Comment by hmaarrfk** [comment]
No response from Original poster.

Please open a new issue providing the requested information in the template if the issue persists.
