### ISSUE TITLE
Torchvision and tensorflow compatibility issue 

### ISSUE THREAD

**Issue by sanujv** [conda-forge/conda-forge.github.io#2220]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
Python3.11.5
Openssl 3.3.1
Many more packages.
```

### Environment info

```shell
We have a local repository configured in one server and updating the packages from conda-forge there
```

### Issue

The few critical packages are giving issue.like torchvision and tensorflow. We have torchvision 2.16.0 downloaded from conda-forge and torchvision.

There are multiple dependency issues coming in

**Comment by hmaarrfk** [comment]
Sorry you are experiencing this issue. 

Please reopen an issue with all the requested information. 

We ask for alot of system info y9u simply skipped over

Very interested in helping you resolve this over all. Please ping me when you reopen.

**Comment by hmaarrfk** [comment]
One thing about our repository is that we use repo-data patches, I'm not sure if you are mirroring them.

Ultimately, as an open source community, we can't offer support to all kinds of customizations.

Please try to create a reproducer with

```
mamba create --channel conda-forge --override-channels --name test python=3.11 "tensorflow>=2.16.2" torchvision
mamba activate test
python -c "SOME CODE THAT CREATES A CRASH"
```

or the like.

Then please provide the full outputs (as requested in the template)

```
mamba list
mamba info
```
