### ISSUE TITLE
Mac Azure pipelines randomly failing on squash merge

### ISSUE THREAD

**Issue by arnabanimesh** [conda-forge/conda-forge.github.io#2225]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

### Issue

Check the builds corresponding to the commit history of https://github.com/conda-forge/fastexcel-feedstock

**Comment by mfansler** [comment]
That is a sporadic network failure. This happens infrequently and at random. Since the macOS SDK is a large download, it is proportionally more likely for such things to occur there.

Maintainers (or core) just need to hit the "Re-run" on the job and should be fine.

I recommend this be closed.
