### ISSUE TITLE
Packages not building

### ISSUE THREAD

**Issue by peastman** [conda-forge/conda-forge.github.io#2226]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
N/A.  This doesn't involve any local operations, just the github build infrastructure.
```

### Environment info

```shell
N/A.  This doesn't involve any local operations, just the github build infrastructure.
```

### Issue

About half the time when I merge a PR from my feedstock, it doesn't trigger new builds.  In the past I was able to force it to build by directly pushing an empty commit, following these instructions provided by @jaimergp:

```
git remote -v
git checkout master
git fetch upstream master
git merge upstream/master
git commit --allow-empty -m "Trigger CI"
git push upstream master
```

But something has changed such that it doesn't work anymore.  How can I force it to build the new packages when just merging the PR doesn't do it?  I have a [release](https://github.com/conda-forge/openmm-feedstock/pull/133) currently blocked by this issue.

**Comment by jaimergp** [comment]
Isn't the default branch `main` for a while now? Might need to adjust those commands.

**Comment by peastman** [comment]
Right, I did change it to main when I executed the commands, sorry.  Here's what I got when I tried to push it:

```
$ git push upstream main
Everything up-to-date
```

My interpretation is that it realizes the empty commit didn't really change anything, so it doesn't create a new commit in the upstream repo.

**Comment by jaimergp** [comment]
Let me give it a try, I'd be surprised if `git` had changed that behavior.

**Comment by peastman** [comment]
> git push upstream HEAD:main should fix this

It looks like that did it.  Thanks!
