### ISSUE TITLE
Playwright package looks like installed but but it is not

### ISSUE THREAD

**Issue by luftuq** [conda-forge/conda-forge.github.io#2228]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
List of packages in environment: "/opt/conda"

  Name              Version   Build               Channel    
───────────────────────────────────────────────────────────────
  _libgcc_mutex     0.1       conda_forge         conda-forge
  _openmp_mutex     4.5       2_gnu               conda-forge
  bzip2             1.0.8     h4bc722e_7          conda-forge
  ca-certificates   2024.7.4  hbcca054_0          conda-forge
  icu               73.2      h59595ed_0          conda-forge
  ld_impl_linux-64  2.40      hf3520f5_7          conda-forge
  libexpat          2.6.2     h59595ed_0          conda-forge
  libffi            3.4.2     h7f98852_5          conda-forge
  libgcc-ng         14.1.0    h77fa898_0          conda-forge
  libgomp           14.1.0    h77fa898_0          conda-forge
  libnsl            2.0.1     hd590300_0          conda-forge
  libsqlite         3.46.0    hde9e2c9_0          conda-forge
  libstdcxx-ng      14.1.0    hc0a3c3a_0          conda-forge
  libuuid           2.38.1    h0b41bf4_0          conda-forge
  libuv             1.48.0    hd590300_0          conda-forge
  libxcrypt         4.4.36    hd590300_1          conda-forge
  libzlib           1.3.1     h4ab18f5_1          conda-forge
  ncurses           6.5       h59595ed_0          conda-forge
  nodejs            22.4.1    h6d9b948_0          conda-forge
  openssl           3.3.1     h4ab18f5_1          conda-forge
  pip               24.0      pyhd8ed1ab_0        conda-forge
  playwright        1.45.1    hbf95b10_1          conda-forge
  python            3.12.4    h194c7f8_0_cpython  conda-forge
  readline          8.2       h8228510_1          conda-forge
  setuptools        70.3.0    pyhd8ed1ab_0        conda-forge
  tk                8.6.13    noxft_h4845f30_101  conda-forge
  tzdata            2024a     h0c530f3_0          conda-forge
  wheel             0.43.0    pyhd8ed1ab_1        conda-forge
  xz                5.2.6     h166bdaf_0          conda-forge
  zlib              1.3.1     h4ab18f5_1          conda-forge
```

### Environment info

```shell
libmamba version : 1.5.8
     micromamba version : 1.5.8
           curl version : libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files : /home/mambauser/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.153=0
                          __glibc=2.36=0
                          __archspec=1=x86_64-v3
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-64
```

### Issue

When playwright is installed using micromamba python still does not recognize it (`import playwright` throws an error). If I run pip install, it works. I prepared devcontainer in which i can replicate the error:

        {
            "name": "name",
            "build":{
                "dockerfile": "Dockerfile",
                "context": "../",
                "args": { "HTTP_PROXY": "${localEnv:HTTP_PROXY}",
                          "HTTPS_PROXY": "${localEnv:HTTPS_PROXY}" 
                        }
            },
            "containerEnv": { "HTTP_PROXY": "${localEnv:HTTP_PROXY}",
                           "HTTPS_PROXY": "${localEnv:HTTPS_PROXY}" 
            },
            "customizations": {
                "vscode": {
                    "extensions": [
                        "ms-python.python"
                    ]
                }
            }
        }
        
With the docker file:

        FROM mambaorg/micromamba
        COPY --chown=$MAMBA_USER:$MAMBA_USER .devcontainer/environment.yaml /tmp/environment.yaml
        RUN micromamba install -y -n base -f /tmp/environment.yaml
        ARG MAMBA_DOCKERFILE_ACTIVATE=1 
        RUN micromamba config append channels conda-forge
        
and environment.yaml:

    name: name
    channels:
      - conda-forge
    dependencies:
      - python
      - playwright
    prefix: /opt/conda/envs/name

**Comment by carterbox** [comment]
https://github.com/conda-forge/playwright-feedstock/blob/main/recipe/meta.yaml

playwright is a nodejs package; it is not a python package.

Search for playwright in our package database: https://conda-forge.org/packages/

Probably you are looking for playwrite-python.

**Comment by luftuq** [comment]
Thank you,
I did not realize that I should look under different name. In retrospect, it's obvious.
