### ISSUE TITLE
New conda-forge bi-weekly developer hangout day and time

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#223]
_cross-posted at the [conda forge google group] (https://groups.google.com/forum/#!topic/conda-forge/rO4crNU6z9E)_

Hi All,

We are now spanning the Pacific time zone (PST) in our bi-weekly developer
meetings! We should probably be a little nicer to our PST friends and move this 
meeting to a little later in the day so those PST folks don't have to get up
early enough to make a 7:00 AM local time meeting.

Here is the link to a doodle poll that you should fill out if you are
interested in participating in these bi-weekly meetings.

http://doodle.com/poll/r3rufrvtgu7nfvyz

This doodle poll will close in one week (2016-09-01) at 12:00 UTC and we will
make a decision at that time regarding the date and time of our next dev 
meeting (either 2016-09-08 or 2016-09-09).

Thanks all!

Best,

Eric

**Comment by jakirkham** [comment]
cc @conda-forge/core (in case you haven't gotten the memo 😉)

**Comment by ericdill** [comment]
New doodle poll for the 2016-09-16 dev call

http://doodle.com/poll/qeubq3sn6rk66hz5

cc @conda-forge/core

**Comment by jakirkham** [comment]
As we have already picked the time to be the same again, can we just make this a simple 👍 or 👎 for having a meeting next Friday at the usual time, @ericdill?

**Comment by msarahan** [comment]
👍

**Comment by ericdill** [comment]
@jakirkham that's fine by me.  I was strictly following marching orders from @jjhelmus

**Comment by jjhelmus** [comment]
I'm happy with a straight up/down vote.  Sorry for the confusion.

**Comment by jakirkham** [comment]
Ah ok. Sorry if I was being contradictory then. Only trying to keep things running smoothly.

**Comment by jakirkham** [comment]
So I'm completely fine if you guys want to have a meeting then, but will be unable to attend personally. The following week shouldn't be an issue.
