### ISSUE TITLE
completely remove `build` in favor of `python-build`

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#2269]
Per the core call we will do the following:

- [x] make sure the linter hints on use of `build` (already done, but added detail https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6313)
- [x] mark all existing `build` packages as broken (https://github.com/conda-forge/admin-requests/pull/1049)
- [x] make an announcement that we are doing the above (https://github.com/conda-forge/conda-forge.github.io/pull/2270)
- [x] turn off the replacement migrator in the bot (https://github.com/regro/cf-scripts/pull/2943)

cc @conda-forge/core

**Comment by jakirkham** [comment]
Thank you Matt! 🙏

**Comment by jakirkham** [comment]
Should we close out these too?

* https://github.com/conda-forge/python-build-feedstock/pull/15
* https://github.com/conda-forge/python-build-feedstock/pull/28

**Comment by beckermr** [comment]
Yes.
