### ISSUE TITLE
Improper selector

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#228]
Encountered the following [error]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/157259421#L682 ) in the team update script. Seems to be this [line]( https://github.com/conda-forge/instaseis-feedstock/blob/30f1e5080891c67b670264a3b78f5a42ec500a4f/recipe/meta.yaml#L42 ) that is causing the problem.

```
Checking instaseis
Error: Invalid selector in meta.yaml line 42:
    - if [[ $TRAVIS == true ]]; then ulimit -n 2048 ; fi  # [osx]
CalledProcessError: Command '['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']' returned non-zero exit status 1
```

cc @pelson @msarahan @conda-forge/instaseis

**Comment by krischer** [comment]
Hmm...that appears to be a valid selector according to

http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors

I'm not sure what's wrong here.

**Comment by patricksnape** [comment]
Is it getting confused somehow by the semicolons? Maybe try wrapping the command in a string?

**Comment by krischer** [comment]
Done in https://github.com/conda-forge/instaseis-feedstock/pull/2.

Can you try again?

**Comment by jakirkham** [comment]
Same [problem]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/157548040#L679-L680 ).

Could we try moving it to [`run_test.sh`]( http://conda.pydata.org/docs/building/meta-yaml.html#test-section )? A `uname` test could be used to ensure it only happens where appropriate.

**Comment by jakirkham** [comment]
Any chance we can try the above suggestion, @krischer? Would love to get this up and running again.

**Comment by krischer** [comment]
Sorry for the delay. New try in https://github.com/conda-forge/instaseis-feedstock/pull/3

**Comment by krischer** [comment]
Weird that the meta-data parser of conda-build fails but conda-build otherwise works fine...

**Comment by jakirkham** [comment]
No worries. Just wanted to make sure this didn't get lost.

Yeah, I'm guessing somehow logic later in `conda-build` cleans this up somehow, but I'm not sure how or why.

**Comment by krischer** [comment]
I just merged the new attempt to fix it. Can you try to run the script again?

**Comment by jakirkham** [comment]
It has been restarted. Currently queued. Will let you know when we have a result.

**Comment by jakirkham** [comment]
Appears everything is working again.

Thanks everyone. Particularly thanks @krischer for working with us get to this corrected.

Closing...
