### ISSUE TITLE
How do we add a hint about a package rename?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge.github.io#2284]
### Your question:

It seems that the coinor maintainers prefer the spelling

```
coin-or-cbc
```
instead of 
```
coincbc
```

Is there a way to add a hint for this, in the same way that we have `matplotlib` -> `matplotlib-base`?

Trying to address some symptoms:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6369

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/coin-or-cbc-feedstock/pull/26

**Comment by jaimergp** [comment]
Probably here https://github.com/conda-forge/conda-smithy/blob/5a1c79054d0508ea30cecf474830972527339a05/conda_smithy/lint_recipe.py#L496-L516

**Comment by isuruf** [comment]
It's at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/linter_hints/hints.toml

**Comment by hmaarrfk** [comment]
Thanks!
