### ISSUE TITLE
Package PETSc

### ISSUE THREAD

**Issue by minrk** [conda-forge/conda-forge.github.io#231]
PETSc maintains [conda recipes](https://bitbucket.org/petsc/conda-recipes/src/bd5a629eaf8b?at=master) for petsc, slepc, mpi, mpi4py. It looks like this is largely the work of @dalcinl.

@dalcinl would you be interested in moving maintenance of these packages over to conda-forge? I'm happy to help, as my goal is to ultimately get [FEniCS](https://fenicsproject.org) packages on conda-forge.

Since that repo appears to include working mpich and openmpi packages, perhaps something could be gleaned to finish up https://github.com/conda-forge/staged-recipes/pull/557 (@msarahan).

**Comment by dalcinl** [comment]
@minrk Please close.

**Comment by dalcinl** [comment]
@ocefpaf What kind of permissions do I need to perform tidying-up work like closing this issue?

**Comment by ocefpaf** [comment]
Issue in this repo only the person that created it or a conda-forge  core member can close.

On the feedstocks that you are a maintainer you can do that.
