### ISSUE TITLE
make conda-forge lower priority than the default channel

### ISSUE THREAD

**Issue by talkaminker** [conda-forge/conda-forge.github.io#232]
I am not sure where to post this but, in the main site https://conda-forge.github.io/
you suggest entering

`conda config --add channels conda-forge`

to the shell to add conda-forge as a channel. the problem is than it will take higher priority over the default conda.
which means for example that running:

`conda update numpy`

will install the blas numpy of conda-forge and not the faster MKL one in the default channel
(also running conda update on any package will reinstall it with the conda-forge one even if there is no new version)

I think the correct line should be:

`conda config --append channels conda-forge`

NOTE:
the suggested solution is only viable with the newer version of conda (4.1.0 and up). older versions have no solution.
so probably you should state in the website:
`conda update conda`
`conda config --append channels conda-forge`

**Comment by jakirkham** [comment]
I don't know if I would agree that MKL is outright faster than OpenBLAS. In any event, it feels like we are using an extreme solution for a much smaller problem. I won't try to reproduce all my thoughts on why this seems problematic, but will direct you to that [comment]( https://github.com/conda-forge/conda-forge.github.io/pull/230#issuecomment-247225139 ).

If you wish to override where particular packages come from, that seems like a channel priority discussion to be had with the `conda` folks. Hopefully something reasonable can come out of this. Maybe there is a bug involved in this case, but there is not enough to tell.

Also we could have a different discussion about providing an "empty" `blas` configuration here that results in these BLAS dependent packages coming from `defaults`. This may come with other tradeoffs like not having access to some BLAS packages provided here that are not in `defaults`, but that could be a choice provided to the user. This would require a fair bit of rebuilding on our part (read: time and planning), but is potentially doable.

A totally different discussion that has been raised before is actually having the option to use MKL at conda-forge. Though concerns with the licensing and what expectations they place on the community need to be better understood. If they are tolerable, this may be an option to purse. However, I'm not optimistic based on past [discussions]( https://mail.scipy.org/pipermail/numpy-discussion/2014-March/069681.html ).

**Comment by jakirkham** [comment]
Going to go ahead and close this for the exact same reasons PR ( https://github.com/conda-forge/conda-forge.github.io/pull/230 ) was closed. If you wish to discuss how to support MKL in conda-forge, please open a fresh issue and we can discuss it there. Thanks.

**Comment by jakirkham** [comment]
> will install the blas numpy of conda-forge and not the faster MKL one in the default channel

FWIW you can also uninstall the `blas` package, which will switch back to `numpy` from `defaults`.
