### ISSUE TITLE
I was invited to join conda-forge but I don't know why?

### ISSUE THREAD

**Issue by dougthor42** [conda-forge/conda-forge.github.io#2327]
### Your question:

I got an email out of the blue asking me to join `conda-forge`. To my knowledge, I have never contributed to `conda-forge` or related project (sorry!) so I'm curious as to why I was invited.

![Image](https://github.com/user-attachments/assets/a475bfce-7e3a-4443-99d1-040f58fb1cb3)

Is it possible to find out _who_ invited me and why?

Note that this is the 2nd time I was invited, so I'm assuming it's intentional...

**Comment by isuruf** [comment]
@dougthor42 it's because you agreed in https://github.com/conda-forge/staged-recipes/pull/10895#issuecomment-588570808. We can remove you if you prefer. (The invitation is sent by our automation scripts)

**Comment by dougthor42** [comment]
Thanks! No wonder I didn't remember - it was so long ago!

Joined 👍
