### ISSUE TITLE
All AppVeyor Python 2.7 builds failing

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#252]
Looks like all AppVeyor Python 2.7 builds are failing:

https://ci.appveyor.com/project/conda-forge/pep257-feedstock/build/job/c632u6l67evx0be2

😢

**Comment by msarahan** [comment]
That's an issue with path being too long in the activate script. It's fixed in the current conda 4.2 release, and might be in conda 4.1.12.  I don't remember.

**Comment by astrofrog** [comment]
@msarahan - any idea why it started happening overnight though?

**Comment by jakirkham** [comment]
Is this the PR ( https://github.com/conda/conda/pull/3349 )?

**Comment by jakirkham** [comment]
So I'm proposing packaging 4.1.12 that has the aforementioned fix in it at our feedstock. ( https://github.com/conda-forge/conda-feedstock/pull/9 ) Please let me know if that will fix the issue @msarahan .

**Comment by msarahan** [comment]
Seems like it should work.

**Comment by jakirkham** [comment]
Will also need to make a patch release of `conda-smithy` with PR ( https://github.com/conda-forge/conda-smithy/pull/329 ) included too as we need to update `conda` right before we activate the freshly installed Miniconda too.

**Comment by jakirkham** [comment]
Alright, this issue should be resolved. Have made a `conda-smithy` release `1.3.3`, which will be needed to re-render feedstocks to fix this issue. Also have redeployed the re-rendering bot to have this version of `conda-smithy`. If you have more issues, please let us know. Going to go ahead and close this out.

cc @conda-forge/core
