### ISSUE TITLE
Issue with automated pinned version PR

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#253]
The following automated PR to update the pinned versions failed in several ways:

https://github.com/conda-forge/glueviz-feedstock/pull/12/files
- It replaced `qtpy` by `qt 4.8.*`
- It replaced `pyqt != 4.11.4` by `4.11.* 4.11.*`
- It replaced `pyqt` by `pyqt 4.11.*` (when in fact the package is compatible with either PyQt4 or 5)
- It replaced `qtconsole` by `qt 4.8.*`.

I will just close the PR, but just wanted to point this out, since some of these changes are simply wrong.

**Comment by jakirkham** [comment]
I've see the first one and that is definitely a bug. The fourth is just a variant on the first one. The second is a bit odd. Did these all occur in one PR or do you have more references?

The third one is technically correct behavior. The decision to pin to PyQt4 is a consequence of the fact that Qt5/PyQt5 don't exist at conda-forge. Have seen some build issues without it. Though @ocefpaf can probably tell you more as he implemented this pinning in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/248 ).

**Comment by astrofrog** [comment]
> The third one is technically correct behavior. The decision to pin to PyQt4 is a consequence of the fact that Qt5/PyQt5 don't exist at conda-forge. Have seen some build issues without it.

I'm not comfortable with this - I think of conda-forge as a place where the canonical version of recipes exist (at least that is how it was advertised to me). The glueviz package is compatible with PyQt4 and PyQt5, so ideally I shouldn't make it so that it's only installable with PyQt 4.11.x. I agree there are issues with incompatibilities between the defaults and conda-forge PyQt/Qt versions (due I guess to library versions they were compiled against) but as far as I can see the correct fix is for those packages to properly declare which versions of libraries they were compiled with - not fix recipes for other packages to force them to use the conda-forge PyQt version. If there are issues, doesn't it mean that either the Qt/PyQt packages in defaults or in conda-forge are not declared properly?

I guess I can understand if this is a temporary pragmatic fix - but I would want to make sure it really is just that - a temporary fix. The problem is that once you've added that pinning, it can only be removed manually, not with a bot, since you don't know which packages are truly compatible with PyQt4 and 5 vs ones that really require 4.

**Comment by jakirkham** [comment]
I hear you loud and clear @astrofrog . Maybe @ocefpaf can better explain the problem or why pinning to 4 (even in Python packages) is the fix. Unfortunately I don't know enough about this particular problem to elucidate it.

**Comment by jakirkham** [comment]
Also relevant issue ( https://github.com/ContinuumIO/anaconda-issues/issues/1164 ).

**Comment by jakirkham** [comment]
The old pinning script is deprecated and mothballed in favor of newer `conda-build` 3 based strategies, which shouldn't fall into such naive problems. So closing this out. If other issues occur, we can discuss further.
