### ISSUE TITLE
Skipping Pinning PRs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#270]
Some things don't need to be pinned even if they do use something from the list that should typically be pinned. This could be due to the fact that they use headers only, are only requiring one of the pinned packages at runtime and not buildtime, or this could be due the fact the dependency is statically linked and exposes no symbols from the dependency. Generating these PRs that simply get closed off comes at a cost. Given all of these cases and the cost of generating needless pinning PRs, it would be very handy if we could disable pinning PRs to feedstocks that don't need them somehow.

cc @pelson

**Comment by pelson** [comment]
I'd be tempted to put an annotating comment that prevents pinning PRs... perhaps:

```
requirements:
  run:
     - python
     - boost   # Specifically unpinned as we do not link against it
```

I guess the alternative syntax is that we explicitly do ```- boost *```.

Either one should be easy to code up in the pinning script.
Thought?

**Comment by jakirkham** [comment]
I like `- boost *` if it works. Nice and succinct.

**Comment by jakirkham** [comment]
Addressed by PR ( https://github.com/conda-forge/conda-forge.github.io/pull/442 ).
