### ISSUE TITLE
pymatgen, pydispatcher and monty

### ISSUE THREAD

**Issue by shyuep** [conda-forge/conda-forge.github.io#274]
Hi, I submitted a PR for the three packages above. However, pymatgen has C extensions taht do not compile on Win Py < 3.5. So the tests are erroring. Can this still be part of conda-forge or is compatibility across all platforms required?

**Comment by jakirkham** [comment]
It is not required for every package to work on all Pythons and platforms.

If they don't work on Windows at all, please just add `skip: true  # [win]` to the `build` section. If they work on Windows with Python 3.5, then add `skip: true  # [win and py<35]`. Make sure there are 2 spaces before the selector `#`. It is always possible to adjust these in the future should you be able to support these later.

Also it is possible that Windows experts in the org can advise you on how to get these packages to build on older Pythons if you are interested. If you would prefer to see what they say, then please wait for them to respond.

Feel free to raise more questions like this in those PRs or on gitter. The former allowing the conversation to remain contiguous and the latter having a broader audience to help answer these questions. Thanks.
