### ISSUE TITLE
win-64 python-3.5.2-2 package no longer accessible

### ISSUE THREAD

**Issue by aburgm** [conda-forge/conda-forge.github.io#278]
The package `python-3.5.2-2` for win64 used to be available on Friday 11/25, but does not seem to be available through conda anymore now:

```
$ conda create -n aoeue python=3.5.2=2
Fetching package metadata ...............
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - python 3.5.2 2

You can search for packages on anaconda.org with

    anaconda search -t conda python

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

The tarball is still on https://anaconda.org/conda-forge/python/files, though. `python-3.5.2-1` is accessible through conda normally as well.

**Comment by aburgm** [comment]
Seems like the package has been labelled as pre-release and is no longer available in the main conda forge distribution. Is this intended? This seems to work in order to install it: `conda create -n aoeue -c conda-forge/label/prerelease python=3.5.2=2`

**Comment by jakirkham** [comment]
Yeah, our upload script seems to be relabeling things in ways it shouldn't, which has made things a bit of a mess. Have fix this I believe and am tracking the labeling issue. Please let us know if you find more issues with labelings.

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/41
