### ISSUE TITLE
Support for "recipe batches"

### ISSUE THREAD

**Issue by gidiko** [conda-forge/conda-forge.github.io#289]
We want to build a single package A but this depends also on other packages let's say B, C, D, which are not in conda-forge or other addressable public repos already.  Also, there are some some extra dependencies between B, C, D, for example B depends on D.

We have recipes for all packages A, B, C, D already and we can build them locally e.g. first C, then D, then B (because it depends on D) and finally A (because it depends on B, C, D).

Now we want to upload the recipes to conda-forge. 

Ideally we would like to upload the full batch of recipes A, B, C, D (e.g. putting them as separate directories under a forked https://github.com/conda-forge/staged-recipes/tree/master/recipes/ (i.e. have recipes/A, recipes/B, recipes/C, recipes/D and not just recipes/example) and have them all built automatically.

The other way of course, would be to follow the order C, D, B, A and wait for each of the recipes to be promoted to a feedstock and merged to the official repo and then go to the next package (so that its dependencies could be resolved by just pointing to the conda-forge which will then have the dependency freshly built) and so on and so forth, but this is much more tedious :)

So, the question is: Is there support in conda-forge for conveniently dealing with "recipe batches"? Upload multiple inter-depending packages as described?

**Comment by jakirkham** [comment]
Yes, `conda-build-all` which is used in `staged-recipes` supports this. Please put together such a PR with all of these recipes and see how it goes.

**Comment by ChrisBarker-NOAA** [comment]
This actually seems like a good idea for small set of closely related packages all maintained by the same organization. Are there any conda-forge repos already using this approach that could be used as examples? It seems the CI build configurations would need to be adopted to invoke conda-build-all, rather than conda build directly -- not sure how easy that is to change.
