### ISSUE TITLE
Consider moving the pinning information to a separate file

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#296]
It might be useful to move the pinned dependencies inside `pin_the_slow_way.py` into a separate json file. This would make it easier to reuse the information in other scripts (such as the linter) and help other communities staying up-to-date with conda-forge's pinnings.

**Comment by jakirkham** [comment]
Completely agree. :+1:

I think this came up somewhere else before, but don't recall where.

Should add this could be reused in docs too.

**Comment by jakirkham** [comment]
One thing we could try is to make this a package. Maybe with a Python script to load the JSON? Should make it easier to update the pinning bot too. Not sure how we would version it, but we could discuss this and other points.
