### ISSUE TITLE
Setup conda-smithy docs

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#3]
A space is needed for conda-smithy docs.
I think it is probably a good idea to use sphinx for generating the conda-smithy docs. The source can live in https://github.com/conda-forge/conda-smithy and the built can live in a `conda-smithy` directory in this repo.

**Comment by pelson** [comment]
Or just as a gh-pages branch in conda-smithy. The URL would then be https://conda-forge.github.io/conda-smithy

**Comment by pelson** [comment]
Also, it would be nice to have a decent 404 on the conda-forge.github.io domain.

**Comment by jakirkham** [comment]
I think we have integrated some rough docs into the webpage. Is this what you had in mind? If so, good to close? If not, what else do we need?
