### ISSUE TITLE
Changing AppVeyor priority on staged-recipes

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#316]
Initially it made sense to have a high priority for AppVeyor builds on staged-recipes as we didn't have very basic parts of the stack. However, the SciPy stack is already included in conda-forge. We provide our own Python interpreter. Also pretty much everything in `root` (e.g. `conda`, `conda-build`, etc.) we package ourselves. The number of feedstocks has far exceeded 1000. Not to mention none of our other CIs (excepting AppVeyor) give preference to staged-recipes. Given all this having staged-recipes get higher priority than any feedstock on AppVeyor regardless of the queuing order, seems at best incredibly inappropriate and at worst an obstacle to maintaining the stack. Have opened this issue to start a discussion about changing staged-recipes to have the same priority as everything else. Maybe others feel the same way. 😉

**Comment by jakirkham** [comment]
cc @conda-forge/core @dopplershift

**Comment by jjhelmus** [comment]
:+1: for making staged-recipes and feedstock have the same priority on AppVeyor and others.  

I'd even be in favor of prioritizing the feedstocks over staged-recipes.  To me fixing bugs and upgrading existing packages is more important than adding new packages but I can understand this might not be everyone's opinion.

**Comment by dopplershift** [comment]
In an ideal world, IMO one of the build jobs would favor feedstocks, while the other would favor staged-recipes. In lieu of that, happy to see everybody equal. That's better than particularly active staged-recipes PRs completely stalling getting anything else built.

**Comment by jakirkham** [comment]
One might argue that we are a bit biased towards feedstocks than staged-recipes given our needs are basically satisfied with the existing feedstocks. 😄 That said, definitely hear where all of you are coming from.

**Comment by jakirkham** [comment]
Having heard nothing but support on this issue, went ahead and dropped the priority from staged-recipes. It is now on par with an ordinary feedstock. Closing this out as this is resolved.
