### ISSUE TITLE
Change CircleCI to use conda-build-all to avoid hitting the wall time

### ISSUE THREAD

**Issue by marscher** [conda-forge/conda-forge.github.io#317]
Currently CircleCI is configured to build all configurations for every change, which hits the wall time for some huge packages (e.g scipy).
In order to avoid that, we should only build the needed configurations (I guess conda-build-all does exactly that?).

**Comment by jakirkham** [comment]
So I may have misunderstood your [comment]( https://gitter.im/conda-forge/conda-forge.github.io?at=588219ed519afee26b8e81c1 ) on gitter. My understanding was you were concerned that we were rebuilding things a second time (e.g. when restarting a failed CI) even if their package was already uploaded. `conda-build-all` checks in advance to see what packages are already uploaded and only builds the ones that have not been. This way one could keep restarting CircleCI until everything is uploaded building some portion of the packages in each new build. Though if I'm misunderstanding this, please feel free to clarify.

**Comment by marscher** [comment]
On 20.01.2017 17:53, jakirkham wrote:
> So I may have misunderstood your comment
> <https://gitter.im/conda-forge/conda-forge.github.io?at=588219ed519afee26b8e81c1>
> on gitter. My understanding was you were concerned that we were
> rebuilding things a second time (e.g. when restarting a failed CI) even
> if their package was already uploaded.
you got me. CircleCI restarts from the beginning currently, this is why 
we are hitting the wall time.

|conda-build-all| checks in
> advance to see what packages are already uploaded and only builds the
> ones that have not been. This way one could keep restarting CircleCI
> until everything is uploaded building some portion of the packages in
> each new build. Though if I'm misunderstanding this, please feel free to
> clarify.
exactly.

**Comment by jakirkham** [comment]
At this point we don't use conda-build-all or CircleCI any more (though they both served us well). So will close this out. Please let us know if you have other issues with time limits.
