### ISSUE TITLE
Please, remove limix_util-feedstock repository.

### ISSUE THREAD

**Issue by Horta** [conda-forge/conda-forge.github.io#322]
Hello,

I'm the author of limix_util package which became irrelevant. Would you mind removing it?

Link: https://github.com/conda-forge/limix_util-feedstock

Thanks.

**Comment by ocefpaf** [comment]
@Horta we usually keep old software as some people may still rely on it. However, I looked at the package and it seems that it is quite specific and you probably are in touch with its users. I will removed it and, if someone feels the need to re-add it, we can do that easily.

**Comment by Horta** [comment]
Thanks a lot =)

I request those things more for keep things simple, more maintainable over time.

**Comment by jakirkham** [comment]
Have removed the associated team as well.

**Comment by jakirkham** [comment]
Should the existing packages be removed?

**Comment by Horta** [comment]
Yes, please =)
