### ISSUE TITLE
mpi4py 2.0.0 (py27_1 ) is broken

### ISSUE THREAD

**Issue by aphearin** [conda-forge/conda-forge.github.io#327]
I use conda-forge and recently installed mpi4py (2.0.0; py27_1), but the application does not work. I did not have this problem with a previous installation using conda on a different but otherwise identical mac - this only comes up when I use conda-forge. This application is critical to my work and I have no choice but to roll back to conda if this is not resolved or if there is not a workaround. 

The following Hello World program fails with the following error message:

> #helloworld.py
> from mpi4py import MPI
> comm = MPI.COMM_WORLD
> rank = comm.Get_rank()
> print("Hello world from process {0}".format(rank))
> 

> $ mpirun -n 1 python helloworld.py 

> Fatal error in MPI_Init_thread: Other MPI error, error stack:
> MPIR_Init_thread(474)..............: 
> MPID_Init(190).....................: channel initialization failed
> MPIDI_CH3_Init(89).................: 
> MPID_nem_init(320).................: 
> MPID_nem_tcp_init(173).............: 
> MPID_nem_tcp_get_business_card(420): 
> MPID_nem_tcp_init(379).............: gethostbyname failed, softshell.local (errno 1)
> 

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/aphearin/anaconda  (writable)
    default environment : /Users/aphearin/anaconda
       envs directories : /Users/aphearin/anaconda/envs
          package cache : /Users/aphearin/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/aphearin/.condarc
           offline mode : False

**Comment by aphearin** [comment]
I was able to resolve this issue by adding the following line to /etc/hosts:

127.0.0.1   softshell.local

**Comment by jakirkham** [comment]
When it comes to particular issues with a package, the best course of action is to start by raising an issue at that feedstock. If it turns out to be an issue with the code itself or a different issue in conda-forge, it can normally be redirected.

Even if this is a solved configuration issue, I'm going to move it over to that feedstock. So that people more informed about mpi4py can weigh in on the best way to solve this issue.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/mpi4py-feedstock #5](https://github.com/conda-forge/mpi4py-feedstock/issues/5) via [**ZenHub**](https://www.zenhub.com/)
