### ISSUE TITLE
Offline version of cartopy

### ISSUE THREAD

**Issue by willirath** [conda-forge/conda-forge.github.io#328]
(I'd be happy to provide a PR myself.)

## Problem

Cartopy provides a very limited set of feature data (shapefiles et al.) and downloads features to the user cache whenever they are needed.  This is usually a good practice, but interferes with people working without permanent internet access (seagoing oceanographers, people in large data-centers who are trapped behind firewalls, someone working on a plane, etc.).

## Proposed solution

Create a feedstock which downloads all features upon installation.

To download all features, use (on python2.7)
```bash
feature_download.py \
    --output ${CONDA_PREFIX}/lib/python2.7/site-packages/cartopy/data physical \
    gshhs cultural cultural-extra
```
with [feature_download.py](https://github.com/SciTools/cartopy/blob/master/tools/feature_download.py) from the cartopy repo.

##  Caveats

Make sure to make use of conda's hard linking across virtual environments?

**Comment by jakirkham** [comment]
For future reference, discussion of changes to an individual package should be conducted on the issue tracker of that feedstock. In this case, the [cartopy feedstock]( https://github.com/conda-forge/cartopy-feedstock ) would be the right place. Am moving this issue over to that feedstock. Please discuss more over there.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/cartopy-feedstock #27](https://github.com/conda-forge/cartopy-feedstock/issues/27) via [**ZenHub**](https://www.zenhub.com/)
