### ISSUE TITLE
Having Automated planned transitions when compiled packages change

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/conda-forge.github.io#333]
I wrote a short [notebook](https://gist.github.com/kain88-de/6162f43ff6648c6ddf7e59ada5af4863) that I can right now use to determine the order in which I have to update packages with dependencies.  This is useful for to see which packages have to be rebuild with numpy 1.12 ( #313 ) first to avoid dependency conflicts. I can also use it to check the order of updates for python 3.6 packages, see [datreant.data](https://github.com/conda-forge/datreant.data-feedstock/pull/3) package what happens if not all dependencies have been updated.

Currently the logic is pretty simple, likely contains bugs and takes like 5 minutes for the initial parsing of the packages so a more manageable data structure. There will also be a problem soon to figure out against which version of a dependency the current packages have already been build, when the `np111py27` string are turned to a 4 digit hash. Currently the notebook just scans for the `np111` and `np112` substrings in the full package name. 

In the end it might also be nice to have a site similar to the  [Debian Transition Tracker](https://release.debian.org/transitions/) to let people keep track of updated packages and where they could help.  Or at least have the rerendering script only work on packages with no detectable dependency conflict.

Would this be something useful for others as well?

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/44

**Comment by CJ-Wright** [comment]
Does a combination of the current migrations system and CFEP-9 meet this? (Can we close?)
