### ISSUE TITLE
Automatically test loading of module via pkg_resources

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-forge.github.io#337]
In https://github.com/conda-forge/scikit-image-feedstock/pull/5#issue-208398146 I ran into an issue where loading a module via setuptools highlights when there are dependencies that are declared in a package's setup.py that are not defined in the conda recipe. I was wondering whether it would be worth/easy adding a standard test for all conda-forge packages to make sure:

```python
from pkg_resources import WorkingSet, Requirement
w = WorkingSet()
r = Requirement('package_name')
w.resolve([r])
```

works? (or there may be more concise ways of testing the same thing)

**Comment by scopatz** [comment]
I am personally disinclined to rely on pkg_resources for anything.

**Comment by dopplershift** [comment]
Is that what the package will end up doing on import anyway?

**Comment by jakirkham** [comment]
This seems to be superseded by recent work on using `pip check`. Perhaps this can be brought up in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/962 ) if this alternative needs further consideration.
