### ISSUE TITLE
AppVeyor builds are not from conda-forge

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#35]
I've know about the issue for a while, but I'm finally getting around to fixing the fact that *all* feedstocks live under my own AppVeyor user. e.g. pelson/matplotlib-feedstock

It turns out that *all* AppVeyor repos must live under a *real* user, so there are no organisational level concepts there. As a result, I've created a "conda-forge" user on AppVeyor, and will slowly be transferring the repositories into that user.

The steps needed:

 - [x] Register a conda-forge user on AppVeyor
 - [x] Create an "all-members" team on the GH conda-forge org. Give that team global "restarting" abilities for *all* registered AppVeyor builds (there is no finer control than that short of some pretty extreme teaming - possible, but not desirable at this point)
 - [x] Register each feedstock under the conda-forge user
 - [x] Submit a PR for each feedstock which updates the conda-forge.yaml to contain an appropriate AppVeyor secret (since the secret will change between users)
 - [x] Remove all of the old ```pelson/*-feedstock``` registrations (to avoid things being built many times)
 - [ ] Update all of the shields so they point to the right place

**Comment by pelson** [comment]
> Register each feedstock under the conda-forge user

Can be achieved with:

```
from conda_smithy import feedstocks
from conda_smithy.ci_register import add_project_to_appveyor


for feedstock in feedstocks.cloned_feedstocks('feedstocks'):
    add_project_to_appveyor('conda-forge', feedstock.name)

```

I'll run this once I have the PR machinery in place to update the BINSTAR_TOKEN for each feedstock.

**Comment by ocefpaf** [comment]
This is awesome @pelson!  Thanks!!

**Comment by jakirkham** [comment]
Have we fixed all the old shields by re-rendering at this point?

**Comment by pelson** [comment]
> Have we fixed all the old shields by re-rendering at this point?

Either way, it will gradually happen. There isn't really anything to be done in this issue now.
