### ISSUE TITLE
Appveyor failure on many repositories. 'curl' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/conda-forge.github.io#357]
It seems that a lot of windows builds have failed with the following error:

```bash
Running Install scripts
curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py > ff_ci_pr_build.py
'curl' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

**Comment by SylvainCorlay** [comment]
So appveyor broke it:
http://help.appveyor.com/discussions/problems/6312-curl-command-not-found

**Comment by jakirkham** [comment]
xref: https://github.com/appveyor/ci/issues/1426

**Comment by jakirkham** [comment]
Proposed fixes in PRs ( https://github.com/conda-forge/staged-recipes/pull/2648 ) and ( https://github.com/conda-forge/conda-smithy/pull/489 ).
