### ISSUE TITLE
Question on using branches

### ISSUE THREAD

**Issue by tritemio** [conda-forge/conda-forge.github.io#365]
My understanding is that conda-forge builds all the commits pushed to any branch, and makes the package available on the conda-forge channel (regardless of the branch). On the contrary PR build packages but they are not made available.

I'm wondering what happens if two branches build the same version of a package? Do the builds can overwrite each other on the conda-forge channel? Does the last build win?

**Comment by jakirkham** [comment]
Nothing is overwritten. Regardless of what branches are used.

Though if both branches are building at the same time, they would be racing to see which one will "win" the package.

**Comment by jakirkham** [comment]
Does that answer your questions @tritemio?

**Comment by tritemio** [comment]
Yes thanks @jakirkham! In other words, the first built version of a package is the one used, and this cannot be replaced. To update the build I need to bump the build number.

Closing it!

**Comment by jakirkham** [comment]
Yep, exactly.
