### ISSUE TITLE
Question: QT pinning, why and future plans

### ISSUE THREAD

**Issue by tritemio** [conda-forge/conda-forge.github.io#366]
In short: why the QT pinning was put in place and what's the plan for removal?

Longer version:
I maintain a package ([fretbursts-feedstock](https://github.com/conda-forge/fretbursts-feedstock)) that depends on pyqt. I recently received a maintenance PR (which I merged) to pin QT to version 4.11. Currently, matplotlib from anaconda come with QT 5.6 and my package causes a downgrade of the QT library. I was wondering what problem the pinning is addressing and when it is expected to be resolved.

**Comment by tritemio** [comment]
Even a link to issues/PR discussing the QT pinning would be usefull.

**Comment by ocefpaf** [comment]
@tritemio the pining was updated so we can have combination of `qt`/`pyqt` that are OK across all platforms in `conda-forge` (`4.11.*`) and the new pining that will work for `Linux` and `Windows` (`5.6.*`).

Because we don't have `qt` builds for `OS X` we cannot guarantee that `qt 5.*`, which links to `libxml2` and `icu`, will work since `defaults` uses a different `icu`/`libxml2` combination.

Hopefully that will answer your questions.

**Comment by tritemio** [comment]
@ocefpaf, thanks for the info!

In [my recipe](https://github.com/conda-forge/fretbursts-feedstock/blob/ca38ad4f1f2e5f2a83a14c0b5369f5d8e0d57f99/recipe/meta.yaml) rendered with conda-smithy 2.2.1 I have qt pinned to 4.11 for all platforms though. Should I remove the pinnning for Linux and Windows?

I tried rerendering with conda-smithy 2.2.2 but I got in import error:

```
$ conda smithy
Traceback (most recent call last):
  File "/Users/anto/miniconda3/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 10, in <module>
    from conda_build.metadata import MetaData
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 9, in <module>
    from .conda_interface import iteritems, PY3, text_type
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_build/conda_interface.py", line 17, in <module>
    from conda.install import (delete_trash, is_linked, linked, linked_data, move_to_trash,  # NOQA
ImportError: cannot import name 'move_to_trash'
```

Should I file an issue?

**Comment by ocefpaf** [comment]
The command to rerender should be `conda smithy rerender`. I am guessing that the error you got there should disappear.  (If not please do report the bug.)

>  Should I remove the pinnning for Linux and Windows?

No, you should pin to `5.6.*` to ensure compatibility with the rest of `conda-forge` packages.
See the painful discussion in https://github.com/conda-forge/mss-feedstock/pull/12

**Comment by tritemio** [comment]
@ocefpaf, I'll follow your advise, thanks.

**Comment by jakirkham** [comment]
Closing as outdated.
