### ISSUE TITLE
Packages aren't updated to python 3.6

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/conda-forge.github.io#368]
I've just noticed that the [griddataformats](https://github.com/conda-forge/griddataformats-feedstock) package hasn't been published on python 3.6 due to skipping the CI build on linux and windows (the osx version is published).  I should also note that there was a [automated PR](https://github.com/conda-forge/griddataformats-feedstock/pull/3) to update the recipe to python 3.6

I'm currently rerunning the circleCi builds to get a python3.6 package. I can't rerun the AppVoyer builds myself though.

I'm not sure if this only affects gridataformats or other packages as well.

**Comment by dopplershift** [comment]
I kicked off a new build, I think that should do it.

**Comment by jakirkham** [comment]
Is it alright if we keep issues like this on the feedstock in question in the future? Just asking this to streamline our communication workflow a bit. 😉 Feel free to ignore for the present issue.

**Comment by kain88-de** [comment]
I think this might be a broader issue. This likely affects other packages as well that were automatically updated.
