### ISSUE TITLE
Feedstocks submodules needs to handle removed repos

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#37]
https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/114947925

https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_feedstocks_submodules.py

**Comment by jakirkham** [comment]
So, as we have now seen removal is handled correctly, can this be closed or are there still some outstanding changes needed elsewhere?

**Comment by pelson** [comment]
Nope. I think we are good to close. Thanks @jakirkham.
