### ISSUE TITLE
Improve yum_requirements.txt documentation

### ISSUE THREAD

**Issue by Lnaden** [conda-forge/conda-forge.github.io#378]
As per discussion on https://github.com/conda-forge/staged-recipes/issues/299#issuecomment-297400029, it would be helpful to see better documentation on how to use `yum_requirements.txt` to install additional yum packages, and the warnings about how those packages will be carried on to any packages which depend on it.

Currently the only mention of it [is on the conda-smithy](https://github.com/conda-forge/conda-forge.github.io/blame/d6dc49c556760143b3382daf4e037692b877b6be/src/conda_smithy.rst#L47) documentation in passing and its up to the user to determine its usage from example in other conda-forge repos.

**Comment by croth1** [comment]
I added a general message discouraging the use of yum_dependencies.txt and two exception to the general rule. See: http://conda-forge.org/docs/maintainer/knowledge_base.html#yum-requirements-txt
