### ISSUE TITLE
Add a Contributor Covenant

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-forge.github.io#379]
`conda-forge` has oodles of packages now and seems pretty darn grown up. It'd be good, perhaps, to add a [contributor covenant](http://contributor-covenant.org/) of some sort. This is doubly true if at some point `conda-forge `ends up ever replacing the default `anaconda` channel.

**Comment by CJ-Wright** [comment]
We have a code of conduct https://conda-forge.org/docs/orga/governance.html#code-of-conduct
Does that meet this need?
