### ISSUE TITLE
Adding a gitter channel

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#41]
As it looks like use of this is going to pick up [substantially]( https://github.com/conda-forge/conda-forge.github.io/issues/22#issuecomment-197117472 ), I wonder if it would be worthwhile to add a gitter channel to field questions of people trying to get stuff up and running. It may also be useful for discussing some of the bigger issues about how this works and ties in with the existing conda ecosystem as things progress.

**Comment by pelson** [comment]
Good idea. I'm waiting for gitter.im to update the available repos (permissions have been approved). I'll check in on this again in a couple of hours.

**Comment by jakirkham** [comment]
I suppose there could be gitter rooms for each feedstock. Don't know if that would be overkill or not. :)

**Comment by pelson** [comment]
> Don't know if that would be overkill or not. :)

Almost certainly initially. I could see some value potentially in the future though. Additionally, there is a mailing list at https://groups.google.com/forum/#!forum/conda-forge

**Comment by jakirkham** [comment]
Did gitter update eventually?

**Comment by pelson** [comment]
No. I needed to add user auth to gitter it turned out. Done now. Thanks @jakirkham

**Comment by jakirkham** [comment]
Ok, cool. Which repo did you put it under or is it organization wide?

**Comment by pelson** [comment]
Woops. https://gitter.im/conda-forge/conda-forge.github.io

**Comment by jakirkham** [comment]
Perfect, thanks @pelson.
