### ISSUE TITLE
Tag "clean" staged-recipes

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#414]
Would it be possible to tag a "clean" staged-recipes commit so that if you rebase onto master (or onto the tag) you don't also download/build the packages which have already been accepted but not moved into its own feedstock?

**Comment by jakirkham** [comment]
I'm not entirely sure if I understand the suggestion, but staged-recipes is already setup to not build anything other than the recipe(s) one proposes in their PR. Is there an instance where this is not working correctly? If so, could you please share some more info?

**Comment by CJ-Wright** [comment]
This ended up building shogun as well
https://circleci.com/gh/CJ-Wright/staged-recipes/108?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jakirkham** [comment]
Ah so it won't work in your fork. To fix this, you will need to disable CircleCI on your fork. Please let me know if you have trouble doing this. Maybe we should take this opportunity to document the steps once you have resolved the issue.

Sadly CircleCI doesn't have a way to distinguish a build on your fork from one in a PR. So it builds only the one on your fork instead. I do hope they fix this. It's confusing for users and difficult to explain. Sorry for the confusion.

**Comment by jakirkham** [comment]
Going to close this out. Though if you have issues disabling CircleCI on your fork, please feel free to ask questions.
