### ISSUE TITLE
Issue with conda-forge noarch

### ISSUE THREAD

**Issue by glemaitre** [conda-forge/conda-forge.github.io#419]
We are in trouble with our CI since yesterday regarding an install of a package (gdcm) present in conda-forge.

In short we get the following:

```
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forge

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.
If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.

$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

.......

PackageNotFoundError: Packages missing in current channels:

  - gdcm

We have searched for the packages in the following channels:
  
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```
Refer to https://travis-ci.org/glemaitre/pydicom/jobs/259682117#L661 for the full traceback.

What is sure is that `gdcm` is available in `https://conda.anaconda.org/conda-forge/linux-64`.

The strange thing is that gdcm feedstock was not updated, the same for miniconda, conda, and travis image. The same successful configuration from 24 hours ago (https://travis-ci.org/pydicom/pydicom/jobs/259333408#L591) was working properly.

I almost sure that we make a mistake somewhere but I don't see where, so any idea is welcomed.

**Comment by jakirkham** [comment]
Thanks @glemaitre. Have been running into similar issues myself. Raised issue ( https://github.com/Anaconda-Platform/support/issues/126 ) upstream. Feel free to share your experience there.

**Comment by glemaitre** [comment]
@jakirkham Thanks

**Comment by jakirkham** [comment]
Closing as discussion moved upstream and this appears to be resolved.

**Comment by jakirkham** [comment]
Sorry. Was on my phone.
