### ISSUE TITLE
Feedstock update script hanging

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#425]
Appears the feedstock update script is hanging and thus getting terminated by Travis CI. Would be great to debug the cause and come up with a fix.

ref: https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/262537120#L1203

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
I've tried that script locally once. It was problematic because of conda 4.3.23 and conda-smithy issue. Shall we remove `conda 4.3.23` from `conda-forge` channel? I don't think many users will care about the difference

**Comment by jakirkham** [comment]
That or we could pin it here. Am slightly in favor of pinning it here only because eventually `conda` will end up getting updated in the channel again and not everyone may be aware of this issue when that happens.

**Comment by jakirkham** [comment]
Also does this error appear to be `conda-execute` related as well?

**Comment by isuruf** [comment]
When conda-execute install the dependencies which include conda_smithy it'll update Conda. That's where the error occurs

**Comment by jakirkham** [comment]
Ok, so maybe PR ( https://github.com/conda-forge/conda-forge.github.io/pull/432 ) will fix it. Assuming that is the only issue.

**Comment by jakirkham** [comment]
Seems there is [another issue]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/269433281 ) with the feedstock update script. It appears the script either hangs or makes too little noise for Travis CI and is thus terminated. Already tried restarting it to no avail.
