### ISSUE TITLE
appveyor builds failing due to transient errors

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-forge.github.io#430]
Appveyor builds of staged-recipes seem to be failing randomly due to transient errors unrelated to the recipe itself, such as failure to contact a URL.  Triggering a rebuild causes a different subset of configurations to fail, with no change to the recipe.  Making a trivial change to the recipe and rebuilding sometimes succeeds, but it's an unreliable process.  And the recipe I'm building doesn't even work on Windows, it has a "skip: True  # [win]" line.

Would it be hard to add automatic retries, and/or skipping the build altogether if the recipe is not written for Windows?

**Comment by jakirkham** [comment]
There were retries added to AppVeyor IIRC.

That said, we have largely (with very few exceptions) moved to Azure for Windows builds (including on `staged-recipes`).

In any event I think we can close this out. Though please let us know if any new issues crop up.
