### ISSUE TITLE
better advertised "noarch"

### ISSUE THREAD

**Issue by Carreau** [conda-forge/conda-forge.github.io#443]
It seem like "noarch" is not advertised enough, the [stable docs](https://conda-forge.org/docs/) do not seem to mention it, and have  no button to switch to the [latest docs, that do](http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages).

I also got confused by the phrasing : 

```
and have fixed requirements (i.e. no backports.... # [py27]).
```

That make sens if you are used to the recipe syntax, but if you coming here to create your first recipe, you might not realize that this is used for conditional dependencies depending on the platform, or the Python version. 

It would be nice also, while we are at it to push communication on twitter/facebook... 
There seem to be a [condaforge twitter](https://twitter.com/condaforge), but not use much. It would be nice if it could regularly tweet "Wow &lt;new package&gt; is now noarch !", I can show you how to setup tweet-deck to not have to log out/in with condaforge user, and delegate permission to multiple users.

**Comment by jakirkham** [comment]
Yeah the stable docs are built on Travis CI, which I'm starting to think is a bad idea. @isuruf sent a PR to try to fix a build issue on Travis CI, but the backlog is really hurting us.

Agreed. Feel free to propose alternative phrasing and/or more examples.

Pinging @conda-forge/core about advertising `noarch` on twitter. Does someone have access to the cf account that can post about using `noarch`?

**Comment by jakirkham** [comment]
Stable docs should now be updated.

**Comment by jakirkham** [comment]
As to the docs, wondering if we should just say no selectors. We probably could add that to the linter as well. Thoughts @isuruf?

**Comment by isuruf** [comment]
Yes, having no selectors is better.

**Comment by jakirkham** [comment]
Does it seem reasonable to teach the linter this?

**Comment by isuruf** [comment]
Yes, it'll catch cases like pytest.

**Comment by jakirkham** [comment]
Ok, have added issue ( https://github.com/conda-forge/conda-smithy/issues/578 ) to keep this on the radar for now.

**Comment by Carreau** [comment]
Great ! Thanks all, I guess there is just a need to figure out the twitter account now, and do more publicity for noarch  !

**Comment by ocefpaf** [comment]
Matthias it is @ericdill who is in charge of the Twitter account at the moment. (I lost access after SciPy due to sheer incompetence to remember the password ;-p)

@ericdill do you have a some time to look into tweet-deck?

**Comment by Carreau** [comment]
FYI here is how I would  allow `@condaforge` to tweet from my account :
`![tweetdeck](https://user-images.githubusercontent.com/335567/30656323-962294a2-9de8-11e7-949a-8cd378990c0b.gif)

And what it looks like to tweet from another account:

![tweetdeck-ii](https://user-images.githubusercontent.com/335567/30656384-d3e736a8-9de8-11e7-877d-c37da9ed0ac8.gif)

**Comment by ericdill** [comment]
@Carreau thanks for pointing this out. @ocefpaf I've added you to the condaforge team via tweetdeck. Would anyone else in @conda-forge/core like to be added?

**Comment by ocefpaf** [comment]
@ericdill thanks a bunch. I'll play with it soon.

**Comment by ocefpaf** [comment]
@ericdill thanks a bunch. I'll play with it soon.

**Comment by ericdill** [comment]
@ocefpaf I think you should have sufficient privileges to grant others access to conda-forge via tweetdeck

**Comment by ocefpaf** [comment]
> @ocefpaf I think you should have sufficient privileges to grant others access to conda-forge via tweetdeck

Thanks! Will do.

In the next meeting we can ask who wants that and grant them the access. I am guessing that at least @pelson may want to tweet using the `@condaforge` handle.

**Comment by CJ-Wright** [comment]
I think "noarch" is a bit better documented now, https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=noarch#noarch-builds please reopen if we need more
