### ISSUE TITLE
Skip AppVeyor in some automated commits

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-forge.github.io#45]
@pelson I believe we don't need to run AppVeyor for some automated commits like this one:

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.124

Can we add a `[skip appveyor]` string to that commit message?

**Comment by pelson** [comment]
Yeah. Good idea. I think there are other things we can do too.

https://github.com/conda-forge/staged-recipes/blob/master/.CI/create_feedstocks.py#L126

**Comment by jakirkham** [comment]
Also, added a request for Circle CI to support more specific commit skip syntax so we can try that too. ( https://discuss.circleci.com/t/skip-ci-commit-message/2770 )

**Comment by jakirkham** [comment]
This issue appears to be referenced before, but is the same idea for Travis CI ( https://github.com/travis-ci/travis-ci/issues/5032 ). Though, admittedly, we don't need this here.
