### ISSUE TITLE
numpy 1.9 not available for win / py36

### ISSUE THREAD

**Issue by jschueller** [conda-forge/conda-forge.github.io#450]
see https://ci.appveyor.com/project/conda-forge/opencv-feedstock/build/1.0.219/job/p9lsi5a204ck10s5
cc @conda-forge/core

**Comment by ocefpaf** [comment]
@msarahan do we have an ETA for `numpy 1.9` on Windows? I tested those from the testing channel and they worked like a charm.

**Comment by msarahan** [comment]
I could not build scipy with Numpy 1.9. there was a bizarre link error with rc.exe. we might still upload Numpy 1.9 on Windows, but or lower bound for our build matrix will be 1.11.

Packages will move from the test channel to a new defaults channel when anaconda 5 is released. There's going to be a new channel to keep the old stuff and new stuff separate.  New conda versions will make this transparent, but old conda versions might need some manual monkeying to see the new stuff.

**Comment by jschueller** [comment]
is there 1.10 available on win / py36 ?

**Comment by ocefpaf** [comment]
> I could not build scipy with Numpy 1.9. there was a bizarre link error with rc.exe. we might still upload Numpy 1.9 on Windows, but or lower bound for our build matrix will be 1.11.

Good to know. Thanks!

> is there 1.10 available on win / py36 ?

That would be nice too.
