### ISSUE TITLE
Updating feedstock listing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#46]
How often does the feedstock listing get updated? ( https://conda-forge.github.io/feedstocks.html )
How does it get triggered? Does this happen in some automated fashion?

**Comment by pelson** [comment]
https://github.com/conda-forge/conda-forge.github.io/blob/master/.travis.yml#L15

**Comment by pelson** [comment]
It turns out to be the same process as the teams update script.

**Comment by jakirkham** [comment]
I see. So, I am not seeing FFTW or qimage2ndarray here. There may be others missing. Did something go wrong?

**Comment by pelson** [comment]
I don't think so. https://travis-ci.org/conda-forge/conda-forge.github.io/builds
I've triggered it again. I'm going to call it a night, and will double check in the morning.

**Comment by jakirkham** [comment]
Cool, thanks @pelson.

**Comment by pelson** [comment]
Looks like an update has gone through to the repo. Could you double check the repo for me? Thanks!

**Comment by jakirkham** [comment]
Still missing from the page.

**Comment by jakirkham** [comment]
Would that have triggered the "feedstocking" of Perl too?

**Comment by jakirkham** [comment]
Sorry, it is in the repo. I think it is a caching issue on GitHub's side then.
