### ISSUE TITLE
old recipe versions

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-forge.github.io#472]
In bioconda, one can keep old recipe versions as part of the recipe:
https://bioconda.github.io/guidelines.html#versions
Is there similar functionality in conda-forge?
It's useful when a recipe requires bootstrapping, e.g. building a compiler version requires an older version to already be installed.  It's also useful for reference (when a recipe significantly changes), or if all packages need to be rebuilt.

**Comment by pelson** [comment]
We use git branches for a similar purpose. e.g. https://github.com/conda-forge/python-feedstock/branches

In terms of bootstrapping a recipe we don't have any particularly robust solution. The conda-forge channel is there for hot-bootstrapping, but for a cold-bootstrap you'd probably end up simply including the necessary *binary* in the feedstock/recipe. Don't know if we have any examples of doing that anywhere though.

I don't think there is anything we need to change here so will close the issue, but happy to take a PR to update the docs if there is a specific use-case you want to address. 

Cheers,
