### ISSUE TITLE
Pin zeromq

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#473]
We should be pinning `zeromq`. Though we haven't been so far. Here is the [ABI/API report]( https://abi-laboratory.pro/tracker/timeline/zeromq/ ). My recommendation would be to go with `4.2.*` (edited typo in version). Thoughts?

cc @conda-forge/zeromq

**Comment by jakirkham** [comment]
cc @conda-forge/pyzmq @conda-forge/cppzmq

**Comment by minrk** [comment]
Yes, definitely. pyzmq is already pinning zeromq to 4.2.*.

**Comment by jakirkham** [comment]
Should be fixed by PR ( https://github.com/conda-forge/conda-forge.github.io/pull/484 ).
