### ISSUE TITLE
ImportError: libicui18n.so.54: cannot open shared object file: No such file or directory with Jupyter magic

### ISSUE THREAD

**Issue by philwilkes** [conda-forge/conda-forge.github.io#477]
I updated my conda environment today (installed geopandas) and now I can not run Jupyter magic such as `%pylab`. I get the error:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-780cbd120058> in <module>()
----> 1 get_ipython().magic(u'pylab')
      2 get_ipython().magic(u'matplotlib inline')
      3 import pandas as pd
      4 import os
      5 import glob

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2158         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2159         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2160         return self.run_line_magic(magic_name, magic_arg_s)
   2161 
   2162     #-------------------------------------------------------------------------

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2079                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2080             with self.builtin_trap:
-> 2081                 result = fn(*args,**kwargs)
   2082             return result
   2083 

<decorator-gen-106> in pylab(self, line)

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in pylab(self, line)
    154             import_all = not args.no_import_all
    155 
--> 156         gui, backend, clobbered = self.shell.enable_pylab(args.gui, import_all=import_all)
    157         self._show_matplotlib_backend(args.gui, backend)
    158         print ("Populating the interactive namespace from numpy and matplotlib")

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_pylab(self, gui, import_all, welcome_message)
   2987         from IPython.core.pylabtools import import_pylab
   2988 
-> 2989         gui, backend = self.enable_matplotlib(gui)
   2990 
   2991         # We want to prevent the loading of pylab to pollute the user's

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   2948                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   2949 
-> 2950         pt.activate_matplotlib(backend)
   2951         pt.configure_inline_support(self, backend)
   2952 

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in activate_matplotlib(backend)
    306     matplotlib.rcParams['backend'] = backend
    307 
--> 308     import matplotlib.pyplot
    309     matplotlib.pyplot.switch_backend(backend)
    310 

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    111 ## Global ##
    112 
--> 113 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    114 
    115 _IP_REGISTERED = None

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup(name)
     58     # imports. 0 means only perform absolute imports.
     59     backend_mod = __import__(backend_name, globals(), locals(),
---> 60                              [backend_name], 0)
     61 
     62     # Things we pull in from all backends

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     14 
     15 from .backend_agg import FigureCanvasAgg
---> 16 from .backend_qt5 import (
     17     QtCore, QtGui, QtWidgets, _BackendQT5, FigureCanvasQT, FigureManagerQT,
     18     NavigationToolbar2QT, backend_version)

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     16     _Backend, FigureCanvasBase, FigureManagerBase, NavigationToolbar2,
     17     TimerBase, cursors)
---> 18 import matplotlib.backends.qt_editor.figureoptions as figureoptions
     19 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     20 from matplotlib.figure import Figure

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py in <module>()
     18 import matplotlib
     19 from matplotlib import cm, markers, colors as mcolors
---> 20 import matplotlib.backends.qt_editor.formlayout as formlayout
     21 from matplotlib.backends.qt_compat import QtGui
     22 

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py in <module>()
     54 
     55 from matplotlib import colors as mcolors
---> 56 from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
     57 
     58 

/home/ucfaptv/.conda/envs/everyday/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py in <module>()
    135     if QT_API == QT_API_PYQT5:
    136         try:
--> 137             from PyQt5 import QtCore, QtGui, QtWidgets
    138             _getSaveFileName = QtWidgets.QFileDialog.getSaveFileName
    139         except ImportError:

ImportError: libicui18n.so.54: cannot open shared object file: No such file or directory`

I can import numpy etc. without using magic. If I roll back `icu` (`pandas install 'icu=54.*`) as suggested in previous posts I can run magic. In both instances I can not import pandas which can't find `pyqt` (which is installed).

**Comment by ocefpaf** [comment]
Please see https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by philwilkes** [comment]
I built a new environment with .bashrc like this:

channels:
  - conda-forge
  - rios
  - defaults

and got the same issues

**Comment by ocefpaf** [comment]
> I built a new environment with .bashrc like this:

You mean `.condarc`, right?

If you need 3 channels it is quite difficult to predict the outcome. Can you paste the commands you used to create the environment?

This works for me:

```shell
conda create --name TEST --yes geopandas jupyter
source activate TEST
jupyter notebook
<call %pylab>
```

![spectacle y13390](https://user-images.githubusercontent.com/950575/32234416-d91b75e6-be43-11e7-9aba-d1b8d9d895be.png)

**Comment by philwilkes** [comment]
Yes, sorry I meant `.condarc`. 

OK, solved the `%pylab` problem by changing the matplotlib backend to `TKAgg`

Working in the new TEST env I still can't import pandas, I get this:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-38d4b0363d82> in <module>()
----> 1 import pandas

/home/ucfaptv/.conda/envs/TEST/lib/python2.7/site-packages/pandas/__init__.py in <module>()
     17 if missing_dependencies:
     18     raise ImportError(
---> 19         "Missing required dependencies {0}".format(missing_dependencies))
     20 del hard_dependencies, dependency, missing_dependencies
     21 

ImportError: Missing required dependencies ['pytz']
```

**Comment by ocefpaf** [comment]
Everything need for `pandas` should be there, including `pytz`. See my conda list of that environment:

```
    backports:                          1.0-py27_1            conda-forge
    backports.functools_lru_cache:      1.4-py27_1            conda-forge
    backports.shutil_get_terminal_size: 1.0.0-py_3            conda-forge
    backports_abc:                      0.5-py27_0            conda-forge
    bleach:                             2.0.0-py27_0          conda-forge
    boost:                              1.64.0-py27_4         conda-forge
    boost-cpp:                          1.64.0-1              conda-forge
    bzip2:                              1.0.6-1               conda-forge
    ca-certificates:                    2017.7.27.1-0         conda-forge
    cairo:                              1.14.6-4              conda-forge
    certifi:                            2017.7.27.1-py27_0    conda-forge
    click:                              6.7-py27_0            conda-forge
    click-plugins:                      1.0.3-py27_0          conda-forge
    cligj:                              0.4.0-py27_0          conda-forge
    configparser:                       3.5.0-py27_0          conda-forge
    curl:                               7.54.1-0              conda-forge
    cycler:                             0.10.0-py27_0         conda-forge
    dbus:                               1.10.22-0             conda-forge
    decorator:                          4.1.2-py27_0          conda-forge
    descartes:                          1.1.0-py27_0          conda-forge
    entrypoints:                        0.2.3-py27_1          conda-forge
    enum34:                             1.1.6-py27_1          conda-forge
    expat:                              2.1.0-3               conda-forge
    fiona:                              1.7.9-py27_0          conda-forge
    fontconfig:                         2.12.1-4              conda-forge
    freetype:                           2.7-1                 conda-forge
    freexl:                             1.0.2-2               conda-forge
    functools32:                        3.2.3.2-py27_1        conda-forge
    geopandas:                          0.3.0-py27_0          conda-forge
    geos:                               3.5.1-1               conda-forge
    gettext:                            0.19.7-1              conda-forge
    giflib:                             5.1.4-0               conda-forge
    glib:                               2.51.4-0              conda-forge
    gmp:                                6.1.2-0               conda-forge
    gst-plugins-base:                   1.8.0-0               conda-forge
    gstreamer:                          1.8.0-2               conda-forge
    hdf4:                               4.2.12-0              conda-forge
    hdf5:                               1.8.18-1              conda-forge
    html5lib:                           0.999999999-py27_0    conda-forge
    icu:                                58.1-1                conda-forge
    intel-openmp:                       2018.0.0-h15fc484_7   defaults   
    ipykernel:                          4.6.1-py27_0          conda-forge
    ipython:                            5.5.0-py27_0          conda-forge
    ipython_genutils:                   0.2.0-py27_0          conda-forge
    ipywidgets:                         7.0.3-py27_1          conda-forge
    jinja2:                             2.9.6-py27_0          conda-forge
    jpeg:                               9b-1                  conda-forge
    json-c:                             0.12.1-0              conda-forge
    jsonschema:                         2.6.0-py27_0          conda-forge
    jupyter:                            1.0.0-py27_0          conda-forge
    jupyter_client:                     5.1.0-py27_0          conda-forge
    jupyter_console:                    5.2.0-py27_0          conda-forge
    jupyter_core:                       4.3.0-py27_0          conda-forge
    kealib:                             1.4.7-3               conda-forge
    krb5:                               1.14.2-0              conda-forge
    libdap4:                            3.18.3-2              conda-forge
    libffi:                             3.2.1-3               conda-forge
    libgcc-ng:                          7.2.0-h7cc24e2_2      defaults   
    libgdal:                            2.1.4-3               conda-forge
    libgfortran:                        3.0.0-1               defaults   
    libgfortran-ng:                     7.2.0-h9f7466a_2      defaults   
    libiconv:                           1.14-4                conda-forge
    libkml:                             1.3.0-1               conda-forge
    libnetcdf:                          4.4.1.1-7             conda-forge
    libpng:                             1.6.28-1              conda-forge
    libpq:                              9.6.3-0               conda-forge
    libsodium:                          1.0.10-0              conda-forge
    libspatialindex:                    1.8.5-1               conda-forge
    libspatialite:                      4.3.0a-15             conda-forge
    libssh2:                            1.8.0-1               conda-forge
    libstdcxx-ng:                       7.2.0-h7a57d05_2      defaults   
    libtiff:                            4.0.7-0               conda-forge
    libxcb:                             1.12-1                conda-forge
    libxml2:                            2.9.5-0               conda-forge
    markupsafe:                         1.0-py27_0            conda-forge
    matplotlib:                         2.1.0-py27_0          conda-forge
    mistune:                            0.8-py27_0            conda-forge
    mkl:                                2018.0.0-hb491cac_4   defaults   
    munch:                              2.2.0-py27_0          conda-forge
    nbconvert:                          5.3.1-py_1            conda-forge
    nbformat:                           4.4.0-py27_0          conda-forge
    ncurses:                            5.9-10                conda-forge
    notebook:                           5.2.0-py27_1          conda-forge
    numpy:                              1.13.3-py27hbcc08e0_0 defaults   
    openjpeg:                           2.1.2-3               conda-forge
    openssl:                            1.0.2l-0              conda-forge
    pandas:                             0.21.0-py27_0         conda-forge
    pandoc:                             2.0.0.1-0             conda-forge
    pandocfilters:                      1.4.1-py27_0          conda-forge
    pathlib2:                           2.3.0-py27_0          conda-forge
    pcre:                               8.39-0                conda-forge
    pexpect:                            4.2.1-py27_0          conda-forge
    pickleshare:                        0.7.4-py27_0          conda-forge
    pip:                                9.0.1-py27_0          conda-forge
    pixman:                             0.34.0-0              conda-forge
    poppler:                            0.52.0-2              conda-forge
    poppler-data:                       0.4.7-0               conda-forge
    proj4:                              4.9.3-4               conda-forge
    prompt_toolkit:                     1.0.15-py27_0         conda-forge
    psycopg2:                           2.7.3.1-py27_0        conda-forge
    ptyprocess:                         0.5.2-py27_0          conda-forge
    pygments:                           2.2.0-py27_0          conda-forge
    pyparsing:                          2.2.0-py27_0          conda-forge
    pyproj:                             1.9.5.1-py27_0        conda-forge
    pyqt:                               5.6.0-py27_4          conda-forge
    pysal:                              1.14.2-py27_1         conda-forge
    python:                             2.7.14-0              conda-forge
    python-dateutil:                    2.6.1-py27_0          conda-forge
    pytz:                               2017.3-py_1           conda-forge
    pyzmq:                              16.0.2-py27_2         conda-forge
    qt:                                 5.6.2-3               conda-forge
    qtconsole:                          4.3.1-py27_0          conda-forge
    readline:                           6.2-0                 conda-forge
    rtree:                              0.8.3-py27_0          conda-forge
    scandir:                            1.6-py27_0            conda-forge
    scipy:                              0.19.1-py27h1edc525_3 defaults   
    setuptools:                         36.6.0-py27_1         conda-forge
    shapely:                            1.6.2-py27_0          conda-forge
    simplegeneric:                      0.8.1-py27_0          conda-forge
    singledispatch:                     3.4.0.3-py27_0        conda-forge
    sip:                                4.18-py27_1           conda-forge
    six:                                1.11.0-py27_1         conda-forge
    sqlalchemy:                         1.1.13-py27_0         conda-forge
    sqlite:                             3.13.0-1              conda-forge
    ssl_match_hostname:                 3.5.0.1-py27_1        conda-forge
    subprocess32:                       3.2.7-py27_0          conda-forge
    terminado:                          0.6-py27_0            conda-forge
    testpath:                           0.3.1-py27_0          conda-forge
    tk:                                 8.5.19-2              conda-forge
    tornado:                            4.5.2-py27_0          conda-forge
    traitlets:                          4.3.2-py27_0          conda-forge
    util-linux:                         2.21-0                defaults   
    wcwidth:                            0.1.7-py27_0          conda-forge
    webencodings:                       0.5-py27_0            conda-forge
    wheel:                              0.30.0-py_1           conda-forge
    widgetsnbextension:                 3.0.6-py27_0          conda-forge
    xerces-c:                           3.1.4-3               conda-forge
    xorg-libxau:                        1.0.8-3               conda-forge
    xorg-libxdmcp:                      1.1.2-3               conda-forge
    xz:                                 5.2.3-0               conda-forge
    zeromq:                             4.2.1-1               conda-forge
    zlib:                               1.2.8-3               conda-forge
```

You probably have a bad installation and/or jupyter kernel mess there. Hard to debug from a distance.
I recommend you to start from a clean slate.

**Comment by philwilkes** [comment]
Thanks for your help. Work around was to install `pytz` with `pip`, now can run `pandas` no problems.
