### ISSUE TITLE
pin libedit

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/conda-forge.github.io#478]
`libedit` should be pinned to something. But I'm not totally sure what: it seems that our `libedit` package is `editline` from http://thrysoee.dk/editline/, currently at version 3.1; [the tracker entry for `editline`](https://abi-laboratory.pro/tracker/timeline/editline/) is for https://github.com/troglobit/editline/ ([source](https://github.com/lvc/upstream-tracker/blob/master/profile/editline.json)), currently at version 1.15.2. I don't know what the relationship is between those two projects with the same name.

cc @conda-forge/libedit

**Comment by jakirkham** [comment]
Do you mind following up with the LVC team? Here is their package [issue tracker]( https://github.com/lvc/upstream-tracker/issues ).

**Comment by dougalsutherland** [comment]
Yep, it seems that the packages are actually just independent despite having the same name. https://github.com/lvc/upstream-tracker/issues/21

**Comment by dougalsutherland** [comment]
Looks like it's slightly complicated: https://abi-laboratory.pro/tracker/timeline/libedit/

That is, there are multiple 3.1 versions, tagged with dates. I guess maybe we should change the libedit recipe to add the date as a minor version?

**Comment by jakirkham** [comment]
Agreed. Looks like the date is part of the `libedit` version for better or worse.

cc @conda-forge/libedit @mingwandroid

**Comment by dougalsutherland** [comment]
I just merged a new `mysql` recipe with a `build` dependency of `libedit 3.1.20170329` and `run` of `libedit >=3.1.20170329`, since it seems to be persistently backwards compatible even from 3.0 to 3.1. I know `pin_the_slow_way` doesn't support that yet, but... 🤷‍♀️.

**Comment by jakirkham** [comment]
Maybe just encourage exact pinning for now? I don't think we are planning to do much with `libedit` yet.

**Comment by mingwandroid** [comment]
> Maybe just encourage exact pinning for now.

Why? https://abi-laboratory.pro/tracker/timeline/libedit

I am planning to do a lot with `libedit` and so would appreciate standardisation here.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-pinning-feedstock #10](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/10) via [**ZenHub**](https://www.zenhub.com/)
