### ISSUE TITLE
Setting up cron jobs for feedstock updates

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#48]
Basically, we want to have this automatically ( https://travis-ci.org/conda-forge/conda-forge.github.io ) triggered at some regular interval.

Relevant [discussion]( https://github.com/conda-forge/conda-forge.github.io/issues/40#issuecomment-197461975 ).

Currently considering (  http://tron-ci.herokuapp.com/ ) ( https://nightli.es/ ) or possibly on some personal infrastructure somewhere (RaspberryPi).

**Comment by jakirkham** [comment]
If you would like me to try setting up Tron CI, I could give it a go, @pelson.

**Comment by pelson** [comment]
> If you would like me to try setting up Tron CI, I could give it a go, @pelson.

Sure thing. :+1: 
Maybe we should also just trigger the travis job to run once staged-recipes runs on master?

**Comment by jakirkham** [comment]
> Sure thing. :+1:

Cool, I will play with this and let you know how it goes.

> Maybe we should also just trigger the travis job to run once staged-recipes runs on master?

This would be the ideal solution. Though am a bit worried about collisions. If we are careful, maybe this can be ok.

**Comment by pelson** [comment]
> Though am a bit worried about collisions.

Hmmm, I confess, I'd satisfied that worry. Is there a particular aspect that you have concerns about?

**Comment by jakirkham** [comment]
No longer worried after seeing your implementation.

This is no longer relevant as rebuilds of docs and feedstocks are triggered after making a new feedstock.

See PRs for details. ( https://github.com/conda-forge/staged-recipes/pull/185 ), ( https://github.com/conda-forge/staged-recipes/pull/186 ), ( https://github.com/conda-forge/staged-recipes/pull/187 ).

**Comment by pelson** [comment]
Thanks @jakirkham. It may still be a useful thing in the near future, but I agree, for now we can park this. :+1:

**Comment by jakirkham** [comment]
Re-opening as I'm beginning to think this is a better way forward after all. Let's discuss again.

**Comment by jakirkham** [comment]
Did you set this up with [nightli.es]( https://nightli.es/ ), @pelson? We could also have our own Heroku app for this so we can better control the interval.

**Comment by jakirkham** [comment]
nightli.es failed to run yesterday and presumably today. So, I ran Travis CI manually.

**Comment by pelson** [comment]
> Did you set this up with nightli.es, @pelson?

I may have tried at some point, but not recently.

>  We could also have our own Heroku app for this so we can better control the interval.

[conda-forge-maintenance](https://github.com/conda-forge/conda-forge-maintenance) would be the place for it. I agree, doing this every 24 hours would be sufficient IMO.

**Comment by jakirkham** [comment]
Ah, ok. Well I saw two commits that indicated this was happening recently; so, figured I should ask.

**Comment by jakirkham** [comment]
Closing in favor of this issue ( https://github.com/conda-forge/conda-forge-maintenance/issues/2 ).

**Comment by jakirkham** [comment]
As FYI, after going through with PR ( https://github.com/conda-forge/staged-recipes/pull/733 ), it seems that nightli.es is running regularly. Recently, I toggled its on status at ~0600UTC, which seems to be a low activity time (from past experience). It seems to have started just running around that time. So, I guess we have this functioning now. 😄

**Comment by jakirkham** [comment]
Travis CI has added their own functionality for this. I enabled it a while back and it has worked fine. Today have disabled nightli.es. Let's see how it goes from here.

**Comment by jakirkham** [comment]
Appears Travis CI's cron job feature (still in beta) is not working. It did not run for 3 days after turning of nightli.es. Have re-enabled nightli.es on this repo for now.

**Comment by jakirkham** [comment]
Have had nightli.es removed. Was unable to get the listing of repos to load for a little while now and Travis CI's cron job service works well. Though it looks like we are going back to live updates of the webpage. So we shouldn't need any cron jobs soon (except maybe as a fail safe).
