### ISSUE TITLE
Pin protobuf

### ISSUE THREAD

**Issue by gokceneraslan** [conda-forge/conda-forge.github.io#488]
As mentioned [here](https://github.com/conda-forge/mosh-feedstock/issues/3#issuecomment-292658505) by @jakirkham, protobuf shoud be pinned. Soname and symbols change in every version (e.g. 3.3 -> 3.4) and dependent packages are broken.

**Comment by jakirkham** [comment]
Right. The current pinning should be 3.4 as noted [here]( https://github.com/conda-forge/conda-forge.github.io/blob/06e20200a735ca2a22848caa6f6ad73c0f8f7419/scripts/pin_the_slow_way.py#L85 ). Please let us know if you have more questions or concerns.

**Comment by gokceneraslan** [comment]
There is protobuf 3.4.1 in `defaults` and protobuf 3.4.0 in conda-forge. So I don't know how would this pin work. Can you help me understanding the build error I get here: https://github.com/conda-forge/mosh-feedstock/pull/5

**Comment by jakirkham** [comment]
Pointed to this elsewhere. Have added PR ( https://github.com/conda-forge/protobuf-feedstock/pull/35 ) to get us to 3.4.1.
