### ISSUE TITLE
Add section about dealing with CI time limits

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#497]
In particular how to workaround 10min timeout due to lack of output and how to deal with long running builds that are close to the CI limit.

**Comment by PrernaSingh587** [comment]
Hi @jakirkham I was just moving past open issues and saw this. Is this still valid? If yes, I could work upon it to document this. Please guide me through this.

**Comment by ssurbhi560** [comment]
Hi @jakirkham, I think I would be able to help with this. I also checked in the docs and there isn't any section which covers this, so this indeed would be a quite useful addition. Can you please share what are some steps one must take to deal with this, that would help me start with this.

**Comment by jakirkham** [comment]
Yeah I think this was related to CI systems we have already dropped. So let's close this as it's no longer relevant. Thanks for checking 🙂
