### ISSUE TITLE
Docs for [ci skip] et al

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#498]
It might be nice to have docs on the commit message based CI skipping (and maybe a discussion about it's being temperamental?

**Comment by jakirkham** [comment]
Also issue ( https://github.com/conda-forge/staged-recipes/issues/1148 ) is relevant. Note that it is a non-actionable issue just tracking this info. Would be happy to close it and have that content absorbed into a doc section somewhere instead.

**Comment by jaimergp** [comment]
This can be closed. See https://github.com/conda-forge/conda-forge.github.io/pull/2297.
