### ISSUE TITLE
CI statistics

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#499]
Do we have in depth statistics from all of the CI services? It could be interesting/helpful to know:
1. How many builds are ran per month
1. How many builds error/fail/pass
1. The correlation between builds failing on one service and failing on others
1. Are there times when we aren't running at full capacity
1. What is the breakdown between staged pushes, staged PRs, feedstock pushes, and feedstock PRs

I guess some larger questions I'm thinking about:
1. Would "gating" OSX with Linux (it must pass on Linux before we run the OSX build (assuming that there is a Linux build)) help us any by reducing Travis load? (Putting aside for a moment if this is something we want to/could do)
1. Other questions I haven't really thought about yet (although more data may reveal)

**Comment by pelson** [comment]
Great idea. The answer I think is, no.

In terms of getting statistics, we'd need to get those from the CI providers themselves (it *may* be that they have an API for it, but I won't hold my breath).

Honestly, I'd love this functionality, but it would be broadly useful **way** beyond conda-forge. For that reason, I'm going to close this. If anybody reads this and decides to pursue the idea of CI statistics (for Travis, AppVeyor, CircleCI) at a github organisation level **please** update this issue and we can start to pull together metrics. 👍
