### ISSUE TITLE
How to programatically determine the build matrix of a feedstock

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#501]
What is the best way to pull the `conda-smithy` version used most recently from a feedstock?

**Comment by jakirkham** [comment]
We have been trying to make that commit message, but that only works if people use the default commit message (or at least the first line) from `conda-smithy` and maintain that commit in the repo's history. That mostly works, but is not guaranteed. This issue ( https://github.com/conda-forge/conda-smithy/issues/168 ) is relevant on the point of tracking the last version of `conda-smithy` used to re-render. The point it raises is that we don't want a re-render just to up the version used, which remains valid even now for a variety of reasons including CI churn.

**Comment by CJ-Wright** [comment]
That's fair, although I've ran into recipes which don't have 3.6 builds. Maybe a better question is how to get the build matrix so we can update all of the builds which lack 3.6 support?

**Comment by pelson** [comment]
I've updated the title to:

```How to programatically determine the build matrix of a feedstock```

As you say, I think the search that we would like to do would be ```give me all the feedstocks that don't yet have python 3.6 in their build matrix```.

**Comment by ericdill** [comment]
@jakirkham can we have conda smithy drop a file in the root of the feedstock, maybe call it `.conda-smithy`, that contains the latest version used to rerender? Then we're not subject to depending on a git commit. Admittedly that relies upon people *not* updating the contents of `.conda-smithy` but that seems less likely to occur than people editing the conda-smithy commit message. 🤷‍♂️

**Comment by ericdill** [comment]
> That's fair, although I've ran into recipes which don't have 3.6 builds. Maybe a better question is how to get the build matrix so we can update all of the builds which lack 3.6 support?

@CJ-Wright do you want the build matrix or do you want to check the contents of the ``conda-forge`` channels for packages that lack py36 support. It's reasonably straightforward to search through the repodata.json on each of the channels for such information

**Comment by dougalsutherland** [comment]
@ericdill As mentioned in https://github.com/conda-forge/conda-smithy/issues/168#issuecomment-219043880, if a conda-smithy update doesn't actually change anything in the rendering, then this would still change the repo on an update, kicking off builds. I guess that could still be okay if conda-smithy detected this situation and added `[skip ci]` to the commit message...

**Comment by pelson** [comment]
> do you want the build matrix or do you want to check the contents of the conda-forge channels for packages that lack py36 support. It's reasonably straightforward to search through the repodata.json on each of the channels for such information

I think this is a pretty good solution. It doesn't help if the recipe explicitly skips python 3.6, but then nor would inspecting the build matrix (you'd need to look at the recipe).

The other option is that when conda-smithy re-renders, it pumps out a build matrix file (perhaps in conda-build.yaml format) that we can programatically inspect. The downside is that we would be introducing redundancy in the feedstock, as this information would be in the conda-build.yaml as well as the CI yaml.

I'm going to close this, as I think the best solution that we have is either to inspect the recipes directly (perhaps through a clone of conda-forge/feedstocks), or to inspect the channel to find all packages that don't have a py36 build.
