### ISSUE TITLE
Some noarch packages do not work properly

### ISSUE THREAD

**Issue by jochym** [conda-forge/conda-forge.github.io#504]
Please some of the maintainers look at the problems with noarch packages causing problems for other packages:
- itsdangerous https://github.com/conda-forge/itsdangerous-feedstock/issues/9
- werkzeug https://github.com/conda-forge/werkzeug-feedstock/issues/8
- nglview https://github.com/conda-forge/nglview-feedstock/issues/5

The affected package is ase (https://github.com/conda-forge/ase-feedstock/pull/15). I had to implement an ugly workaround for this but it would be better if this was fixed upstream. Maybe there should be some guidelines regarding when noarch package should not be used?

**Comment by isuruf** [comment]
Have you checked with the latest conda-build 2.x package?

**Comment by jochym** [comment]
Yes, these builds use updated conda environments - they are standard conda-forge feedstocks.
The problem is that noarch packages are installed but do not function properly. Some parts are missing or not detected by setuptools and/or other programs. After installing earlier arch packages everything works as expected.

**Comment by isuruf** [comment]
I tried and `conda-build=2.1.18` works without a problem. https://circleci.com/gh/isuruf/ase-feedstock/6

**Comment by jochym** [comment]
That will be a very good news indeed. Did you change anything in meta.yaml ? Or just rebuild?

**Comment by isuruf** [comment]
I just reverted https://github.com/conda-forge/ase-feedstock/pull/14

**Comment by jochym** [comment]
Ok - let me try that. I have probably over-fixed this - back to simplifying.

**Comment by jochym** [comment]
The reason it succeeded is unfortunately that the tests did not run (upstream changed silently the test setup from 3.14->3.15). See this build: (https://circleci.com/workflow-run/576b7cba-3887-41a1-a9f7-b398116b746f). So I think the py<36 packages are broken but I think I'll use just flask pinning for py<36 and it should work around all the problems.

**Comment by jakirkham** [comment]
I wonder if issue ( https://github.com/conda-forge/ase-feedstock/issues/16 ) is also causing some problems.

**Comment by jochym** [comment]
That well may be, in local tests it now builds and tests properly - except the output is too large for CCI to handle. I'll create another even simpler build.

**Comment by jochym** [comment]
Thanks @jakirkham @isuruf for your help. It was of course my fault at the end!

**Comment by jakirkham** [comment]
Glad to hear that you were able to fix it.
