### ISSUE TITLE
Continuous Ticking

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#512]
It might be nice to have `tick-my-feedstocks` set up to run continuously on all the conda-forge packages. A few ways to accomplish this are:
1. Have a dedicated system(s) which run this as a cron job.
1. Run this in the webservice
1. Run this via travis

Personally I like option 3 which fully automates the service without getting in the way of the webservice (which I understand to be more reactive than proactive) and without needing a dedicated system. 

To do this we could:
1. Set up a repo for ticking feedstocks (not the source but an implementation)
1. Set up travis with this repo
1. Have travis run the tick-my-feedstocks script for all the conda-forge repos.
1. Run until done or travis global timeout kills the job
1. Run this as a daily cron so that every day we get more repos covered.

This would require the code to recognize that some version bumping PRs are in progress and filter out PRs already issued (so we don't re-issue PRs every day). One way to do this is to have a central file to track which repos have been bumped. In this system the script would write some info to a `YAML` file info about the PR issued (feedstock name, current version, bumped version, timestamp, url used to get version, etc.) `doctr` will push this file back onto GH someplace so we can keep track of the info outside of Travis. When another run begins it can read this file to filter feedstocks which have already been PR'd. If users don't want to wait for the main job to get to their feedstock, they are welcome to run their own version of this with their own keys.
Edit: Just as a note the file mentioned above is essentially the conda-forge directed acyclic dependency graph

Once could even consider breaking this up into two parts: one script/repo which goes and finds all the feedstocks which need ticking, and another which runs the actual ticking software. This may allow us to distribute the load better if we could use multiple CI's for ticking the software (each CI would need to run on a different recipe but we could split the list up evenly (or load balanced) between the CI's (eg a dedicated file for `Travis` which tells it which repos are on it's list)).

One major bottleneck may be GH api usage, but I'm not certain (another reason to separate the task into two parts).

Note that Travis may be interchangeable with other CI's (I just know that Travis has cron jobs and `doctr` supports it)

**Comment by CJ-Wright** [comment]
Please see https://github.com/regro/cf-graph/pull/1 for a prototype. Reviews welcome!

**Comment by CJ-Wright** [comment]
@conda-forge/core I'd be very interested in some thoughts on the PR. @justcalamari and I are hoping start testing this semi-live in the near future.

**Comment by jakirkham** [comment]
cc @pmlandwehr

**Comment by pmlandwehr** [comment]
I am entirely in favor of something like this existing. Given that tick-my-feedstocks is so focused on an individual and y'all are going to (rightly) maintain a copy of the complete DAG, it may be better to just steal a lot from tick-my-feedstocks and then go your own way.

**Comment by CJ-Wright** [comment]
I'm going to close this as the prototype system seems to be working (although with a few bugs to work out). 
Please feel free to add issues and/or PRs to https://github.com/regro/cf-graph and https://github.com/regro/cf-scripts
