### ISSUE TITLE
petsc.mod missing when wrapping fortran around petsc4py

### ISSUE THREAD

**Issue by apatlpo** [conda-forge/conda-forge.github.io#516]
I am trying to wrap fortran code around petsc4py and encountered the issue described at:
https://lists.mcs.anl.gov/pipermail/petsc-users/2018-January/034261.html

It appears the conda install of petsc does not come with petsc.mod files.

Is it intended?

**Comment by jakirkham** [comment]
Could you please move this issue to the `petsc` feedstock? Thanks.
