### ISSUE TITLE
Packages available before the merge

### ISSUE THREAD

**Issue by domenico-somma** [conda-forge/conda-forge.github.io#517]
Hi Guys,
I am quite new about python packaging, github and conda forge, I see something odd and I want be sure I am doing everything properly.

To update the feedstock
https://github.com/conda-forge/papillon-feedstock
What I do is:
* Fork the feedstock
* Edit the recipe as desired (just the recipe/meta.yaml)
* pull request

as described here:
https://conda-forge.org/#contribute

In the specific:
> Your recipe will automatically be built on Windows, Linux and OSX to test that it works, but the new distribution will not yet be available on the conda-forge channel.
> Once the recipe is ready it will be merged. The recipe will then automatically be built and uploaded to the conda-forge channel. 

Now, my pull request didn't work (I don't know why yet)
https://github.com/conda-forge/papillon-feedstock/pull/2
so I didn't merge it. But the packages are already available for the download:
https://anaconda.org/conda-forge/papillon

But this shouldn't be. Am I doing something wrong???

**Comment by isuruf** [comment]
You should push to your fork, but you pushed to conda-forge repo, https://github.com/conda-forge/papillon-feedstock.
