### ISSUE TITLE
Pinning gettext

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#524]
Trying to figure out how we should be pinning [`gettext`]( https://github.com/conda-forge/gettext-feedstock ). While there don't appear to be that many breaking changes. It does appear the SONAME has changed a few times in recent history. Posting the [API/ABI Report]( https://abi-laboratory.pro/tracker/timeline/gettext/ ) here for reference. Pinnings in the org currently vary from none at all, to setting some lower bound in `build`/run`, to pinning to an exact version. Thoughts on how to standardize this?

cc @conda-forge/gettext @conda-forge/core

**Comment by isuruf** [comment]
changing of soname in 0.19.8 was a mistake which was reverted in 0.19.8.1, so there's no need to pin.
Defaults on the other hand has released some R packages compiled with 0.19.8 leading to shared library missing errors. I've reported it to them, but no luck getting them to change.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-pinning-feedstock #11](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/11) via [**ZenHub**](https://www.zenhub.com/)
