### ISSUE TITLE
feedstocks page hangs when using filter

### ISSUE THREAD

**Issue by djm158** [conda-forge/conda-forge.github.io#529]
I noticed that the filter items search bar at https://conda-forge.org/feedstocks/ causes my browser to hang on the first letter I type into the search bar. I'd love to help improve this functionality for the site if deemed necessary.

**Comment by djm158** [comment]
Potential fix is loading all of the <li> elements first and parsing out their strings. Then as the user types into the search bar, we filter based on the search text, but instead build an entire new list and replace the existin <ul> dom element. 

Prototype:

```js
       var items = document.getElementsByClassName('list-group-item');
       var data = new Array(items.length);
       var links = new Array(items.length);
       for(var i = 0; i < items.length; i++) {
         data[i] = items[i].innerText;
         links[i] = items[i].firstElementChild.href;
       }

       $('#searchfield').show().on('change keyup keypress paste', function(){
         var searchterm =  $('#searchfield').val().toLowerCase();

         var output = '';
         for(var i = 0; i < data.length; i++) {
           if(data[i].indexOf(searchterm) >= 0) {
             output += '<li class="list-group-item"><a href="' + links[i] + '">' + data[i] + '</a></li>';
           }
         }
         console.log(output);
         $('.list-group').html(output);
       })
```

**Comment by jakirkham** [comment]
Yeah noticed this as well. Thanks for trying to improve it.
