### ISSUE TITLE
improve documentation for building this repo

### ISSUE THREAD

**Issue by djm158** [conda-forge/conda-forge.github.io#530]
It would be helpful if the README contained info for building the documentation in this repo locally. Something like:

## Contributing 

```sh
git clone https://github.com/conda-forge/conda-forge.github.io.git
cd conda-forge.github.io
```

### Development environment

install [conda](https://conda.io/docs/user-guide/install/index.html#)

```sh
conda install -n root -c conda-forge conda-smithy
```

### Build the documentation

install [shpinx](http://www.sphinx-doc.org/en/master/)

```sh
conda install sphinx
```

Then navigate to the `src` directory.

Windows:

```sh
./make.bat
```

UNIX:

```sh
make
```

### Build the html for http://conda-forge.org

```sh
python scripts/generate_html.py --html-source "."
```

then navigate to `index.html` in the root of your `conda-forge.github.io`

**Comment by ChrisBarker-NOAA** [comment]
Shouldn’t that be:

conda install sphinx 

:-)

**Comment by djm158** [comment]
haha updated 😊

**Comment by jakirkham** [comment]
Sure a PR would be welcome.

I think it is actually simpler than the steps above as we no longer generate the feedstock listing in this repo. So it's just install `sphinx` and run `make` (Windows normally checks some executable extensions for you).

**Comment by djm158** [comment]
will `make` generate the html for `feedstocks.html.tmpl`? If so could you point me where to look? It appears that `make` generates the documentation pages.

**Comment by jakirkham** [comment]
Sorry are you wanting to generate the feedstock listing or the docs?

The feedstock listing code has largely been moved out of this repo (with the exception of the template) into this [webservices' function]( https://github.com/conda-forge/conda-forge-webservices/blob/1cbc6580ddf155f86c63ee8cbcae80b84900aee7/conda_forge_webservices/feedstocks_service.py#L16 ).

Correct, `make` should just generate the docs.

**Comment by djm158** [comment]
Ohhh okay that makes sense. I was just trying to generate the listing to work on #531.

**Comment by jakirkham** [comment]
Yeah, sorry, it's not very dev friendly ATM as it requires 3 repos to build currently (webservices, feedstocks, and the webpage repo). Basically we list the contents of the feedstocks repo and use that to fill out the webpage template. It lives at webservices as we do live updating on Heroku when new feedstocks are made.

If you have any ideas about how we can make it more dev friendly, definitely would be open to suggestions.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/540 ). Though further improvements are certainly welcome :)
