### ISSUE TITLE
conda-forge-admin, please rerender does nothing

### ISSUE THREAD

**Issue by zerothi** [conda-forge/conda-forge.github.io#535]
In https://github.com/conda-forge/siesta-feedstock/pull/1

I have tried to re-render several times, but nothing happens?

Secondly, I don't know if anything broke because in the staged PR https://github.com/conda-forge/staged-recipes/pull/5026 it build correctly on Unix. However, after the merge, it is listed as "build: disabled" for all OS.

**Comment by ocefpaf** [comment]
That feedstock was created 2 days ago, there is nothing to rerender.

**Comment by ocefpaf** [comment]
> Secondly, I don't know if anything broke because in the staged PR conda-forge/staged-recipes#5026 it build correctly on Unix. However, after the merge, it is listed as "build: disabled" for all OS.

That is probably b/c of  `skip: true  # [win or osx or not py36]`. Please open an issue in the feedstock.
