### ISSUE TITLE
Briefly explain purpose/history of conda-forge

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#536]
Frequently users less familiar or new to conda-forge end up asking a few of the same questions. They tend to be along the following lines.

1. What is conda-forge?
2. Why does conda-forge exist?
3. How does conda-forge relate to defaults?

There are probably more questions along these lines. While there are answers to some of these questions in the docs, blog posts, and sometimes SO questions, we could really benefit from one clean page that answers these questions succinctly. These could live on a doc page, FAQ, or even the main page. We could then link out to additional resources for more info.

**Comment by croth1** [comment]
I added a brief introductory section to the docs: http://conda-forge.org/docs/user/introduction.html

It would be nice if somebody could review it and propose corrections & extensions.
