### ISSUE TITLE
Why conda-forge install many irrelevant packages

### ISSUE THREAD

**Issue by Yuyang01** [conda-forge/conda-forge.github.io#548]
After I run : conda install -c conda-forge matplotlib

It suggests me to install many packages although there are many packages that I do not know what they are.
I just want install matplotlib!!!! It gives me more than 10 packages to be installed!!!!
Is this a bug? Thank you.

**Comment by Yuyang01** [comment]
(pytf) parallels@ubuntu:~$ conda install -c conda-forge matplotlib
Solving environment: done

## Package Plan ##

  environment location: /home/parallels/bin/miniconda3/envs/pytf

  added / updated specs: 
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB
    libxml2-2.9.8              |                0         5.0 MB  conda-forge
    numpy-1.14.2               |   py36hdbf6ddf_0         4.0 MB
    fontconfig-2.13.0          |                0         964 KB  conda-forge
    sip-4.18                   |           py36_1         263 KB  conda-forge
    expat-2.2.5                |                0         434 KB  conda-forge
    libxcb-1.13                |                0         541 KB  conda-forge
    tornado-5.0.1              |           py36_1         657 KB  conda-forge
    icu-58.2                   |                0        22.7 MB  conda-forge
    matplotlib-2.2.2           |           py36_0         9.2 MB  conda-forge
    pytz-2018.3                |             py_0         217 KB  conda-forge
    six-1.11.0                 |           py36_1          21 KB  conda-forge
    kiwisolver-1.0.1           |           py36_1         925 KB  conda-forge
    pcre-8.41                  |                1         729 KB  conda-forge
    xorg-libxau-1.0.8          |                3          14 KB  conda-forge
    glib-2.53.6                |       h5d9569c_2         8.4 MB
    python-dateutil-2.7.0      |             py_0         200 KB  conda-forge
    dbus-1.10.22               |                0         1.6 MB  conda-forge
    ca-certificates-2018.1.18  |                0         140 KB  conda-forge
    libuuid-1.0.3              |                1          34 KB  conda-forge
    qt-5.6.2                   |      h974d657_12        44.5 MB
    backports-1.0              |           py36_1           4 KB  conda-forge
    jpeg-9b                    |                2         1.0 MB  conda-forge
    intel-openmp-2018.0.0      |                8         620 KB
    gstreamer-1.12.4           |       hb53b477_0         3.6 MB
    certifi-2018.1.18          |           py36_0         143 KB  conda-forge
    libiconv-1.15              |                0         2.0 MB  conda-forge
    mkl-2018.0.2               |                1       205.2 MB
    pyparsing-2.2.0            |           py36_0          95 KB  conda-forge
    xorg-libxdmcp-1.1.2        |                3          21 KB  conda-forge
    gst-plugins-base-1.12.4    |       h33fb286_0         4.8 MB
    backports.functools_lru_cache-1.5|           py36_0          11 KB  conda-forge
    libpng-1.6.34              |                0         305 KB  conda-forge
    freetype-2.8.1             |                0         2.9 MB  conda-forge
    openssl-1.0.2n             |                0         3.5 MB  conda-forge
    cycler-0.10.0              |           py36_0          14 KB  conda-forge
    pyqt-5.6.0                 |           py36_4         5.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       331.4 MB

The following NEW packages will be INSTALLED:

    backports:                     1.0-py36_1            conda-forge
    backports.functools_lru_cache: 1.5-py36_0            conda-forge
    cycler:                        0.10.0-py36_0         conda-forge
    dbus:                          1.10.22-0             conda-forge
    expat:                         2.2.5-0               conda-forge
.......
.......

**Comment by isuruf** [comment]
Matplotlib pacakge has dependencies. It needs python, numpy, cycler, etc. Are you saying you want to install matplotlib, but not python, numpy, etc?

**Comment by jakirkham** [comment]
That said, the `backports` are not really needed for Python 3.6. PR ( https://github.com/conda-forge/matplotlib-feedstock/pull/154 ) will drop them.

Though I'm guessing the concern is the sheer size of packages being pulled in, which dropping `backports` will barely effect. If that's the case, have to say I'm sympathetic, @Yuyang01. We use containers at work and everytime I watch Qt and friends pile into our install (because of `matplotlib`) I have to sigh. These things simply aren't useful for our use case and they are quite large.

We had discussed previously making different backends for `matplotlib` optional. ( https://github.com/conda-forge/matplotlib-feedstock/issues/2 ) That could help, but it could also cause problems as things like Qt are still need to plot for other use cases. So instead of getting complaints about a lot of packages getting installed, we will get complaints about loads of things being missing and stuff not working. Not an easy problem to solve. 😞

Generally would advise that specific packaging concerns be raised on the relevant feedstock in the future, @Yuyang01. Thanks for raising.

**Comment by ChrisBarker-NOAA** [comment]
On Thu, Mar 22, 2018 at 11:55 PM, jakirkham <notifications@github.com>
wrote:

> Though I'm guessing the concern is the sheer size of packages being pulled
> in, which dropping backports will barely effect. If that's the case, have
> to say I'm sympathetic, @Yuyang01 <https://github.com/yuyang01>. We use
> containers at work and everytime I watch Qt and friends pile into our
> install (because of matplotlib) I have to sigh. These things simply
> aren't useful for our use case and they are quite large.


yeah, QT really bugs me too (doesn't ipython pull it in also?)


> We had discussed previously making different backends for matplotlib
> optional.
>
really good idea.

> ( conda-forge/matplotlib-feedstock#2
> <https://github.com/conda-forge/matplotlib-feedstock/issues/2> ) That
> could help, but it could also cause problems as things like Qt are still
> need to plot for other use cases.
>
what is QT needed for if you aren't using the QT back-end???

lots of folks only use the agg back-end -- no GUI at all.

Also, I don't think wxPython is pulled in, so why qt?

-CHB



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by kayibal** [comment]
+1
