### ISSUE TITLE
Conda-Forge by the numbers

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#549]
Should we have some sort of dashboard which shows "Conda-Forge by the numbers"? This would provide an easy place to see (but not limited to):
1. How many recipes on CF
1. How many total downloads of CF packages
1. Current members on CF
1. Total number of commits across the org

**Comment by jakirkham** [comment]
Sounds like a good idea. Much of this info is already available from GitHub in one way or another. So it would be good if we could even make GitHub update it for us (to avoid some more complex build process we manage ourselves).

**Comment by CJ-Wright** [comment]
Maybe badges?

**Comment by jaimergp** [comment]
I think this can be closed thanks to https://github.com/conda-forge/conda-forge.github.io/pull/1712

**Comment by jaimergp** [comment]
Website shows this info now:

![image](https://user-images.githubusercontent.com/2559438/165055840-eee04097-d50f-4da2-a12b-a366e371b9b6.png)
