### ISSUE TITLE
Extra information for bot

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#559]
It might be nice to put some metadata for the autotick bot into the `extra` section (maybe as a `autotick-bot` subsection?).

This may provide a good way for maintainers to interact with the bot for their recipes without having to directly poke the graph (which is currently discouraged).

Things that could go into this subsection:
- a bool which describes if to have the bot issue PRs (rather than a central blacklist)
- something that tells the bot that we should respect updates to old tags (security updates). For example tell the bot that it should track versions as it currently does but also track `9.x` releases and `8.x` releases as separate from the main versions (so an update from `9.3` to `9.4` would be PRed by the bot).
- more things that maintainers would like to have access to. (feel free to add more!)
Attn: @ocefpaf

**Comment by viniciusdc** [comment]
@CJ-Wright Any news with this ?

**Comment by CJ-Wright** [comment]
Not really most of this information has gone into the conda-forge configs rather than in the recipe. I'm going to close accordingly.

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.
