### ISSUE TITLE
All feedstock windows builds are broken with conda=4.5

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#560]
https://ci.appveyor.com/project/conda-forge/awscli-feedstock/build/1.0.172

cc @conda-forge/core

**Comment by msarahan** [comment]
this is caused by the issue you reported at https://github.com/conda/conda/issues/7144

Your fix at https://github.com/conda-forge/conda-smithy/issues/731 is my recommended approach.  We may need to pull conda 4.5 for a little while.

**Comment by isuruf** [comment]
No, this is another issue. `call conda.bat` issue again.

**Comment by msarahan** [comment]
Hm... yes.  Conda doesn't have the conda.bat redirects at all anymore.  The new pattern might be something like

``%SYS_PYTHON%\..\conda.exe``

this might only work with conda-build 3.

**Comment by jakirkham** [comment]
Is this now resolved? Saw this [build that passed recently]( https://ci.appveyor.com/project/conda-forge/otfmi-feedstock/build/1.0.26 ). That said, this may not be representative. So would be good to know whether there are other live issues.
