### ISSUE TITLE
Accessing CIs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#571]
Probably worth a few lines about how to access CIs and typical solutions if they don't behave as expected (e.g. Travis Sync for permissions to restart, etc.) given how often this comes up.

**Comment by prachi237** [comment]
@jakirkham  can I get some more info regarding this, if this is not yet implemented , I would like to add them

**Comment by jakirkham** [comment]
I think this has been mostly addressed by adding bot actions like [this one] ( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-restart-ci ). Let's go ahead and close
