### ISSUE TITLE
Communicating New Recipe Policies/Best Practices

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/conda-forge.github.io#578]
@jakirkham suggested that I start a new issue here to discuss ways of communicating new recipe policies and best practices, as well as conda behavior changes. If you're not following every issue on a number of repos, it's hard to tell what changes are in the pipeline or under discussion. 

The only idea that I had was some sort of low volume email list or newsletter that highlights when a change is made to the documentation that reviewers should know about, or if a major change is under discussion that will effect how recipes are written. I imagine the list/newsletter would mostly be subscribed to by staged-recipe reviewers. 

Thoughts?

**Comment by kain88-de** [comment]
A best practice update would also be nice for maintainers to know if packages need to be updated or if I can start to use new compiler options in builds (conda-build 3). 

This would also be good to communicate larger general changes that happen with conda-forge packages.

A list/newsletter/blog (RSS) style option would definitely be nice.

**Comment by jakirkham** [comment]
Thanks all. These are good ideas.

Hadn't thought about a newsletter for this, but agree that would be a good option. There is a mailing list, but it's been relative unstructured and not used for this intent. We could look at adding a thread in there for this purpose.

We have discussed a blog before (even in the past few weeks). Maybe we could have it dual for other purposes (e.g. have a feed, maybe IFTTT to send out an email). Good thinking.

Any thoughts on how we handle questions for announced changes (particularly given volume is a concern)? Thought on how we should do things for proposed changes?

cc @conda-forge/core

**Comment by mbargull** [comment]
("Bioconda awareness ping": @conda-forge/bioconda-recipes)

**Comment by CurtLH** [comment]
Whatever option is taken, I hope it's something that can be searched against and a complete history is available for new members to review when they join.

I recently had a question about building recipes for multiple versions of R.  I searched all the documentation that I could find, but wasn't able to find an explanation.  I ended up opening an [issue](https://github.com/conda-forge/conda-forge.github.io/issues/580), and my question was promptly answered.  Apparently there was a decision to drop support for R 3.3.2, which I completely support.  However, I haven't seen this decision communicated outside of the issues/PRs linked to within my question.  

It would be great to have a place to read about these types of changes when they're made as well as to reference after the fact.

**Comment by jakirkham** [comment]
We've added a news page accessible from the website, which can serve this purpose.

ref: https://conda-forge.org/docs/news_announce.html

**Comment by beckermr** [comment]
I'm adding an RSS feed from the news page: https://github.com/conda-forge/conda-forge.github.io/pull/1221

**Comment by jakirkham** [comment]
Thank you for doing that! 😄

Should we do this for the blog as well?

**Comment by beckermr** [comment]
The blog has one already. I added a link to it in the documentation.

**Comment by beckermr** [comment]
https://conda-forge.org/blog/atom.xml

**Comment by beckermr** [comment]
I think maybe this issue can be closed?

**Comment by jakirkham** [comment]
Interesting one uses Atom and the other RSS. Maybe we should use RSS for both (or Atom)?

**Comment by jakirkham** [comment]
Yeah let's close. We can follow up on other things in new issues.
