### ISSUE TITLE
Blog piece

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-forge.github.io#58]
We should write something and ask continuum to post at their blog/page.

Pinging @rsignell-usgs (who gave the idea) and I @jakirkham (who is probably the most engajedmember so far :wink:).

**Comment by pelson** [comment]
:+1:

**Comment by rsignell-usgs** [comment]
I sent email to Travis & Co. about the idea.

**Comment by jakirkham** [comment]
Great idea! :smile:

**Comment by ocefpaf** [comment]
Done in: https://docs.google.com/document/d/1dkuBli6LuuvBAw1TohdpOPhXYEv-TReOo9MZ0w-5IkY/edit

PS: We also have a draft for the Code of Conduct: https://docs.google.com/document/d/10dxX0Zse0Rx1HqsxC73Wfsghmy5m8PP8cHuBIOhWKpc/edit

**Comment by pelson** [comment]
Sorry I've not yet had a chance to look at it yet @ocefpaf. We should totally have discussed this at the last meeting and got and action from everybody to read it and provide feedback by a particular date. Will it be too long until the next meeting?

**Comment by ocefpaf** [comment]
I know that @msarahan already took a look (and fixed much of my bad English :wink:), and @rsignell-usgs and @jjhelmus just requested access so they will probably read it today.

So next meeting is fine. We should wait a little longer to give people more time to take a look.

**Comment by jakirkham** [comment]
It's here. Thanks @msarahan for letting us [know]( https://gitter.im/conda-forge/conda-forge.github.io?at=5730e7ccf16c085106621bfa ).

https://www.continuum.io/blog/developer-blog/community-conda-forge

**Comment by pelson** [comment]
Awesome! Thanks for seeing this through everybody. :tada:
