### ISSUE TITLE
How to determine which versions of R a package builds for?

### ISSUE THREAD

**Issue by CurtLH** [conda-forge/conda-forge.github.io#580]
It seems that some R packages are built for 3.3.2 and 3.4.1, where other R packages build for just one version or the other. However, when constructing the recipe/meta.yaml, there isn't a section to select which version of R that the package should be build for in the same way as with a Python package.

How are the versions that an R package builds for determined?

**Comment by dougalsutherland** [comment]
You actually can do the same skips for R as for Python.

The difference is just that we dropped 3.3.2 support a while ago (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/28 / https://github.com/conda-forge/r-base-feedstock/issues/36), but not all R packages have been [re-rendered](https://conda-forge.org/docs/conda_smithy.html) since.

**Comment by CurtLH** [comment]
Good to know.  Thanks @dougalsutherland!

**Comment by jakirkham** [comment]
As to how they are determined, this will get much more obvious going forward (thanks to recent updates in our tooling). Namely there is a directory call `.ci_support` and that will list all configurations the package is currently built with. More details are in the individual files. For example, [here's the directory from `numba`]( https://github.com/conda-forge/numba-feedstock/tree/9f77dbda2a5e01393f8b0ada6d38e3415327e137/.ci_support ). One can see it is built with Python 2.7, 3.5, and 3.6. It is also apparent, which platforms are supported. Currently just macOS and Linux in this case.

Going forward, we are making some improvements to the R stack to allow removing version dependence on `r-base` when it is not needed by a package. ( https://github.com/conda-forge/r-base-feedstock/pull/43 ) These are known as `noarch` packages. This will make it easier to upgrade the R stack both for maintainers and users as fewer packages will need rebuilds to work with a newer `r-base`.

If there are particular packages that have not updated to newer versions of R, would raise an issue on their feedstocks to get the maintainer's attention on this issue. It may be the case that some of these issues require resolution upstream from the package needed. Please be patient with maintainers as they figure these issues out.
