### ISSUE TITLE
Add --verbose to pip line

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#589]
Otherwise the logs are pretty useless

**Comment by ocefpaf** [comment]
I'm OK with that bit some people think that is already too long :stuck_out_tongue_closed_eyes:

**Comment by isuruf** [comment]
If it's too long then a jinja variable defined in `conda-forge-pinning` can do `{{ pip_install_line }}`.

**Comment by jakirkham** [comment]
Admittedly we are just talking about the docs, right? So there is no harm with adding it. People can always delete when they copy if they want to.

**Comment by isuruf** [comment]
Yes, just the docs

**Comment by pkgw** [comment]
Potentially related question. The current docs ([here](https://conda-forge.org/docs/meta.html#use-pip)) say that the recommended line is:

```
script: "{{ PYTHON }} -m pip install . -vvv"
```

But the example recipe ([here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L33)) has this version:

```
script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
```

The two should at least be consistent. Which is preferred?

**Comment by jakirkham** [comment]
The `staged-recipes` example is out of date and needs to be updated to match the docs. `conda-build` now sets all of the other arguments except the verbosity level and directory.

**Comment by croth1** [comment]
Currently the docs recommend:  `"{{ PYTHON }} -m pip install . --no-deps -vv"`. Let's consider this done 👍
