### ISSUE TITLE
No Gravatar icon on https://anaconda.org/conda-forge

### ISSUE THREAD

**Issue by peterjc** [conda-forge/conda-forge.github.io#591]
I could't see a better place to open this issue, which is not really about the webpage but the wider internet footprint of the project.

Some projects have a nice icon on their anaconda page, e.g.

https://anaconda.org/r
https://anaconda.org/anaconda
https://anaconda.org/spyder-ide

Others have a default randomly generated image, e.g.

https://anaconda.org/conda-forge

Can someone upload the conda-forge logo to Gravatar for whatever email address is associated with the anaconda.org account?

See also #588

**Comment by jakirkham** [comment]
cc @pelson

**Comment by pelson** [comment]
I've updated the conda-forge gravatar account, so hopefully that should do the trick.

I tried doing this a couple of times before, and hadn't realised it was hooked into gravatar (I even raised a question somewhere on one of the many anaconda issue trackers).

Glad it was so easy to do 😄

**Comment by peterjc** [comment]
Lovely - its a small thing but it looks good, thanks!

**Comment by jakirkham** [comment]
Thanks Phil!
