### ISSUE TITLE
Clarifying docs

### ISSUE THREAD

**Issue by ChayaSt** [conda-forge/conda-forge.github.io#607]
@msarahan, here are some points that can be clarified in the documentation: 

1. There is no explanation why conda-forge (vs default conda channel) in the documentation. This should probably be explained in the beginning of the about page. 
2.  The section below checklist is titled "What happens after the PR to staged-recipes is merged". This can be a little confusing. It might be clearer to add a step to merge the PR to staged recipes after going through the checklist in the step by step instructions https://conda-forge.org/docs/recipe.html#step-by-step-instructions

**Comment by scopatz** [comment]
Thanks for brining this up @ChayaSt! Pull requests are definitely welcome!

**Comment by croth1** [comment]
I made following changes to the docs:
 http://conda-forge.org/docs/user/introduction.html#why-conda-forge addressing (1)
 http://conda-forge.org/docs/maintainer/adding_pkgs.html#feedback-and-revision addressing (2)

Thanks @ChayaSt for giving feedback!
