### ISSUE TITLE
noarch: python with non-console entry points?

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/conda-forge.github.io#633]
I was under the impression that this worked, but apparently @mariusvniekerk thinks it doesn't: https://github.com/conda-forge/glue-vispy-viewers-feedstock/pull/25#issuecomment-406765996

Whichever is the case, this is something that we should document....

cc @astrofrog-conda-forge

**Comment by scopatz** [comment]
What do you mean by non-consols? Non -cli

**Comment by mbargull** [comment]
I would assume this works, but maybe it's best to just try it out, I guess.
One issue might be https://github.com/conda/conda/issues/7693 (`egg-info` dirs not being renamed), though.

**Comment by synapticarbors** [comment]
Do we have a final answer on how to handle this yet? If we think it's problematic, perhaps a note of caution should be added to the `noarch` docs recommending that it should be avoided for packages with non-console entry points.

**Comment by mbargull** [comment]
xref'ing the latest conversation between @synapticarbors and me: https://github.com/conda-forge/pybtex-feedstock/pull/4#issuecomment-426403985

**Comment by mbargull** [comment]
My guess is someone should implement https://github.com/conda/conda/issues/7693 and "try it out" (preferably by writing test cases for this in `conda`).

**Comment by croth1** [comment]
@conda-forge/core does anybody know the answer here? This seems like a common problem and should go in the documentation.

**Comment by mariusvniekerk** [comment]
So we have a fair amount of pytest packages with non console entry points. It seems like it's fine.

**Comment by croth1** [comment]
Thanks for the feedback @mariusvniekerk. I will update the documentation soon 👍
