### ISSUE TITLE
DOC: Skipping Python versions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#638]
We explain in the docs [how to skip a platform]( https://conda-forge.org/docs/meta.html#excluding-a-platform ), but not how to skip a Python version. Even though we [refer to it later]( https://conda-forge.org/docs/meta.html#building-noarch-packages ). Would be good to have this be explicit in the docs.

**Comment by croth1** [comment]
This is done 👍
