### ISSUE TITLE
Migrating from XCode 6.4 to new macOS image on Travis CI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#641]
Travis CI is planning to drop the XCode 6.4 macOS image we have been using in January 2019 (see warning in screenshot below). We should evaluate and decide what image of the ones they provide we should switch to. Also we will need to update all feedstocks and staged-recipes with this change. For some cases, this may impact what versions of macOS we can support. So we should contemplate this carefully.

<img width="1552" alt="screen-shot-2018-08-27-at-22 09 00" src="https://user-images.githubusercontent.com/3019665/44936869-7e1cd400-ad44-11e8-9bd9-c9b55a0adf5e.png">

cc @conda-forge/core

**Comment by scopatz** [comment]
Can we just switch to the next lowest XCode version?

**Comment by jakirkham** [comment]
That's probably a safe option. Here's the [list of supported versions]( https://docs.travis-ci.com/user/reference/osx/#os-x-version ).

The other thing we can do is download the macOS SDK (e.g. 10.9), which we plan to support. This is [what we already do for CircleCI's macOS builds]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/53c72da7595e0f84bbe5fb43f92a29ff7d1ac56f/recipe/run_conda_forge_build_setup_osx#L15-L20 ) as they have really new images and new versions of XCode. Here's CircleCI's [list of XCode versions]( https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions ) for comparison/reference.

**Comment by scopatz** [comment]
Yeah that would be fine too! They are fairly large, though, right? Does downloading significantly increase build time?

**Comment by jakirkham** [comment]
Not really. They range between ~20-40MBs (compressed). So the size of one conda package. 😉

Honestly not sure. However given the size is reasonable and lack of user complaints about download time, am guessing this is a non-issue. Though that is a pretty rough measure. 😄

**Comment by scopatz** [comment]
Yeah, that sounds totally reasonable

**Comment by jakirkham** [comment]
As a note here, there were [some issues using `xcode9.4` for PyQt recently]( https://github.com/conda-forge/pyqt-feedstock/pull/43#issuecomment-447996683 ). So we had to move it back to `xcode6.4`.

cc @ccordoba12

**Comment by isuruf** [comment]
That's an issue with PyQt or Qt

**Comment by ccordoba12** [comment]
I think the solution is to move the Qt stack to 5.9, but no one seems to be willing to invest the time necessary to do that.

**Comment by CJ-Wright** [comment]
The bot could support a Qt pinning migration if that is what is needed.

**Comment by jakirkham** [comment]
The first thing we would need to do to support Qt 5.9 is backport @mingwandroid's [work from AD]( https://github.com/AnacondaRecipes/qt-feedstock ). This would then need to be followed by similar backports for PyQt and PySide.

I'm not sure how many things actually pin to Qt directly. That said, I think simply getting these 3 packages built should be the focus before worrying about involving the bot. Expect simply building them would be a fair amount of work.
