### ISSUE TITLE
Configure Travis CI's GitHub App

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#644]
Currently we are using GitHub's Services, which is [planned for deprecation October 1, 2018]( https://developer.github.com/changes/2018-04-25-github-services-deprecation/ ). The migration path is to switch to GitHub Apps or GitHub Webhhooks. The good news is nearly everything we use already works off of GitHub Webhooks. Unfortunately Travis CI uses GitHub's Services. So it will need to be migrated.

With Travis CI, they have opted to [support GitHub Apps]( https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com ). Fortunately they do provide a [migration solution for **existing** repos in orgs with 50+ repos]( https://docs.travis-ci.com/user/travis-migrate-to-apps-gem-guide/ ). We can try to use that verbatim or possible tweak it if needed. However for new repos, we need to make [some changes]( https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#new-repositories ). Am not sure if more changes are needed. Will require some research to be sure.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by jakirkham** [comment]
Ping @conda-forge/core. This is the deadline now.

**Comment by beckermr** [comment]
This is fixed AFAIK. We have a few webhooks lying around from when we moved from .org to .com, but these can be deleted by hand as needed. Closing!
