### ISSUE TITLE
Feedback as requested by @jakirkham on Gitter

### ISSUE THREAD

**Issue by PhilipMay** [conda-forge/conda-forge.github.io#645]
Hi everybody,
my name is Philip and I am new to conda-force.
At the moment I am maintaining the hyperopt package.
@jakirkham asked me on Gitter to give some feedback.
I think this is a very good idea - so here it is:

1. When I was first thinking to build a conda package
I had a look into conda-forge and asked myself: "Hey,
what's the difference of uploading packaged to anaconda.org
or publishing them to conda-forge?" 
Maybe you could publish a chapter where you talk about 
the differences and advantages.

2. The "Packaging the License Manually" chaper is not 100% clear to me.
For me it ~~was~~ is not 100% clear if the LICENSE.txt file must be included
in the same directory as the meta.yaml or not. Even when it is included
in the tarball.
See here: https://conda-forge.org/docs/meta.html#packaging-the-license-manually

3. Everything else was much to read but good and understandable to me. 

Thanks for your work
Philip

**Comment by scopatz** [comment]
Hi @PhilipMay - thanks for the feedback!  Please feel free to put in PRs that make the text of the documentation more clear to you. All of those docs are in this repo :)

**Comment by PhilipMay** [comment]
@scopatz yes - well, good idea. But actually I do not know the exact answer for both topics. So it would be cool if someone else could do that.

**Comment by scopatz** [comment]
@PhilipMay - from what you said, it seems like you understand (2) :wink:

**Comment by PhilipMay** [comment]
> @PhilipMay - from what you said, it seems like you understand (2) 😉

Well, yes you are right. I changed the text. Sorry for the confusion.

**Comment by croth1** [comment]
In the linked commit introduced changes that hopefully clarify the docs. Thanks for your feedback @PhilipMay!
