### ISSUE TITLE
Some packages don't support Python 3.7

### ISSUE THREAD

**Issue by tats-u** [conda-forge/conda-forge.github.io#649]
I tried to install packages in conda-forge to Python 3.7, but they try to downgrading my Python to 3.6.  The auto generated code by @ conda-forge-admin does not support 3.7.

Packages tries to downgrade Python 3.7:
- neovim
  - greenlet
  - msgpack-python
- librosa
  - audioread
- ansible
  - **dogpile.cache**
  - **netifaces**
  - oslo.serialization
  - oslo.utils
  - python-ironicclient
  - shade

Migrate from: https://github.com/conda-forge/feedstocks/issues/52#issuecomment-423261928

**Comment by scopatz** [comment]
Hi @tats-u! This will happen automatically as part of the compiler migration (see [the status page](https://conda-forge.org/status/)). 

You can also update recipes manually. I don't know the steps here but @ocefpaf might be able to list them

**Comment by ocefpaf** [comment]
You need to add a line with `max_py_ver: '37'` in the `conda-forge.yml` and then re-render. But before doing that check if the recipe can be `noarch`.

**Comment by tats-u** [comment]
I see.    Thank you.
I feel migration from 3.6 to 3.7 is slower than that from 3.5 to 3.6, and if it is true, why do you think?

**Comment by jakirkham** [comment]
Closing as the compiler migration is complete, which included Python 3.7 rebuilds. For individual packages that may still be missing Python 3.7 support, please raise on the respective feedstock to get in touch with maintainers about addressing the issue. Thanks!
