### ISSUE TITLE
Terminate AppVeyor if a package is in the channel

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-forge.github.io#65]
When re-starting Appveyor jobs that crashed to due connection problems (or any other random problem) the whole matrix gets re-build. Not sure if it is possible, but maybe we should do

`- 'python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main'`

first and, if the package is already there, cancel the build.

**Comment by pelson** [comment]
In a feedstock or in staged-recipes? The latter is a quick win, but the former is kind of questionable IMO.

**Comment by ocefpaf** [comment]
> but the former is kind of questionable IMO.

Because one would have to always build the build number to see a build happening?

**Comment by pelson** [comment]
> Because one would have to always build the build number to see a build happening?

If you've made a change to the feedstock but not bumped the build number, you still want to know it works, even if you don't want a new binary. Checking upfront to determine whether to do the work brings us back to one of the major issues with multi-recipe repositories (the fact that you have to look for *whether* a recipe need building or not).

I'm not sure we are going to be able to do anything about that (other than by upgrading AppVeyor [I've started a conversation with them, and will let you know if anything comes of it])

**Comment by ocefpaf** [comment]
> If you've made a change to the feedstock but not bumped the build number, you still want to know it works, even if you don't want a new binary. 

I get that. I just thought that this would be a minor problem than re-starting everything.

> I'm not sure we are going to be able to do anything about that (other than by upgrading AppVeyor [I've started a conversation with them, and will let you know if anything comes of it])

That works too :smile:
