### ISSUE TITLE
suggestion: choose a more visually pleasing sphinx theme

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#652]
Do you think changing the sphinx theme is a good idea? IMO the default theme alabaster has a very poor user experience, especially when it comes to structuring the content in the navigation bar. IMO, switching to sphinx_rtd_theme would improve the UX massively by improving the navigation.

**Comment by scopatz** [comment]
We are always happy to have UX improvements, but I personally dislike the RTD theme.

**Comment by ocefpaf** [comment]
I'm not a fan of RTD either.

**Comment by croth1** [comment]
Hmhm, fair enough - doesn't have to be rtd. I find many of the available ones more pleasing than alabaster. Maybe my dislike of alabaster is a pet peeve of mine. To me it looks a bit like somebody forgot to upload the style sheet 😬

**Comment by scopatz** [comment]
I'd still like to do some work on the color scheme and template.

**Comment by scopatz** [comment]
done
