### ISSUE TITLE
tickbot does not resubmit migration PR with bot-rerun

### ISSUE THREAD

**Issue by jschueller** [conda-forge/conda-forge.github.io#664]
I received a migration PR to the openturns feedstock:
https://github.com/conda-forge/openturns-feedstock/pull/64
It failed, because of some bugs.
In the mean time I made modifications so the PR had conflicts.
As advised I added the label "bot-rerun" to the PR.
The bot closed it but did not resubmit it.

Worse it now considers this package migrated as it fired migrations PRs to children packages like this one:
https://github.com/conda-forge/otfftw-feedstock/pulls

**Comment by CJ-Wright** [comment]
Thank you for reporting! (Although in the future please send autotick issues over to https://github.com/regro/cf-scripts).
I'm working on removing the bad commits. After that I will check that the bot's records for openturns are correct. After which you should be able to add the `bot-rerun` label to all the children and they will get rescheduled appropriately. I'll post here when everything is ready to go.

**Comment by CJ-Wright** [comment]
Everything should be good to go, you should get a PR for openturns soon, and `bot-rerun` should work on the children.

**Comment by jschueller** [comment]
Thank you!
