### ISSUE TITLE
Add staged-recipes review team to docs

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#666]
We have explicitly listed the [core team](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/core.csv) and the [bot team](https://github.com/conda-forge/conda-forge.github.io/tree/master/src/subgroups). Should we also consider listing the staged-recipes team?

**Comment by scopatz** [comment]
:+1:

**Comment by croth1** [comment]
If still of interest these should go here in the new documentation. http://conda-forge.org/docs/orga/subteams.html.

I don't know enough about conda-forge to draft these myself. Anybody from @conda-forge/core able to help here?
