### ISSUE TITLE
R packages from sources other than CRAN

### ISSUE THREAD

**Issue by dbast** [conda-forge/conda-forge.github.io#668]
How to deal with R package sources other than CRAN?

Most R packages are using CRAN as source, which serves as a good quality gate as CRAN does `check` the package and also does some lifecycle management if required. (Option A)

There are also some R packages which are created directly from github archives  `https://github.com/*/$pkg/{archive, releases}/*.{zip, tar.gz}`. There is no additional CRAN which does checks, it is all up to the repo contributors their CI and the conda package maintainer to bring a "good" version to conda-forge. (Option B)

Currently around 1200 packages are built from CRAN and around 15 are built from github:
* `rg cran feedstocks -g "**/r-*/*/meta.yaml" --files-with-matches | wc -l`
* `rg cran feedstocks -g "**/r-*/*/meta.yaml" --files-without-match | wc -l`

There is now a package [0] with some unique functionality following a changing API, that was packaged via CRAN but is now outdated and not working anymore. New releases are all done via a drat repo. Releasing again to CRAN seems not to happen [1] "Option A" and getting their releases tagged in the repo also seems not to happen [2], which would enable "Option B".

The drat repo is owned by the same github project as package source code repo. And it is so more or less as reliable as the source code repo itself or as to what I refer to as "Option B".

For more details and how a change looks like, see also https://github.com/conda-forge/r-aws.s3-feedstock/pull/3

Possible options here I see here:
1. Sources other than CRAN should be the exception, but are fine.
2. There is no general rule for switching sources to other than CRAN, it requires negotiation with at least two recipe maintainers.
3. Packages that follow a somehow fast changing API can be packaged from sources other than CRAN.
4. Drat is fine for the aws.* packages, but we don't decide anything else now.

Tagging the R package maintainers to get notified: @johanneskoester, @bgruening, @daler, @jdblischak, @cbrueffer

What do you think?

Thanks

Daniel

[0] https://github.com/conda-forge/r-aws.s3-feedstock
[1] https://github.com/cloudyr/aws.s3/issues/239
[2] https://github.com/cloudyr/aws.s3/issues/257

**Comment by dbast** [comment]
Thanks, for those two perspectives. I would express it a bit differently:
1. From a user perspective, I expect up-to-date and as stable/working as possible packages with a reproducible version and creation process. Which not necessarily means that conda-forge is only a compiled CRAN mirror. I also enjoy the easy installation of good/unique packages which cannot be or are not available on CRAN, e.g. because of crazy compile requirements.
2. From a maintainer perspective, there are in general so many mostly non-R packages (a bit over 1000) building from the release/archive mechanism of a github repo. That means ensuring quality happens by looking at the according repo, reading changelogs, issues etc. And the feedstock documents in a transparent reproducible way what is inside a package that can be downloaded and installed. The bot https://github.com/regro-cf-autotick-bot also supports the release/archive mechanism of a github repo, if a package is build from those. 

Isn't it the power of conda-forge to not be limited to pypi and cran? 

There are currently 13.3k pkgs on CRAN and maybe all in all 16.1k R pkgs, according to https://cran.r-project.org/web/packages/ and https://www.rdocumentation.org/

**Comment by dbast** [comment]
By inspecting the "dev" branch of https://github.com/conda-forge/cairo-feedstock, I just learned that uploading the newer not-yet-cran-uploaded versions of the cloudyr aws.* packages to conda-forge/dev would be also an option. The versions are also listed here https://anaconda.org/conda-forge/cairo/files and the user can decide what version to use.

That would mean for packages on CRAN, CRAN=main-label=feedstock-master-branch, newer-than-CRAN=dev-label=feedstock-dev-branch ... newer-than-cran does not necessarily that it is a bleeding edge version, can be still a maintainer released version.

There is a expectation mismatch if the cran/main version is less stable/working than the dev version.

**Comment by jdblischak** [comment]
@dbast I'm open to the possibility of using non-CRAN sources for R packages. My hope was to get some consensus from multiple maintainers on guidelines for handling this situation.

@bgruening @cbrueffer Are you ok with supporting non-CRAN versions of R packages on conda-forge? If yes, would you prefer these packages be labeled "main" or "dev"? Do you have any opinions on when this should should be used (e.g. Does the CRAN version have to be broken or just outdated? How long since the last CRAN release should we consider using a non-CRAN source for the package?)

**Comment by cbrueffer** [comment]
I think non-CRAN packages are fine, but the specifics may vary too much on a case-by-case basis to make general rules. E.g., in the `r-aws.s3` case it appears pretty clear that the non-CRAN package should be the canonical one. That requires a judgement call on a case-by-case basis though...

**Comment by mingwandroid** [comment]
CRAN does not serve as a good quality gate as far as macOS binaries are concerned.

**Comment by jdblischak** [comment]
@dbast There don't seem to be any strong objections. So I'd say that if there is a good reason for not using the CRAN package, and you're willing to maintain the recipe, then go ahead.

**Comment by dbast** [comment]
@jdblischak Sounds good. Thanks!

**Comment by jdblischak** [comment]
@dbast Could you please close this Issue now that we've reached a decision? Thanks!

**Comment by dbast** [comment]
Thanks for the reminder. Closing.
