### ISSUE TITLE
Upload noarch:generic to gcc7

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#674]
Now that some r packages are being built as noarch:generic, they are only uploaded to the main channel and not to gcc7. (Since there are no compilers involved, these packages are only uploaded to main)

How do we want to handle this? A cron job?

Btw, anybody know how to add a label using anaconda client? I can't seem to find it.

Tried the following, but it doesn't work.
```
anaconda copy --to-owner conda-forge --from-label main --to-label gcc8 conda-forge/r-heatmap3/1.1.1/noarch/r-heatmap3-1.1.1-r351_1001.tar.bz2
```

cc @conda-forge/core

**Comment by isuruf** [comment]
We could add a hack to the upload script to upload to both labels

**Comment by isuruf** [comment]
Here's a script that does that,
```python
import subprocess
import json
from binstar_client.utils import get_server_api
from conda_smithy.ci_register import anaconda_token

def get_packages(label):
    pkgs_json = json.loads(subprocess.check_output("conda search '*[channel={},subdir=noarch]' --json".format(label), shell=True))
    pkgs = []
    for _, data in pkgs_json.items():
        for pkg in data:
            pkgs.append((pkg['name'], pkg['version'], pkg['fn'])) 
    return set(pkgs)

all_pkgs = get_packages("conda-forge/label/main")
copied_pkgs = get_packages("conda-forge/label/gcc7")

site = "https://api.anaconda.org"
aserver_api = get_server_api(anaconda_token, site)

for pkg in all_pkgs - copied_pkgs:
    aserver_api.add_channel(
            "gcc7",
            "conda-forge",
            package=pkg[0],
            version=pkg[1],
            filename="noarch/"+pkg[2],
        )
```

**Comment by mariusvniekerk** [comment]
We have a script on regro we can run if needed that we ran prior to python landing

**Comment by mariusvniekerk** [comment]
Cc @scopatz

**Comment by dbast** [comment]
There are now lots of noarch R packages that are missing the gcc7 label with their latest version, e.g.:
```
r-broom
r-cli
r-knitr
r-lintr
r-remotes
r-rmarkdown
r-rstudioapi
r-sessioninfo
r-sparklyr
r-styler
r-tinytex
```

In lots of cases @bgruening added the gcc7 label ... thanks!

How to get those packages labeled ... any way to run the above script?

Long term will be via upload or the script via bot?

**Comment by scopatz** [comment]
The script is available at and is pretty robust https://github.com/regro/libcflib/blob/master/scripts/noarch-gcc7-relabel.xsh

**Comment by bgruening** [comment]
I would prefer that the bot is doing this. We are mostly done with the migration hopefully, but the next migration the bot should add both labels, imho.

@scopatz thanks for the link, I will try this one out.
@dbast all updated

**Comment by dbast** [comment]
Thanks!

**Comment by CJ-Wright** [comment]
@bgruening I'm hoping that the next migration we won't need multiple labels, maybe?

**Comment by bgruening** [comment]
You are an optimist @CJ-Wright :)

**Comment by jakirkham** [comment]
This use to be possible using [`channel_targets`]( https://github.com/conda-forge/conda-smithy/blob/a2c15f4075e62b7b578a85951d7f6771c549c195/conda_smithy/configure_feedstock.py#L273 ). Not sure if that is still viable.

**Comment by dbast** [comment]
@bgruening Some missing package labels for the latest versions:

```
r-callr
r-pillar
r-repr
```

**Comment by bgruening** [comment]
Fixed.

**Comment by jakirkham** [comment]
Going to close as what was in `gcc7` was moved to `main` today and what was in `main` previously is now in `cf201901`.
