### ISSUE TITLE
Guard against path_conflicts (avoid broken envs)

### ISSUE THREAD

**Issue by tjd2002** [conda-forge/conda-forge.github.io#686]
**Feature request: check packages for path conflicts in CI.**

If two packages in conda-forge have path conflicts (i.e. they install files at the same location), then they are capable of clobbering each other on install. This is likely to leave the environment corrupted even after the offending package is fixed and updated. (See for instance https://github.com/conda-forge/conda-forge.github.io/issues/684#issuecomment-447068018 )

Would it be desirable for CI to help to prevent this situation by checking the list of files installed by a package against the file list of all other packages in conda-forge?. It could issue an advisory comment on the PR about which other packages conflict. 

The check could be restricted to packages that might conceivably be co-installed, i.e. same arch (+noarch); latest version only. There should also be some mechanism for whitelisting expected conflicts, to avoid annoying developers.

Alternatively, this could be implemented as a QA check that is run occasionally by a bot, that then auto-files issues on feedstocks that are found to have conflicting files. I suppose one (I) could start just by looking at the files list at https://github.com/regro/libcflib and creating a report to see how widespread the issue is.

**Comment by scopatz** [comment]
I think using libcflib for this is a great idea!

**Comment by beckermr** [comment]
This is happening in artifact-validation and has been rolled into issue #https://github.com/conda-forge/conda-forge.github.io/issues/1189.

I am going to close this issue to clean things up.
