### ISSUE TITLE
Add tips and tricks section to the docs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#689]
There's various miscellaneous build knowledge that people ask about and it would be nice to collect and share this somewhere that isn't really `conda-build` knowledge, but is useful when building packages. For example, [this bit about fixing the CMake library install directory]( https://github.com/conda-forge/lapack-feedstock/blob/823a3c98b4cb5ce9fb8f91f5d46a7481de27c039/recipe/build.sh#L7 ) or [this MSBuild trick on AppVeyor]( https://github.com/conda-forge/libsodium-feedstock/blob/d605bef7327df45020fa69d10c8ae82deb4ab218/recipe/bld.bat#L9-L16 ). Having a "Tips and Tricks" section might be nice place to start listing these sorts of things. If we start accumulating a lot of them, we can always do a bit of reorganization to give them a bit more structure.

**Comment by croth1** [comment]
The new documentation has a
-  knowledge base section for maintainer tips & tricks: http://conda-forge.org/docs/maintainer/knowledge_base.html 
- tips & tricks section for non-developer user information: http://conda-forge.org/docs/user/tipsandtricks.html

I transitioned windows specific developer information from the old documentation to: `Knowledge Base -> Particularities on Windows` (http://conda-forge.org/docs/maintainer/knowledge_base.html#particularities-on-windows) 

Unfortunately, I have too little knowledge/context to include these two particular bits of information myself.

**Comment by jakirkham** [comment]
That already seems useful. Thanks again for all of your work on the docs. Hopefully people can fill in more details as needed. Let's close this out 🙂
