### ISSUE TITLE
Use Netlify to preview webpage changes

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#691]
To simplify the process for previewing changes made to the webpage in PRs here, we might consider using [Netlify]( https://www.netlify.com/ ). Here's a [nice example project]( https://github.com/jdillard/continuous-sphinx ) using Sphinx.

**Comment by ForgottenProgramme** [comment]
I'm taking this up, @viniciusdc.   :)

**Comment by ForgottenProgramme** [comment]
@jakirkham, @ocefpaf 

@viniciusdc helped me find this blog on how to integrate Netlify CI into a repository:
https://davidgarcia.dev/posts/previewing-documentation-in-pull-request/

It requires, 
1. Creating an account on Netlify. How are we going to do that? 
2. After making an account, we need to authorize the github account that contains the docs repository. 

Can I please have some pointers on how to proceed with this? 
Thanks. <3

**Comment by beckermr** [comment]
This will require a member of core.

**Comment by ForgottenProgramme** [comment]
@viniciusdc

**Comment by ocefpaf** [comment]
Maybe we can leave changes like those for once Outreachy starts to avoid requiring a core decision/action at this moment.

**Comment by ForgottenProgramme** [comment]
> Maybe we can leave changes like those for once Outreachy starts to avoid requiring a core decision/action at this moment.

@ocefpaf
Yes, I think that would be the right thing to do.

**Comment by ForgottenProgramme** [comment]
I will be working on integrating Netlify this week. 

I found this article on how we're supposed link our conda-forge.github.io repository to Netlify : https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/

Once that's done, we're supposed to activate 'Deploy Preview'

**Comment by ocefpaf** [comment]
> IIUC we can only use the deploy preview feature if we first host our docs on Netlify.

That will require a core meeting :-/

Maybe let's start with something that won't need a core meeting :smile:

**Comment by ForgottenProgramme** [comment]
Okay. :)
Putting this on hold.

**Comment by kathatherine** [comment]
@beckermr This should probably not include the "Outreachy" tag to avoid confusion, unless we want to have a Core meeting about it soon.

**Comment by beckermr** [comment]
done and agreed!

**Comment by jakirkham** [comment]
Maybe we could do this with a GHA

https://github.com/marketplace/actions/deploy-pr-preview

**Comment by beckermr** [comment]
this issue is completed.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-forge.github.io/pull/2072
