### ISSUE TITLE
conda-forge preventing installation of packages

### ISSUE THREAD

**Issue by NickMacro** [conda-forge/conda-forge.github.io#692]
Hello,

I recently encountered a problem that is documented in https://github.com/conda/conda/issues/8051.

It appears that removing and re-adding conda-forge to the list of channels in conda resolves the problem.  Just thought this might be useful information for your team.

Thank you for making such an excellent product.

**Comment by jakirkham** [comment]
Interesting. Thanks for the info. Let's close this and track that issue 🙂
