### ISSUE TITLE
Build compiler activation recipes in conda-forge

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#694]
Defaults is really slow in updating the compiler activation recipes even after sending PRs. Thoughts about building the compiler activation recipes ourselves?

cc @conda-forge/core, @mingwandroid

**Comment by msarahan** [comment]
If flags introduce a compatibility breaking change, it's really better to handle that change in concert with defaults. Forking this may seem easier in the short term to compensate for our lack of time or attention, but I think it will cause broader teeth gnashing by more people in the long run.

I think perspective is important: are we doing things for developers at the cost of users? I think the answer to that regarding this change is yes, but maybe I'm not totally understanding things.

**Comment by mingwandroid** [comment]
This flag shouldn't introduce any compatibility changes. Let's just build and release these.

**Comment by isuruf** [comment]
Can you take a look at https://github.com/AnacondaRecipes/aggregate/pull/115 as well?
