### ISSUE TITLE
Toolchain: Unsatisfiable dependencies for platform linux-64

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/conda-forge.github.io#699]
I have trouble to get the toolchain compilers to work: 
`Unsatisfiable dependencies for platform linux-64: {'toolchain==2.4.0=0', 'toolchain_cxx_linux-64', 'toolchain_c_linux-64'}`

https://circleci.com/gh/conda-forge/lammps-feedstock/179

Best,

Jan

**Comment by scopatz** [comment]
We have removed toolchain.  You should be able to update your recipe and rerender

**Comment by jan-janssen** [comment]
I tried, but it did not work: 

> Hi! This is the friendly automated conda-forge-webservice.
> 
> I tried to re-render for you, but it looks like there was nothing to do.

https://github.com/conda-forge/lammps-feedstock/pull/4

**Comment by jan-janssen** [comment]
So instead of using the label gcc - I am going to use the label main then? 
https://github.com/conda-forge/lammps-feedstock/pull/6 I have to admit I did not find many packages with MPI integration in conda-forge so I looked at https://github.com/conda-forge/mpi4py-feedstock for inspiration.

**Comment by scopatz** [comment]
The rerender bot's behavior can be modified in both conda-smithy and conda-forge-webservices. I have often thought it should report it's errors

**Comment by jan-janssen** [comment]
@xhochy Thanks - I opened a new pull request for this https://github.com/conda-forge/lammps-feedstock/pull/9
