### ISSUE TITLE
--no-deps line in meta.yamll

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-forge.github.io#700]
at https://github.com/conda-forge/conda-forge.github.io/blob/57bd4d0268dce505fb6f382a29764f984f10ba9e/docs/meta.html#L317

what is the --no-deps line that this is referring to?  The suggested pip install line does not have --no-deps.

**Comment by croth1** [comment]
This issue should be fixed now: http://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip
