### ISSUE TITLE
CircleCI test fail on permission denied on remote repos

### ISSUE THREAD

**Issue by StephanSiemen** [conda-forge/conda-forge.github.io#706]
Sorry, got stuck working on

  https://github.com/conda-forge/magics-feedstock

where builds on CircleCI (Linux) fail on master branch. On PRs the CI tests pass. Failures are not triggered by code compilation, but at the very beginning of the build process by a permission problem (see error message below) when trying to read from repo - I assume the 'magics-feedstock' one. Looks like a ssh key problem to me. The annoying side effect is that users get a pretty old magics version under Linux :-(

Is there anything I, as maintainer, can do or is this to do with the general setup of CircleCI?

Thanks
@StephanSiemen 

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

**Comment by scopatz** [comment]
try this: https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-update-circle

**Comment by StephanSiemen** [comment]
Tests are now running. Thanks
