### ISSUE TITLE
Package -> Feedstock mapping

### ISSUE THREAD

**Issue by epruesse** [conda-forge/conda-forge.github.io#711]
(moved from https://github.com/conda-forge/staged-recipes/issues/7714)

It would be great if there was a way to find the feedstock repo given a package name. Since this information is conda-forge specific, it will never be included on the `conda` side of things.

Incidentally, there is a discrepancy on the website - the `Packages` link really displays `Feedstocks`.

**Comment by scopatz** [comment]
I believe that you can find this info in [libcflib](https://github.com/regro/libcflib) and [libcfgraph](https://github.com/regro/libcfgraph)

**Comment by scopatz** [comment]
And PRs welcome if you want to change anything about how this works

**Comment by epruesse** [comment]
Well - I could download that whole massive thing and traverse the `parent_recipe` in the `json` files, true. I was just hoping that there might be a step inside of CF pipeline where it's trivial to export that data. It would also allow to have a `package` list here that points to the `feedstocks`, rather than just listing the feedstocks. With `outputs` seeing more use, the distinction has become relevant.

FYI: My use case is the link-out to CF from the Bioconda package docs (e.g. https://bioconda.github.io/recipes/arb-bio/README.html) - some of the CF links work, but some lead to 404 because the feedstock has a name different from the package.

**Comment by scopatz** [comment]
Well, you don't have to download libcflib.  This is definitely in alpha, but we provide a hosted version of `python -m libcflib.rest` at http://35.192.108.152.  This is what is used in the `elm-src/` dir in this repo to power the search and artifact views on conda-forge.org.  So you can do something like the following to get an artifact JSON.

```
$ curl "http://35.192.108.152/artifact?pkg=rever&channel=conda-forge&arch=linux-64&name=rever-0.2.3-py36_0.json"
```

**Comment by scopatz** [comment]
Actually, unfortunately, it might only be in https://github.com/regro/cf-graph3 in the graph.pkl object.  We haven't finished migrating that data yet. @CJ-Wright would know more

**Comment by epruesse** [comment]
While the `graph.pkl` at 22MB is quite manageable, it does contain references to types I can't easily load. `frozendict` is ok, but there is no package containing `conda_forge_tick` as far as I can tell?

**Comment by scopatz** [comment]
`conda_forge_tick` lives in https://github.com/regro/cf-scripts

**Comment by epruesse** [comment]
Well, yes - I can `pip install` it. But I'd prefer to have only `conda install`ed things in the docker container building our docs.

**Comment by scopatz** [comment]
Yep, these are common issues I have with the way cf-scripts works right now.  Any help is most appreciated!

**Comment by scopatz** [comment]
Even just switching the graph.pkl over to a JSON format would be a huge help and should be relatively easy to do in cf-scripts

**Comment by CJ-Wright** [comment]
I would gladly merge a cf-scripts-feedstock!

**Comment by jakirkham** [comment]
Are there issues for these over at cf-scripts?

**Comment by CJ-Wright** [comment]
Their might be an issue for the json translation I'm not sure about the package part

**Comment by jakirkham** [comment]
I wonder if we could populate some of the relevant webpage content in each feedstock's repo. This way it could be made available in the listing, but the main listing wouldn't need to track it all.

**Comment by CJ-Wright** [comment]
Can you expand on that some? What data do you want to see?

**Comment by jakirkham** [comment]
I'm mostly thinking of the OP's question. How do we include useful info about packages in feedstocks on the webpage.

Am mostly thinking of content conda-smithy might add during a re-render since it is already passing over the recipe data and committing to the feedstock.

**Comment by beckermr** [comment]
We have the conda-forge/feedstock-outputs repo now that stores this master mapping for all of conda-forge. I am closing this issue.

**Comment by jakirkham** [comment]
We'd discussed having a link to the recipe added to Anaconda.org at one point as well. Maybe this is something else we should consider?

cc @chenghlee

**Comment by beckermr** [comment]
Let's make a new issue somewhere to track this.

**Comment by jakirkham** [comment]
We do already just have to find it 😄

**Comment by jakirkham** [comment]
https://github.com/conda/conda-build/issues/2462
