### ISSUE TITLE
Prototype of restructured documentation

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#713]
In the last days, I made efforts prototyping a more organised structure for our documentation. I have now finished migrating all the current content into the new shape and would be happy to receive feedback.

You can access the restructured version here: 

https://cf-docs-restructure.readthedocs.io/en/docs_restructure/

There are a couple of things that still need to be filled with content and probably a lot of room for improvement.

**Comment by scopatz** [comment]
Excellent! Looking forward to a PR here

**Comment by croth1** [comment]
Since merging this would not do an incremental update but rather completely replace the existing documentation, I think there are a couple of things we should discuss:

- Is this widely considered to be an improvement over the existing docs?
- Are there important things missing that suggest more restructuring?
- Do we first want to fill all the remaining gaps before we replace the old docs, or do we want to merge it and then keep filling the gaps.

**Comment by croth1** [comment]
The new documentation is available since #718
