### ISSUE TITLE
CMake is finding GCC when building in Windows with `-G "Ninja"` in Azure Pipelines

### ISSUE THREAD

**Issue by tadeu** [conda-forge/conda-forge.github.io#714]
This [recipe](https://github.com/conda-forge/cminpack-feedstock/pull/3) is building in [AppVeyor](https://ci.appveyor.com/project/conda-forge/cminpack-feedstock/builds/22463152), but is [failing in Azure Pipelines (win64)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=14181&view=logs&jobId=2cc45e14-23e3-52d7-b33a-8c2744410b97):

```
%SRC_DIR%>SET "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"  

%SRC_DIR%>CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcvarsall.bat" amd64  
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe -- broken
CMake Error at D:/bld/cminpack_1550515875602/_build_env/Library/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/ProgramData/chocolatey/bin/gcc.exe"

  is not able to compile a simple test program.
```

**Comment by scopatz** [comment]
Azure cmake windows builds are a known failure right now

**Comment by thewtex** [comment]
Here is how we address this for ITK:

https://github.com/InsightSoftwareConsortium/ITK/blob/54cec2ae1bf5c7fcdf36804b7f6417d7d0f2a943/Testing/ContinuousIntegration/AzurePipelinesWindows.yml#L38-L41

https://github.com/InsightSoftwareConsortium/ITK/blob/54cec2ae1bf5c7fcdf36804b7f6417d7d0f2a943/Testing/ContinuousIntegration/AzurePipelinesWindows.yml#L45-L46

HTH

**Comment by tadeu** [comment]
Interesting, but AFAIK, `conda build` should already call the correct `vcvars` script :/

**Comment by scopatz** [comment]
CC @mariusvniekerk

**Comment by tadeu** [comment]
related https://github.com/conda-forge/staged-recipes/issues/7715

**Comment by thewtex** [comment]
In addition to sourcing `vcvars`, the compiler should be explicitly specified for CMake.  This is possible with `-DCMAKE_CXX_COMPILER=cl.exe` and `-DCMAKE_C_COMPILER=cl.exe` or setting the standard environmental variables `CC=cl.exe`, `CXX=cl.exe`.

**Comment by jakirkham** [comment]
Is this issue still live? Any examples of current problems? If not, maybe we should close it out. Thoughts? 🙂

**Comment by tadeu** [comment]
The issue seems fixed (probably on Azure side), I've temporarily [changed the recipe with the original problem](https://github.com/conda-forge/cminpack-feedstock/pull/9) to use Ninja again, and it is working! Feel free to close it.

**Comment by jakirkham** [comment]
Ok good to know. Thanks for the update.
