### ISSUE TITLE
URL for Artifactory remote repository

### ISSUE THREAD

**Issue by hrzafer** [conda-forge/conda-forge.github.io#716]
Hi,

In my organization, we can only download conda packages within our network. We use Artifactory and create proxy remote repositories to access packages outside our network. On Artifactory, we can simply create a proxy repo and point it to https://repo.continuum.io/pkgs/main/. Then Artifactory fetches and caches the requested packages. 

Is there a similar URL for conda-forge packages? We'd like to create another remote proxy repo for conda-forge as well.

Thanks

**Comment by isuruf** [comment]
https://conda.anaconda.org/conda-forge

**Comment by hrzafer** [comment]
@isuruf That URL does not provide a regular conda repository structure. It should contain sub folders for different platforms and there should be `repodata.json` inside each platform specific folder.

Something like that:

```
https://repo.continuum.io/pkgs/main/
	https://repo.continuum.io/pkgs/main/linux-64/
		repodata.json	7.1 MB	2019-02-20 19:29:58 +0000	38cb5870cf49edde1be99aacad9f45da
		package-01.tar.bz2
		package-02.tar.bz2
		...
	https://repo.continuum.io/pkgs/main/win-64/
		repodata.json	7.1 MB	2019-02-20 19:29:58 +0000	38cb5870cf49edde1be99aacad9f45da
		package-01.tar.bz2
		package-02.tar.bz2
		...
	https://repo.continuum.io/pkgs/main/linux-ppc64le/
		repodata.json	7.1 MB	2019-02-20 19:29:58 +0000	38cb5870cf49edde1be99aacad9f45da
		package-01.tar.bz2
		package-02.tar.bz2
		...
```

**Comment by isuruf** [comment]
Are you saying that the URL doesn't have subfolders and repodata.json?

**Comment by jakirkham** [comment]
For example, here's the `linux-64` packages for conda-forge.

ref: https://conda.anaconda.org/conda-forge/linux-64/

**Comment by hrzafer** [comment]
@isuruf when I click on your link it directs me to https://anaconda.org/conda-forge/repo?type=conda&label=main. That was why I couldn't see it as a web directory.

@jakirkham When I click on the link you send, and manually delete the /linux-64, I am able to see what I want. 

Thanks both of you guys.

**Comment by oscar6echo** [comment]
The remote url https://conda.anaconda.org/conda-forge does work for me too.  

However it should be pointed out that Artifactory web interface has a misleading though not critical bug.  
For the correct url: The **Test** button displays a pop up: _"Connection failed: Error 404: Not Found"_.
For the  **wrong** remote url https://anaconda.org/conda-forge it shows_"Success etc".

Beware !

**Comment by Jose-Matsuda** [comment]
Apologies for commenting on an older issue but is https://conda.anaconda.org/conda-forge/ still accurate for this? I've been able to use the original url https://repo.anaconda.com/pkgs/main fine and install packages but cannot say the same for https://conda.anaconda.org/conda-forge/ .
