### ISSUE TITLE
Document CDT/yum_requirements best practices

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#717]
Basically in the case of things like `mesa-libGL`, we still need them in `yum_requirements.txt` and as a CDT. Please correct me if I have misunderstood this @mingwandroid.

ref: https://github.com/conda-forge/gstreamer-feedstock/pull/22/files#r250954664

**Comment by croth1** [comment]
I have recently added a section regarding mesa-libGL to the restructured docs: https://cf-docs-restructure.readthedocs.io/en/docs_restructure/maintainer/knowledge_base.html#libgl. Would be nice if you could also proof read and check for conceptual errors.

**Comment by jakirkham** [comment]
For `libxfixes`, we can just use the conda-forge packge [`xorg-libxfixes`]( https://github.com/conda-forge/xorg-libxfixes-feedstock ).

**Comment by croth1** [comment]
The updated version is now in the real docs and uses the `xorg-libxfixes` conda-forge package : http://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
