### ISSUE TITLE
Add mergify bot to the organization

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/conda-forge.github.io#722]
https://mergify.io/ is a new web service that automatically merges PRs after CIs are green.

Given the very, very long queues in conda-forge (especially in Appveyor), I think it'd be really handy to add this service to the organization. Else, we have to remember to manually merge PRs for two days or more, and sometimes we forget to do it (it's happened to me a couple of times).

**Comment by CJ-Wright** [comment]
My biggest question is logistical. How do we register all our current and future feedstocks with mergify?

**Comment by isuruf** [comment]
There's an option to register all current and future feedstocks.

**Comment by isuruf** [comment]
There's also https://github.com/phstc/probot-merge-when-green which doesn't require a configuration file per repo

**Comment by CJ-Wright** [comment]
Hmm maybe they'll support Azure soon?

**Comment by isuruf** [comment]
Does mergify support github checks? Circleci and Appveyor only support statuses and Azure supports only checks. (Travis supports both)

I think it's not hard to write our own script in conda-forge-webservice to do this.

**Comment by beckermr** [comment]
The github actions give us a nice way to do this now. We have an open issue to make it work off of automerge labels and it works now for bot updates.

**Comment by jakirkham** [comment]
This works off automerge labels now. Just add an automerge label to the feedstock PR and a bot will merge it once CI passes.
