### ISSUE TITLE
ReadTheDocs is out of sync

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/conda-forge.github.io#735]
It seems the ReadTheDocs version of the documentation is out of sync. At the very least it is missing the changes from #730, see [here](https://conda-forge.readthedocs.io/en/latest/meta.html#packaging-the-license-manually) and [here](http://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=packaging%20license#packaging-the-licence-manually).

**Comment by croth1** [comment]
The RTD version is ancient. IMO we should take it down. I see little point hosting the documentation twice.

**Comment by scopatz** [comment]
I agree, we should take it down. Don't know who put it up though...

**Comment by brainwane** [comment]
It might be worth asking Read the Docs to follow their [policy for abandoned RtD projects](https://docs.readthedocs.io/en/stable/abandoned-projects.html) on this.

**Comment by jakirkham** [comment]
Mostly what we wanted was a redirect to the current docs. Deleting would just allow name squatters to grab it, which would be bad. Unfortunately that was a bit annoying to get working correctly. I think we have sorted that out now though.
