### ISSUE TITLE
AppVeyor continuing to run on some noarch feedstocks

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-forge.github.io#736]
I am seeing an issue where AppVeyor continues to run even after a rerender on some `noarch` feedstocks.  It always fails, leading to an incorrect red x on all commits and merges.  Here are two example feedstocks where this is happening:
https://github.com/conda-forge/pyevtk-feedstock/pull/1
https://github.com/conda-forge/python-slugify-feedstock/issues/12

**Comment by jakirkham** [comment]
Thanks @xylar.

I looked at both of these and they did not have the "Skip branches without appveyor.yml" checkbox checked in the AppVeyor settings. This is normally done by conda-smithy automatically when converting a recipe to a feedstock in `staged-recipes`. Have gone ahead and manually checked these boxes.

That said, it would be good to readd both of these recipes as is through `staged-recipes`. This should fix any other settings that might be similarly off.

cc @sodre (for awareness about python-slugify)

**Comment by xylar** [comment]
Thanks @jakirkham.  I've re-added pyevtk and it does, indeed, seem to have resulted in cleaner results.  You could either close this or wait for a response from the `python-slugify` developers, I'll leave that up to you.

**Comment by jakirkham** [comment]
Thanks @xylar. Let's go ahead and close.

@sodre, if you still have issues with `python-slugify`, please let us know. 🙂
