### ISSUE TITLE
Make package listing more prominent on the webpage

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#74]
Would be nice to have a link at the top near "ABOUT" and "CONTRIBUTE" that says something like "PACKAGES" that links to the package listing. Seems this get buried a bit now. With nearly 200 packages, we should be advertising that so people can see the extent immediately or those looking for it can get there quickly.

**Comment by pelson** [comment]
:+1:
I might be tempted to do #39 at the same time.

**Comment by jakirkham** [comment]
Sure, however you want to do it.

Note we quickly went over 200 packages. Things are heating up. :smile:

**Comment by jakirkham** [comment]
Can you believe it has been only 10 days and now we have over 300 packages?! This is amazing.

**Comment by jakirkham** [comment]
Added by @janschulz in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/152 ).
