### ISSUE TITLE
Updated NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [conda-forge/conda-forge.github.io#747]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-conda-forge/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by croth1** [comment]
Thanks @lisamartin72, I sent you an email to lisa@numfocus.org to double-check this request!
