### ISSUE TITLE
selecting text on chrome

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-forge.github.io#75]
When I select text on the website (e.g. the config addition), there is no selection marker (-> no blue background), but it seems the text is selected and is copy-abel (sp?).

It would be nice to get a visual response when I want to copy something.

**Comment by jcb91** [comment]
Although the non-styled selection might be useful/necessary for some things, I think it's a reasonable assumption that anything in a `code` tag should probably not be subject to this...

**Comment by jakirkham** [comment]
Believe this is fixed by PR ( https://github.com/conda-forge/conda-forge.github.io/pull/186 ). Reopen or re-raise if this is not the case.
