### ISSUE TITLE
conda-forge.org/docs/recipe.html page missing

### ISSUE THREAD

**Issue by thewtex** [conda-forge/conda-forge.github.io#750]
> Sorry, the page you were looking for does not exist.

Is returned for:

https://conda-forge.org/docs/recipe.html

which is a link here:

https://conda-forge.org/#contribute

**Comment by scopatz** [comment]
Thanks Matt, where is the link from? We restructured the docs

**Comment by thewtex** [comment]
I confirmed that the link is fixed here: https://conda-forge.org/#contribute - thanks @scopatz !
