### ISSUE TITLE
Requesting to be added as a maintainer of google-cloud-bigquery-storage-feedstock

### ISSUE THREAD

**Issue by tswast** [conda-forge/conda-forge.github.io#764]
I maintain the google-cloud-bigquery-storage package (https://github.com/googleapis/google-cloud-python/tree/master/bigquery_storage), and I'd like to ensure the conda packages stay up to date.

I've submitted https://github.com/conda-forge/google-cloud-bigquery-storage-feedstock/pull/1 to be added as a maintainer, but no response by the existing maintainer.

**Comment by isuruf** [comment]
Done.
