### ISSUE TITLE
After installing cuda with anaconda, the nvcc -V command does not work

### ISSUE THREAD

**Issue by ma3252788** [conda-forge/conda-forge.github.io#775]
Expected Behaviour
if I type: nvcc -V
it should be the correct version

Actual Behaviour
No matter what version of cuda I install, using the nvcc -V command will get the same version.

Steps to Reproduce
1 Install anaconda
2 Create an environment pytorch
3 activation environment
4 install pytorch, conda install pytorch-gpu
5 View the cuda version using the nvcc -V command
6 change the cuda version, conda install cudatoolkit=9.2
No matter how I change the cuda version, when I use nvcc -V, the display is 9.0

ST3, Anaconda and OS versions
4.5.4

**Comment by ma3252788** [comment]
Like this picture, after I installed cuda, I used nvcc -V and I didn't get anything.
![](https://camo.githubusercontent.com/3eb627d5b3ce5b06d6715e367e65abb188cd7254/687474703a2f2f66696c6573736c2e6d616368756e6a69652e636f6d2f626c6f672f66696c652f32303139303432323134343131362e706e67)

**Comment by croth1** [comment]
Hi @ma3252788,

We do not package any GPU packages here at conda-forge, so this is not the right bug tracker for your issue. I think this is the right place: https://github.com/ContinuumIO/anaconda-issues/issues.
