### ISSUE TITLE
Guidance for build numbers

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/conda-forge.github.io#779]
It looks like a lot of packages started using a build number of >=1000 when they switched to the new compiler stack.  Is that an official convention?  Should I strive to keep that convention in the packages I help maintain?

For instance, today I merged https://github.com/conda-forge/librdkafka-feedstock/pull/30, which reset the build number from `1002` to `0`.  Was that a bad thing to do?

**Comment by isuruf** [comment]
If you are building a new version that hasn't been built before then resetting to 0 is the correct thing. Otherwise increase the build number.

**Comment by stuarteberg** [comment]
Gotcha.  Thanks!
