### ISSUE TITLE
conda update --all tries to update zstd above the pin.

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge.github.io#781]
When formerly unpinned packages get pinned, the solver can get confused. Currently this happens with `zstd`. When I run `conda update --all`, the solver tries to update zstd from the pinned version 1.3.3 to version 1.3.8 and in turn has to downgrade everything depending on zstd to versions that did not have zstd pinned.

```
[...]
  zstd                                              1.3.3-1 --> 1.3.8-ha9f0a20_1003

The following packages will be DOWNGRADED:

  arrow-cpp                           0.13.0-py36ha71616b_0 --> 0.12.1-py36h2ddd891_0
  libprotobuf                              3.7.1-hfbae3c0_0 --> 3.6.1-hd9629dc_1001
  libtiff                              4.0.10-h344961e_1002 --> 4.0.10-h79f4b77_1001
  pyarrow                             0.13.0-py36hb37e6aa_0 --> 0.12.1-py36hf9e6f3b_0
```

Is there any way to prevent this behaviour?

**Comment by scopatz** [comment]
I think when you can install zstd you can pin the version you want to use.

**Comment by croth1** [comment]
Ah, I didn't think about this. That's a good idea. There are docs here: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning

**Comment by scopatz** [comment]
Yeah that's it
