### ISSUE TITLE
Scipy 2019 attendees

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#791]
On the dev call today (2019-05-29) it was suggested that we keep a list of who is going to SciPy 2019 this year and that we should track it here on this issue tracker. 

Activities at scipy
* Team dinner?
* BOF submitted
* Sprint submitted
* Any talks?
* Tools plenary -- yes, proposal was accepted

Confirmed attendees
* @scopatz 
* @ocefpaf 
* @mariusvniekerk 
* @mwcraig 
* @jakirkham
* @ericdill 
* @loriab 

[edit] NOTE: Please edit this issue with updates, it may become unwieldy to make the events + the attendees a series of patches on the original post :)

**Comment by ocefpaf** [comment]
Activities:

- BoF: applied, waiting for a confirmation
- Sprint: applied and confirmed
- Lunch/Dinner dates:

**Comment by ocefpaf** [comment]
Ping @conda-forge/core, @conda-forge/staged-recipes, and @conda-forge/r.

**Comment by SylvainCorlay** [comment]
I won't be attending scipy, but from the @QuantStack team, @wolfv will be there. Might be interesting to talk about `mamba`.

**Comment by wolfv** [comment]
Yep, I'll be there! Looking forward to meet the conda-forge team!

**Comment by CJ-Wright** [comment]
Can I close this?

**Comment by ocefpaf** [comment]
> Can I close this?

Time to setup up a 2020 one ;-p

**Comment by CJ-Wright** [comment]
I'd be happy to keep this perma open with a title of Scipy attendees, but I thought I'd try to cut down the issues and clean house, esp. if we are tweeing out requests for help.

**Comment by ocefpaf** [comment]
> I'd be happy to keep this perma open with a title of Scipy attendees, but I thought I'd try to cut down the issues and clean house, esp. if we are tweeing out requests for help.

Oh no. Let's do a new one when the time comes.

**Comment by msarahan** [comment]
Yeah, then we look more productive!
