### ISSUE TITLE
Dirty cache on Azure Windows builds leads to build failures

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-forge.github.io#798]
In the Azure Windows builds, we see continuous failing builds due to 

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/win-64/vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2'.
  download saved to: C:\Miniconda\pkgs\vs2015_win-64-14.0.25420-h55c1224_10.tar.bz2
  expected md5 sum: dfe2f62e921307f44e554b7c47aee31f
  actual md5 sum: 41f6a336e854ee8df80f70574d9b7883
```

See e.g. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=42146&view=logs

As per https://github.com/ContinuumIO/anaconda-issues/issues/11004#issuecomment-502115069 this should have been fixed on the Anaconda side but still pop up in our builds. Do we have a cache on Azure DevOps that we can clear or is there somewhere a tainted intermediate?

**Comment by jakirkham** [comment]
Is this still occurring?

**Comment by xhochy** [comment]
No, haven't see this for a long time.
