### ISSUE TITLE
ppc64le builds failing on Travis

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-forge.github.io#806]
@conda-forge/arm-arch 

Build on Travis currently all fail with 

```
Status: Downloaded newer image for condaforge/linux-anvil-ppc64le:latest
standard_init_linux.go:185: exec user process caused "exec format error"
The command "if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi" exited with 1.
``` 

Workaround is to use Azure but that is just a workaround as builds will then be emulated.

**Comment by isuruf** [comment]
Can you link a log?

**Comment by xhochy** [comment]
See here https://travis-ci.com/conda-forge/grpc-cpp-feedstock/builds/118692907

The problem is that this machine is x86

**Comment by isuruf** [comment]
Travis-CI.com doesn't support ppc64le, only Travis-CI.org does

**Comment by xhochy** [comment]
Ah, this was confusing me. There is also a successful travis-ci.org build on that commit that I didn't see as it succeeded.

**Comment by xhochy** [comment]
Do we know where these travis-ci.com come from and how to disable them?

**Comment by CJ-Wright** [comment]
Is there a way to disable travis-ci.com?

**Comment by jakirkham** [comment]
That’s probably not the right direction. `.org` has been deprecated.
