### ISSUE TITLE
Cannot install clickhouse-driver

### ISSUE THREAD

**Issue by ghuname** [conda-forge/conda-forge.github.io#818]
Hi,

as it is described on https://anaconda.org/conda-forge/clickhouse-driver I tried to install clickhouse-driver, but with no success.

```
(base) C:\Users\user>conda install -c conda-forge clickhouse-driver
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\user\Miniconda3

  added / updated specs:
    - clickhouse-driver


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.9                |           py37_0         3.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

  clickhouse-driver  conda-forge/win-64::clickhouse-driver-0.0.20-py37_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.5.15-0 --> conda-forge::ca-certificates-2019.6.16-hecc5488_0
  certifi               pkgs/main::certifi-2019.6.16-py37_0 --> conda-forge::certifi-2019.6.16-py37_1

The following packages will be SUPERSEDED by a higher-priority channel:

  conda                                           pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1c-he774522_1 --> conda-forge::openssl-1.1.1c-hfa6e2cd_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.7.9          | 3.0 MB    | ############################################################################ | 100%

InvalidArchiveError('Error with archive C:\\Users\\user\\Miniconda3\\pkgs\\conda-4.7.9-py37_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink (errno=22, retcode=-25, archive_p=2395210200784)')


(base) C:\Users\user>
```

What should I do?

Regards.

**Comment by xhochy** [comment]
This seems to be a problem with an installation of `conda`, not `clickhouse-driver`. Can you check whether the installation works in a separate environment and not in `base`?

**Comment by ghuname** [comment]
Hi,

I tried to create new environment, but while doing it, I was informed that a new version of conda is available. I stopped creation of new environment, and I run miniconda upgrade process.
After upgrade has finished, by executing "conda install -c conda-forge clickhouse-driver" I was able to install clickhouse_driver with no problem.


```
(base) C:\Users\user>conda create --name test
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.9
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda

```
Thanks for pointing out to me that it could be a conda problem.

Best regards.

**Comment by CJ-Wright** [comment]
Can we close this issue?

**Comment by brando90** [comment]
> Hi,
> 
> I tried to create new environment, but while doing it, I was informed that a new version of conda is available. I stopped creation of new environment, and I run miniconda upgrade process.
> After upgrade has finished, by executing "conda install -c conda-forge clickhouse-driver" I was able to install clickhouse_driver with no problem.
> 
> ```
> (base) C:\Users\user>conda create --name test
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.7.9
>   latest version: 4.7.10
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> ```
> 
> Thanks for pointing out to me that it could be a conda problem.
> 
> Best regards.

How did you made your update work? I ran the command you suggested:

```
conda update -n base -c defaults conda
```

but got a similar error to you:

'''
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/ruamel_yaml-0.15.87-py36h1de35cc_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652196284928)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/tqdm-4.40.2-py_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652203294208)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/dask-core-2.9.0-py_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652196284928)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/chardet-3.0.4-py36_1003.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652196443136)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/python-3.6.9-h359304d_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652203294208)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/conda-package-handling-1.6.0-py36h1de35cc_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652203294208)',)
InvalidArchiveError('Error with archive /Users/brandomiranda/miniconda3/pkgs/conda-4.8.0-py36_1.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nUnrecognized archive format (errno=79, retcode=-30, archive_p=140652243754496)',)
'''

I also tried re-installing mini conda but it didn't work either...unsure what to do next...

**Comment by xhochy** [comment]
@brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.

**Comment by brando90** [comment]
> @brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.

Thanks for the quick reply. I thought I did that already but I will try again.

Just to double+triple check, its using this link right?

https://docs.conda.io/en/latest/miniconda.html

I used the dmg last time. Will try again. If it fails I will use their bash thing or install the larger conda...

**Comment by xhochy** [comment]
> > @brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.
> 
> Thanks for the quick reply. I thought I did that already but I will try again.
> 
> Just to double+triple check, its using this link right?
> 
> https://docs.conda.io/en/latest/miniconda.html
> 
> I used the dmg last time. Will try again. If it fails I will use their bash thing or install the larger conda...

Yes, this is the right one. I normally use the bash one. It is probably best to wipe out the existing one first to make sure that no traces of the existing, broken files are present.

**Comment by brando90** [comment]
> > > @brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.
> > 
> > 
> > Thanks for the quick reply. I thought I did that already but I will try again.
> > Just to double+triple check, its using this link right?
> > https://docs.conda.io/en/latest/miniconda.html
> > I used the dmg last time. Will try again. If it fails I will use their bash thing or install the larger conda...
> 
> Yes, this is the right one. I normally use the bash one. It is probably best to wipe out the existing one first to make sure that no traces of the existing, broken files are present.

Sorry bothering you more, but since I already tried this once I wanted to double-check I'm doing this right. Is the only folder I need to delete the following?

```
rm -r /Users/brandomiranda/opt/miniconda3
```

**Comment by xhochy** [comment]
> > > > @brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.
> > > 
> > > 
> > > Thanks for the quick reply. I thought I did that already but I will try again.
> > > Just to double+triple check, its using this link right?
> > > https://docs.conda.io/en/latest/miniconda.html
> > > I used the dmg last time. Will try again. If it fails I will use their bash thing or install the larger conda...
> > 
> > 
> > Yes, this is the right one. I normally use the bash one. It is probably best to wipe out the existing one first to make sure that no traces of the existing, broken files are present.
> 
> Sorry bothering you more, but since I already tried this once I wanted to double-check I'm doing this right. Is the only folder I need to delete the following?
> 
> ```
> rm -r /Users/brandomiranda/opt/miniconda3
> ```

yes

**Comment by brando90** [comment]
> > > > > @brando90 Looks like in your case, your base miniconda3 installation is broken. You can either try to delete the above files and separately update `libarchive` but I guess it will be more time-efficient for you to re-install the latest miniconda.
> > > > 
> > > > 
> > > > Thanks for the quick reply. I thought I did that already but I will try again.
> > > > Just to double+triple check, its using this link right?
> > > > https://docs.conda.io/en/latest/miniconda.html
> > > > I used the dmg last time. Will try again. If it fails I will use their bash thing or install the larger conda...
> > > 
> > > 
> > > Yes, this is the right one. I normally use the bash one. It is probably best to wipe out the existing one first to make sure that no traces of the existing, broken files are present.
> > 
> > 
> > Sorry bothering you more, but since I already tried this once I wanted to double-check I'm doing this right. Is the only folder I need to delete the following?
> > ```
> > rm -r /Users/brandomiranda/opt/miniconda3
> > ```
> 
> yes

Weird I found another conda in my computer! I wonder if the new OS Catalina is whats causing me these issues...

location:

```
(base) brandomiranda~ ❯ sudo rm -rf /Users/brandomiranda/miniconda3/
```

also, weird it only allowed me to sudo delete it... :/

**Comment by brando90** [comment]
weird something is definitively wrong with my installation, now it complains that it can't find the conda command in the right place (although it seems to know about the command):

```
(base) brandomiranda~ ❯ conda
conda:2: no such file or directory: /Users/brandomiranda/miniconda3/bin/conda
```

**Comment by brando90** [comment]
Ok the problem of how it knows about the conda command even though it's installed in a different place was solved by removing conda code added to my `.bash_profile`. An older version of conda must have installed it. Now I removed that AND conda files at `/Users/brandomiranda/opt/miniconda3` so I have no conda.

I tried again with the dmg installer and now it installed its stuff to:

```
/Users/brandomiranda/opt/miniconda3
```

however, it doesn't know about the conda command yet. Is that suppose to happen? Seems odd to me.  Perhaps I will try the bash installer this time...

**Comment by brando90** [comment]
To install with bash do:

Set permissions for where the installer is at:
```
chmod +x Miniconda3-latest-MacOSX-x86_64.sh
```

then run the installer:
```
./Miniconda3-latest-MacOSX-x86_64.sh
```

----

Ok that at least installed the conda command "properly" but it doesn't seem that conda its working properly yet unfortuantely, idk why. See new error messages:

```
(base) brandomiranda~ ❯ conda create -n automl python=3.7

NotWritableError: The current user does not have write permissions to a required path.
  path: /Users/brandomiranda/.conda/envs/.conda_envs_dir_test
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /Users/brandomiranda/.conda/envs/.conda_envs_dir_test

In general, it's not advisable to use 'sudo conda'.
```

**Comment by brando90** [comment]
great, another weird error:
```
(base) brandomiranda~ ❯ sudo chown 501:20 /Users/brandomiranda/.conda/envs/.conda_envs_dir_test
chown: /Users/brandomiranda/.conda/envs/.conda_envs_dir_test: No such file or directory
```

**Comment by brando90** [comment]
Sorry for the spam @xhochy, but was the way you installed Conda as follows when using bash:
```
$ chmod +x Miniconda3-latest-MacOSX-x86_64.sh
$ ./Miniconda3-latest-MacOSX-x86_64.sh
```
or how do you recommend installing miniconda?

**Comment by brando90** [comment]
I guess the only thing left to try is to install the full anaconda if some variant of the above does not work...

I read on the other issue something about installing with sudo causing problems...but I didn't do that but idk if using that chmod command before hand causes unforsee issues...

**Comment by brando90** [comment]
> was my problem caused by the following two commands?
> 
> ```
> $ chmod +x Miniconda3-latest-MacOSX-x86_64.sh
> $ ./Miniconda3-latest-MacOSX-x86_64.sh
> ```

seems the right command is:

```
bash Miniconda3-latest-MacOSX-x86_64.sh
```

the install instruction on a different webpage...alas:

https://conda.io/projects/conda/en/latest/user-guide/install/macos.html

thought I still get issues:

```
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: | WARNING conda.core.path_actions:verify(963): Unable to create environments file. Path not writable.
  environment location: /Users/brandomiranda/.conda/environments.txt

done
Executing transaction: | WARNING conda.core.envs_manager:register_env(52): Unable to register environment. Path not writable or missing.
  environment location: /Users/brandomiranda/miniconda3/envs/myenv
  registry file: /Users/brandomiranda/.conda/environments.txt
done
```

**Comment by brando90** [comment]
test installation by creating an env with the command: 
```
$ conda create -n myenv python=3.6
```
