### ISSUE TITLE
New Feedstocks do not run CI initially

### ISSUE THREAD

**Issue by saraedum** [conda-forge/conda-forge.github.io#828]
When a new feedstock is created after a merge in staged-recipes, the CI does not run. Adding an empty commit on the feedstock seems to be a workaround.

You can see this e.g. here: https://github.com/conda-forge/4ti2-feedstock/commits/master

The two initial commits do not have the CI connected. Only the following manual commit got a CI run.

**Comment by lesteve** [comment]
We saw the same thing in https://github.com/conda-forge/tinyxml-feedstock/commits/master and https://github.com/conda-forge/urdfdom_headers-feedstock/commits/master.

**Comment by jakirkham** [comment]
Is this still an issue? If so, could you please point us to an example where it is still happening? If not, maybe we should close it out.

**Comment by lesteve** [comment]
I believe this was fixed at the time so I am going to close it.

**Comment by lesteve** [comment]
Actually I was not the one who created this issue, so someone else should close it.

**Comment by jakirkham** [comment]
Thanks Loïc! 🙂 Closing...
