### ISSUE TITLE
It get complicated to search the docs as we add the meeting minutes 

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-forge.github.io#837]
Someone just reported to me that it is getting hard to find relevant parts of the docs when searching it b/c of the meeting minutes are found.

Maybe we can figure out a way to decouple those two.

**Comment by jakirkham** [comment]
Maybe [this SO]( https://stackoverflow.com/q/8313476/3877089 ) is useful?

**Comment by rgommers** [comment]
Note that it's very hard to find these minutes. After learning from @scopatz about a meeting, I found no mentions on conda-forge.org, did find https://github.com/conda-forge/conda-forge.github.io#conda-forge-dev-meetings which says _"A directory containing the minutes from previous dev meetings can be found in /src/minutes or on our website at insert website link here."_. The rest of that paragraph (e.g. meeting time and link to calendar invite) are also outdated.

I finally found https://conda-forge.org/docs/minutes/00_intro.html

+1 for decoupling but also for making it easier to find this info

**Comment by jakirkham** [comment]
Yeah these got reorged relatively recently. There is definitely room for improvement. Though the meeting notes are definitely more open that they were (even though the visibility has room for improvement). Thanks for raising Ralf!

**Comment by viniciusdc** [comment]
@jakirkham any new thoughts on this ?

**Comment by jakirkham** [comment]
I think this may have already been addressed ( https://github.com/conda-forge/conda-forge.github.io/pull/1216 )
