### ISSUE TITLE
Create a blog page

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-forge.github.io#838]
@croth1 you are our docs hero! What do you suggest for us as a blogging platform and how, if that is a good idea, could we integrate that with the pages generated here?

**Comment by croth1** [comment]
Uhh, I have no experience with blogging whatsoever, sorry :-(

**Comment by ocefpaf** [comment]
> Uhh, I have no experience with blogging whatsoever, sorry :-(

No problem. Do you think we can integrate something similar to the meeting notes in the docs page? Or would that be a bad idea given side effects like #837?

**Comment by CJ-Wright** [comment]
xref: github.com/conda-forge/blog

**Comment by jakirkham** [comment]
Yep, this exists. Thanks @ocefpaf for getting us started. Let's keep working on improving it and adding content. 🙂
