### ISSUE TITLE
Member removal not working

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#84]
We seem to be unable to remove members from a team after they have been removed from the maintainer's list see this quote from this [comment]( https://github.com/conda-forge/staged-recipes/pull/320#discussion_r59412606 ) from @pelson.

> It used to, but now it just warns:
>
> https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/122567637:
>
> ```
> Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']
> AN OLD MEMBER (dan-blanchard) NEEDS TO BE REMOVED FROM conda-forge/certifi-feedstock
> THE conda-forge-webservices TEAM NEEDS TO BE REMOVED.
> Keeping  Core
> Keeping  all-members
> Keeping  conda-forge.github.io
> ```
> 
> The message about the conda-forge-webservices team also needs updating.

**Comment by pelson** [comment]
Yes, that was intentional. I have, in the past, deleted every single team by accident, much to my embarrassment 😄 - so I just disabled the deleting part and added a print statement instead.

The messages do need dealing with though. The team update is trivial (do you have access to teams @jakirkham?) and the special case for conda-forge-webservices needs to live in https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_teams.py#L140.

**Comment by jakirkham** [comment]
> Yes, that was intentional. I have, in the past, deleted every single team by accident, much to my embarrassment 😄 - so I just disabled the deleting part and added a print statement instead.

That's fair. Something like "with great power comes great responsibility". Disabling seems safe. :wink:

> The messages do need dealing with though.

Sure. It probably should be quiet about `conda-forge-webservices`.

> The team update is trivial (do you have access to teams @jakirkham?)...

I think you need to be an owner to have that sort of access. Though I could be mistaken.

> ...the special case for conda-forge-webservices needs to live in https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_teams.py#L140.

Oh, that's an easy enough fix. I can do a PR if you haven't already.

**Comment by pelson** [comment]
Awesome. Thanks @jakirkham

**Comment by jakirkham** [comment]
Added in this PR ( https://github.com/conda-forge/conda-forge.github.io/pull/85 ).

**Comment by pelson** [comment]
Think we are all good here then.
