### ISSUE TITLE
CDT feedstocks: separate or one per CentOS version?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#851]
Do we want to create separate feedstocks for CDTs for different arches or one feedstock? The package names have the arch appended, but we can create one feedstock if we want.

cc @jayfurmanek, @jakirkham

**Comment by jayfurmanek** [comment]
FYI - I did put this up today: https://github.com/conda-forge/staged-recipes/pull/9395  to add CDTs for ppc64le arch.

**Comment by jayfurmanek** [comment]
I've been working on getting the dependencies for the r-base recipe built for ppc64le. The CDTs are the last ones needed, r-base builds fine with the recipes from the above mentioned PR, built locally.

I can see the sense in consolidating recipes - if there is a need to update, they'll all get updated.

On the other hand, some aarch64 CDT were already pushed in separately, and most CDTs for x86-64 just come from defaults. Many ppc64le CDTs are in defaults as well.  So this is a bit messy no matter which way you slice it.

**Comment by isuruf** [comment]
On second thought, since these CDT recipes are build only once, there's really no point putting the effort into merging them.

**Comment by jayfurmanek** [comment]
Yup - they should never need updating if they're done right.

**Comment by jayfurmanek** [comment]
The other benefit of consolidating is ensuring you have the same set for all cos7 supported platforms. But..since defaults has a partial set already and aarch64 has some merged in, its a bit a rework with the payoff just being some organizational cleanliness.

**Comment by jakirkham** [comment]
It seems like we have gone for a separate one. Is that right? If so, should we close this out?

**Comment by beckermr** [comment]
yeah this can be closed given all of the cos7 stuff we did
