### ISSUE TITLE
Easier path for "how to get help" on the website

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/conda-forge.github.io#852]
Where/how to submit an issue is not always obvious to users who don't really know about how conda-forge is organized; @ocefpaf reported that many users would rather just work around stuff themselves instead rather than reporting issues upstream.

It might help to have a big "help" button (or similar) on the website, and maybe linked from various repos as well, describing where to go to report issues: how to find a feedstock repo for a given package name, what kinds of things go on the webpage repo, etc.

We could also think about ways to make this more friendly, especially in the case when feedstock maintainers don't respond right away.

**Comment by viniciusdc** [comment]
@ocefpaf Any suggestions on what we should address to this besides the #880 ? (If not, we can close this or reformulate as an Outreachy issue)

**Comment by ocefpaf** [comment]
I'm OK closing this. If @djsutherland feels that #880 is not really what she thought on when opening this issue we can re-open it later.
