### ISSUE TITLE
Migration from appveyor to azure

### ISSUE THREAD

**Issue by ericdill** [conda-forge/conda-forge.github.io#857]
There was a discussion in the core meeting on [2019-08-07](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/minutes/2019-08-07.md#migrate-away-from-appveyor-marius--isuru) around the migration from Azure to Appveyor between @mariusvniekerk and @isuruf. The initial discussion concluded a couple of things:

* Everything that doesn't use CMake or msbuild is a candidate to migrate off of Appveyor
* Could also just throw _everything_ at Azure and then use the Azure API to figure out which builds are successful. The counterpoint to this approach is that using the build status isn't ideal since Azure logs are only available for a limited time. Could also use cfgraph to determine if cmake is used. 

One question is why we are migrating from Appveyor to Azure? With Appveyor we have a plan that is 4 concurrent builds. We also add ~4 feedstocks per day. We are just running out of capacity on Appveyor and, by comparison, we have effectively unlimited builds on Azure (with 200 concurrent jobs).

Things that need to be addressed here are:

[ ] Get a list of packages to KEEP on Appveyor
[ ] Change the default build to Azure and figure out how to let feedstock maintainers opt-in to using Appveyor if needed. This likely needs a new smithy release.

@mariusvniekerk, @isuruf and anyone else interested should take over discussion / ownership of this issue at this point.

**Comment by scopatz** [comment]
This is pretty urgent, because we want to get back on the free plan ASAP

**Comment by isuruf** [comment]
I've got a script that creates commits like https://github.com/conda-forge/bzip2-feedstock/commit/33b3732f85ecf455298822a235901608c9d71e26 automatically. Shall I run it now?

**Comment by scopatz** [comment]
Yes, please!

**Comment by isuruf** [comment]
There are 75 repositories failing,

See the cell before last at https://gist.github.com/isuruf/b366d2e8aeb1c01b0c472be2aa74ef36

**Comment by njzjz** [comment]
conda-forge/hmmlearn-feedstock#5 failed with `RuntimeError: This PR needs a rerender to switch from appveyor to azure`. But https://github.com/conda-forge/hmmlearn-feedstock/pull/5/commits/5d2886431a166244582d5462bdde1a8d9a0fce64 has rerendered it. How to fix it?

**Comment by isuruf** [comment]
@njzjz, you need to merge with master and then rerender.

**Comment by CJ-Wright** [comment]
What is the status of this, can we close?

**Comment by njzjz** [comment]
Hi, can you turn off appveyor for https://github.com/conda-forge/openbabel-feedstock? We have migrated to azure but still have a appveyor check. (conda-forge/openbabel-feedstock#5)

**Comment by jakirkham** [comment]
We don't actually turn off CIs. We merely disable builds with them (using whatever mechanism they find convenient). That said, sometimes the CI will run spuriously anyways. Would just ignore it.

**Comment by beckermr** [comment]
This is done!
