### ISSUE TITLE
support for external MPI libraries

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#860]
So I use miniconda installations on HPC clusters a lot. One of the things you have to do when rolling your own environment in this case is to install mpi4py via pip and make sure it compiles against the local MPI libraries that come with the cluster (as opposed to conda installing its own MPI `.so`'s). 

For a given conda environment, this is not a huge pain, but it does make updating or managing envs hard because the solver complains and is always attempting to install its own versions. 

It is this last thing I'd like to figure out how to fix or make easier. In principle, for many packages, this won't ever be fixed since we cannot maintain packages that ship the MPI libraries of random clusters. However, given that there is a standard set of symbols for these libraries, we may be able to somehow link the local libraries into the conda env. 

So for example, you could imagine the following.

1. have the user define an environment variable (say `CONDA_EXTERNAL_MPI_PREFIX`) that points to the local installation.
2. build a conda package (say `mpi-external`) that has an activation script that uses the env variable above to symlink the libraries in the right spot.
3. build an empty shell mpi4py package that exists only to make the conda solver happy (it should have some unique version to make it easy to pin etc, but won't do any installs)
4. the user can pip install mpi4py in the env as normal

Another way to think about this problem is to treat MPI as CDT for these cases. We could attempt to add something like the mpi-external above as one of the MPI options in the MPI build matrix and make sure to install some sort of platform specific global MPI installation when doing builds. 

@minrk @isuruf any thoughts here?

**Comment by isuruf** [comment]
> However, given that there is a standard set of symbols for these libraries, 

Are you sure? Even mpich and openmpi don't have the same set of symbols.

**Comment by beckermr** [comment]
Closing for now! Thanks all!
