### ISSUE TITLE
WinError126 during package installation with conda-forge

### ISSUE THREAD

**Issue by Aeksioglu** [conda-forge/conda-forge.github.io#863]
Hello ,
I am trying to install packages with conda-forge like for poppler,  "install -c conda-forge poppler"
Conda run the command and prompted to download below packages but none of them is successful due to the WinError126 error. Same result for another package (pytesseract). I don't have any idea about the issue, need help about it.

Proceed ([y]/n)? y
Downloading and Extracting Packages
openssl-1.0.2r       | 5.4 MB    |                   |   0%
glib-2.58.3          | 3.5 MB    |                     |   0%
pip-19.2.3           | 1.9 MB    |                     |   0%
poppler-data-0.4.9   | 3.4 MB    |              |   0%
openjpeg-2.3.1       | 225 KB    |                |   0%
gettext-0.19.8.1     | 5.0 MB    |                  |   0%
poppler-0.75.0       | 1.9 MB    |                 |   0%
libffi-3.2.1         | 36 KB     |                       |   0%
krb5-1.16.1          | 825 KB    |                   |   0%
ca-certificates-2019 | 181 KB    |             |   0%
pcre-8.41            | 453 KB    |                   |   0%
libssh2-1.8.0        | 184 KB    |                  |   0%
jpeg-9c              | 314 KB    |                   |   0%
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found

**Comment by scopatz** [comment]
CC @conda-forge/staged-recipes @conda-forge/core

**Comment by CJ-Wright** [comment]
Can you please provide the output of `conda info` and `conda list`?

**Comment by Aeksioglu** [comment]
conda info

     active environment : base
    active env location : C:\Users\hp\Anaconda3
            shell level : 1
       user config file : C:\Users\hp\.condarc
 populated config files : C:\Users\hp\.condarc
          conda version : 4.7.11
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       virtual packages :
       base environment : C:\Users\hp\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\hp\Anaconda3\pkgs
                          C:\Users\hp\.conda\pkgs
                          C:\Users\hp\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\hp\Anaconda3\envs
                          C:\Users\hp\.conda\envs
                          C:\Users\hp\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

conda list
# packages in environment at C:\Users\hp\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
_r-mutex                  1.0.0               anacondar_1
_tflow_select             2.3.0                       mkl
absl-py                   0.7.1                    py37_0
alabaster                 0.7.12                   py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0    anaconda
anaconda-project          0.8.2                    py37_0
asn1crypto                0.24.0                   py37_0
astor                     0.7.1                    py37_0
astroid                   2.2.5                    py37_0
astropy                   3.1.2            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.1.0                   py37_1
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.7.1                    py37_1
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.15.0               h7bd577a_0
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py37_1
cffi                      1.12.2           py37h7a1dbc1_1
chardet                   3.0.4                    py37_1
click                     7.0                      py37_0
cloudpickle               0.8.0                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
colorlover                0.3.0                      py_0    conda-forge
comtypes                  1.1.7                    py37_0
conda                     4.7.11                   py37_0
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.3.10                   py37_0
conda-verify              3.1.1                    py37_0
console_shortcut          0.1.1                         3
contextlib2               0.5.5                    py37_0
cryptography              2.3.1            py37h74b6da3_0
cufflinks-py              0.13.0                     py_0    conda-forge
cycler                    0.10.0                   py37_0
cython                    0.29.6           py37ha925a31_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask-core                 1.1.4                    py37_1
decorator                 4.4.0                    py37_1
defusedxml                0.5.0                    py37_1
distributed               1.26.0                   py37_1
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
filelock                  3.0.10                   py37_0
flask                     1.0.2                    py37_1
font-ttf-dejavu-sans-mono 2.37                 h6964260_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                h7457263_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fonts-anaconda            1                    h8fa9717_0
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
gast                      0.2.2                    py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.6                      py37_1
greenlet                  0.4.15           py37hfa6e2cd_0
grpcio                    1.14.1           py37h5c4b210_0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.8                      py37_0
intel-openmp              2019.3                      203
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.4.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.16                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4                      py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
jupyterlab                0.35.4           py37hf63ae98_0
jupyterlab_server         0.2.0                    py37_0
keras-applications        1.0.8                      py_0
keras-preprocessing       1.1.0                      py_1
keyring                   18.0.0                   py37_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libarchive                3.3.3                h798a506_1
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libmklml                  2019.0.3                      0
libopencv                 3.4.1                h875b8b8_3
libpng                    1.6.36               h2a8f88b_0
libprotobuf               3.8.0                h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.28.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.3.2            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2-bash                   4.3.042                       5
m2-coreutils              8.25                        102
m2-findutils              4.6.0                         2
m2-gcc-libs               5.3.0                         4
m2-gmp                    6.1.0                         3
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libiconv               1.14                          3
m2-libintl                0.19.7                        4
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-c-ares              1.11.0                        2
m2w64-ca-certificates     20150426                    104
m2w64-curl                7.48.0                        2
m2w64-diffutils           3.3.2                         2
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gnutls              3.4.11                        2
m2w64-grep                2.24                          2
m2w64-gsl                 2.1                           2
m2w64-jansson             2.7                           3
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libidn              1.32                          4
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libmetalink         0.1.3                         2
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libssh2             1.7.0                         2
m2w64-libsystre           1.0.1                         3
m2w64-libtasn1            4.7                           2
m2w64-libtiff             4.0.6                         2
m2w64-libtre-git          122.c2f5d13                   5
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-nettle              3.1.1                         4
m2w64-nghttp2             1.9.2                         2
m2w64-openblas            0.2.19                        1
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        3
m2w64-pcre                8.38                          2
m2w64-rtmpdump-git        499.a107cef                   4
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37he774522_0
matplotlib                2.2.2            py37had4c4a9_2
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.3                      203
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
mock                      3.0.5                    py37_0
more-itertools            6.0.0                    py37_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
mtcnn                     0.0.9                    pypi_0    pypi
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.1                    py37_3
nbformat                  4.4.0                    py37_0
networkx                  2.2                      py37_1
nltk                      3.4.3                    py37_0    anaconda
nose                      1.3.7                    py37_2
notebook                  5.7.8                    py37_0
numba                     0.43.1           py37hf9181ef_0
numpy                     1.16.2           py37h19fb1c0_0
numpy-base                1.16.2           py37hc3f5095_0
numpydoc                  0.8.0                    py37_0
olefile                   0.46                     py37_0
opencv                    3.4.1            py37h6fd60c2_3
openjdk                   8.0.152              h7382acf_1
openpyxl                  2.6.1                    py37_1
openssl                   1.0.2s               he774522_0
packaging                 19.0                     py37_0
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.3.4                    py37_0
partd                     0.3.10                   py37_1
path.py                   11.5.0                   py37_0
pathlib2                  2.3.3                    py37_0
patsy                     0.5.1                    py37_0
pdf2image                 1.7.1                    pypi_0    pypi
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.2.0            py37h08bbbbd_0    anaconda
pip                       19.2.3                   pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0
plotly                    3.10.0                     py_0
pluggy                    0.9.0                    py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
prometheus_client         0.6.0                    py37_0
prompt_toolkit            2.0.9                    py37_0
protobuf                  3.8.0            py37h33f27b4_0
psutil                    5.6.1            py37he774522_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
py-opencv                 3.4.1            py37h1b0d24d_3
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pyflakes                  2.1.1                    py37_0
pygments                  2.3.1                    py37_0
pylint                    2.3.1                    py37_0
pyodbc                    4.0.26           py37ha925a31_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyqt                      5.6.0            py37ha878b3d_6
pyreadline                2.1                      py37_1
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.6.8                    py37_0
pytesseract               0.3.0                    pypi_0    pypi
pytest                    4.3.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.3.0                    py37_0
pytest-openfiles          0.3.2                    py37_0
pytest-remotedata         0.3.1                    py37_0
python                    3.7.1                h33f27b4_4
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                      py37_6
pytrends                  4.6.0                    pypi_0    pypi
pytz                      2018.9                   py37_0
pywavelets                1.0.2            py37h8c2d366_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1              py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.6.2           vc14h6f8c307_12
qtawesome                 0.5.7                    py37_1
qtconsole                 4.4.3                    py37_0
qtpy                      1.7.0                    py37_1
r-askpass                 1.0                       r36_0
r-assertthat              0.2.1             r36h6115d3f_0
r-backports               1.1.4             r36h6115d3f_0
r-base                    3.6.1                h8a96d1b_0
r-base64enc               0.1_3             r36h6115d3f_4
r-bh                      1.69.0_1          r36h6115d3f_0
r-bit                     1.1_14            r36h6115d3f_0
r-bit64                   0.9_7             r36h6115d3f_0
r-bitops                  1.0_6             r36h6115d3f_4
r-blob                    1.1.1             r36h6115d3f_0
r-catools                 1.17.1.2          r36h6115d3f_0
r-cellranger              1.1.0             r36h6115d3f_0
r-cli                     1.1.0             r36h6115d3f_0
r-clipr                   0.6.0             r36h6115d3f_0
r-config                  0.3               r36h6115d3f_0
r-crayon                  1.3.4             r36h6115d3f_0
r-curl                    3.3               r36h6115d3f_0
r-dbi                     1.0.0             r36h6115d3f_0
r-dbplyr                  1.4.0             r36h6115d3f_0
r-digest                  0.6.18            r36h6115d3f_0
r-dplyr                   0.8.0.1           r36h6115d3f_0
r-ellipsis                0.1.0             r36h6115d3f_0
r-evaluate                0.13              r36h6115d3f_0
r-fansi                   0.4.0             r36h6115d3f_0
r-forcats                 0.4.0             r36h6115d3f_0
r-forge                   0.2.0             r36h6115d3f_0
r-generics                0.0.2             r36h6115d3f_0
r-glue                    1.3.1             r36h6115d3f_0
r-haven                   2.1.0             r36h6115d3f_0
r-highr                   0.8               r36h6115d3f_0
r-hms                     0.4.2             r36h6115d3f_0
r-htmltools               0.3.6             r36h6115d3f_0
r-htmlwidgets             1.3               r36h6115d3f_0
r-httpuv                  1.5.1             r36h6115d3f_0
r-httr                    1.4.0             r36h6115d3f_0
r-jsonlite                1.6               r36h6115d3f_0
r-knitr                   1.22              r36h6115d3f_0
r-later                   0.8.0             r36h6115d3f_0
r-magrittr                1.5               r36h6115d3f_4
r-markdown                0.9               r36h6115d3f_0
r-mime                    0.6               r36h6115d3f_0
r-miniui                  0.1.1.1           r36h6115d3f_0
r-mongolite               2.0.1             r36h6115d3f_0
r-odbc                    1.1.5                     r36_0
r-openssl                 1.3               r36h6115d3f_0
r-packrat                 0.5.0             r36h6115d3f_0
r-pillar                  1.3.1             r36h6115d3f_0
r-pkgconfig               2.0.2             r36h6115d3f_0
r-pki                     0.1_5.1           r36h6115d3f_1
r-plogr                   0.2.0             r36h6115d3f_0
r-prettyunits             1.0.2             r36h6115d3f_0
r-profvis                 0.3.5             r36h6115d3f_0
r-progress                1.2.0             r36h6115d3f_0
r-promises                1.0.1             r36h6115d3f_0
r-purrr                   0.3.2             r36h6115d3f_0
r-r2d3                    0.2.3             r36h6115d3f_0
r-r6                      2.4.0             r36h6115d3f_0
r-rappdirs                0.3.1             r36h6115d3f_0
r-rcpp                    1.0.1             r36h6115d3f_0
r-rcurl                   1.95_4.12         r36h6115d3f_0
r-readr                   1.3.1             r36h6115d3f_0
r-readxl                  1.3.1             r36h6115d3f_0
r-rematch                 1.0.1             r36h6115d3f_0
r-rjava                   0.9_11            r36h6115d3f_0
r-rjdbc                   0.2_7.1           r36h6115d3f_0
r-rjsonio                 1.3_1.1           r36h6115d3f_0
r-rlang                   0.3.4             r36h6115d3f_0
r-rmarkdown               1.12              r36h6115d3f_0
r-rprojroot               1.3_2             r36h6115d3f_0
r-rsconnect               0.8.13            r36h6115d3f_0
r-rstudioapi              0.10              r36h6115d3f_0
r-shiny                   1.3.2             r36h6115d3f_0
r-sourcetools             0.1.7             r36h6115d3f_0
r-sparklyr                1.0.0             r36h6115d3f_0
r-stringi                 1.4.3             r36h6115d3f_0
r-stringr                 1.4.0             r36h6115d3f_0
r-sys                     3.2               r36h6115d3f_0
r-tibble                  2.1.1             r36h6115d3f_0
r-tidyr                   0.8.3             r36h6115d3f_0
r-tidyselect              0.2.5             r36h6115d3f_0
r-tinytex                 0.12              r36h6115d3f_0
r-utf8                    1.1.4             r36h6115d3f_0
r-withr                   2.1.2             r36h6115d3f_0
r-xfun                    0.6               r36h6115d3f_0
r-xml2                    1.2.0             r36h6115d3f_0
r-xtable                  1.8_4             r36h6115d3f_0
r-yaml                    2.2.0             r36h6115d3f_0
requests                  2.21.0                   py37_0
retrying                  1.3.3                    py37_2
rope                      0.12.0                   py37_0
rstudio                   1.1.456          vc14h1ad3211_1  [vc14]
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-learn              0.20.3           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
setuptools                40.8.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.18.1           py37h6538335_2
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.8                      py37_0
sphinx                    1.8.5                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.3                    py37_0
spyder-kernels            0.4.2                    py37_0
sqlalchemy                1.3.1            py37he774522_0
sqlite                    3.27.2               he774522_0
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.3                      py37_0
tbb                       2019.4               h74a9793_0
tblib                     1.3.2                    py37_0
tensorboard               1.13.1           py37h33f27b4_0
tensorflow                1.13.1          mkl_py37h9463c59_0
tensorflow-base           1.13.1          mkl_py37hcaf7020_0
tensorflow-estimator      1.13.0                     py_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
toolz                     0.9.0                    py37_0
tornado                   6.0.2            py37he774522_0
tqdm                      4.31.1                   py37_1
traitlets                 4.3.2                    py37_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.33.1                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.1           py37he774522_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.1.5                    py37_0
xlwings                   0.15.4                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zict                      0.1.4                    py37_0
zipp                      0.3.3                    py37_1
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.3                hfe6a214_0

**Comment by Aeksioglu** [comment]
Found a way with reinstalling anaconda which comes with 4.7.12 version of conda. While installing a package I faced compatibility problem so conda cannot solve the environment. Then I downgraded conda "conda update conda=4.6.12" and the issue is finally solved.
