### ISSUE TITLE
cannot re-render the PR

### ISSUE THREAD

**Issue by njzjz** [conda-forge/conda-forge.github.io#881]
Issue:

In conda-forge/hmmlearn-feedstock#5, I tried to rerender the PR but @conda-forge-linter said it wasn't able to push the commit. I have already checked the "Allow edits from maintainers" box.

![image](https://user-images.githubusercontent.com/9496702/65987515-f37d3b80-e453-11e9-85ec-71c4eeb3d0ef.png)
![image](https://user-images.githubusercontent.com/9496702/65987522-f841ef80-e453-11e9-9129-024319b25d6c.png)

**Comment by isuruf** [comment]
@conda-forge/core, we are running out of memory in the heroku instance.

**Comment by CJ-Wright** [comment]
Hmm, is this because of a leak? Do we need to knock the heroku instance over?

**Comment by isuruf** [comment]
@CJ-Wright, no. It uses around 50 MB when idle and a rerender takes like 500 MB, but limit is 512 MB.

**Comment by CJ-Wright** [comment]
hmm ok

**Comment by jakirkham** [comment]
There have been a number of improvements to the bot of late. So am going to close this out, but please let us know if you see more issues and we can take a look 🙂

**Comment by finagle29** [comment]
This is happening to me too on conda-forge/linetools-feedstock#2
![image](https://user-images.githubusercontent.com/5816532/92981442-ad479f00-f44e-11ea-9a1b-46ea1f44dd86.png)
![image](https://user-images.githubusercontent.com/5816532/92981447-b33d8000-f44e-11ea-9ec3-e1a3cdf3cce9.png)

**Comment by jakirkham** [comment]
Please raise a new issue.
