### ISSUE TITLE
Minor typo: "relict" in documentation

### ISSUE THREAD

**Issue by brainwane** [conda-forge/conda-forge.github.io#884]
Issue:

`src/maintainer/maintainer_faq.rst` has the word "relict" which is a misspelling of "relic". This is visible on the built HTML page at https://conda-forge.org/docs/maintainer/maintainer_faq.html .

(This is a good first issue for a new contributor to fix.)

**Comment by rannie-peralta** [comment]
Let me help to fix this one.

**Comment by rannie-peralta** [comment]
Will build automatically update the corresponding `.rst.txt` and `.html` files? or I have to update those manually?

**Comment by croth1** [comment]
You only have to change the .rst files. Everything else is autogenerated.
