### ISSUE TITLE
Minor style issue: capitalizing "Anaconda Cloud" in documentation

### ISSUE THREAD

**Issue by brainwane** [conda-forge/conda-forge.github.io#885]
Issue:

`src/user/introduction.rst` has the phrase "anaconda cloud" when it would probably be better to capitalize it as "Anaconda Cloud". This is visible on the built HTML page at https://conda-forge.org/docs/user/introduction.html#why-conda-forge .

(This is a good first issue for a new contributor to fix. See https://conda-forge.org/docs/user/contributing.html#improving-the-documentation for guidance.)

**Comment by loldja** [comment]
Looking at this!

**Comment by loldja** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/887

**Comment by CJ-Wright** [comment]
Fixed
