### ISSUE TITLE
Minor style issue: capitalizing OS names in documentation

### ISSUE THREAD

**Issue by brainwane** [conda-forge/conda-forge.github.io#886]
Issue:

`src/user/introduction.rst` has the line

> by default, we build packages for macOS, linux amd64 and windows amd64

when it would probably be better to capitalize proper nouns:

> by default, we build packages for macOS, Linux AMD64, and Windows AMD64

This is visible on the built HTML page at https://conda-forge.org/docs/user/introduction.html#why-conda-forge .

(This is a good first issue for a new contributor to fix. See https://conda-forge.org/docs/user/contributing.html#improving-the-documentation for guidance.)

**Comment by isuruf** [comment]
`macOS` is a brand name with that exact spelling.

**Comment by brainwane** [comment]
OK! Amending my suggestion accordingly. Thanks!

**Comment by jakirkham** [comment]
Yeah they have changed the spelling and capitalization over the years.

**Comment by robertpd** [comment]
I can grab this.

**Comment by robertpd** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/888

**Comment by CJ-Wright** [comment]
Fixed
