### ISSUE TITLE
Meta Docs!

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#889]
It would be nice to add some docs to the Readme and/or docs about how to edit the docs. This can be particularly confusing, since we have multiple dirs which have docs, but only one dir that will actually impact the docs, `src`.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/884 and a whole bunch of my doc PRs 🐑

**Comment by jakirkham** [comment]
Maybe a contribution guide and PR checklist would be good

**Comment by sodre** [comment]
Should we switch to using the gh-pages branch for hosting the published website? That would reduce the confusion.

**Comment by jakirkham** [comment]
Is that possible on the webpage repo? Thought we were limited to `master`

**Comment by sodre** [comment]
@jakirkham, you're right. I fixed my comment.

**Comment by jakirkham** [comment]
No worries. Agree that would be easier if possible 🙂

**Comment by ForgottenProgramme** [comment]
I guess, this has been fixed. 
PR Checklist has been created. 
Also, the 'improving the documentation' section (https://conda-forge.org/docs/user/contributing.html#improve-the-documentation) mentions the following:

>The source text is stored there in the src/ subdirectory and is formatted using Python’s reStructuredText system.

Perhaps, to clarify further, after '..stored in the src/ subdirectory' we can add 'and NOT in the /docs subdirectory'. 

@jakirkham 
@CJ-Wright

**Comment by kathatherine** [comment]
@beckermr This able to be closed? I don't have permissions myself.

**Comment by beckermr** [comment]
thank you!
