### ISSUE TITLE
Agenda for 2016-04-15

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#89]
Please add comments for agenda items.

Minutes to follow in this description.

Uncertain if the invite link works: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MDhiNGpydHF1ZTFiNTI2ODFjMjYxZ2Q1bjhfMjAxNjA0MTVUMTQwMDAwWiBwZWxzb24ucHViQG0&tmsrc=pelson.pub%40gmail.com

Hangout link: https://hangouts.google.com/call/7fxvcgjutfg4po6c4jpwyitwi4e
Time: 1400-1500 UTC/GMT

We will happily help with any pertinent packaging problems that people have in these meetings, but the primary focus must be geared towards the underlying infrastructure being directed appropriately for conda-forge package maintainers. 

Agenda summary:
  * Welcome
  * How do we manage agendas and minutes?
  * conda-forge: where are we
  * Next meeting?
  * PyPI metadata redundancy
  * Python3 vs Python==3
  * External developers to github.com/continuum repos
  * Centos5 vs Centos6
  * Features and where they sit with feedstocks
  * Complex licenses (e.g. MKL)
  * Packaging python itself
  * conda-forge docs
  * VC features
  * yum requirements
  * Low level packaging
  * NetCDF

**Comment by pelson** [comment]
First item: How should we manage our agenda and minutes

**Comment by pelson** [comment]
Second item: Where are we with conda-forge (N users, packages etc.)? Where are our bottlenecks? What are the perceived issues that we should address before attempting even more exposure?

**Comment by pelson** [comment]
Based on feedback from http://doodle.com/poll/5wuiges2s5u3u6uk, when should we have our next meeting?

**Comment by jakirkham** [comment]
Could we pick a regular occurring time that we stick with for a little while? Having it floating from week to week is a bit challenging for me. I understand we are getting more feedback from others, which requires some adjustment potentially, but it would nice to have something we can plan around.

**Comment by takluyver** [comment]
Item: I don't want conda-forge to duplicate a lot of PyPI metadata, and I certainly don't want it to duplicate metadata and then get out of date because people forget to update it. How can we make this more automatic? I suggested that for typical pure-Python packages, we could have a list of package names and a bot that checks for new versions on PyPI and converts wheels to conda packages. Discussion on conda-forge/staged-recipes#323.

Item: A `python3` package - ways to use Python 3 applications with `python=2` environments (conda-forge/staged-recipes#339)

**Comment by jakirkham** [comment]
Item: Opening up of some Continuum controlled repos? Heroku buildpack? Base build image?

Status Update: CentOS 5 (or glibc version constraint older than CentOS 6) usage survey.

Item: Feature support in conda-forge. Primarily BLAS support (ignoring MKL for now). How do we write recipes that support multiple BLASes? Do we need multiple feedstocks (for each package e.g. `numpy_openblas` and `numpy_atlas`) here, changes to conda-smithy, etc.? What granularity of BLAS selection do we want?

Item: Looking into dependencies with more complex licensing. For example, CUDA (not too bad), cuDNN, MKL, etc.

**Comment by jjhelmus** [comment]
Item: Packaging software already in the default channel, #22. Specifically Python, conda and related packages which would allow for the creation of a custom conda-forge distribution using only conda-forge packages, #90.

**Comment by jakirkham** [comment]
Is there somewhere we could open source our last meeting agenda? I'd like to put it in a repo somewhere at least so people can see it before our next meeting. @pelson @ocefpaf, thoughts on this?

**Comment by jakirkham** [comment]
Item: Hosting docs somewhere? Related issue ( https://github.com/conda-forge/conda-forge.github.io/issues/91 ).

**Comment by jakirkham** [comment]
Item: VC package (Python free). See this proposed recipe ( https://github.com/conda-forge/staged-recipes/pull/363 )

**Comment by jakirkham** [comment]
Item: Discuss yum requirements. See this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/82 ). This PR ( https://github.com/conda-forge/conda-smithy/pull/134 ) and discussion within. Also, this PR ( https://github.com/conda-forge/staged-recipes/pull/346 ), this PR ( https://github.com/conda-forge/conda-smithy/pull/135 ), and this example application PR ( https://github.com/conda-forge/pyopengl-feedstock/pull/3 ).

**Comment by jakirkham** [comment]
Does anyone want to raise any other tabled issues from last time, @pelson @ocefpaf @msarahan?

**Comment by jakirkham** [comment]
Item: Low level packaging ( https://github.com/conda-forge/conda-forge.github.io/issues/81 ). How far is too far? Should system tools be packaged? When should they packaged? How/when should they be used? How should they be organized (same channel, different channel, subchannel)?

**Comment by pelson** [comment]
Item: NetCDF is broken... https://github.com/conda-forge/staged-recipes/pull/213

**Comment by jakirkham** [comment]
> Item: NetCDF is broken... https://github.com/conda-forge/staged-recipes/pull/213

Yeah, we have to get that out of the backlog it is causing all sorts of grief for people. I was just looking at it again earlier.

**Comment by ocefpaf** [comment]
> Item: NetCDF is broken... https://github.com/conda-forge/staged-recipes/pull/213

Thanks for adding that. I am really concerned about this since we added our own version of `hdf5`.

We just got `zlib` out and I am working in `hdf4` BTW.

**Comment by jakirkham** [comment]
Is the version of `zlib` the same or different from the one in `defaults`?

**Comment by ocefpaf** [comment]
> Is the version of `zlib` the same or different from the one in `defaults`?

Version? Yes. Build method? Unknown.

**Comment by jakirkham** [comment]
Yep, looks to be the same version that HDF5 was built with so shouldn't have any weird linkage issues. If we do, I can bump the build number on HDF5.

**Comment by takluyver** [comment]
Sorry, I was planning to join, but there seems to be something up with the wifi. I can get a wired network connection, but only in the open plan office, and I don't want to disturb other people.

**Comment by ericdill** [comment]
Link to the hackpad for meeting notes: https://hackpad.com/conda-forge-meeting-2016-04-15-WZIa4PBQ6sz

**Comment by ericdill** [comment]
Suggestion regarding the hackpad: One top-level heading (#) per meeting and then just keep this as the running notes for the meetings

**Comment by jakirkham** [comment]
> Sorry, I was planning to join, but there seems to be something up with the wifi. I can get a wired network connection, but only in the open plan office, and I don't want to disturb other people.

Sorry you weren't able to make it, @takluyver. We have held off on discussing the issues you raised because we are interested in hearing your thoughts on them and discussing them with you. Our next meeting with be on 29 April at the same time, so if you are able to make it then we would be interested in talking with you more.

**Comment by takluyver** [comment]
I think I should be able to make it then - thanks for postponing those points!

**Comment by pelson** [comment]
Sorry you couldn't join us @takluyver. I've added your items onto the next agenda.

To everybody: Please feel free to add other items at  https://hackpad.com/conda-forge-hangouts-WZIa4PBQ6sz

**Comment by pelson** [comment]
P.S. Minutes proposed as a PR at https://github.com/conda-forge/conda-forge.github.io/pull/94

**Comment by jakirkham** [comment]
Docs ( https://github.com/conda-forge/conda-forge.github.io/pull/95 ) very much in progress.

**Comment by jakirkham** [comment]
Added an organizational hackpad. See issue ( https://github.com/conda-forge/conda-forge.github.io/issues/101 ) for details.

**Comment by jakirkham** [comment]
Correction @takluyver @ericdill @jjhelmus and others, I meeting next week is schedule for Friday not Thursday. The time will remain the same 1400 UTC.

This has been updated on the Hackpad and the errata addressed in the archived minutes in this repo. 

 Hope everyone can still make it. Sorry for the confusion.
