### ISSUE TITLE
Packages that require new OSX SDKs

### ISSUE THREAD

**Issue by allanleal** [conda-forge/conda-forge.github.io#891]
Issue:

We have moved from C++14 to C++17 and there are now a couple of issues when building our library on conda-forge. I'll focus for now on the OSX issue only. When compiling our Python bindings using `pybind11`, with clang 9.0.0, we get errors with a note as this:

~~~
note: 'operator delete' has been explicitly marked unavailable here
_LIBCPP_OVERRIDABLE_FUNC_VIS _LIBCPP_AVAILABILITY_SIZED_NEW_DELETE void  operator delete(void* __p, std::size_t __sz) _NOEXCEPT;
~~~

We have already investigated this issue in the web, and we now add the compile options `-fno-aligned-allocation -fno-sized-deallocation`, which have been enough to solve the exact same issue in our own machines (making sure `clang 9.0.0` from conda-forge is used). However, the issue is not resolved with these options when compiling in a conda-forge environment. Full build log available in this [Azure link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=79088).

@isuruf has pointed out that this is due to an older SDK and a newer one could be provided as a solution. 

The full build log (with all env and conda system info) in this text file:

[conda-forge-osx-build-log.txt](https://github.com/conda-forge/conda-forge.github.io/files/3706777/conda-forge-osx-build-log.txt)

**Comment by isuruf** [comment]
It is possible to override this at https://github.com/conda-forge/qt-feedstock/blob/master/recipe/conda_build_config.yaml

Issue is that it is impossible atm to prevent users on older systems installing packages targeting newer ones. We should come up with a strategy as the number of packages needing this is slowly rising. From 1 package (qt) from several months ago to a handful now.

I though about a package like `macos_ver` that is a dependency of all compiled packages, but conda solver always installs the latest possible version, so this might become confusing.

cc @kalefranz, @mingwandroid, @conda-forge/core, @conda-forge/staged-recipes

**Comment by allanleal** [comment]
Thanks @isuruf . @tadeu pointed out that this other [`conda_build_config.yaml`](https://github.com/conda-forge/mesalib-feedstock/blob/master/conda_build_config.yaml), for `mesalib`, is also a possible solution. Can you comment which one would be more adequate (if this at all matters)?

**Comment by beckermr** [comment]
Is a virtual package the right choice here?

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#managing-virtual-packages

**Comment by isuruf** [comment]
Yes. A virtual package seems like the correct approach. I'm sure @kalefranz and @mingwandroid will accept a PR for `conda`.

**Comment by jjhelmus** [comment]
For reference, conda/conda#8267 is the PR where the `__cuda` virtual package was implemented.  That was the first (and right now only) virtual package.  Hopefully with the framework in place adding more virtual packages will require fewer additions to conda.

**Comment by beckermr** [comment]
Sounds good. I am backed up on PRs ATM so no promises. :)

**Comment by beckermr** [comment]
Here is a PR. I need to sign the CLA which will take time with my local lawyers. 

https://github.com/conda/conda/pull/9349

**Comment by jakirkham** [comment]
Also issue ( https://github.com/conda/conda/issues/9348 ) about adding virtual packages to track system C library version may be of interest.

**Comment by isuruf** [comment]
We need to send PRs to the following feedstocks with run_constrained added as in https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

- [ ] openmpi
- [ ] qt
- [ ] pyqt
- [ ] nodejs
- [ ] javafx
- [ ] reaktoro
- [ ] ldas-tools-al
- [ ] freecad

cc @conda-forge/openmpi, @conda-forge/qt, @conda-forge/pyqt, @conda-forge/javafx, @conda-forge/reaktoro, @conda-forge/ldas-tools-al, @conda-forge/freecad, @conda-forge/core

**Comment by marcelotrevisani** [comment]
Cc: @allanleal

**Comment by beckermr** [comment]
See this one for openmpi: https://github.com/conda-forge/openmpi-feedstock/pull/49

**Comment by klugem** [comment]
> We need to send PRs to the following feedstocks with run_constrained added as in https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

> * [x]  javafx-sdk

Done.

**Comment by looooo** [comment]
please review: https://github.com/conda-forge/freecad-feedstock/pull/31

**Comment by beckermr** [comment]
I did the last of these

https://github.com/conda-forge/ldas-tools-al-feedstock/pull/11
https://github.com/conda-forge/reaktoro-feedstock/pull/12/files

**Comment by allanleal** [comment]
Hi guys, thanks a lot for this fix. 

I'm wondering if we need to do anything with `recipe/conda_build_config.yaml` in `reaktoro-feedstock`? We have this config in there:

~~~
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.12'                # [osx]
~~~

**Comment by beckermr** [comment]
We keep this as is.

**Comment by beckermr** [comment]
I put up a PR for the repo data patches.

**Comment by beckermr** [comment]
We still need to merge the nodejs PR.

**Comment by beckermr** [comment]
And sill me made the wrong PR for the repo data. I will redo now.

**Comment by beckermr** [comment]
fixed.

**Comment by isuruf** [comment]
Thanks @beckermr
