### ISSUE TITLE
https://github.com/conda-forge/feedstocks/blob/master/README.md empty

### ISSUE THREAD

**Issue by peterjc** [conda-forge/conda-forge.github.io#892]
Currently this README is empty:

https://github.com/conda-forge/feedstocks/blob/master/README.md

I was looking at this for where to report an issue, and https://conda-forge.org/ directed me here. Perhaps the feedstocks README could be a stub pointing at https://conda-forge.org/ ?

**Comment by viniciusdc** [comment]
@conda-forge/core Is there anything else to do with this issue?

**Comment by peterjc** [comment]
Thank you - should have closed this already
