### ISSUE TITLE
cistools feedstocks

### ISSUE THREAD

**Issue by duncanwp** [conda-forge/conda-forge.github.io#9]
I've a few conda recipes which it would be nice to merge in from https://github.com/cistools/conda-recipes. Mostly CIS, hdf4 and a couple of other dependencies. 

Let me know if I can help.

**Comment by pelson** [comment]
For those few recipes, feel free to propose a PR against conda-forge/staged-recipes. At a point when conda-forge is up and ready, we will be able to convert those recipes into proper feedstocks.

**Comment by duncanwp** [comment]
Great, will do.

Do you have a rough timeline for this to be up and ready? How much time are you guys able to give this?

Thanks


On 4 Jan 2016, at 16:05, Phil Elson <notifications@github.com<mailto:notifications@github.com>> wrote:


For those few recipes, feel free to propose a PR against conda-forge/staged-recipes. At a point when conda-forge is up and ready, we will be able to convert those recipes into proper feedstocks.

**Comment by pelson** [comment]
> How much time are you guys able to give this?

It is currently a hobby project, so never more than ~5hrs a week at the moment from me. That situation could change over the next few weeks though.

> Do you have a rough timeline for this to be up and ready?

Not concretely, although I'm keen to have conda-forge bedded before conference season this year. Do you have a driver / deadline, or just scoping?

Cheers,

**Comment by duncanwp** [comment]
Not concretely, although I'm keen to have conda-forge bedded before conference season this year. Do you have a driver / deadline, or just scoping?

No, just scoping - it’s a nice idea and I’m looking forward to being able to tell people about it!


On 4 Jan 2016, at 16:25, Phil Elson <notifications@github.com<mailto:notifications@github.com>> wrote:


How much time are you guys able to give this?

It is currently a hobby project, so never more than ~5hrs a week at the moment from me. That situation could change over the next few weeks though.

Do you have a rough timeline for this to be up and ready?

Not concretely, although I'm keen to have conda-forge bedded before conference season this year. Do you have a driver / deadline, or just scoping?

Cheers,

**Comment by ChrisBarker-NOAA** [comment]
On Jan 4, 2016, at 8:26 AM, Phil Elson <notifications@github.com> wrote:

How much time are you guys able to give this?

It is currently a hobby project, so never more than ~5hrs a week at the
moment from me. That situation could change over the next few weeks though.

Maybe some of us can help?

Not concretely, although I'm keen to have conda-forge bedded before
conference season this year.

I hope so -- I've gone and put in a talk proposal for pyCon :-)

Which gives me an incentive to help.

Meanwhile, is there a reason not to start populating the conda-forge
community channel with the tooling currently available?

I love the conda-smithy approach, but it's not so bad to do by hand, and we
could still support the community and limit duplication of effort while we
hammer out the kinks in the tools.

-CHB

Do you have a driver / deadline, or just scoping?

Cheers,

—
Reply to this email directly or view it on GitHub
<https://github.com/conda-forge/conda-forge.github.io/issues/9#issuecomment-168723633>
.

**Comment by pelson** [comment]
> Maybe some of us can help?

Certainly! There are a few high level issues in https://github.com/conda-forge/conda-forge.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 which could be looked at. If there is a specific bit of conda-forge which you want to get involved in, just shout and I will help coordinate.

**Comment by ChrisBarker-NOAA** [comment]
On Tue, Jan 5, 2016 at 1:31 AM, Phil Elson <notifications@github.com> wrote:

> Maybe some of us can help?
>
> Certainly! There are a few high level issues in
> https://github.com/conda-forge/conda-forge.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
> which could be looked at. If there is a specific bit of conda-forge which
> you want to get involved in, just shout and I will help coordinate.
>
Excellent -- I had looked in the conda-smithy repo and didn't really see
anything -- these look like good low-hanging fruit.

Now to find some roundtits somewhere....

-CHB



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda-forge/conda-forge.github.io/issues/9#issuecomment-168946069>
> .
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by jakirkham** [comment]
Still interested in doing this, @duncanwp? Should be pretty straightforward. Some of those exists as feedstocks I believe. So for those maybe signing up as a maintainer would be good. Happy to help when you are ready.

**Comment by pelson** [comment]
How things change. conda-forge has really taken flight in the 5 months since this was opened. @duncanwp - if there is anything we can do please get in touch (gitter: https://gitter.im/conda-forge/conda-forge.github.io)
