### ISSUE TITLE
Docs only repo

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#91]
To get movement started on this, I would like to propose that we add a repo called something like `conda-forge-docs`. It's purpose would literally just be to hold docs about conda-forge. The docs would all be reStructuredText and we could set it up with [readthedocs]( http://readthedocs.org/ ) to autobuild and display the docs for `master`. Adding any dependencies to build the docs should be pretty easy as they [support `conda`]( https://github.com/rtfd/readthedocs.org/issues/857 ). All of this should make it visible, easy to maintain, and easy to point to from other places. We may decide on better places to move these later, which is totally fine by me, but I think we should at least give them a home somewhere to begin with.

Any thoughts or suggestions here would be appreciated?

**Comment by jakirkham** [comment]
It has been decided the docs will live in this repo in a directory called `docs`. Just using Markdown for now.

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda-forge/conda-forge.github.io/pull/95 ) for progress.

**Comment by pelson** [comment]
👍 . Closing this issue for now.
