### ISSUE TITLE
Add script to unwatch everything that I'm not a maintainer of

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#92]
Us poor administrators of conda-forge get swamped with notifications from all sorts of feedstocks. I really only want to hear from those that I maintain, or those that mention me or the @conda-forge/core team.

Shouldn't be too hard to write.

**Comment by mwcraig** [comment]
+100

**Comment by pelson** [comment]
@mwcraig - please see https://github.com/conda-forge/conda-forge.github.io/pull/110.

Heads up to everybody here: I will not see PR notifications unless I am a maintainer of a package, or have been pinged. 🎉 

Let met know if you have any issues with running it.
