### ISSUE TITLE
CI breaks because of use of environ

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge.github.io#93]
https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/123324519

Looks like the change to use ```environ``` in https://github.com/conda-forge/staged-recipes/pull/358 broke the teams script.

**Comment by jakirkham** [comment]
Is that the right PR?

**Comment by pelson** [comment]
> Is that the right PR?

Yes, I believe so. https://github.com/conda-forge/staged-recipes/pull/358/files#diff-6db6ec9d7e8339bb0382b2c28399db45R29

**Comment by jakirkham** [comment]
Sorry, I see what you mean. Why would that cause it to break though? Is it just because `PY_VER` is undefined? Could we just pick an arbitrary value and set it in advance?

**Comment by pelson** [comment]
The problem is https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_teams.py#L82.

The result isn't important, so we can just mock out what environment does in there I think.

**Comment by jakirkham** [comment]
Are you awake or is that just more automation?

**Comment by jakirkham** [comment]
Close, but not quite. Let's try again.

**Comment by jakirkham** [comment]
Nearly there.

**Comment by jakirkham** [comment]
Nope. There are too many fun tricks in this line.

**Comment by jakirkham** [comment]
Maybe we solve this before hitting #100. :stuck_out_tongue_winking_eye:

**Comment by jakirkham** [comment]
:tada: Solved! :tada:

Happy to discuss with anyone how this went down.

**Comment by pelson** [comment]
Hmmm. No, I wasn't awake. Thanks for solving, but I'm going to have to dig into the reason for the automatic labelling... slightly concerned. (I have no idea why you were assigned either)

**Comment by pelson** [comment]
> Hmmm. No, I wasn't awake. Thanks for solving, but I'm going to have to dig into the reason for the automatic labelling... slightly concerned. (I have no idea why you were assigned either)
 
I wonder if it was waffle.io. I've cut it off to see if that is the source of the automatic labelling.

**Comment by jakirkham** [comment]
> Hmmm. No, I wasn't awake.

I figured not. Was half joking.

> Thanks for solving...

Sure. If you have other thoughts on it, feel free to let me know.

> I'm going to have to dig into the reason for the automatic labelling...

Have also seen `in progress` labels in other places. Tried [asking]( https://gitter.im/conda-forge/conda-forge.github.io?at=57005014e4a8384a1bbe4cb6 ) about it a couple weekends ago, but think everyone was busy.

> I wonder if it was waffle.io. I've cut it off to see if that is the source of the automatic labelling.

Sounds good.
