### ISSUE TITLE
File not found error 'epsg' anaconda ubuntu proj6

### ISSUE THREAD

**Issue by Siv0a** [conda-forge/conda-forge.github.io#936]
![Screenshot from 2019-11-27 16-36-58](https://user-images.githubusercontent.com/58256038/69718371-3007a380-1134-11ea-8bdf-a71d92d864a5.png)

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
There is no `conda list` or `conda info`, as requested in the issue template, for us to debug. Most likely you are mixing channels b/c `basemap` is not compatible with `proj4 >=6` and you have `6.2.1` there in your error message. Please see 
https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge and https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it
