### ISSUE TITLE
DOC X11 for matplotlib

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#941]
We should add docs that people may need to add a yum_requirements file if they want to import parts of matplotlib/matplotlib base in the conda-forge CI. 

@CJ-Wright @scopatz for viz

**Comment by CJ-Wright** [comment]
Why does matplotlib-base need yum things?

**Comment by beckermr** [comment]
Well it appears our docker containers do not have x11.so by default. So if you import parts of the library that need to link at runtime to libX11.so, then you get an error.

**Comment by beckermr** [comment]
I'd argue that since conda expects end users to have X11 themselves, we should be shipping it in our docker containers. However, if we are not going to do that, then we need to make sure people know to use yum to get it.

**Comment by CJ-Wright** [comment]
Ah I thought base didn't have the x11 bits

**Comment by beckermr** [comment]
Nope it still does because of `tk` IIUIC.

**Comment by dopplershift** [comment]
@beckermr That's correct.
