### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by Elmue** [conda-forge/conda-forge.github.io#945]
Hello

Thanks for compiling all these files and making them available.
I downloaded LibSsh2.dll for Windows 64 bit here:
https://anaconda.org/conda-forge/libssh2/1.8.2/download/win-64/libssh2-1.8.2-h642c060_2.tar.bz2

Inside is the file libssh2.dll
This file has a dependency to libcrypto-1_1-x64.dll

But libcrypto is completely missing on Conda Forge.

If I search for "libcrypto" on anaconda.org/search
I only find libcryptominisat which contains cryptominisat5win.dll.

**Comment by isuruf** [comment]
Use the conda package manager, otherwise you are on your own.

**Comment by isuruf** [comment]
If you want to download these dependencies separately, have a look at the `info/index.json` for the dependencies.

**Comment by Elmue** [comment]
No. You are wrong.
Index.json says

"depends": [
    "openssl >=1.1.1a,<1.1.2a",
    "vc 14.*",
    "zlib >=1.2.11,<1.3.0a0"
  ],

Where do you see anything about libcrypto-1_1-x64.dll there ???
Do you close all issues here like that ?
It is completely obvious that you never looked into this file before closing my issue.
And how does your package manger know about the dependency to libcrypto-1_1-x64.dll if there is no hint at all in none of the json files ??

**Comment by Elmue** [comment]
And even if libcryto would be mentioned in Index.json :
It is not downloadable on Conda Forge.
(As I wrote above)

**Comment by isuruf** [comment]
> Where do you see anything about libcrypto-1_1-x64.dll there ???

It's in `openssl`.

> Do you close all issues here like that ?

Yes, when the issue relates to something that's unsupported by conda-forge.

> It is completely obvious that you never looked into this file before closing my issue.

Please don't make accusations like that.

**Comment by msarahan** [comment]
The dependencies in index.json are package names, not file names. Conda packages are not standalone file bundles. If you extract them and put files where you want manually, you better know exactly what you're doing, or you'll waste a lot of your time. @isuruf has been generous with his time to answer you at all. We invite you to learn more about how the conda package ecosystem works, but we will not answer further questions about how you can misuse our content and complain that it doesn't work.
