### ISSUE TITLE
Poppler for 32 bit Windows missing

### ISSUE THREAD

**Issue by Elmue** [conda-forge/conda-forge.github.io#946]
Hello

It is really great that you provide all these files for all operating systems.
I downloaded Poppler for Windows 64 here:
https://anaconda.org/conda-forge/poppler/0.83.0/download/win-64/poppler-0.83.0-h1affe6b_0.tar.bz2

It works great.
But why don't you compile Poppler also for Windows 32 bit ?
All the other files which I downloaded on CondaForge exist as 32 bit and 64 bit version.
Why is Poppler an exception ?

To run Poppler there is no need to use a 64 bit version.
While the 32 bit version runs on Windows 64 and 32, the 64 bit version is limited to run only on Windows 64. You won't believe: There are still many Windows 32 bit installations out there!
So if you want to omit a platform it would make much more sense to omit 64 bit rather than 32 bit.

**Comment by ocefpaf** [comment]
Windows 32 is not supported in conda-forge. Sorry.
