### ISSUE TITLE
Inconsistent file names

### ISSUE THREAD

**Issue by Elmue** [conda-forge/conda-forge.github.io#947]
Hello

When you download the libtiff library
https://anaconda.org/conda-forge/libtiff/4.0.10/download/win-64/libtiff-4.0.10-h21b02b4_1005.tar.bz2
inside is a TIFF.DLL

This DLL has a dependency to LIBLZMA.DLL
When you search on Cond Forge for "liblzma" you find 
https://anaconda.org/msys2/m2-liblzma/5.2.2/download/win-64/m2-liblzma-5.2.2-2.tar.bz2

But there is no LIBLZMA.DLL in it.
This package contains the correct DLL but the file name is MSYS-LZMA-5.DLL

If someone does not know that this is the same as LIBLZMA.DLL it becomes difficult.
Why do you use inconsistent file names in different packages ?

**Comment by isuruf** [comment]
`m2-liblzma` package is not from conda-forge. If you don't want to use the conda package manager, you are on your own.
