### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chmreid** [conda-forge/conda-forge.github.io#955]
On this page <https://conda-forge.readthedocs.io/en/latest/recipe.html>

The link with the text `Writing the “meta.yml”` is broken

It points to <https://conda-forge.org/docs/meta.html>

It should point to <https://conda-forge.readthedocs.io/en/latest/meta.html>

I can't figure out how to fix this link, the "Page Source" link at the bottom of the page just points to <https://conda-forge.readthedocs.io/en/latest/_sources/recipe.rst.txt> and that text does not appear to be in this repository

Hopefully someone can fix this, thanks!

**Comment by chmreid** [comment]
The [Improving This Documentation](https://conda-forge.readthedocs.io/en/latest/self-improvement.html) page says the documentation is all in this repo, so I don't know why `recipe.rst` or `recipe.rst.txt` is not in this repo. If things have moved, the Improving This Documentation page may need a little love too.

**Comment by croth1** [comment]
The RTD version of the conda-forge docs is out of date. It looks like we do not know how remove it.
xref: https://github.com/conda-forge/conda-forge.github.io/issues/735

The current version of the docs is here: https://conda-forge.org/docs/

**Comment by chmreid** [comment]
Hello, wondering what happened to all of the content at conda-forge.readthedocs.io? Was this migrated to a different conda documentation site? Or has it been orphaned? (The conda-forge readthedocs site has valuable info and shows up at the top of google searches, and would be worth saving somewhere.)
