### ISSUE TITLE
updates to gfortran again?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#961]
It appears the scipy folks are discussing Fortran2003. I think we would have to migrate our fortran compilers to support this. 

xref: https://github.com/scipy/scipy/issues/11421

**Comment by isuruf** [comment]
You mean gfortran 8 or above? We use gfortran 7.3.0 on linux and mac.

**Comment by beckermr** [comment]
Right. Fortran2003 is the language def and we would need at least 4.8. Some features are 4.9

**Comment by isuruf** [comment]
? `7.3 > 4.9`

**Comment by beckermr** [comment]
Ach sorry yes. 🤦‍♂ 8 or above, maybe 9 on both linux and osx

**Comment by beckermr** [comment]
Here is the page. Looks like 8 would do the trick modulo bugs: https://gcc.gnu.org/wiki/Fortran2003Status

**Comment by beckermr** [comment]
scipy issue was closed. closing

**Comment by h-vetinari** [comment]
Actually, for _full_ support of Fortran2003 (which will surely be necessary eventually), it seems that gcc >= 9.0 is required, see "Asynchronous input/output" in the [status page](https://gcc.gnu.org/wiki/Fortran2003Status).

Although, one can hope that with LLVM 11 later this year, we might have a x-platform fortran-compiler, depending how things develop with https://github.com/flang-compiler/f18/issues/876 (they were reasonably close to inclusion for LLVM 10 already; let's hope 11's the charm)

**Comment by beckermr** [comment]
I’d be nervous about moving conda-forge to flang. Gfortran seems like a decent standard for now.

**Comment by scopatz** [comment]
flang on windows seems like a reasonable thing to do, though

**Comment by h-vetinari** [comment]
Sure, start with windows (finally scipy on CF!), and if the standards question comes up again, it can then still be weighed what's the better course of action.

**Comment by jakirkham** [comment]
FWIW people have tried this before ( https://github.com/conda-forge/scipy-feedstock/pull/78 ), but maybe the tooling has improved in the intervening time?

Thoughts @isuruf? 🙂

**Comment by h-vetinari** [comment]
@jakirkham, @isuruf is more than just a little involved already. 😉
Conda-forge's [flang](https://github.com/conda-forge/flang-feedstock) is [tracking](https://github.com/conda-forge/flang-feedstock/blob/d0cdb760a19f31f418810979bc3920b5a5ccb545/recipe/meta.yaml#L13) his personal `flang-compiler/flang` fork (predecessor to `flang-compiler/f18`), and he's not just [actively](https://github.com/flang-compiler/f18/issues/971#issuecomment-592121394) [involved](https://github.com/flang-compiler/f18/pulls?q=is%3Apr+author%3Aisuruf), but actually going to [lead](http://lists.llvm.org/pipermail/llvm-dev/2020-February/139378.html) the windows support effort for `f18` in the context of them merging into LLVM.

**Comment by jakirkham** [comment]
I'm very aware of all of this @h-vetinari 😄

**Comment by h-vetinari** [comment]
Pardon me if that was all very obvious ('m sure the following will be too).

I just misunderstood the question about the scipy-status, as it seems to me from [his](https://github.com/isuruf/flang/issues/129#issuecomment-506933387) [comments](https://github.com/conda-forge/scipy-feedstock/issues/80#issuecomment-552509426) that scipy is clearly a target once that capability lands (originally it was hoped to be [windows support](https://github.com/flang-compiler/flang/pulls/isuruf) in flang itself), but now everyone is putting their efforts into f18, and I would guess that not much will happen before that sees a release in LLVM. Although, to be fair, @mariusvniekerk [did prepare](https://github.com/conda-forge/scipy-feedstock/issues/119) a conda-forge scipy build with VS2017 + 2019 and Intel IFort.

**Comment by isuruf** [comment]
flang development has stopped now and everyone is putting their efforts on f18.
code generation in f18 landed 4 days ago and it still experimental and the runtime libraries are being written. It's a long way from being usable, but it'll get there. f18 is more receptive in getting windows patches merged, so when f18 is ready for other platforms, it'll probably be for windows too.
