### ISSUE TITLE
Contrary to docs, can't push to `git://github.com/regro-cf-autotick-bot/<package>-feedstock.git`

### ISSUE THREAD

**Issue by guyer** [conda-forge/conda-forge.github.io#964]
[Edited to clarify this is a documentation issue]

Contrary to [Pushing to regro-cf-autotick-bot branch](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch), you can't push to `git://github.com/regro-cf-autotick-bot/<package>-feedstock.git`. Per the comments below, it needs to be `git@github.com:regro-cf-autotick-bot/<package>-feedstock.git`.

```bash
$ git push git://github.com/regro-cf-autotick-bot/gmsh-feedstock.git 4.5.2
fatal: remote error: 
  You can't push to git://github.com/regro-cf-autotick-bot/gmsh-feedstock.git
  Use https://github.com/regro-cf-autotick-bot/gmsh-feedstock.git
$ git st
On branch regro-cf-autotick-bot-4.5.2
nothing to commit, working tree clean
$ git remote -v
guyer	git@github.com:guyer/gmsh-feedstock.git (fetch)
guyer	git@github.com:guyer/gmsh-feedstock.git (push)
origin	https://github.com/conda-forge/gmsh-feedstock.git (fetch)
origin	https://github.com/conda-forge/gmsh-feedstock.git (push)
regro-cf-autotick-bot	git://github.com/regro-cf-autotick-bot/gmsh-feedstock.git (fetch)
regro-cf-autotick-bot	git://github.com/regro-cf-autotick-bot/gmsh-feedstock.git (push)
$ git remote set-url regro-cf-autotick-bot git@github.com:regro-cf-autotick-bot/gmsh-feedstock.git
$ git push regro-cf-autotick-bot 4.5.2
X11 forwarding request failed on channel 0
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 706 bytes | 176.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:regro-cf-autotick-bot/gmsh-feedstock.git
   6880c93..c09306b  4.5.2 -> 4.5.2
```

I've read [this](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch) and [this](https://github.com/conda-forge/staged-recipes/issues/9522) and [this](https://github.com/conda-forge/conda-forge.github.io/issues/894), and I couldn't see what I was missing.

**Comment by CJ-Wright** [comment]
what about `git push git@github.com/regro-cf-autotick-bot/gmsh-feedstock.git`? I have never used `git://...` before.

**Comment by isuruf** [comment]
You can't push over `git://` protocol to github. (See https://stackoverflow.com/questions/19317264/does-github-support-git-protocol-for-pull) You need to use HTTPS (`https://`) or SSH (`git@`)

**Comment by guyer** [comment]
Thank you! That's not what https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch says.

Also, for anyone who stumbles across this, it's `git@github.com:regro-cf-autotick-bot/gmsh-feedstock.git` with a `:`, not a `/`.

**Comment by CJ-Wright** [comment]
@guyer would you be able to put up a PR fixing the docs?

**Comment by guyer** [comment]
@CJ-Wright done: #965
