### ISSUE TITLE
Document new broken package workflow

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#973]
Recently @isuruf did some nice work to [label packages as broken]( https://github.com/conda-forge/cf-mark-broken ). It would be good to add this workflow to the docs (once we are comfortable sharing) so that we can point maintainers wanting to mark packages as broken to this.

**Comment by isuruf** [comment]
PRs welcome.

**Comment by jakirkham** [comment]
Is that your indication that this is safe to share more broadly? 😉

**Comment by isuruf** [comment]
Yes, we've had a few PRs merged successfully and it worked fine.
