### ISSUE TITLE
Acknowledge OSU OSL and Works on Arm

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge.github.io#974]
They are providing ppc64le and aarch64 servers to conda-forge for long running builds and debugging.

**Comment by CJ-Wright** [comment]
It would be good to have a "conda-forge is brought to you with help from ... and maintainers like you, thank you!" Page

**Comment by jakirkham** [comment]
Yeah this has come up before. I can't seem to find the issue now though 🤔

**Comment by scopatz** [comment]
Maybe we need a sponsors page in full

**Comment by beckermr** [comment]
This is done.
