### ISSUE TITLE
Improve advanced communication about major initatives

### ISSUE THREAD

**Issue by hajapy** [conda-forge/conda-forge.github.io#992]
As a conda-forge user it would be helpful to receive advance notice that a major conda-forge initiative (such as a compiler migration, or the recent pypy migration) is underway or about to begin. Without such notice, builds and environment creation can fail unexpectedly and often in ways that require digging through github commits on multiple projects / anaconda.org files listings to see "what changed and when".  The state of these migrations is already listed on https://conda-forge.org/status/, so this issue is just about the lack of advanced notification.

**Comment by scopatz** [comment]
We'd love to have PRs that help you
