### ISSUE TITLE
CFEP-13 implementation mega-thread

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#993]
## Output Validation, Registration and Copies

- put in conda-forge-webservices and smithy
- [x] code to validate outputs (https://github.com/conda-forge/conda-forge-webservices/pull/344)
  - NOTE: some outputs are written to by more than once recipe - so we only need 
  to check duplicates for registering new outputs - we can allow duplicates inserted by hand when performing copies.
- [x] code to copy outputs (https://github.com/conda-forge/conda-forge-webservices/pull/344)
- [x] copy endpoint (https://github.com/conda-forge/conda-forge-webservices/pull/356)
- [x] validation endpoint (https://github.com/conda-forge/conda-forge-webservices/pull/356)
- [x] register endpoint (https://github.com/conda-forge/conda-forge-webservices/pull/356)
- [x] need to change CI scripts to call copy endpoint (https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/81)
- [x] force CI scripts to upload even if it exists when using validation, use staging token (https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/82, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/83, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/85)
- [x] change smithy to validate (https://github.com/conda-forge/conda-smithy/pull/1283, https://github.com/conda-forge/conda-smithy/pull/1295)
- [x] add python to exempt list for appveyor (https://github.com/conda-forge/conda-forge-webservices/pull/373)
- [x] shard the outputs repo (https://github.com/conda-forge/conda-forge-webservices/pull/389)
- [x] compute outputs as we migrate feedstocks (https://github.com/conda-forge/admin-migrations/pull/32)

## Key Generation, Registration and Validation

- put in conda-smithy and staged recipes
- [x] code to generate keys and push them to the CI services (https://github.com/conda-forge/conda-smithy/pull/1247)
- [x] code to register the keys in the key store w/ hashing (https://github.com/conda-forge/conda-smithy/pull/1247)
- [x] code to validate keys (https://github.com/conda-forge/conda-smithy/pull/1261)
- [x] change staged recipes to add the right tokens (https://github.com/conda-forge/staged-recipes/pull/11651)

## Deprecations, Migrations and Token Rotations
- [x] add code to smithy to rotate the binstar tokens (https://github.com/conda-forge/conda-smithy/pull/1291)
- [x] deprecate vs2008 and python 2.7 (https://github.com/conda-forge/cfep/pull/26, https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/491)
- [x] deprecate appveyor and vs2015 (https://github.com/conda-forge/conda-forge.github.io/issues/1012)
- [x] turn off appveyor for all feedstocks after merging libssh2 move to azure (https://github.com/conda-forge/admin-migrations/pull/44)
- [x] deactivate the current binstar token and put the new one in heroku
- [x] need to write an admin migration to migrate all of the BINSTAR tokens to the staging org (https://github.com/conda-forge/admin-migrations/pull/29)
- [x] need to write an admin migration to generate and register keys for all current feedstocks (https://github.com/conda-forge/admin-migrations/pull/29)
- [x] clean all secure tokens from feedstocks w/ an admin migration

## UX Items
- [x] make an announcement (https://github.com/conda-forge/conda-forge.github.io/pull/1058)
- [x] ~move cf-mark-broken to admin-requests and add token reregistration~
- [x] enable the admin bot to comment on SHAs when a copy fails (https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/89, https://github.com/conda-forge/conda-forge-webservices/pull/375)

**Comment by beckermr** [comment]
One of our wonderful libusb maintainers, @ryanvolz, used this code snippet to find `msbuild` on our azure images. Should we / can we port this to other feedstocks that need `msbuild`?

```
set "MSBUILD_CMD=%VSINSTALLDIR%MSBuild\%VS_VERSION%\Bin\MSBuild.exe"
if not exist "%MSBUILD_CMD%" (
  :: Azure has at least VS 2017
  :: find VS 2017+ installations using vswhere tool
  echo Searching for MSBuild using vswhere...
  set "VSWHERE_CMD=C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
  if not exist "!VSWHERE_CMD!" (
    set "VSWHERE_CMD=vswhere"
  )
  echo vswhere path: !VSWHERE_CMD!
  for /f "usebackq tokens=*" %%i in (`"!VSWHERE_CMD!" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
    set "MSBUILD_CMD=%%i"
  )
  if not exist "!MSBUILD_CMD!" (
    :: try just finding the VS 2017 installation path
    for /f "usebackq tokens=*" %%i in (`"!VSWHERE_CMD!" -latest -products * -requires Microsoft.Component.MSBuild -version ^[15.0^,16.0^) -property installationPath`) do (
      set "vsdir=%%i"
    )
    set "MSBUILD_CMD=!vsdir!\MSBuild\15.0\Bin\MSBuild.exe"
    if not exist "!MSBUILD_CMD!" (
      :: try a sensible default
      set "MSBUILD_CMD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
      if not exist "!MSBUILD_CMD!" (
        echo Could not find MSBuild.exe
        exit 1
      )
    )
  )
  echo MSBuild path: !MSBUILD_CMD!
)
```

**Comment by beckermr** [comment]
cc @isuruf @jakirkham @ocefpaf

**Comment by isuruf** [comment]
It's not enough to find `msbuild.exe`. If the `msbuild.exe` is found from VS2017, it'll use cl.exe from VS2017. I tried setting some variables to make it find VS2015, but didn't work.

**Comment by isuruf** [comment]
Finding `msbuild.exe` like that is equivalent to using `vs2017_win-64` package with the disadvantage that the dependency `vc>=14` is added instead of `vc>=14.1`

**Comment by beckermr** [comment]
I don't fully follow @isuruf but do we need to mark those builds of libusb broken?

**Comment by jakirkham** [comment]
cc @ryanvolz (in case you have thoughts on `msbuild` usage on Azure 🙂)

**Comment by ryanvolz** [comment]
The logs show that the build used VC14 paths for cl.exe, etc., so it looked fine to me. Installing the vs_2015 package seemed to set the environment variables in such a way that the right toolchain gets used even if it's the newer msbuild that kicks it off. But I only know enough to hack this together and could be wrong in thinking that it worked.

**Comment by isuruf** [comment]
Can you post the link for the logs?

**Comment by ryanvolz** [comment]
> Can you post the link for the logs?

Hopefully this works:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=133973&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=3002d0ca-d910-5264-f0e4-809a5057fac4&l=444

**Comment by isuruf** [comment]
Ah, so `libusb` has a solution file specifically for vs2015.  This is not the case for most packages.

**Comment by jakirkham** [comment]
How are other packages you have seen using `msbuild`?

**Comment by isuruf** [comment]
> How are other packages you have seen using msbuild?

They have one solution file for all versions

**Comment by ryanvolz** [comment]
> Ah, so `libusb` has a solution file specifically for vs2015. This is not the case for most packages.

Ok, that makes sense. I wasn't sure how exactly the toolchain was getting selected. I did just try a build of `libusb` locally that forced using the VS2017 solution file even with the VS2015 package and setup, and it did fail because it couldn't find the right Windows SDK.

Until just now, the `libusb` recipe had the following code snippet to upgrade VS2005 vcproj files to get VS2008 files that weren't otherwise provided:
```
if "%VS_YEAR%" == "2008" (
  call vcbuild /upgrade msvc\libusb_dll_2005.vcproj
  if errorlevel 1 exit 1
  call vcbuild /upgrade msvc\libusb_static_2005.vcproj
  if errorlevel 1 exit 1
  call vcbuild /upgrade msvc\listdevs_2005.vcproj
  if errorlevel 1 exit 1
  call vcbuild /upgrade msvc\stress_2005.vcproj
  if errorlevel 1 exit 1
  call vcbuild /upgrade msvc\xusb_2005.vcproj
  if errorlevel 1 exit 1
  set SLN_FILE="msvc\libusb_2005.sln"
  set TOOLSVERSION=3.5
)
```

Maybe that's helpful for some other packages?

**Comment by beckermr** [comment]
kk. I won't be porting this around then. Sounds like we will need to update to vs2017 or w/e to get this done.
