### ISSUE TITLE
Document (im)mutability of packages

### ISSUE THREAD

**Issue by gatesn** [conda-forge/conda-forge.github.io#995]
Issue: It's not clear whether conda-forge allows packages to be mutated after they're initially published. If they can and are mutated, can Conda Forge provide an audit log or history of such changes?

**Comment by scopatz** [comment]
The only mutation that is really allowed is that we can change the labels on a package, e.g. moving from `main` to `broken`

**Comment by gatesn** [comment]
And do you know if that is different from Anaconda.org?

In particular we saw something on our systems that suggested the Python package on Conda Forge was mutated ~7 days ago. But can’t find anything to suggest that’s possible or has happened on the Conda Forge site or Anaconda.org.

**Comment by isuruf** [comment]
We hotfixed the metadata, but that doesn't change the python package, only the metadata in `repodata.json` file for the channel.

**Comment by gatesn** [comment]
So the checksum stayed the same, but the repodata entry changed? 

Or would the checksum also change since the index.json would be updated to reflect the new metadata?

**Comment by mariusvniekerk** [comment]
The artifact checksum is immutable.  We never edit artifacts.  The metadata in repodata.json is used when determining solutions for conda's solver.

**Comment by jjhelmus** [comment]
It should be noted that the immutability of packages is a policy of conda-forge not a feature of anaconda.org.  Anaconda.org allows packages to be deleted and replaced with a new version.  I would not recommend this but it is possible on anaconda.org for packages to mutate.
